### ISSUE TITLE
Neutron metadata proxy not monitored

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1002]
##### What version (commit) do you encounter this issue on?
All

##### What type of issue is this (bug, feature, documentation, regression)?

Feature

##### What is the expected behavior?

RPC will be notified by Maas if one of the neutron-ns-metadata proxy, neutron-metadata agent is down or not responding
This request is similar to https://github.com/rcbops/rpc-openstack/issues/569

##### What is actually happening?

N/A

##### How can we reproduce this issue?

N/A

##### How can we verify your issue is addressed?

Maas Alarm kicks off is one of the mentioned processes is not running or the metadata address is not reachable. Also watch https://bugs.launchpad.net/neutron/+bug/1570958

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

No workaround present 

##### What is your evaluation on the importance of this issue, and why?

We see recurring issues with failing metadata proxies so it is urgent

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2
- [ ] liberty-12.1
- [ ] kilo

**Comment by prometheanfire** [comment]
would this check work for you @BjoernT?

    ip netns exec qrouter-UUID ss -lntp | grep 9697

**Comment by BjoernT** [comment]
It's a lot more difficult. If the network is isolated, the neutron-ns-metadata proxy should listen to 169.254.169.254 via http://169.254.169.254/latest/meta-data inside the qdhcp namespace and then forwarding requests to the neutron-metadata process inside the neutron_agents container
If the network is not isolated the qrouter namespace will have a iptables rule redirecting 169.254.169.254 to a local neutron-ns-metadata proxy (port 80 usually), perhaps a curl to http://169.254.169.254/latest/meta-data can work to.
There are several criteria in neutron when it considers the network as isolated so we have to resemble the neutron logic here a little bit

**Comment by prometheanfire** [comment]
I'd rather not redo work neutron itself is doing.  That way lies much badness.  Given neutron controls spinning up this service, how are we supposed to know when the customer creates a new network and needs a new check/alarm?

**Comment by BjoernT** [comment]
that's why we have to replicate the neutron way of determine if a network is isolated or not so we can just write one plugin and that checks all current networks

**Comment by prometheanfire** [comment]
I'm not sure that's possible.  Also even more than that, I'm worried about changing networks and the like.  What happens when a customer deletes a network we were monitoring?  Adds a new network, etc.  On my personal deployment at home there are three neutron-ns-metadata-proxy services running.

**Comment by BjoernT** [comment]
@prometheanfire Please update as briefly discussed, so we know what the dev position is. Thanks

**Comment by prometheanfire** [comment]
Sure,

Problematically this is not something we want to do.  We have to fool nova and neutron into giving us a return on the metadata.  We'd also have to track network creation and deletion.  This is bad for a couple of reasons out side of technical, security (getting metadata for a customer instance) being a big one.

The other option that was discussed was to run a VM in the customer env for each network they wish to have monitored, which brings other issues of it's own.  I'll let support raise that if needed though.

Closing this.

**Comment by BjoernT** [comment]
Please reopen, we need a solution. If the monitoring can only be realized through a small coreos VM for example so be it. No monitoring is not a alternative, I'm open to suggestions.

**Comment by b3rnard0** [comment]
We are going to tackle this as an medium sized enhancement here: https://github.com/rcbops/u-suk-dev/issues/239
