### ISSUE TITLE
Increase number of metric per maas check

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1003]
##### What version (commit) do you encounter this issue on?

All

##### What type of issue is this (bug, feature, documentation, regression)?

Feature

##### What is the expected behavior?

Increase the limit to the current allowed number.
I'm currently asking the MAAS team what the limit is

##### What is actually happening?

Disk util checks fail on large swift deployments

##### How can we reproduce this issue?

Install a disk util check with has large number scsi devices and verify inside the intelligence console 

##### How can we verify your issue is addressed?

All disk util checks return OK

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Low prio

##### What is your evaluation on the importance of this issue, and why?

- 

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.1
- [ ] liberty-12.0
- [ ] kilo

**Comment by npawelek** [comment]
https://github.com/rcbops/rpc-openstack/issues/1180 has a PR for this issue. The monitoring team increased the limit from 30 to 50.

**Comment by git-harry** [comment]
As referenced above, there is another issue tracking this same work so I will close this issue in favour of https://github.com/rcbops/rpc-openstack/issues/1180
