### ISSUE TITLE
pip failing to install rackspace-monitoring-cli causing MaaS failure

### ISSUE THREAD

**Issue by xeregin** [rcbops/rpc-openstack#1008]
##### What version (commit) do you encounter this issue on?
OSA: 11.2.12
RPC-O: 11.1.6

##### What type of issue is this (bug, feature, documentation, regression)?
Bug

##### What is the expected behavior?
The setup-maas script will typically install the rackspace-monitoring-cli package on each configured node.

##### What is actually happening?
pip is failing to install rmc because --allow-all-external has been deprecated and no longer has any effect.

Here is what you will see:
```
failed: [605076-storage01] => (item=rackspace-monitoring-cli) => {"cmd": "/usr/local/bin/pip install rackspace-monitoring-cli", "failed": true, "item": "rackspace-monitoring-cli"}
msg: stdout: Ignoring indexes: https://pypi.python.org/simple
Collecting rackspace-monitoring-cli

:stderr: DEPRECATION: --allow-all-external has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
  Could not find a version that satisfies the requirement rackspace-monitoring-cli (from versions: )
No matching distribution found for rackspace-monitoring-cli
```

##### How can we reproduce this issue?
Build a lab using 11.2.12, configure MaaS, and attempt to deploy MaaS.

##### How can we verify your issue is addressed?
If MaaS successfully deploys, the issue has been addressed...

##### What is your evaluation on the importance of this issue, and why?
This prevents MaaS from deploying, therefore it should have some elevated priority. It can be worked around, but this should not be necessary...

##### What branches / milestones do you believe this issue should target?
11.2.12 is the first lab that I have seen this behavior in, and may be carried foward.

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.1
- [ ] liberty-12.0
- [ ] kilo

**Comment by xeregin** [comment]
Sorry, this is most likely 11.1.6.
11.2.12 is the OSA version.

**Comment by xeregin** [comment]
Manually, this would be resolved using:
```
pip install --upgrade --isolated rackspace-monitoring-cli
```

**Comment by b3rnard0** [comment]
At a minimum, this should be a known issue in 11.1.7. Adding docs. 

cc: @erikmwilson @robb-romans

**Comment by git-harry** [comment]
The branch kilo is passing the periodic testing that we have [1].

The bug is unclear but gives the impression that the setup-maas.yml playbook is being applied to an OSA build. If that's the case were the rpc-o playbooks repo-build.yml and repo-pip-setup.yml run first? They are required to ensure that rackspace-monitoring-cli is on the repo server.

http://jenkins.propter.net/job/RPC-AIO/4211/

**Comment by git-harry** [comment]
@xeregin would you mind providing an update to this in response to my previous comment. Also I've not heard any further issues due to this so I'd like to know if it is still causing problems.

**Comment by git-harry** [comment]
@xeregin based on the time this issue has been here, the lack of any additional reports and the fact we are now on r11.1.17, I'm going to close it. If you think it is still important let me know and we can look to reopen it.
