### ISSUE TITLE
Memcached monitoring should be using curr_connections instead of total_connections

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/rpc-openstack#1025]
Memcached monitoring should be using curr_connections, which is the current active connection count, instead of total_connections, which is the lifetime total connections, and should alert when curr_connection is close to the configured max in memcached_connections.

##### What version (commit) do you encounter this issue on?

r11.1.5 (and all others)

##### What type of issue is this (bug, feature, documentation, regression)?

Feature (and bug?) / Bug (and feature?)

##### What is the expected behavior?

MaaS memcached plugin checks the currently active memcached connections.

##### What is actually happening?

MaaS memcached plugin checks the total lifetime memcached connections.

##### How can we reproduce this issue?

Run the plugin and look at the metric

##### How can we verify your issue is addressed?

Run the plugin and look at the metric

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

N/A

##### What is your evaluation on the importance of this issue, and why?

Medium. Customers are impacted when the memcached connection limit is hit. Alerts are generated because memcached cannot open a new connection to provide stats to the plugin.

##### What branches / milestones do you believe this issue should target?

All supported

###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.2
- [x] liberty-12.1
- [x] kilo

Reference issue #1023

**Comment by prometheanfire** [comment]
#1023 as a refrence

**Comment by prometheanfire** [comment]
so, changing the metric is easy, do we need to create a new alarm as well?

**Comment by BjoernT** [comment]
Are we going to backport this ?

**Comment by prometheanfire** [comment]
yes, need master to merge first though

**Comment by prometheanfire** [comment]
merged, closing :D
