### ISSUE TITLE
[TRACKING] Beaver repo_pip_lockdown dep causes repo rebuild to fail

### ISSUE THREAD

**Issue by hughsaunders** [rcbops/rpc-openstack#1028]
##### What version (commit) do you encounter this issue on?
Upgrades within liberty (eg r12.2.0rc1 --> master)

##### What type of issue is this (bug, feature, documentation, regression)?
bug

##### What is the expected behavior?
The repo server does not have its pip conf locked down to itself, preventing future repo builds from failing. This also means that Minor upgrades will be successful.

##### What is actually happening?
The beaver role depends on pip_lock_down and is applied to all hosts. This includes the repo server which causes the repo server's pip configuration to be locked down. This causes future repo builds to fail as no external package sources are available.

##### How can we reproduce this issue?
Deploy RPC liberty, then re-run the repo build playbook, alternatively deploy a rpc liberty version than attempt to upgrade to a newer liberty version. 

##### How can we verify your issue is addressed?
Upgrades and re-runs of repo-build are successful  after a full RPC liberty deploy.

##### What is your evaluation on the importance of this issue, and why?
Medium - it needs to be fixed, impact is mostly on gates at the moment, the impact for customers is low as ops can manually remove the pip.conf from the repo servers and continue.

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2
- [ ] liberty-12.1

**Comment by hughsaunders** [comment]
There are two things to fix here:

[ ] Remove the pip_lock_down dep from the beaver role
[ ] Add a cleanup step to deploy.sh

**Comment by hughsaunders** [comment]
@git-harry has proposed a fix for this upstream in two patches:
- 1 https://review.openstack.org/#/c/310475/ - Supply environment variable to repo build tasks that overrides pip lock down and allows external repo access.
- 2e https://review.openstack.org/#/c/310479/ - Add pip_lock_down dep back into repo_server role. 

RPC PR no longer required.

**Comment by git-harry** [comment]
There is also https://review.openstack.org/#/c/310690/

**Comment by prometheanfire** [comment]
we might need to make sure this is backported upstream

**Comment by prometheanfire** [comment]
needs backport to mitaka and liberty

**Comment by git-harry** [comment]
The upstream changes proposed above impact gating and there is no guarantee the work will be backported to liberty.

This project needs to address the issue locally pending the outcome of the upstream fix.

**Comment by prometheanfire** [comment]
I think only  Remove the pip_lock_down dep from the beaver role is needed now

**Comment by git-harry** [comment]
I'm removing the pip_lock_down item from the list, the beaver role needs to install the same versions on the repo containers as every other host. If beaver does not drop in a pip.conf file the repo containers get different versions to everything else.

We can use this issue to carry on tracking the upstream effort. I will reset the check boxes and change the priority to prio-2 now that we have a workaround in place.

**Comment by mancdaz** [comment]
@hughsaunders does https://github.com/rcbops/rpc-openstack/pull/1159 address the issue here?

**Comment by git-harry** [comment]
@mancdaz I don't think that pull request changes things. The pip.conf file was already being deleted and still suffers from the same potential issues after that change.

**Comment by git-harry** [comment]
Closing based on original issue being addressed.
