### ISSUE TITLE
Rsyslog container is dual logging to /var/log and /var/log/log-storage

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1031]
##### What version (commit) do you encounter this issue on?

r11.1.6

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

remote logging only to /var/log/log-storage

##### What is actually happening?

Currently it seems that remote messages are also logged to the local /var/log/syslog file in addition
to /var/log/log-storage for all remote hosts. Hence we double the logging volume now

##### How can we reproduce this issue?

/var/log/syslog contains remote messages

##### How can we verify your issue is addressed?

Only local messages show up inside /var/log/syslog of the rsyslog container 

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Medium

##### What is your evaluation on the importance of this issue, and why?

-

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2 https://github.com/rcbops/rpc-openstack/pull/1422
- [ ] mitaka-13.0

**Comment by d34dh0r53** [comment]
I have tried recreating this on greenfield kilo and liberty deployments, as well as on a kilo to liberty upgrade.  I have a feeling that this may be an artifact introduced on a juno to kilo upgrade.  @BjoernT Can you verify whether you see this on upgraded environments only or on greenfield envs as well?

**Comment by BjoernT** [comment]
Yes also happen in new installs 

```
==> log-storage/12345-compute016/snmpd.log <==
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:43082->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: message repeated 3 times: [ Connection from UDP: [127.0.0.1]:43082->[127.0.0.1]:161]
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:43720->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:43082->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:43720->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:43082->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:43720->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:58835->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: message repeated 4 times: [ Connection from UDP: [127.0.0.1]:58835->[127.0.0.1]:161]
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:45356->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:45356->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:58835->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:45356->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:38145->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: message repeated 4 times: [ Connection from UDP: [127.0.0.1]:38145->[127.0.0.1]:161]
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:55900->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:38145->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:55900->[127.0.0.1]:161
^C
root@12346-logging01_rsyslog_container-4e3a342c:/var/log# grep compute016 syslog  |grep 'May 12 20:42:02'
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:43082->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: message repeated 3 times: [ Connection from UDP: [127.0.0.1]:43082->[127.0.0.1]:161]
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:43720->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:43082->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:43720->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:43082->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:43720->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:58835->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: message repeated 4 times: [ Connection from UDP: [127.0.0.1]:58835->[127.0.0.1]:161]
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:45356->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:45356->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:58835->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:45356->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:38145->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: message repeated 4 times: [ Connection from UDP: [127.0.0.1]:38145->[127.0.0.1]:161]
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:55900->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:38145->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:55900->[127.0.0.1]:161
May 12 20:42:02 12345-compute016 snmpd[8534]: Connection from UDP: [127.0.0.1]:55900->[127.0.0.1]:161
```

**Comment by BjoernT** [comment]
cron and snmpd seems to do that primarily

**Comment by BjoernT** [comment]
Oh, all processes are doing it, perhaps 
```
*.*;auth,authpriv.none  -/var/log/syslog
```
is the culprit and we need to change *.* to local.* or so. Don't remember how to separate local from remote rsyslog traffic

**Comment by mancdaz** [comment]
Hi @BjoernT 

This is actually an issue in openstack-ansible, not rpc-openstack, since it is to do with the rsyslog container config which is all built by openstack-ansible.

Would you mind please opening a bug there giving as much information as possible, because if you believe this affects liberty and master then it can still be fixed there. However I think the likelyhood of this being fixed in kilo is very low given that kilo in OSA is about to EOL and all non-critical fixes are being -1

/cc @git-harry

**Comment by BjoernT** [comment]
@b3rnard0 Please remove invalid tag, given that we now track OSA issues in RPC-O. Thanks

**Comment by git-harry** [comment]
@BjoernT are you able to provide the upstream bug to which this issue relates? There have been several recent fixes to remove log duplication and it is possible this issue has been addressed as part of that. I had a look and could not find it.

**Comment by Apsu** [comment]
@git-harry @BjoernT https://review.openstack.org/#/c/367649/ appears to be the upstream change and it just merged today. Looks like we're good to go on this card.

**Comment by BjoernT** [comment]
Don't think those are related, https://review.openstack.org/#/c/367649/  is just for ansible logs.
The true dual logging on server side has been fixed via https://review.openstack.org/#/q/topic:bug/1621559

**Comment by Apsu** [comment]
@BjoernT Ah, right you are. All of that has merged, though, so it does look like this card is good to go.

**Comment by BjoernT** [comment]
Yes we can update/close this issue once we sha bump for all active releases.

**Comment by Apsu** [comment]
Cool, moving to Pending SHA update column.
