### ISSUE TITLE
Add flake8 checks to enforce commit message style per contributing documentation

### ISSUE THREAD

**Issue by sigmavirus24** [rcbops/rpc-openstack#1036]
##### What version (commit) do you encounter this issue on?
N/A

##### What type of issue is this (bug, feature, documentation, regression)?
Feature

##### What is the expected behavior?
Gate checks catch commit message style violations

##### What is actually happening?
People are forced to enforce commit message style on review

##### How can we reproduce this issue?
Create a commit that violates the style guide and run the existing flake8 checks against it.

##### How can we verify your issue is addressed?
Apply the patch and re-run the flake8 checks.

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
N/a

##### What is your evaluation on the importance of this issue, and why?
This is very low importance

###### Remove branches (lines) you do not wish to target.

- [x] Master (See #1034)
- [x] liberty-12.2 (See #1086)
- [x] liberty-12.1
- [ ] kilo

**Comment by b3rnard0** [comment]
@mancdaz @sigmavirus24 This looks like it is done?

**Comment by sigmavirus24** [comment]
I don't think we ever backported this to kilo, but then I'm not sure we want to. @git-harry ?

**Comment by git-harry** [comment]
@sigmavirus24 it's pretty low priority so it's not worth a major investment in time, but if it cherry-picks cleanly I see to reason not to do it given it is only a backport.
