### ISSUE TITLE
Paramiko v2.0 causes bootstrap-ansible.sh to fail

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#1037]
##### What version (commit) do you encounter this issue on?
master
##### What type of issue is this (bug, feature, documentation, regression)?
bug
##### What is the expected behavior?
bootstrap-ansible.sh should install ansible and all its dependencies.
##### What is actually happening?
bootstrap-ansible.sh fails because the new version of paramiko requires additional libraries to support cryptography.

http://jenkins.propter.net/job/RPC-AIO/4825/console
##### How can we reproduce this issue?
Attempt to deploy an AIO.
##### How can we verify your issue is addressed?
bootstrap-ansible.sh should exit after successfully installing ansible.
##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
Run the following prior to bootstrap-ansible.sh
```
apt-get install build-essential libssl-dev libffi-dev
```
##### What is your evaluation on the importance of this issue, and why?
High, this impacts all branches and all new deployments.
###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.1
- [x] liberty-12.0
- [x] kilo

**Comment by git-harry** [comment]
There are open reviews to address this in OSA

https://review.openstack.org/#/c/311187/1
https://review.openstack.org/#/c/311193/1

**Comment by prometheanfire** [comment]
we will need to leave this open so we can revert #1051 when 11.2.15 is released with the upstream fix

**Comment by git-harry** [comment]
The required OSA SHA has merged in all Liberty branches.

**Comment by prometheanfire** [comment]
guess that means we can revert?

**Comment by git-harry** [comment]
Yes, the changes to deploy.sh can be reverted.
