### ISSUE TITLE
why am I labeling / milestoning all PRs?

### ISSUE THREAD

**Issue by prometheanfire** [rcbops/rpc-openstack#1042]
##### What version (commit) do you encounter this issue on?
hell if I know or care

##### What type of issue is this (bug, feature, documentation, regression)?
documentation

##### What is the expected behavior?
people that submit PRs properly label / milestone their PRs

##### What is actually happening?
I'm having to do all the labeling / milestoning

##### How can we reproduce this issue?
submit a PR and wait for someone else (me) to prioritize it

##### How can we verify your issue is addressed?
I'm not labeling / milestoning all the PRs

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
Do their job?

##### What is your evaluation on the importance of this issue, and why?
meh

###### Remove branches (lines) you do not wish to target.
- [ ] Master

**Comment by prometheanfire** [comment]
should the PR submitter do it or the PTL for labels?  Same question for milestones.

**Comment by mancdaz** [comment]
Can't this just be handled at the triage meetings? Do you really want all and sundry labelling issues however they see fit?

**Comment by prometheanfire** [comment]
It is handled there for issues.  What I was looking for is that when people create the PR they just copy the labels from the issue.  Waiting for a triage for pull requests means that the pull requests have an additional delay (people normally don't review things that are not prioritized).

**Comment by mancdaz** [comment]
@prometheanfire yeah sorry I missed that it was for PRs. Chatting with @git-harry we could maybe implement a Jenkins job based on PR trigger, to copy labels over.

**Comment by prometheanfire** [comment]
ya, that'd work.  This is something that seems automatable.

**Comment by git-harry** [comment]
It should no longer be necessary to copy labels onto pull request, the use of Waffle and the 'Connected' keyword should allow these things to be appropriately tracked.
