### ISSUE TITLE
Updating OSA SHA to 12.0.12 causes upgrading nova_console to fail

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#1058]
##### What version (commit) do you encounter this issue on?
master
##### What type of issue is this (bug, feature, documentation, regression)?
bug
##### What is the expected behavior?
The task 'Get package from git' in 'playbooks/roles/os_nova/tasks/nova_console_spice_install.yml' should update the spice-html5 repo to the version specified in 'playbooks/defaults/repo_packages/openstack_other.yml'.
##### What is actually happening?
Updating the OSA SHA to 12.0.12 causes this task to fail, an extract of the error message returned by Ansible is " {'msg': 'Failed to checkout 54cc41299bea8cd681ed0262735e0fd821cd774a', 'failed': True, 'attempts': 5}".
##### How can we reproduce this issue?
Deploy r11.1.7 then checkout master, change the OSA SHA to 12.0.12 and perform an upgrade.
##### How can we verify your issue is addressed?
Run a successful upgrade where the SHA for the Spice console software is different for the two versions.
##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
I have not tested this but I suspect 'git pull' on the master branch of the spice-html5 repo (/var/www/repo/openstackgit/spice-html5) on the repo server, prior to an upgrade, would resolve the issue.
##### What is your evaluation on the importance of this issue, and why?
Hugh, this is preventing the project from updating to the latest OSA liberty release.
###### Remove branches (lines) you do not wish to target.
- [x] Master
- [ ] liberty-12.2
- [ ] liberty-12.1

**Comment by prometheanfire** [comment]
rpc-repo was fixed

The issue was that building the upper-reqs was removed from the repo-build role.  We pinned the version of that role on the rpc-repo box and now we are fixed (after kicking off a job).

**Comment by git-harry** [comment]
I'm not sure why updating the Kilo repo is required to make sure Liberty has the correct version available however the immediate issue is resolved so closing this issue.
