### ISSUE TITLE
Cannot configure custom solutions through the ansible playbook

### ISSUE THREAD

**Issue by miguelgrinberg** [rcbops/rpc-openstack#106]
The only way is to manually create a config file in the horizon containers.

**Comment by miguelgrinberg** [comment]
@mattt416 I think this was closed by mistake, you probably referenced the wrong bug# in your commit.

**Comment by nrb** [comment]
Unassigning for now. This may be impacted by larger solutions template discussions, too.

**Comment by BjoernT** [comment]
Not sure if that needs to be addressed still

**Comment by d34dh0r53** [comment]
This can be re-opened if it still needs to be addressed.
