### ISSUE TITLE
Security Hardening filling up syslog and user.log on logging host

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/rpc-openstack#1067]
##### What version (commit) do you encounter this issue on?
r12.2.0rc1
##### What type of issue is this (bug, feature, documentation, regression)?
bug
##### What is actually happening?
user.log and syslog are filling up with all user access logs, this causes the / dir to fill in under 2 minutes
##### How can we reproduce this issue?
install security hardening
##### How can we verify your issue is addressed?
https://bugs.launchpad.net/openstack-ansible/+bug/1577944
##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
https://bugs.launchpad.net/openstack-ansible/+bug/1577944
##### What is your evaluation on the importance of this issue, and why?
https://bugs.launchpad.net/openstack-ansible/+bug/1577944
###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.2

```
-rw-r-----  1 root      adm        2048000 May  5 20:49 rackspace-monitoring-agent.log
-rw-r-----  1 syslog    adm     8215937024 May 10 11:08 syslog
-rw-r-----  1 syslog    adm    17127411712 May  4 06:25 syslog.1
drwxr-xr-x  2 root      root          4096 May 10 06:25 sysstat
-rw-r--r--  1 root      root        491561 May  3 15:03 udev
drwxr-xr-x  2 root      root          4096 Feb 29 16:30 unattended-upgrades
drwxr-xr-x  2 root      root         12288 May  4 10:51 upstart
-rw-r-----  1 syslog    adm     8202944512 May 10 11:08 user.log
```

**Comment by d34dh0r53** [comment]
This has been fixed upstream and will be included in the next SHA bump,

**Comment by jacobwagner** [comment]
@d34dh0r53 ty sir, just wanted to track this here

**Comment by git-harry** [comment]
It sounds like fixing this is a requirement for r12.2.0 so I'll target this at the next release candidate.
