### ISSUE TITLE
elasticsearch: uuid query doesn't work properly

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/rpc-openstack#107]
Due to the default analyzer the uuid string is broken up and anything in a query beyond the first dash is ignored. We need the option of changing the analyzer and we must default to one that works properly for our needs.

**Comment by nrb** [comment]
@odyssey4me Is this still valid after our switch to beaver?

**Comment by odyssey4me** [comment]
Yes - this is to do with the ElasticSearch configuration, not log collection. See #257 for the technical detail.

**Comment by nrb** [comment]
Closing, as #257 is a more detailed report.
