### ISSUE TITLE
SSH errors due to the number of forks

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#1070]
##### What version (commit) do you encounter this issue on?

all
##### What type of issue is this (bug, feature, documentation, regression)?

bug
##### What is the expected behavior?

Ansible has the parameter forks [1] that controls the number of parallel processes. For large deployments, increasing the number of forks has the potential to significantly reduce the time taken to complete the deployment.

[1] http://docs.ansible.com/ansible/intro_configuration.html#forks
##### What is actually happening?

The default number of forks used by RPCO is the number of processors on the deployment host. This is generally being overridden by support to a much higher number e.g. 75. This can cause a problem when using delegate_to because the host to which the task is delegated cannot support that number of SSH sessions. The number of sessions allowed for the SSH daemon [2] is set by MaxSessions which defaults to 10. The investigation of this issue has previously been done upstream [3].

On customer deployments the number of processors is likely to exceed 10 which means that by default there is the potential for SSH connection errors and overriding the value to 75 is obviously a potential problem.

[2] http://docs.openstack.org/developer/openstack-ansible/install-guide/app-tips.html#ansible-forks
[3] https://bugs.launchpad.net/openstack-ansible/+bug/1479812
##### How can we reproduce this issue?

Set a high number of forks and run a task that delegates more than MaxSessions connections to a single host.
##### How can we verify your issue is addressed?

This will be addressed when there is no longer confusion about the use of forks. This could be addressed by adjusting the number of MaxSessions, forks or just with documentation.
##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

It is possible to adjust the number of forks set and so there is no inherent reason that a deployment should be affected by this issue.
##### What is your evaluation on the importance of this issue, and why?

This issue reoccurs but does not prevent deployments happening and so is probably a prio-2.
###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2
- [ ] liberty-12.1
- [ ] kilo

**Comment by odyssey4me** [comment]
FYI I have patched OSA master to be rid of the ``FORKS`` environment variable and to provide more guidance in the documentation: https://review.openstack.org/319213

**Comment by prometheanfire** [comment]
so, question... shouldn't this be part of the base image?

**Comment by odyssey4me** [comment]
@prometheanfire By 'base image' what do you mean? When it comes to CDC's there is no 'base image' for the hosts.

**Comment by prometheanfire** [comment]
true, I'm just trying to determine if rpc-o should handle this or not, I suspect we should, but at least for rackspace kicks this would be nice to change the default.

**Comment by odyssey4me** [comment]
RPC-O should, at the very least, ensure that there is awareness of this and that any deployment documentation highlights that elevating the number of forks higher than 10 for certain host groups may cause unpredictable failures.

**Comment by prometheanfire** [comment]
making a new playbook for this, mostly based off of major's sshd config changes / method used in osa-security, aio is building now.

**Comment by evrardjp** [comment]
@prometheanfire I think @odyssey4me 's message was about awareness, not only code.
I think documentation is a minimum, and a conversation with the users of this code should be a "must".

**Comment by prometheanfire** [comment]
I'll bring it up at the meeting

**Comment by prometheanfire** [comment]
so, options (as I see them)

1. only update docs to tell support to do it themselves (we don't make changes like this), also, submit a but to have the base images updated (doesn't help cdc)
2. use the ssh role that's brought in by openstack-ansible.  This stomps on the sshd_config and removes settings laid down by openstack-ansible-security.
3. create new role (we don't have one in rpc-o that's for pre-setup) that set's up the sshd_config file and does not interfere with what openstack-ansible-security lays down.

I first chose option 3, but people didn't like that, so tried option 2.  I'd much prefer to go back to option 3 as I feel it's the correct solution.

**Comment by odyssey4me** [comment]
Regarding option 2, if the right vars are fed to the role it would not stomp on the settings set by the security role.

**Comment by prometheanfire** [comment]
@odyssey4me so I'd have to read in the file, set the right variables, then run the rolle that stomps on the file to change the least amount of things?  I fee like this would be a bit more complicated then option 3.  If upstream switches to using the role for setting up ssh in osa-security then I'd think we can be fine.  @major what do you think.

**Comment by odyssey4me** [comment]
@prometheanfire No, set the vars to get to the end goal config that is desired. It produces the opinionated sshd_config. If the goal desired is simply to change one line, then just use a lineinfile change. The decision that has to be made is whether we're managing the config or not. If we are, then own the whole thing and make it opinionated. If we're not, then don't touch it and just document what happens if you go beyond the boundaries set by the defaults.

**Comment by prometheanfire** [comment]
@odyssey4me so are we suposed to ignore whether or not osa-security is enabled?  Because if it's enabled we would be modifying the file, again, disabling it's security.  The problem we have is that we have two incompatible methods of modifying the file.  If using the ssh role we cannot also use osa-security.  My role was as close as we could get to lineinfile (and in fact does use line in file as part of it).

**Comment by odyssey4me** [comment]
@prometheanfire I'm not sure how I can make this any clearer. If you give the ansible-sshd role the right vars then it will configure sshd_config any way you want it to be.

In other words, if there is a conflict between the defaults of the two roles - then you can set both roles to use the same settings.

I'm not sure how else I can explain that both roles are configurable and can result in the same config file laid down. It only takes the right vars to be set.

**Comment by prometheanfire** [comment]
@odyssey4me please read https://github.com/openstack/openstack-ansible-security/blob/master/tasks/rhel6stig/sshd.yml  the ssh role will remove the marker at the very least.  I do agree that it can probably be converted to use the ssh role though, but that's more @major's domain.

**Comment by odyssey4me** [comment]
@prometheanfire No, actually it's the domain of any downstream consumer for the role. If you want it to behave differently then you push a patch up with the proposed change. That patch either gets accepted, rejected or feedback for improvement.

In the case of the security role the deployer (RPC) has the ability to enable/disable any part of what the role does. If RPC is using another role to rewrite sshd_config which complies with the same rules which the STIG recommends, then the compliance bit is covered and we all go along our merry way.

**Comment by prometheanfire** [comment]
@odyssey4me I'm fine with submitting the patch, I just want to verify with upstream before doing the work.

**Comment by major** [comment]
Even if the `sshd_config` is rewritten by the sshd ansible module, someone could re-run the security role and have those additional configurations appended.

**Comment by prometheanfire** [comment]
True, if they are always run as a pair the output would remain the same.  I'm not sure that's a good thing though (requiring them to always run together).

**Comment by mattt416** [comment]
A couple questions for my own understanding:

1. Are we trying to eliminate ssh errors here or are we trying to improve performance?
2. Support are already deploying big environments, so what combination of forks and MaxSessions are they using?  If they are adjusting MaxSessions, how are they doing that?

One thing I noticed running rpc-openstack on a low resource VirtualBox VM specifically is that we have an inconsistent fork configuration.  For example, in rpcd/playbooks/ansible.cfg we set `forks = 15` and in scripts/functions.sh we do `export FORKS=${FORKS:-$(grep -c ^processor /proc/cpuinfo)}`.  Perhaps a good place to start would be removing these inconsistencies (and bringing things in line w/ how it's done in openstack-ansible), and then look at updating sshd_config if we're looking to further improve performance?

--Matt

**Comment by odyssey4me** [comment]
Agreed.

In my view we keep it simple - we just add to the documentation that when executing playbooks against the control plane & swift storage (not sure where else we're using delegate_to a lot) that forks should remain 10 and below. For compute forks can be set to any number. With the documentation should be an explanation of why this different behaviour is important.

**Comment by prometheanfire** [comment]
@mattt416 
1. We are trying to eliminate errors
2. unknown @BjoernT what specific options (forks) are you using in large envs to hit this
3. I think this is just support

I think removing the setting of forks in `rpcd/playbooks/ansible.cfg` would be enough to get some consistency.

@odyssey4me 

Doc updates alone are fine if support is satisfied with it, but I do think making forks consistent between `rpcd/playbooks/ansible.cfg` and `scripts/functions.sh` would be a good idea (as @mattt416 suggests)

**Comment by odyssey4me** [comment]
If you use the ``ANSIBLE_FORKS`` environment variable, it overrides the setting in ``ansible.cfg``. I would recommend removing the setting entirely from ansible.cfg or setting it to 10 at the maximum. The setting can still be overridden at will through the environment variable, but at least the default will be safe.

**Comment by prometheanfire** [comment]
@odyssey4me yep, that part sounds good (removing the setting from `ansible.cfg`)  I think that all three of us agree on that.  Once I get a little more direction from support I think we'll be good.

@BjoernT would a doc update for this be sufficient?

**Comment by evrardjp** [comment]
I'd remove it everywhere we mention it, and leave that to the deployer to tweak with an env var.
But explaining that fiddling with the var is "at your own risk".

**Comment by major** [comment]
One of the reasons why I had trouble with ``lineinfile`` for the ssh configuration is due to those ``Match`` configurations at the end of the ``sshd_config``.  You can't place any lines below the ``Match`` configuration lines because the ssh daemon will think they're associated with those match configurations.

For the security role, I had to find a spot above the match configs and add a marker. I then add each configuration right under the marker.

**Comment by prometheanfire** [comment]
if suggesting `lineinfile` with the `before` option on a `sshd_config` file with multiple match stanzas it will place the line above the LAST match, breaking the config.

**Comment by major** [comment]
Yeah, if you have a situation like this:

```
Match User user1
    X11Forwarding no
Match User user2
    X11Forwarding no
```

and you tell Ansible to add a line before "^Match", you get:

```
Match User user1
    X11Forwarding no
<-- Line added by Ansible here -->
Match User user2
    X11Forwarding no
```

![Facepalm](http://www.reactiongifs.com/r/facepalm.gif)

**Comment by alextricity25** [comment]
@prometheanfire Thanks for looking into this!
After reading through the comments both here and in the connected PR, it sounds like the best thing to do for us right now would be to document and clean up any inconsistencies that @mattt416 mentioned. I don't think it's worth introducing the ``rpc_setup_infrastructure`` role at the moment, but if it's something people think we should do, then we can create a separate card that covers the entirety of that scope of work.

**Comment by prometheanfire** [comment]
@alextricity25 I'm not sure that will solve the actual issue, the stuff he noted should be moved to a separate card in my opinion.

**Comment by b3rnard0** [comment]
@prometheanfire Is this still blocked?

**Comment by prometheanfire** [comment]
I'd say no
