### ISSUE TITLE
Incorrect ceph role is being pulled down

### ISSUE THREAD

**Issue by mattt416** [rcbops/rpc-openstack#1071]
##### What version (commit) do you encounter this issue on?

12.1.1

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

Ceph should deploy, it does not.

##### What is actually happening?

Ceph does not deploy.  It throws an error when deploying MONs stating:

```
fatal: [ceph-aio_ceph_mon_container-26e67c07] => error while evaluating conditional: cephx and is_ceph_infernalis
```

##### How can we reproduce this issue?

Deploy 12.1.1 w/ DEPLOY_CEPH=yes

##### How can we verify your issue is addressed?

The deploy of ceph will fail with the above error.

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

As a deployer, you can:

```
# cd /opt/rpc-openstack/rpcd/playbooks/roles
# rm -rf ceph.ceph-common
# ln -s ceph-common/ ceph.ceph-common
```

##### What is your evaluation on the importance of this issue, and why?

High

This issue is due to the galaxy roles for ceph-ansible updating, but the issue is actually due to our configuration.  Originally, the role was called ceph-common, but it is now called ceph.ceph-common.  A dependency has been added to all the roles on ceph.ceph-common which means we install both ceph-common and ceph.ceph-common (installed automatically as a dependency).  When ceph is deployed, it uses ceph.ceph-common which is newer than the ceph-common we pull down and hence the failure.

This was actually an issue before, but the ceph-ansible galaxy roles were updated today which brought master of ceph.ceph-common much further ahead than the ceph-common we were pinning. 

###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.2
- [x] liberty-12.1

**Comment by prometheanfire** [comment]
hmm, I have hit this in gate, so it's gate blocking as well, going to raise to expedited because of that

**Comment by prometheanfire** [comment]
needs backports

**Comment by prometheanfire** [comment]
closing, all merged
