### ISSUE TITLE
Use Kibana version >= 4

### ISSUE THREAD

**Issue by galstrom21** [rcbops/rpc-openstack#1073]
##### What version (commit) do you encounter this issue on?
12.1.1

##### What type of issue is this (bug, feature, documentation, regression)?
enhancement

##### What is the expected behavior?
An updated kibana would remove the need for an enduser's browser to connect directly with elasticsearch. As well as adding the ability to start using the elasticsearch beats dashboards.

##### What is your evaluation on the importance of this issue, and why?
Medium

The new version of Kibana will help with operator adoption of the ELK into their workflow, as it is now accessible over an SSH tunnel. This is also a precursor to being able to use ElasticSearch beats for additional data collection from the environment.

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2

**Comment by git-harry** [comment]
This issue was closed because there is already an effort underway to address concerns related to the current logging solution.
