### ISSUE TITLE
All maas plugins broken in Liberty after upgrade from Kilo

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1080]
##### What version (commit) do you encounter this issue on?

r12.1.1

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

It Works

##### What is actually happening?

All maas plugins broken in Liberty after upgrading from Kilo

```
/usr/lib/rackspace-monitoring-agent/plugins# ./hp_monitoring.py
Traceback (most recent call last):
  File "./hp_monitoring.py", line 17, in <module>
    import maas_common
  File "/usr/lib/rackspace-monitoring-agent/plugins/maas_common.py", line 51, in <module>
    from cinderclient import client as c_client
  File "/usr/local/lib/python2.7/dist-packages/cinderclient/client.py", line 46, in <module>
    from eventlet import sleep
  File "/usr/local/lib/python2.7/dist-packages/eventlet/__init__.py", line 10, in <module>
    from eventlet import convenience
  File "/usr/local/lib/python2.7/dist-packages/eventlet/convenience.py", line 3, in <module>
    from eventlet import greenio
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 440, in <module>
    from OpenSSL import SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 68, in <module>
    error=-1)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 57, in wrapper
    ffi.def_extern(name=name, **kwargs)(func)
AttributeError: 'CompiledFFI' object has no attribute 'def_extern'
```

##### How can we reproduce this issue?

N/A

##### How can we verify your issue is addressed?

N/A
##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Prio 1

##### What is your evaluation on the importance of this issue, and why?

Customer impacting 

###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.2
- [x] liberty-12.1

**Comment by BjoernT** [comment]
So I fix this temporarily with 
 pip install --force-reinstall nova

The issue is that none of the MAAS plugin stuff runs inside a VENS and nova was still 2015.1.4 while the liberty version is now 12.x, so a normal pip install would never upgrade the package due to the "downgrade of versioning"

So all maas python plugins have to implement the OSA venvs

**Comment by mancdaz** [comment]
@BjoernT 

How can we reproduce this issue? N/A
How can we verify your issue is addressed? N/A
If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution? Prio 1

This is not very helpful - in order to help fix these issues please include al of this information. Understanding the environment in which you saw this as well as how to reproduce it makes it much easier for us to address.

**Comment by BjoernT** [comment]
@mancdaz I can only answer what I can and that includes how to reproduce it. Just upgrade a Kilo to Liberty and go from there. That's all I know.

**Comment by mancdaz** [comment]
@BjoernT that's my point - nowhere in your bug report did you mention that this is encountered on an upgrade. That's crucial information that makes a difference.

**Comment by BjoernT** [comment]
Yes that is fine, just let me know if you need info and I usually provide it.

**Comment by sigmavirus24** [comment]
/me is currently working through an upgrade

**Comment by BjoernT** [comment]
Looks like reinstalling cryptography fixed it in my aio test.
On first glance it did not even update/downgrade packages doing that:

Installing collected packages: setuptools, enum34, ipaddress, pyasn1, six, idna, pycparser, cffi, cryptography
  Found existing installation: setuptools 21.0.0
    Uninstalling setuptools-21.0.0:
      Successfully uninstalled setuptools-21.0.0
  Found existing installation: enum34 1.1.2
    Uninstalling enum34-1.1.2:
      Successfully uninstalled enum34-1.1.2
  Found existing installation: ipaddress 1.0.16
    Uninstalling ipaddress-1.0.16:
      Successfully uninstalled ipaddress-1.0.16
  Found existing installation: pyasn1 0.1.9
    Uninstalling pyasn1-0.1.9:
      Successfully uninstalled pyasn1-0.1.9
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: idna 2.0
    Uninstalling idna-2.0:
      Successfully uninstalled idna-2.0
  Found existing installation: pycparser 2.14
    Uninstalling pycparser-2.14:
      Successfully uninstalled pycparser-2.14
  Found existing installation: cffi 1.3.1
    Uninstalling cffi-1.3.1:
      Successfully uninstalled cffi-1.3.1
  Found existing installation: cryptography 1.2.2
    Uninstalling cryptography-1.2.2:
      Successfully uninstalled cryptography-1.2.2
Successfully installed cffi-1.3.1 cryptography-1.1.2 enum34-1.1.1 idna-2.0 ipaddress-1.0.15 pyasn1-0.1.9 pycparser-2.14 setuptools-21.0.0 six-1.10.0

**Comment by sigmavirus24** [comment]
So I just did an upgrade to r12.1.2 and couldn't reproduce this. Granted it was an AIO and not a multinode. But every plugin I tried worked perfectly fine after running setup-maas.yml to ugprade the maas bits.

**Comment by BjoernT** [comment]
@sigmavirus24  Did you try the upgrade with ` echo 'pip_install_options: "--force-reinstall"' >> /etc/openstack_deploy/user_deleteme_post_upgrade_variables.yml` ?

**Comment by sigmavirus24** [comment]
@BjoernT I ran the upgrade with that today and again couldn't reproduce it when trying to upgrade to r12.1.2.

**Comment by sigmavirus24** [comment]
Wait, I may have spoken too soon. 💃

**Comment by sigmavirus24** [comment]
Yep, I did speak too soon. I can reproduce this and I have a fix that's hilariously simple I think

**Comment by sigmavirus24** [comment]
@BjoernT check out #1102

**Comment by BjoernT** [comment]
Can we make it part of a pip package (rackspace-monitoring or similar) so that pip installs will trigger it rather than the playbooks.

**Comment by sigmavirus24** [comment]
Uh, I don't think so. The monitoring agent is a lua package that we put on our mirrors for people to use. I guess we could put work into making the plugins into a pip package that has those dependencies, but I'm not sure how we like that. #1102 is at least a stop-gap solution for this particular problem.

I'm also fairly certain that we manually put the plugin scripts into a very particular location on disk so that the monitoring agent will find them. It would be a lot of shenanigans to get them into the right place through python packaging (although probably possible).

**Comment by prometheanfire** [comment]
needs backports
