### ISSUE TITLE
OSA [1544425]: 12.1.1 /etc/swift/dispersion.conf using wrong auth version

### ISSUE THREAD

**Issue by timolow** [rcbops/rpc-openstack#1089]
##### What version (commit) do you encounter this issue on?
DISTRIB_RELEASE="r12.1.1"
##### What type of issue is this (bug, feature, documentation, regression)?
Bug
##### What is the expected behavior?
Swift-dispersion-* should work properly with values set in /etc/swift/dispersion.conf
##### What is actually happening?
v2 of keystone is still present in dispersion.conf
##### How can we reproduce this issue?
install 12.1.1 and run swift-dispersion-populate from any swift proxy node.
(swift-12.0.13)root@infra1_swift_proxy_container-5f1bc8c4:/openstack/venvs/swift-12.0.13/bin# swift-dispersion-populate
Using storage policy: default
Traceback (most recent call last):
  File "/openstack/venvs/swift-12.0.13/bin/swift-dispersion-populate", line 164, in <module>
    insecure=insecure)
  File "/openstack/venvs/swift-12.0.13/lib/python2.7/site-packages/swiftclient/client.py", line 490, in get_auth
    auth_version=auth_version)
  File "/openstack/venvs/swift-12.0.13/lib/python2.7/site-packages/swiftclient/client.py", line 418, in get_auth_keystone
    raise ClientException('Authorization Failure. %s' % err)
swiftclient.exceptions.ClientException: Authorization Failure. Authorization Failed: The resource could not be found. (HTTP 404) (Request-ID: req-99c40219-9153-479b-ab76-874cfc156638)

##### How can we verify your issue is addressed?

swift-dispersion-* should run without issue on new install.

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

update value to 3.0
##### What is your evaluation on the importance of this issue, and why?
low
###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.2
- [x] liberty-12.1

**Comment by BjoernT** [comment]
https://bugs.launchpad.net/openstack-ansible/+bug/1544425

**Comment by prometheanfire** [comment]
only kilo to go, but kilo is dead so....

**Comment by mancdaz** [comment]
@prometheanfire it's not dead yet either in OSA or rpc-o. The upstream backport needs to be done.

**Comment by BjoernT** [comment]
The liberty back port has been done with https://review.openstack.org/#/c/318914/, so if we bump the SHAs we are afterwards

**Comment by mancdaz** [comment]
@BjoernT kilo

**Comment by BjoernT** [comment]
I don't think we have to fix that in kilo, considering we are v2 only there

**Comment by mancdaz** [comment]
@BjoernT good shout, thanks
