### ISSUE TITLE
CDM alarms should have both warning and critical threshold

### ISSUE THREAD

**Issue by kstev** [rcbops/rpc-openstack#1091]
##### What version (commit) do you encounter this issue on?
r12.2.0

##### What type of issue is this (bug, feature, documentation, regression)?
Feature

##### What is the expected behavior?
CDM alarms should possess a CRITICAL threshold so that a Rackspace support ticket will be generated on tripping the alarm.
 
##### What is actually happening?
For example, the cpu_check alarm will never generate a support ticket as there is no critical threshold defined. This being the case, 90% of Rackspace customers will never derive much value from this alarm.

##### How can we reproduce this issue?
Generate very high CPU (stress?). Monitor for MaaS alert tickets. See none

##### How can we verify your issue is addressed?
Generate very high CPU (stress?). Monitor for MaaS alert tickets. See alerts

##### What is your evaluation on the importance of this issue, and why?
Low. Not having a critical threshold did cause us to not see an issue and therefore caused a 24 hour "outage" for one of my customers that experienced a hardware issue. That being said, it was probably an edge case.

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2
- [ ] liberty-12.1
- [ ] kilo

**Comment by git-harry** [comment]
This was never backported to liberty, was that intentional?
