### ISSUE TITLE
Cinder service check failed

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1098]
##### What version (commit) do you encounter this issue on?

r11.1.9

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

cinder service check will locate cinder-scheduler services on bare metal along with proper reporting of the cinder-volume_status metric when one or many backends are down

##### What is actually happening?

```
Print service array:
{u'status': u'enabled', u'binary': u'cinder-scheduler', u'zone': u'nova', u'host': u'12345-cinder01', u'updated_at': u'2016-05-22T20:59:33.000000', u'state': u'up', u'disabled_reason': None}
{u'status': u'enabled', u'binary': u'cinder-volume', u'zone': u'nova', u'host': u'12345-cinder01@lvm', u'updated_at': u'2016-05-22T20:59:32.000000', u'state': u'up', u'disabled_reason': None}
{u'status': u'enabled', u'binary': u'cinder-backup', u'zone': u'nova', u'host': u'12345-cinder01', u'updated_at': u'2016-05-22T20:59:33.000000', u'state': u'up', u'disabled_reason': None}

Plugin output:
status okay
metric cinder-volume-lvm_status uint32 1
metric cinder-backup_status uint32 1
```
##### How can we reproduce this issue?

Install maas on a cinder bare metal which also runs the cinder-scheduler

##### How can we verify your issue is addressed?

No more errors

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Prio 2

##### What is your evaluation on the importance of this issue, and why?

Customer plugins report false alarms now

###### Remove branches (lines) you do not wish to target.
- [x] Master (#1241)
- [x] liberty-12.2 (#1250)
- [x] kilo

**Comment by andymcc** [comment]
I've submitted a fix that takes into consideration the feedback from the previous PR - since we hadn't had movement in 4 weeks - if we can get that reviewed and merged we can close this out (post backports).

**Comment by andymcc** [comment]
Will need to adjust the actual monitors to match the metrics.

**Comment by andymcc** [comment]
OK passing tests -ready for reviews!

**Comment by sigmavirus24** [comment]
@alextricity25 why did you close this?

**Comment by andymcc** [comment]
ok we're all done - backports are ready. closing this out!
