### ISSUE TITLE
Please add a place for support scripts

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1099]
##### What version (commit) do you encounter this issue on?

Any
##### What type of issue is this (bug, feature, documentation, regression)?

Feature
##### What is the expected behavior?

As the rpc-o support folks, we see a need to contribute scripts to RPC-O in order or ease administration and make the product easier to consume for all admin folks.
##### What is actually happening?

N/A
##### How can we reproduce this issue?

N/A
##### How can we verify your issue is addressed?

N/A
##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

N/A
##### What is your evaluation on the importance of this issue, and why?

---
###### For each pull request, update the branch line to reference it.
- [x] master - https://github.com/rcbops/rpc-openstack/pull/1035
- [ ] mitaka-13.1
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo
##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:
##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:
##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.
##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues)
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc)
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by prometheanfire** [comment]
The main think I'm not sure of here is if it should target all the way back to kilo or not, it's a smaller change that shouldn't effect much in practice though.

**Comment by BjoernT** [comment]
@prometheanfire  This is only of master, perhaps liberty

**Comment by npawelek** [comment]
@prometheanfire Any update on this issue?

**Comment by prometheanfire** [comment]
This needs to be put in a swimlane, can someone join our triage meeting or bug @b3rnard0 about this?

**Comment by b3rnard0** [comment]
@rcbops/support-feedback This is marked as prio-3. Is this of a higher priority than the issues currently marked as prio-2? Was there a reason this was not discussed at the bug triage? We are happy to update the priority on this if we all agree that is the case and we'll commit to it once have capacity.

cc: @git-harry @mancdaz @claco @prometheanfire

**Comment by robb-romans** [comment]
Is there a docs impact?

**Comment by npawelek** [comment]
@b3rnard0 I spoke with @BjoernT about this and his thoughts were that the work has pretty much been completed and it needed to either be merged or provide feedback on any problems. Priority wise I think it's fine.. just something we may be able to knock out quickly.

**Comment by git-harry** [comment]
@npawelek the triage meeting is where we discuss/agree what the engineering team will commit to work next. If an issue already has a pull request, that may mean it flows more quickly along the stages of our process but that does not allow to skip parts of it. As an engineering team our expectation is that there is support representation at the triage meetings that is able to highlight and discuss what are currently considered to be support's most important issues to address.

If you ever want to check what we are currently working on, take a look at [our board](https://waffle.io/rcbops/u-suk-dev). If it is not on the board, we have made no commitment to it.

**Comment by b3rnard0** [comment]
@alextricity25 Created a meeting to discuss this issue.

**Comment by alextricity25** [comment]
PR #1035  is ready for review

**Comment by alextricity25** [comment]
Due to the amount of changes that were made in #1035, and the amount of discussion that we had, I don't feel like it's necessary to backport this change given our current priorities. @BjoernT would it be okay with you if this change was kept on master? It would be included in the Newton release.

**Comment by BjoernT** [comment]
Yes it would be OK if we don't back port it since this particular problem only existed to due the different validation inside verify-local
