### ISSUE TITLE
horizon extension fails to update/install

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1100]
##### What version (commit) do you encounter this issue on?

r12.1.1

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

Installs without errors

##### What is actually happening?
```
TASK: [horizon_extensions | Install python dependencies] **********************
failed: [Infra01_horizon_container-8ed2a89b] => {"cmd": "/usr/local/bin/pip install --force-reinstall -r /opt/rackspace/horizon-extensions/requirements.txt", "failed": true}
msg: stdout: Ignoring indexes: https://pypi.python.org/simple
Collecting markdown (from -r /opt/rackspace/horizon-extensions/requirements.txt (line 1))

:stderr: DEPRECATION: --allow-all-external has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
  Could not find a version that satisfies the requirement markdown (from -r /opt/rackspace/horizon-extensions/requirements.txt (line 1)) (from versions: )
No matching distribution found for markdown (from -r /opt/rackspace/horizon-extensions/requirements.txt (line 1))

failed: [infra02_horizon_container-755bd245] => {"cmd": "/usr/local/bin/pip install --force-reinstall -r /opt/rackspace/horizon-extensions/requirements.txt", "failed": true}
msg: stdout: Ignoring indexes: https://pypi.python.org/simple
Collecting markdown (from -r /opt/rackspace/horizon-extensions/requirements.txt (line 1))

:stderr: DEPRECATION: --allow-all-external has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
  Could not find a version that satisfies the requirement markdown (from -r /opt/rackspace/horizon-extensions/requirements.txt (line 1)) (from versions: )
No matching distribution found for markdown (from -r /opt/rackspace/horizon-extensions/requirements.txt (line 1))

failed: [infra03_horizon_container-e5e8181e] => {"cmd": "/usr/local/bin/pip install --force-reinstall -r /opt/rackspace/horizon-extensions/requirements.txt", "failed": true}
msg: stdout: Ignoring indexes: https://pypi.python.org/simple
Collecting markdown (from -r /opt/rackspace/horizon-extensions/requirements.txt (line 1))

:stderr: DEPRECATION: --allow-all-external has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
  Could not find a version that satisfies the requirement markdown (from -r /opt/rackspace/horizon-extensions/requirements.txt (line 1)) (from versions: )
No matching distribution found for markdown (from -r /opt/rackspace/horizon-extensions/requirements.txt (line 1))
```

FATAL: all hosts have already failed -- aborting

##### How can we reproduce this issue?

Upgrade from Kilo to Liberty r12.1.1

##### How can we verify your issue is addressed?

Install works

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

N/A

##### What is your evaluation on the importance of this issue, and why?

Prio 2

###### Remove branches (lines) you do not wish to target.
- [x] Master -- #1104
- [x] liberty-12.2 -- #1108
- [x] liberty-12.1 -- #1127

**Comment by jpmontez** [comment]
Seeing this bug in r12.2.0rc2 [here](http://jenkins.openstack-ansible.com/job/RPC-OA/130/console).

Labelling as impacting QE.

**Comment by r1chardj0n3s** [comment]
Given that the requirement is for a bare package name "markdown" and that package exists and has a downloadable file on pypi.python.org I suspect some intermediary package mirror/cache is missing "markdown" for some reason.

**Comment by d34dh0r53** [comment]
I have a fix for this and I'm going to use it as the pair programming task for both @cloader89 and @Frank-ZhangXin we will get this merged tomorrow (`05/26/2016`)

**Comment by b3rnard0** [comment]
@d34dh0r53 Thanks. Do we think we can get an rc out tomorrow for it?

**Comment by d34dh0r53** [comment]
@b3rnard0 yeah, barring any gating issues we should be able to cut the RC.

**Comment by d34dh0r53** [comment]
@git-harry gating of #1104 took a really long time so I'm going to leave #1108 in your capable hands to get reviewed, voted and merged so that either of us can cut RC3 once it's in there.

**Comment by mancdaz** [comment]
re-opening as @evrardjp has some further investigation to do here. The patches do not necessarily solve the issue

**Comment by mancdaz** [comment]
I'm marking this bug closed. The fixes from @d34dh0r53 ensure that markdown is getting built as a pip wheel (by adding a _pip_packages section which gets parsed by the py_pkgs script), and given that the original issue was that the markdown wheel could not be found, I believe this to be adequate for the way horizon_extensions is getting installed in liberty.

The subsequent patch added in to master by @evrardjp is targeted at mitaka, and changes the way that horizon_extensions itself is getting built/installed. As this is effectively a refactor, I doubt we'd want to backport it.

**Comment by mancdaz** [comment]
After discussion we have decided to backport https://github.com/rcbops/rpc-openstack/pull/1156 to liberty branches. I will use this issue to target those PRs

**Comment by mancdaz** [comment]
- [ ] 12.1 backport https://github.com/rcbops/rpc-openstack/pull/1207
- [ ] 12.2 backport https://github.com/rcbops/rpc-openstack/pull/1208
