### ISSUE TITLE
OSA [1579612]: heat domain setup fails with keystone using self signed certs Edit

### ISSUE THREAD

**Issue by b3rnard0** [rcbops/rpc-openstack#1129]
##### What version (commit) do you encounter this issue on?

Master

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

See https://bugs.launchpad.net/openstack-ansible/+bug/1579612

##### What is actually happening?

See https://bugs.launchpad.net/openstack-ansible/+bug/1579612

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

See https://bugs.launchpad.net/openstack-ansible/+bug/1579612

##### How can we reproduce this issue?

See https://bugs.launchpad.net/openstack-ansible/+bug/1579612

##### How can we verify your issue is addressed?

See https://bugs.launchpad.net/openstack-ansible/+bug/1579612

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

See https://bugs.launchpad.net/openstack-ansible/+bug/1579612

##### What is your evaluation on the importance of this issue, and why?

See https://bugs.launchpad.net/openstack-ansible/+bug/1579612

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2
- [ ] liberty-12.1
- [ ] kilo

**Comment by b3rnard0** [comment]
@mancdaz Can you please add details to this card so that we can get the backport prioritized.

**Comment by mancdaz** [comment]
@b3rnard0 the patch has been committed to master and stable/mitaka branches in OSA. Someone will need to rework the patch for liberty (a straight cherry-pick won't work due to the change in role structure between liberty and stable/mitaka).  Once that's done and merged, a SHA bump will need to happen to include the OSA fix in rpc-o

**Comment by nategraf** [comment]
Back-port to Liberty submitted for review upstream 
https://review.openstack.org/#/c/347564/

**Comment by alextricity25** [comment]
@nategraf I made some comments.

**Comment by alextricity25** [comment]
@nategraf I've make some comments on the latest patch set

**Comment by nategraf** [comment]
Reviews that need to be completed in order:
1. https://review.openstack.org/#/c/348964/
2. https://review.openstack.org/#/c/348533/
3. https://review.openstack.org/#/c/348330/

Once all three of these patches are merged, this bug will be closed
