### ISSUE TITLE
cinder_volume maas template is looking for the wrong metric

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#1171]
##### What version (commit) do you encounter this issue on?

master (a457cf2cb3aa9c1fd079f7aa851fba1e636ac836)

##### What type of issue is this (bug, feature, documentation, regression)?

bug

##### What is the expected behavior?

The maas template to set up monitoring for the cinder services is looking for the wrong metric. The template can be found here https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/templates/cinder_volume_check.yaml.j2#L15

The template should set up the check against the correct metric (```cinder-volume-<backendname>_status```) which is reported by the plugin :

```
# ./cinder_service_check.py --host master1 172.29.236.100
status okay
metric cinder-volume-lvm_status uint32 1
metric cinder-backup_status uint32 1
```

##### What is actually happening?

The template is looking for the metric ```cinder-volume_status```:

```     if (metric["cinder-volume_status"] != 1) {```

An alarm is being triggered in maas:

```metric "cinder-volume_status" is not available```

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Setting up monitoring on an all in one - it's the only alarm that alerted

##### How can we reproduce this issue?

run an all in one on master, setting ```DEPLOY_MAAS=yes```, then go to intelligence.rackspace.com and check your aio server checks/alarms

##### How can we verify your issue is addressed?

Doing the above will result in no alarms

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

One could edit the template manually to deploy the correct check. Or disable the check in the console.

##### What is your evaluation on the importance of this issue, and why?

I'd suggest perhaps prio-3, 2 at worst.

###### Remove branches (lines) you do not wish to target.

Not actually sure when this was introduced so leaving all here for now

- [ ] Master
- [ ] liberty-12.2
- [ ] liberty-12.1
- [ ] kilo

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

**Comment by mancdaz** [comment]
Looks like this was introduced with ef3f99fb909da4c16adbc5dd33a21d22be5a38ca

**Comment by git-harry** [comment]
There is a related issue, https://github.com/rcbops/rpc-openstack/issues/1098, that is already in progress and will address this issue.
