### ISSUE TITLE
ceph_osd_stats check fails with > 10 osd

### ISSUE THREAD

**Issue by npawelek** [rcbops/rpc-openstack#1182]
##### What version (commit) do you encounter this issue on?

Kilo+
##### What type of issue is this (bug, feature, documentation, regression)?

bug
##### What is the expected behavior?

The ceph_osd_stats check is able to successfully complete with more than 10 osd
##### What is actually happening?

With more than 10 osd on a ceph node, the ceph_monitoring.py check will attempt to build five metrics per osd causing the check to fail due to the metrics limit of 50. It appears that we're building metrics for 'up', 'in', 'kb', 'kb_used', and 'kb_avail'. However, only metric 'up' is actually used by any current alarm criteria that is deployed up to the current Liberty release.
##### How can we reproduce this issue?

Run the check on a node with >10 osd with an updated limits in maas_common.py as outlined here: 
https://github.com/rcbops/rpc-openstack/issues/1180
##### How can we verify your issue is addressed?

Limit number of metrics allowing the check to pass. Potentially only building metrics against the values which are being used in alarm criteria.
##### What is your evaluation on the importance of this issue, and why?

Unable to effectively monitor ceph osd's
###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.2
- [ ] kilo
##### Does your change require documentation?
- [ ] No documentation required for this change

**Comment by mancdaz** [comment]
Given that we are primarily focused on monitoring with these plugins, rather than gathering arbitrary metrics for capacity planning (appformix is targeted at that), I would advocate removing those things that we are not alerting on.

**Comment by git-harry** [comment]
@npawelek to add further details.

**Comment by npawelek** [comment]
We generate 5 metrics per ceph OSD in the environment and we're only evaluating against 1, whether it's 'up' or not. Due to current metric limit of 50, when we deploy accounts with more than 10 ceph OSD, these checks will fail post-deploy. The deployment workaround is to comment out some of the unused metrics to allow evaluation of the checks once it's handed over to the customer. This typically results in commenting out the following lines where metrics are generated.

#        for key in ('kb', 'kb_used', 'kb_avail'):
#            name = '_'.join((osd_ref, key))
#            maas_common.metric(name, 'uint64', osd[key])

**Comment by tomc603** [comment]
@Frank-ZhangXin worked with @mattt416 yesterday to build an AIO with more than the default number of OSD.

**Comment by Frank-ZhangXin** [comment]
@mattt416 AIO with ceph is completed, but I wonder how we manually add more osd to one single osd node? Thanks

**Comment by mattt416** [comment]
@Frank-ZhangXin, if your AIO is already deployed, update /etc/openstack_deploy/user_rpco_variables_overrides.yml from:

```
osd_directories:
  - /var/lib/ceph/osd/mydir1
```

to:

```
osd_directories:
  - /var/lib/ceph/osd/mydir1
  - /var/lib/ceph/osd/mydir2
  - /var/lib/ceph/osd/mydir3
  - /var/lib/ceph/osd/mydir4
  - /var/lib/ceph/osd/mydir5
  - /var/lib/ceph/osd/mydir6
  ...
```

After that, you'll need to re-run ceph-osd.yml.

**Comment by Frank-ZhangXin** [comment]
Having issues with re-setup ceph afterward AIO deployment. Working with @mattt416 now.

**Comment by Frank-ZhangXin** [comment]
Update:
This bug is verified in master and can be reproduced. MaaS did send warning about exceed 50 metrics per OSD host.

**Comment by Frank-ZhangXin** [comment]
@git-harry Here's the cause of this bug: https://github.com/rcbops/rpc-openstack/blob/master/maas/plugins/ceph_monitoring.py#L73-L83
(5 different attributes: "up, in, kb, kb_used, kb_avaiblable")
Five different metrics normally are added to one OSD and MaaS side require maximum number of metrics won't be more than 50.
I don't know if every attribute really need a metric necessarily. Need advice, thanks.

**Comment by russwclark** [comment]
@npawelek @Frank-ZhangXin 
I think we could reduce the metrics collected to "up & kb_available" then we can figure out a threshold for kb_available and implement an alarm for that.  I think we should alarm when ceph is running out of space?  Nathan, what are your thoughts?

**Comment by Frank-ZhangXin** [comment]
@russwclark 
It would be OK with me if 'up' and 'kb_available' two are enough for metric. Looks Nathan is out today, but I'm gonna make a PR with this idea.

**Comment by b3rnard0** [comment]
@rcbops/support-feedback Feedback on this issue appreciated if Nathan is out for the next couple of days.

**Comment by npawelek** [comment]
@Frank-ZhangXin I apologize for the delay.

I'm fairly certain that we deploy file system disk space used checks/alarms for OSD mount points on ceph nodes. As such, I don't think it's necessary to retain anything other than the 'up' metric which is what we're alarming on. I'd rather limit the potential to hit the cap as I can see more than 25 ceph nodes being deployed in an environment.

Let me know if you have any additional questions or concerns.

**Comment by mancdaz** [comment]
@npawelek bear in mind, though, that when the plugin is called on any particular host, it will only be passed the IDs of the OSDs on that host (because of the way the maas template is constructed). So you aren't limited by the number of ceph storage nodes in an environment (or total OSDs in an environment which is what I *think* you were saying), but rather by the number of OSDs on an individual host. 25 in that case is probably plenty.

Having said that, your logic is sound if we already monitor the disk space on the mounts, and I'm all for removing redundant metrics, so just looking at 'up' still seems like a good suggestion to me.

**Comment by npawelek** [comment]
@mancdaz Correct, thanks for clarifying that

**Comment by Frank-ZhangXin** [comment]
@npawelek hey, Nathan, is it necessary still backport to Kilo?

**Comment by alextricity25** [comment]
@Frank-ZhangXin, the original bug description does mention it's also a problem with Kilo environments. I think it would be a good idea to backport this to Kilo.

**Comment by BjoernT** [comment]
FYI, in the past a back port was turned down since it's a change of the default behavior. I would have loved to get this addressed ASAP but we couldn't

**Comment by git-harry** [comment]
@Frank-ZhangXin why has this been moved to 'status-pending-sha-update'?

**Comment by Frank-ZhangXin** [comment]
@alextricity25 got it, will do soon
@git-harry sorry, that was a mistake and I should move it to done column.
