### ISSUE TITLE
MaaS API Authentication fails are not reported correctly

### ISSUE THREAD

**Issue by hughsaunders** [rcbops/rpc-openstack#1188]
##### What version (commit) do you encounter this issue on?
liberty / e828f30a68645bb489c439669facbad88288bbec

##### What type of issue is this (bug, feature, documentation, regression)?
bug

##### What is the expected behavior?
If MaaS credentials are missing or incorrect, the first task that attempts to use them should fail. 

##### What is actually happening?
MaaS credentials are used in a shell pipeline, where the last command in the pipeline is wc, which always succeeds. 

```
- name: Entity {{ entity_name }} count
  shell: "raxmon-entities-list | grep ' label={{ entity_name }} provider=Rackspace Monitoring ...>$' | wc -l"
  register: entity_count
```
[link](https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/tasks/raxmon_agent_install.yml#L41-L48)

This leads to a subsequent failure:

```
15:34:20 failed: [jrpcaioiad-c34] => {"failed": true}
15:34:20 msg: Zero entities with the label jrpcaioiad-c34 exist. Entities should be created as part of the hardware provisioning process, if missing, please consult the internal documentation for associating one with the device.
```

This failure is misleading, as the problem is not the lack of entities, but that inability of the previous task to query the api for entities.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Gate job for [rename user variables patch](https://github.com/rcbops/rpc-openstack/pull/1165)

##### How can we reproduce this issue?

Remove rackspace_cloud_* from the variables and deploy RPC including MaaS

##### How can we verify your issue is addressed?

Ensure that if MaaS credentials are missing or incorrect, the resulting failure indicates an inability to authenticate to the MaaS API. 

##### What is your evaluation on the importance of this issue, and why?

Low.. doesn't actually cause a failure, but can make diagnosing other failures more difficult.

###### Remove branches (lines) you do not wish to target.
- [ ] Master

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

**Comment by alextricity25** [comment]
This is a good candidate for impacts-onboarding if we end up having to look for more.

**Comment by b3rnard0** [comment]
- [ ] Reproduce the issue. (N/A)
- [ ] Create a PR for fix and/or docs.
- [ ] Incorporate feedback from pull request reviews.
- [ ]  What is the gating for this on DEV and/or QE? Add related gating if appropriate. Also make sure current gating passes with this fix.
- [ ] Reach out to reporter to determine if the fix is resolving the issue.
- [ ] What are the upgrade impacts (if any).
- [ ] What are the backports are needed (if any).
