### ISSUE TITLE
beaver has no access to /var/log/neutron/neutron-dnsmasq.log

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/rpc-openstack#119]
Beaver issues the following error on neutron containers:

```
[Errno 13] Permission denied: '/var/log/neutron/neutron-dnsmasq.log'
```

This is due to the fact that the ownership and permissions don't allow it:

```
-rw-r----- 1 nobody  root     1124 May 27 21:08 neutron-dnsmasq.log
```

We either need to find a way to set the mode to 644 or the ownership to a group which beaver is a member of, ie {beaver,syslog,adm}

**Comment by odyssey4me** [comment]
This is largely a cosmetic error and it doesn't absolutely have to be fixed. That said, the lack of indexing of this log file does mean that some errors may be missed.

**Comment by BjoernT** [comment]
Still a valid issue, if there are actively errors logged we should include them into beaver

**Comment by cloudnull** [comment]
We're no longer using Beaver. This can be dropped. Should this come back up or be something we need to address in the future please re-open the issue.
