### ISSUE TITLE
Add successorator to deploy.sh

### ISSUE THREAD

**Issue by alextricity25** [rcbops/rpc-openstack#1191]
##### What type of issue is this (bug, feature, documentation, regression)?
feature
##### What is the expected behavior?
Gate tests should be more reliable and not fail due to issues not related to the code being tested.

##### What is actually happening?
I propose that we implement a "successorator" function in deploy.sh. Similar to what is done here:
https://github.com/openstack/openstack-ansible/blob/master/scripts/scripts-library.sh#L43-L69

Gate tests are failing due to random issues that happen during the configuration/build phase and sometimes even when the tempest tests are running. This can be caused by short network downtimes, server resource constraints, network saturation, or race conditions.
These failures happen as a result of events happening *outside* of the new code being tested. This can lead to multiple, annoying and timely rechecks.

##### How can we verify your issue is addressed?
Assuming the new code changes are not a result of a failure, then we should see a rise in successful builds in Jenkins. In particular, the RPC Multinode jobs.

##### What is your evaluation on the importance of this issue, and why?
Medium, or prio-2. Development is not halted because of this and it doesn't affect the value of the product.

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2
- [ ] liberty-12.1
- [ ] kilo

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

**Comment by byronmccollum** [comment]
Deploy.sh is not exclusively used for gating, but is also used for production deployments.

Adding successorator can delay a failing deployment (think misconfiguration) from terminally halting as soon as possible. Successorator can also patch over issues (and has in the past) where tasks consistently fail the first attempt, and pass during subsequent attempts. It's use (especially in gating) can give a false impression of correctness. If something is failing, and successerator gets it to pass, then scrutiny is needed over *why* its not passing the first time.

In fact, successerator used to be part of deploy.sh, but was removed for some of these reasons.

https://github.com/rcbops/rpc-openstack/commit/9e7ffb4bd943a2b6354bfb6cca07ac4f1da9011e

**Comment by git-harry** [comment]
I am fundamentally opposed to anything like this. We need to be better at identifying and addressing bugs, as Byron has already said automatically rerunning on failure just increases the likelihood that more bugs will make it through.

**Comment by alextricity25** [comment]
I see both of your points.
What about breaking down the gating jobs into small chained tasks? For example, instead of having one job that runs the [build.sh](https://github.com/hughsaunders/rpc-heat-ansible/blob/rpc_gating/jenkins/build.sh) script, we first run a job that tests they laying down of the infrastructure(which will make sure all heat resources are successfully built), then test setup-hosts.yml, then setup-infrastructure, then setup-openstack, then the rpc-playbooks. We could even split these tasks into smaller jobs that test each individual playbook. So instead of saying "recheck_aio", it would be "recheck_openstack", or "recheck_cinder". 
I understand that this would mean the jenkins slave(s) would now need to live a little longer, but couldn't we implement a TTL on that environment? Instead of deleting it right after the job is complete, let it live for a while so the devs could invoke these smaller rechecks without having to re-build the environment. Is that at all possible or am I just dreaming? :)

**Comment by mancdaz** [comment]
@alextricity25 jenkins doesn't really work like that, but if it's a jenkins change you're after, you should file it over in https://github.com/rcbops/jenkins-rpc

/cc @hughsaunders

**Comment by git-harry** [comment]
It sounds like the benefit you're describing is that rechecks are potentially quicker. I dislike this because it's not a repeatable test. I come back to the point that if we're constantly getting hit by a bug we should fix it.

**Comment by git-harry** [comment]
This was discussed in today's meeting. The consensus was that this is invalid because it has the potential to hide genuine issues and that it would be better to attempt to address the issues in the playbooks than work around them.
