### ISSUE TITLE
old maas playbooks are still present

### ISSUE THREAD

**Issue by evrardjp** [rcbops/rpc-openstack#1209]
##### What version (commit) do you encounter this issue on?
master
##### What type of issue is this (bug, feature, documentation, regression)?
bug/whishlist
##### What is the expected behavior?
Since they have been deprecated for a while, these playbooks should have been removed
##### What is actually happening?
There are still useless files that can confuse people in the rpc/playbooks folder
##### How can we reproduce this issue?
ls rpcd/playbooks/maas* returns results
ls rpcd/playbooks/test-maas.yml returns results
##### How can we verify your issue is addressed?
ls rpcd/playbooks/maas* returns no results
ls rpcd/playbooks/test-maas.yml returns no results
##### What is your evaluation on the importance of this issue, and why?
Lowest importance ever?
##### What branches / milestones do you believe this issue should target?
- [ ] Master

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

**Comment by git-harry** [comment]
I believe the following files were only required by Kilo to Liberty upgrades and can now be removed.
```
$ ls rpcd/playbooks/maas*
rpcd/playbooks/maas-20151013-1-requirements.yml	rpcd/playbooks/maas-20151013-2-pre-migrate.yml	rpcd/playbooks/maas-20151013-3-purge-checks.yml	rpcd/playbooks/maas-20151013-6-post-migrate.yml
```

rpcd/playbooks/test-maas.yml in conjunction with maas/testing was used to test that MaaS deployment code was only modified as expected. This testing code has not been maintained for some time and is not currently used.

**Comment by b3rnard0** [comment]
- [x] Reproduce the issue. (N/A)
- [ ] Create a PR for fix and/or docs.
- [ ] Incorporate feedback from pull request reviews.
- [ ]  What is the gating for this on DEV and/or QE? Add related gating if appropriate. Also make sure current gating passes with this fix.
- [ ] Reach out to reporter to determine if the fix is resolving the issue.
- [ ] What are the upgrade impacts (if any).
- [ ] What are the backports are needed (if any).
