### ISSUE TITLE
[bug] logstash: if timestamp is in log, ensure that it replaces the timestamp the log was received

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/rpc-openstack#121]
In some logs, the timestamp of the event is recorded and this timestamp is derived into a field - however, some of the filters don't replace the event timestamp with that value. Each filter should be reviewed and edited to do this.

**Comment by rackertom** [comment]
@odyssey4me I'd love to talk about this for a second. Are we talking about events where the event data doesn't contain a time stamp value? Event timestamp is the ts assigned by logstash when the agent received/processed the event. Using that as a default value for the event data's timestamp value isn't a bad guess, but I wanted to be sure that we weren't talking about modifying the event's timestamp itself and instead talking about the event's data's timestamp.

**Comment by odyssey4me** [comment]
@rackertom The logs message contains a timestamp (ie the data) which may differ from the timestamp that logstash receives it. The message that needs to be stored is the time of the real event (ie that contained in the data) not the time that logstash received it. This is because there may be a backlog of logs, or network connectivity, or whatever that causes there to be a period of time where the logs are not transmitted at the time of generation.

**Comment by rackertom** [comment]
@odyssey4me Great. I just wanted to be sure we made this clear for future us, because those guys are probably jerks and might have done it wrong.

**Comment by odyssey4me** [comment]
This really needs to be fixed in the logstash filters. Right now the timestamps on events can't be trusted as they are often the timestamp the log was processed, not the timestamp for the event.

**Comment by mendeni** [comment]
https://rpc-openstack.atlassian.net/browse/RO-2316
