### ISSUE TITLE
Ceph Monitoring picks wrong OSD ids per node

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1213]
##### What version (commit) do you encounter this issue on?

12.1.3
##### What type of issue is this (bug, feature, documentation, regression)?

Bug
##### What is the expected behavior?

Checks are updated/installed with correct OSD count from the current OSD tree
##### What is actually happening?

After adding ceph OSD nodes we noticed the OSD ids for nodes did not match what was reported by Ceph:

```
ceph osd tree

-5  20.51990     host xxx-ceph004
 3   1.09000         osd.3                up  1.00000          1.00000
 9   1.09000         osd.9                up  1.00000          1.00000
12   1.09000         osd.12               up  1.00000          1.00000
19   1.00999         osd.19               up  1.00000          1.00000
25   1.00999         osd.25               up  1.00000          1.00000
30   1.00999         osd.30               up  1.00000          1.00000
34   1.00999         osd.34               up  1.00000          1.00000
39   1.00999         osd.39               up  1.00000          1.00000
45   1.00999         osd.45               up  1.00000          1.00000
49   1.00999         osd.49               up  1.00000          1.00000
55   1.00999         osd.55               up  1.00000          1.00000
59   1.00999         osd.59               up  1.00000          1.00000
65   1.00999         osd.65               up  1.00000          1.00000
70   1.00999         osd.70               up  1.00000          1.00000
76   1.00999         osd.76               up  1.00000          1.00000
81   1.00999         osd.81               up  1.00000          1.00000
86   1.00999         osd.86               up  1.00000          1.00000
90   1.00999         osd.90               up  1.00000          1.00000
94   1.09000         osd.94               up  1.00000          1.00000
97   1.00999         osd.97               up  1.00000          1.00000
```

Whats currently in MAAS:

```
Host: xxx-ceph004

check: ceph_monitoring.py 

args
--name client.raxmon --keyring /etc/ceph/ceph.client.raxmon.keyring osd --osd_ids 85 70 81 34 95 55 80 12 75 28 9 45 19 86 54 97 65 30 49 13 23 39 76 98 3 94 8 59 18 25 90 38 33 43 
```
##### What were you attempting to do when you encountered this error (give as much detail as possible)?

Manually correct the issue
##### How can we reproduce this issue?

Adding new OSDs
##### How can we verify your issue is addressed?

OSD count matches tree
##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

N/A
##### What is your evaluation on the importance of this issue, and why?

Mid
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo
##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:
##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:
##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.
##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues)
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc)
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by mancdaz** [comment]
Hi @BjoernT was the monitoring correct before you added OSDs? How many OSDs did you add?

**Comment by mancdaz** [comment]
Also @BjoernT could you please describe the steps, and the playbooks you ran, to add the OSDs? Specifically, did you re-run the maas playbook(s) after adding the OSDs?

**Comment by BjoernT** [comment]
- The MAAS plugins were green before adding the nodes.
- We ran these plays in the following order to add hosts:
  - setup-hosts 
  - ceph-all
  - setup-infrastructure
  - setup-openstack
  - sites

Since this was done in a virtual lab I guess it would be easily reproducible with adding attached block devices

**Comment by mancdaz** [comment]
Hi @BjoernT the maas playbooks also need to be run to rebuild the maas config template, since that is what determines the args that get passed to the plugin (in this case, the OSD ids). It would be great if you could reproduce first, and then try running the setup-maas.yml playbook and see if that corrects the issue.

If there are still issues, it would be useful to see the output of ```ls -l /var/lib/ceph/osd``` because this is what is used to determine the OSD ids to pass to the plugin in the template.

**Comment by BjoernT** [comment]
@mancdaz the maas playbooks are inside the site.yml

**Comment by mancdaz** [comment]
@BjoernT ok thanks. As I say, if you can reproduce it in the lab and provide the following, it would be really helpful to pin down what's going on:

Prior to adding OSDs:
- The list of actual running OSDs on the host, including IDs
- The relevant ceph maas config file (```/etc/rackspace-monitoring-agent.conf.d/ceph_osd_stats--xxxxxxxxx```)
- The output of ```ls -l /var/lib/ceph/osd``` on the affected host
- The host specific part of the output from ```ceph osd tree```

After adding new OSDs and running playbooks:
- The relevant ceph maas config file (```/etc/rackspace-monitoring-agent.conf.d/ceph_osd_stats--xxxxxxxxx```)
- The output of ```ls -l /var/lib/ceph/osd``` on the affected host
- The host specific part of the output from ```ceph osd tree```

**Comment by BjoernT** [comment]
This can not be delivered since we fixed it already to get the checks working. Please try reproducing it in the same way we on boarded the volumes

**Comment by Frank-ZhangXin** [comment]
Update: duplicating test enviroment, and expect more detail of this case. @BjoernT

**Comment by Frank-ZhangXin** [comment]
@BjoernT Can you tell me more about how you checked MaaS side OSD status? I saw ceph_monitoring.py is used for that, but no idea where the args are. Thanks.

**Comment by Frank-ZhangXin** [comment]
Update:

Test environment: AIO

Initially fresh new ceph deployment with 3 osd hosts and each one has 1 OSD (totally 3 OSDs).
Afterward following @BjoernT instruction, manually added one osd host and totally there're 4 OSDs existing after a serial of re-setups.

On monitor host, using `ceph osd tree`, 4 OSDs are displayed as 'osd0', 'osd1', 'osd2' and 'osd3', and status is green.
Checking same OSDs on MaaS by using `python ceph_monitoring.py --name client.raxmon --keyring /etc/ceph/ceph.client.raxmon.keyring osd --osd_ids #` for each OSD.

All status are showing normal and correct.

>root@frank-aio:/usr/lib/rackspace-monitoring-agent/plugins# python ceph_monitoring.py --name client.raxmon --keyring /etc/ceph/ceph.client.raxmon.keyring osd --osd_ids 0
status okay
metric osd.0_up uint32 1
metric osd.0_in uint32 1
metric osd.0_kb uint64 1238514032
metric osd.0_kb_used uint64 74912236
metric osd.0_kb_avail uint64 1113150248

@BjoernT What do you think about this? It looks the OSD ids not reordered or messed.

**Comment by Frank-ZhangXin** [comment]
@rcbops/support-feedback Hi, folks, anyone can give me some opinion or feedback? Thanks!

**Comment by Frank-ZhangXin** [comment]
Update: 
@b3rnard0 Just talk to @BjoernT about this bug, he said he would test this situation again by next week and would let us know what happens in customer environment.

**Comment by mancdaz** [comment]
from @BjoernT 

"Let’s close it for now.
The ask to add OSD is not often, we seem to have build a new ceph cluster last week rather than adding so the situation would be different.
I will open up the bug if it ever reappears, the AIO testing should be ok for now"

**Comment by Frank-ZhangXin** [comment]
@mancdaz thank you, Daren
