### ISSUE TITLE
Move holland into a venv

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#1215]
##### What version (commit) do you encounter this issue on?
master
##### What type of issue is this (bug, feature, documentation, regression)?
enhancement
##### What is the expected behavior?
Holland is run from a venv
##### What is actually happening?
Holland is installed directly in the galera containers
##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
N/A
##### How can we reproduce this issue?
N/A
##### How can we verify your issue is addressed?
Holland is contained within a venv
##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
N/A
##### What is your evaluation on the importance of this issue, and why?
Low. There are no known issues caused by this. This creates a layer of separation between the Python packages required by Holland and those that are required by the OSA galera containers.
###### Remove branches (lines) you do not wish to target.
- [ ] Master

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

**Comment by alextricity25** [comment]
We need to wait for https://github.com/rcbops/jenkins-rpc/pull/620 to merge before we can unblock this
