### ISSUE TITLE
Kibana config.js  has incorrect value for elasticsearch_public_url

### ISSUE THREAD

**Issue by Rydor** [rcbops/rpc-openstack#1223]
##### What version (commit) do you encounter this issue on?
12.2.0

##### What type of issue is this (bug, feature, documentation, regression)?
Bug

##### What is the expected behavior?
I would like to be able to log into a working kibana portal

In the kibana container on the logging node, if you;
cd /opt/kibana-3.1.2/ 
less config.js 
look for the elasticsearch: value and not see a trailing /

##### What is actually happening?
The kibana portal is currently giving an error indicating it can't connect to the elasticsearch server. 

I believe this is because:
Currently running the /rpcd/playbook/kibana.yml playbook attempts to setup the kibana role. The rpc-openstack/rpcd/playbooks/roles/kibana/defaults/main.yml specifies on line 23
elasticsearch_public_url: '"https://"+window.location.hostname+":8443/elasticsearch/"' 

As a result of the trailing / when kibana finishes setting up and you browse to the kibana portal you get an error connecting to elasticsearch server. If you are in chrome you can use the developer console to see the url that is being used to communicate with elasticsearch has "Request URL:http://204.232.187.36:8443/elasticsearch//_nodes/" 

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Log into the kibana portal
##### How can we reproduce this issue?
Attempt to access the kibana portal after running a greenfield deployment with deploy elk = true witin deploy.sh
##### How can we verify your issue is addressed?
Once you can actually log into the kibana portal.
##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
If you log into the logging node and connect to the kibana container then modify the /opt/kibana-3.1.2/config.js file to change the elasticsearch: value to; elasticsearch: "http://"+window.location.hostname+":8443/elasticsearch" it will work.

I have verified the fix works, but i am not sure if that is the correct way to fix this issue.

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2
- [ ] kilo

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

**Comment by Rydor** [comment]
There were actually two changes that had to be made to https://"+window.location.hostname+":8443/elasticsearch/ 

The first was to remove the trailing / and the second was to change https to http. I wasn't sure if the second was due to how we have ELK setup in the QE lab and/or if it was ok to run on http.

**Comment by git-harry** [comment]
I haven't tested this but based on the assumption that Kibana is broken, I've set this a prio-1. In addition the var elasticsearch_public_url can be overridden as a workaround instead of manually modifying the config file.

**Comment by BjoernT** [comment]
Interesting, this exact config works for us since we use F5 and SSL certs are properly installed.
I guess it is little unrealistic to test against HTTP knowing that we run HTTPS on the public side, no customer would accept HTTP on public IPs. I assume you guys tested against a haproxy ?

**Comment by git-harry** [comment]
@Rydor I'm attempting to reproduce the issue you have described but have had no success. I have deployed an AIO of r12.2.0 and Kibana works for me - I am able to login and the dashboard displays event data. In /var/log/apache2/ssl_access.log I see the following entries related to URL you reference:
```
172.29.236.100 - - [13/Jul/2016:16:20:29 +0000] "GET /elasticsearch//_nodes HTTP/1.1" 200 3958 "https://x.x.x.x:8443/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
172.29.236.100 - - [13/Jul/2016:16:20:29 +0000] "GET /elasticsearch//_nodes HTTP/1.1" 200 3958 "https://x.x.x.x:8443/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
```

While it does appear that the value of elasticsearch_public_url should be modified it also does not appear to be having any adverse effects.

This value appears to have ended with a '/' since the code was first introduced 9c01d070, that combined with my inability to reproduce the issue and @BjoernT's comment that he also not seeing this it leads me to believe the '/' is not the root cause. Have you tried reproducing it? It would be helpful if you are able to define the exact steps to create the failure. What user vars are you setting?

**Comment by Rydor** [comment]
Unfortunately I did not deploy either of the environments which I tested this in. I have verified the same issue was occurring in both qe-iad3-lab02 and qe-iad3-lab03. I also verified that the proposed fix resolved the issue in both labs. 

From my initial research into ELK I attempted to setup an AIO with ELK. I noticed that the AIO does not deploy the ELK stack to a logging node like we have in the labs. Instead an AIO has the ELK stack setup in containers on the infra node(or only node part of the AIO install). This difference between how the lab is setup and how an AIO is setup may explain the differences in our testing results.

**Comment by git-harry** [comment]
I have tested this on a multinode deployment built using heat but was unable to reproduce the issue. @Rydor would you mind taking a look at the logs on your deployments and updating this issue with those that record the issue you're seeing.

**Comment by b3rnard0** [comment]
@Rydor Any updates? Thank you!

cc: @tbyrom138

**Comment by Rydor** [comment]
Sorry for the delay, I have been working with Jacob to get more information. After digging in further we believe this to be related to an environmental issue involving the F5 load balancers and the expired certificates within out labs. We are going to continue to track this as an environment issue as we were unable to reproduce in an AIO, multi-node CS deployment, nor in SAT6.

At this time please feel free to close this issue. If we uncover any additional information which might be relevant we will open a new issue with more information, but at this time we believe this to be related to environment issues.
