### ISSUE TITLE
deploy.sh fails on Rackspace standard 30GB flavor cloud server

### ISSUE THREAD

**Issue by nategraf** [rcbops/rpc-openstack#1235]
##### What version (commit) do you encounter this issue on?
master

##### What type of issue is this (bug, feature, documentation, regression)?
bug

##### What is the expected behavior?
The deploy.sh script should automatically detect the main install partition (mounted to the root directory) as well as any additional valid data partitions. The script should be able to differentiate between an available data partition which the user wants to utilize and a partition which is invalid, such as a  small swap partition as it was in this case.  The existence of a swap partition should not cause the install to fail.

##### What is actually happening?
It appears that the script is attempting to use the 2GB xvdc device as a data partition addition to the main partition which is mounted to root. When checking to make sure the xvdc device is large enough to be utilized as a data partition, the check fails. It considers this a failure condition for deployment.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
I was running the deploy.sh script in installation of an AIO node onto a Rackspace standard  30GB server flavor cloud server.

##### How can we reproduce this issue?
Spin up a Rackspace standard  30GB flavor cloud server, or any other VM with a secondary device designate as swap storage, then run the following commands:
`# apt-get update`
`# git clone --recursive https://github.com/rcbops/rpc-openstack /opt/rpc-openstack`
`# cd /opt/rpc-openstack/`
`# ./scripts/deploy.sh`

##### How can we verify your issue is addressed?
Run the above steps and if the deploy script completes without failing on disk size check, the issue is fixed.

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
Delete line 53 from deploy.sh. This will ensure that the script does not try to install a data drive.

##### What is your evaluation on the importance of this issue, and why?
Medium. I will only impact some systems and is fairly simple to work around.

###### The list below is what is currently supported for backports
- [x] Master
- [ ] liberty-12.2
- [ ] kilo

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

[1]
paste.openstack.org/show/532084/

**Comment by nategraf** [comment]
In order to fix this issue an approach needs to be decided.  So far I have found two places where the behavior can be changed to fix this issue.

- The deploy.sh script could be barred from automatically configuration  on data partitions, and instead specify data partition manually, or ask for confirmation before trying to configure the partition. 
- A data drive failing the size check could remove it from future configurations rather than failing the whole deployment

**Comment by alextricity25** [comment]
Although I'm not completely against the first option, it might break some of the tooling that uses the deploy.sh if we require the invoker to input a data partition(for example, Jenkins, i also have a tool that uses deploy.sh and depends on being to run without user interaction). On the other hand, you could always use environment variables to keep the script non-interactive. However, that still might require these other tools to make changes on their side, which is best to avoid.

What about writing in some logic to check to see if the device has a swap partition? If so, do nothing, if not,  then assign it as the DATA_DISK_DEVICE. The logic can be written up some where around here:
https://github.com/rcbops/rpc-openstack/blob/master/scripts/deploy.sh#L50

**Comment by odyssey4me** [comment]
The allocation of the secondary disk was lifted from the gate-check-commit script in OSA. That has since evolved, so it'd perhaps be best to try something similar instead of re-inventing the wheel.

See https://github.com/openstack/openstack-ansible/blob/master/scripts/gate-check-commit.sh#L43-L52

**Comment by nategraf** [comment]
Until this bug is fixed here are two options to work around it:
1. Comment out the following lines 48 and 49 of deploy.sh [1]. This will prevent the script from recognizing potential data partitions.
2. Use the 30GB computer flavor for the server instead. 

[1]
[](https://github.com/rcbops/rpc-openstack/blob/master/scripts/deploy.sh#L48-L49)

**Comment by nategraf** [comment]
Thanks odyssey4me for the pointer. I explored a couple other ideas, but the gate check code you linked seems to be the best approach.

**Comment by b3rnard0** [comment]
@nategraf What's left on this is the backports?
