### ISSUE TITLE
Unable to exclude local checks with maas_excluded_checks override

### ISSUE THREAD

**Issue by npawelek** [rcbops/rpc-openstack#1251]
##### On which version(s) do you encounter this issue?

/opt/rpc-openstack/rpcd/playbooks# git describe --all
r12.1.1

##### What type of issue is this? Please tick the appropriate box.
- [X] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior? 

Override 'maas_excluded_checks' variable with the name of the local check you want to remove. Run the setup-maas.yml playbook to deploy checks except those in 'maas_excluded_checks'. After successful completion of the playbook, the associated check yaml files still exist and are loaded.

##### What is actually happening?

It appears that variable 'maas_excluded_checks' isn't being properly included in 'roles/rpc_maas/tasks/maas_exclude.yml' to remove local checks. Running setup-maas.yml with a different override variable name does properly remove the excluded check yaml definitions from '/etc/rackspace-monitoring-agent.conf.d'.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Remove the following checks for MaaS integration with Plumgrid:
neutron_dhcp_agent_check
neutron_l3_agent_check
neutron_linuxbridge_agent_check
neutron_metadata_agent_check
neutron_metering_agent_check
nova_api_metadata_local_check

##### How can we reproduce this issue?

Run setup-maas.yml with the default 'maas_excluded_checks' override in '/etc/openstack_deploy/user_extras_variables.yml'.

##### How can we verify your issue is addressed?

After deployment the associated checks do not have yaml definitions in '/etc/rackspace-monitoring-agent.conf.d'

##### If you are using or know of a workaround please describe the necessary steps?

1. Run setup-maas.yml with a different override variable name in '/etc/openstack_deploy/user_extras_variables.yml'.
2. Make the following changes to task 'roles/rpc_maas/tasks/maas_exclude.yml'
   a. Update the variable name to match override in the associated plays.
   b. Add another '-' between {{ item }}-{{ inventory_hostname }}. This appears to be resolved in https://github.com/rcbops/rpc-openstack/issues/1098, but is broken in r12.1.1.

##### What is your evaluation on the importance of this issue, and why?

Required for MaaS integration with Plumgrid

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by andymcc** [comment]
@npawelek I actually fixed this already in: https://github.com/rcbops/rpc-openstack/pull/1250 (I noticed it was broken when testing the cinder checks and made the quick change).
It's currently being back-ported where appropriate, so I'm going to close this bug out.
