### ISSUE TITLE
OpenCompute Hardware Monitoring Checks - Feature Request

### ISSUE THREAD

**Issue by txgunslinger77** [rcbops/rpc-openstack#1252]
##### On which version(s) do you encounter this issue? 

Quanta, Supermicro, OpenCompute

###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
\# git describe --all
12.0.16-8-g6992c9d

##### What type of issue is this? Please tick the appropriate box.
- [ ] bug - existing functionality that does not work for you as documented
- [X] feature - new functionality that you would like to see added

##### What is the expected behavior?
Alerts are generated for OpenCompute hardware failures such as degraded RAID arrays, failed adapters, etc.

##### What is actually happening?
Hardware failures/changes are occurring without any hardware-specific alerts being generated. Incidental alerts for services which require write access are being generated, but quicker resolution to the root issue is necessary to avoid time spent interpreting incidental alerts and correcting the actual problem.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
The file system on the deployment host (infra01) changed to read-only, which spawned errors, but nothing directly related to what caused db writes to fail (galera errors, etc.). A more specific and less interpretive method of determining hardware faults is necessary.

NOTE: It is currently unknown what caused this to happen, and the infra node in question will be re-imaged tomorrow unfortunately.

##### How can we reproduce this issue?
On a completed OpenCompute deployment, intentionally cause a hardware failure (recoverable type) and see what, if anything, alerts.

##### How can we verify your issue is addressed?
OpenCompute nodes will fire alerts for hardware failures/errors.

##### If you are using or know of a workaround please describe the necessary steps?
Other than Quanta's proprietary QSM monitoring product (an additional licensing cost not included with the hardware), there is nothing like Dell or HP hardware monitoring (OMSA, hpasscli, etc.) that is available for OpenCompute systems.

Workaround: In the absence of OpenCompute-specific hardware checks, perhaps using branded gear (HP, Dell) for the control plane (which have checks, though rpc-maas lacks hardware checks for these systems too), and leaving OpenCompute gear to be used as commodity devices (pets) for nova compute services may be a short-term solution.

##### What is your evaluation on the importance of this issue, and why?
Having 2 of 3 control nodes experience critical hardware issues without knowing they occurred is vital to the stability OpenStack private clouds. Quicker resolution to the root issue is necessary to correct the actual problem and avoid time spent interpreting incidental alerts.

In my experience, OpenCompute hardware lacks the quality and reliability compared to branded gear to be seriously considered for critical infrastructure private clouds, and certainly not for use in the control plane which supports any private cloud.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment]
This is being tracked as a feature enhancement on a separate list https://github.com/rcbops/u-suk-dev/issues/241

**Comment by txgunslinger77** [comment]
I have updated this feature request to exclude OpenCompute, and change the scope of the request to a hardware-agnostic file system monitoring check that tests read-write capability of the disks on a hypervisor. Please let me know if this should be a separate request.

**Comment by txgunslinger77** [comment]
I am unable to view the link - I simply get a 404 not found...

**Comment by git-harry** [comment]
@txgunslinger77 I'm confused now. Are you saying the original feature request was wrong and you aren't looking for hardware monitoring similar to that provided for Dell and HP hardware or was I mistaken in what you were requesting?

**Comment by txgunslinger77** [comment]
Sorry for the confusion. I'll try to explain...
Given that OpenCompute standard vendors have various classes of a given chassis with more or less features, the example I provided here was originally used to highlight the quality failings of OpenCompute gear. I believe I was in error doing so, given the aforementioned degrees of quality available - my experience was with the lowest quality standard, and thus not necessarily indicative.

That realization however, does not negate the crux of my request, that being the need for a specific check to monitor for file system write status (RO vs. RW). While I experienced this on OpenCompute hardware, what happened could potentially occur on any hardware. Having an infra node suddenly go into Read-only mode has serious implications for the entire deployment, as Galera has just lost quorum, and this is the main reason for my request.

I apologize for the confusion, as I had not fully distilled my need before submitting this request. Please let me know if I should revert and close this to open a new request, or something else. This is my first submission and any guidance in the ways of git would be appreciated.

**Comment by git-harry** [comment]
My interpretation of what you've said is that there are two things here:
1. there is no hardware monitoring in place for OpenCompute similar to what is currently in place for Dell/HP gear
2. you had a filesystem go into read-only mode.

If that's the case then we should keep the issues separate, this helps us with tracking and reporting on the work. Leave this one as was to record the general requirement for hardware monitoring and create a separate issue for the specific filesystem monitoring requirement.

**Comment by txgunslinger77** [comment]
yes you have it correct and I will open a separate issue for the file
system check, thank you

**Comment by git-harry** [comment]
Thanks @txgunslinger77
