### ISSUE TITLE
No LBaaS Neutron Checks for MaaS - RPC 12.2

### ISSUE THREAD

**Issue by brainerd123** [rcbops/rpc-openstack#1263]
##### On which version(s) do you encounter this issue?
12.2 series

###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

Liberty 12.2

heads/stable/mitaka

##### What type of issue is this? Please tick the appropriate box.
- [X ] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

There are no MaaS checks for lbaas as part of the 12.2. release.  

##### What is actually happening?

We had an LbaaS neutron agent go down and there was no MaaS so we weren't notified.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Use LBaaS

##### How can we reproduce this issue?

Install the latest MaaS against 12.2.

##### How can we verify your issue is addressed?

These are the only checks MaaS has for Neutron/LBaaS on the infra

 (chIRTND4iH) [ Enabled] [      OK] [    neutron_metering_agent_check] Period: 60
 (chbR60RBIM) [ Enabled] [      OK] [            lb_api_check_neutron] Period: 60
 (chiLgQrVGT) [ Enabled] [      OK] [         neutron_api_local_check] Period: 60
 (chjbyS9KZB) [ Enabled] [      OK] [ neutron_linuxbridge_agent_check] Period: 60
 (chnEzg24Tu) [ Enabled] [      OK] [        neutron_dhcp_agent_check] Period: 60
 (chnX1kaGTS) [ Enabled] [      OK] [          neutron_l3_agent_check] Period: 60
 (chx5mDEyyU) [ Enabled] [      OK] [    neutron_metadata_agent_check] Period: 60

##### If you are using or know of a workaround please describe the necessary steps?

No work around other than manually checking the service.

##### What is your evaluation on the importance of this issue, and why?

High.  This is a new release/feature and MaaS should have been included. 

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment]
This feature is still in tech preview and so does not include monitoring support.
