### ISSUE TITLE
scripts/deploy.sh can't run twice on master

### ISSUE THREAD

**Issue by evrardjp** [rcbops/rpc-openstack#1273]
##### On which version(s) do you encounter this issue?
master

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
Ability to use ./scripts/deploy.sh multiple times

##### What is actually happening?
Impossible to use ./scripts/deploy.sh multiple times, due to a failure in a mv line.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Ran the ./scripts/deploy.sh , it failed for an unrelated reason, then restarted the scripts/deploy.sh, which activated a different part of its code, by checking the existence of the folder /etc/openstack_deploy. (It wasn't existing before for, and it now exists after my first run)

##### How can we reproduce this issue?
Run the script twice.

##### How can we verify your issue is addressed?

You can run the script twice.

##### What is your evaluation on the importance of this issue, and why?
Moderate priority: High criticality (could impact gates for minor upgrades later, negative impact on deployer confidence, ...) - Low impact (master only - no customer affected) 

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by evrardjp** [comment]
Probably a 
`if test -f /etc/openstack_deploy/user_variables.yml; then`

on L62 and L121 would help.

**Comment by mancdaz** [comment]
@evrardjp at what point did your run fail for you to see this? If ```/etc/openstack_deploy``` already exists, the step to mv the ```/etc/openstack_deploy/user_variables.yml ``` file would be skipped.

Can you please provide very clear steps to reproduce?

**Comment by evrardjp** [comment]
Sorry my bad, it's a problem with my paste, it's not in user_variables, but for secrets.

L62 is to be ignored. Only L121 is important.
