### ISSUE TITLE
Reporting the remaining steps when upgrade.sh fails

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#1300]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
all versions
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
If upgrade.sh fails it should return a list of the remaining steps required to complete the upgrade, similar to what is done by [openstack-ansible](https://github.com/openstack/openstack-ansible/blob/master/scripts/run-upgrade.sh#L66-L78).
##### What is actually happening?
If the upgrade fails while running OSA's run-upgrade.sh script, the remaining OSA steps will be reported but under no circumstances are RPCO specific steps listed.
##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
This can be seen when there is a failure while running upgrade.sh
##### How can we reproduce this issue?
Run scripts/upgrade.sh and view the output if it fails.
##### How can we verify your issue is addressed?
If upgrade.sh fails it will list the remaining steps to be completed.
##### If you are using or know of a workaround please describe the necessary steps?
Reviewing the script will allow one to work out what is left to do.
##### What is your evaluation on the importance of this issue, and why?
This does not prevent upgrades from happening but does make failure recovery harder.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
Would this be address by https://review.openstack.org/#/c/352488/, @Frank-ZhangXin??

**Comment by Frank-ZhangXin** [comment]
@alextricity25 seems people don't agree they're same, but they might be similar. I can take a look at this one as well.

**Comment by git-harry** [comment]
To confirm 352488 does not address this issue. The upstream review is to fix a bug in the OSA upgrade script run-upgrade.sh. This issue is to address the lack of reporting by upgrade.sh, the RPCO upgrade script, when it fails.

**Comment by cloader89** [comment]
I will start with a Liberty -> Mitaka fix, then do a Kilo -> Liberty

**Comment by cloader89** [comment]
Update @git-harry it appears that this has already been done in both upgrades. Can you verify?

**Comment by cloader89** [comment]
@git-harry I see that upgrade.sh has two other files, scripts-library.sh and deploy.sh. Did you want recursive fail reports or just for upgrade.sh?

**Comment by git-harry** [comment]
@cloader89 deploy.sh makes sense but not scripts-library.sh. We might want to break deploy.sh off into a separate task. Have a go with upgrade.sh and see how that goes.

**Comment by cloader89** [comment]
Update: I am rewriting some of the items in upgrade.sh  to have it iteratively keep track of what's being run -- should have a PR by the end of the day.

**Comment by cloader89** [comment]
Update: I am still working on it, found a good piece from the run-upgrade.sh file in OSA I am templating. 

What's left to do: Finish up the new upgrade.sh file and test it.

Do I have any blockers: no

**Comment by cloader89** [comment]
Update: Worked on my PR from 1236 today. It has been in review for a while, spending time focusing on that. I am also looking into seeing if I can include the .sh files as part of the replay of remaining tasks. Using a lock/trap methodology.

**Comment by cloader89** [comment]
Made significant progress today. I have written a draft of the changes I wish to propose for deploy.sh. Since deploy.sh is the only file that has the playbooks for RPC-O, not already inside of OSA. I have created a branch. https://github.com/rcbops/rpc-openstack/tree/issues/1300

Here is the failed output of upgrade.sh (deploy.sh) of what I have left.
http://paste.openstack.org/show/582821/

@git-harry please let me know what your thoughts are so far. If you are satisfied, I will create a PR.

Additionally, @Apsu had mentioned to potentially add a resume capability in the script to essentially pick back up where it failed. Thoughts? Maybe in actually upgrade.sh?

**Comment by cloader89** [comment]
Update: Ready for reviews
