### ISSUE TITLE
Swift Logs Need Multiline Regular Expression

### ISSUE THREAD

**Issue by sigmavirus24** [rcbops/rpc-openstack#1305]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

```
# git describe --all
heads/master
```
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added
##### What is the expected behavior?

Filebeat should be detecting multiline logs in swift logs and shipping them to logstash as multiline events. The Beaver role did not do this previously so the Filebeat role didn't add it. This is a bug in that we should be doing this (like we do for every other service) and a feature in that swift does not use `oslo.log` so it's log format is different and thus requires a new regular expression.
##### What is actually happening?

See [this event](https://104.239.156.122:8443/app/kibana#/doc/logstash-*/logstash-2016.08.09/log?id=AVZwaMTvXLZuH-GTE9vm&_g=%28refreshInterval:%28display:Off,pause:!f,value:0%29,time:%28from:'2016-08-09T17:45:22.454Z',mode:absolute,to:'2016-08-09T17:45:23.997Z'%29%29) as an example. The Traceback is not turned into a multiline log event.
##### What were you attempting to do when you encountered this error (give as much detail as possible)?

Test #1299 
##### How can we reproduce this issue?

Deploy RPC OpenStack, log into kibana and search using

```
source:/var/log/swift/swift-proxy-server.log Traceback
```
##### How can we verify your issue is addressed?

When the above search shows results that are multiline strings that have the full traceback.
##### If you are using or know of a workaround please describe the necessary steps?

n/a
##### What is your evaluation on the importance of this issue, and why?

Low importance because of the fact that we did not previously provide this functionality and were aiming for parity. This should be fixed post r13.0.0 release in my opinion.

---
###### For each pull request, update the branch line to reference it.
- [x] master
- [ ] mitaka-13.1
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo
##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:
##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:
##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.
##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues)
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc)
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by sigmavirus24** [comment]
@erikmwilson since you're handling the documentation for our logging updates, you should probably add this as a known-bug.

**Comment by d34dh0r53** [comment]
I have created a PR that captures the most common multi-line messages in the various swift logs.  The problem with swift logs are that there are multiple entities that are multiline and the filebeat multiline patterns do not make it easy to perform multiple checks.  I am going to investigate using logstash to gather the other multiline entities.
