### ISSUE TITLE
verify-maas only works on an AIO

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#1306]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

heads/master

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
The verify-maas.yml playbook completes successfully, or rather is at least able to run (even if some alarms are failing, which could be legitimate)

##### What is actually happening?
On all nodes except the deployment node, ansible fails because the task is trying to use the ```rpc-maas-tool.py``` script from ```/opt/rpc-openstack/scripts```, and that directory only exists on the deployment host.

```
TASK: [Verify Checks & Alarms are registered] *********************************
ok: [533800-node11]
failed: [533811-node15] => {"attempts": 8, "changed": false, "cmd": ". /openstack/venvs/maas-UNKNOWN_RELEASE/bin/activate\n /opt/rpc-openstack/scripts/rpc-maas-tool.py verify-created --entity 533811-node15.ukospoc.com", "delta": "0:00:00.005510", "end": "2016-08-09 16:54:33.766599", "failed": true, "failed_when_result": true, "rc": 127, "start": "2016-08-09 16:54:33.761089", "stdout_lines": [], "warnings": []}
stderr: /bin/sh: 2: /opt/rpc-openstack/scripts/rpc-maas-tool.py: not found
msg: Task failed as maximum retries was encountered
failed: [533810-node14] => {"attempts": 8, "changed": false, "cmd": ". /openstack/venvs/maas-UNKNOWN_RELEASE/bin/activate\n /opt/rpc-openstack/scripts/rpc-maas-tool.py verify-created --entity 533810-node14.ukospoc.com", "delta": "0:00:00.004363", "end": "2016-08-09 16:54:33.895546", "failed": true, "failed_when_result": true, "rc": 127, "start": "2016-08-09 16:54:33.891183", "stdout_lines": [], "warnings": []}
stderr: /bin/sh: 2: /opt/rpc-openstack/scripts/rpc-maas-tool.py: not found
msg: Task failed as maximum retries was encountered
failed: [533809-node13] => {"attempts": 8, "changed": false, "cmd": ". /openstack/venvs/maas-UNKNOWN_RELEASE/bin/activate\n /opt/rpc-openstack/scripts/rpc-maas-tool.py verify-created --entity 533809-node13.ukospoc.com", "delta": "0:00:00.004165", "end": "2016-08-09 16:54:33.909117", "failed": true, "failed_when_result": true, "rc": 127, "start": "2016-08-09 16:54:33.904952", "stdout_lines": [], "warnings": []}
stderr: /bin/sh: 2: /opt/rpc-openstack/scripts/rpc-maas-tool.py: not found
msg: Task failed as maximum retries was encountered
failed: [533808-node12] => {"attempts": 8, "changed": false, "cmd": ". /openstack/venvs/maas-UNKNOWN_RELEASE/bin/activate\n /opt/rpc-openstack/scripts/rpc-maas-tool.py verify-created --entity 533808-node12.ukospoc.com", "delta": "0:00:00.006509", "end": "2016-08-09 16:54:33.932594", "failed": true, "failed_when_result": true, "rc": 127, "start": "2016-08-09 16:54:33.926085", "stdout_lines": [], "warnings": []}
stderr: /bin/sh: 2: /opt/rpc-openstack/scripts/rpc-maas-tool.py: not found
msg: Task failed as maximum retries was encountered
```

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Run a multinode deployment and verify that mass was configured successfully by running the ```verify-maas.yml``` playbook

##### How can we reproduce this issue?

Do a multinode deployment, run ```setup-maas.yml```, and then run ```verify-maas.yml```, and you will see the errors

##### How can we verify your issue is addressed?

When the ```verify-maas.yml``` playbook is run, it is at least able to complete on all nodes (even if perhaps some checks/alarms are failing)

##### If you are using or know of a workaround please describe the necessary steps?

copy the entire ```/opt/rpc-openstack/scripts``` directory over to each host

##### What is your evaluation on the importance of this issue, and why?

Somewhat important, given that the deploy script runs verify-maas as part of the deployment - all multinode deployments using this will fail.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master https://github.com/rcbops/rpc-openstack/issues/1306

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [x] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links: this will be addressed by the multinode gating work

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment]
Liberty is already using the script module, the change to venvs introduced this bug.
