### ISSUE TITLE
cinder_backup maas check doesn't use venv

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#1307]
##### On which version(s) do you encounter this issue?

heads/master
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added
##### What is the expected behavior?

The cinder backup check is created as expected, using the venv wrapper where necessary
##### What is actually happening?

The cinder backup check was added without the 'run_plugin_in_venv' wrapper, which creates the check incorrectly. It actually still runs, but at some point if dependencies are added in to the venv in the future, that don't exist on the host, it will fail.

https://github.com/rcbops/rpc-openstack/blob/e1dd1a4ab74d8de14d6ffedb7d53b3c6d6d913c0/rpcd/playbooks/roles/rpc_maas/templates/cinder_backup_check.yaml.j2#L7-L8
##### What were you attempting to do when you encountered this error (give as much detail as possible)?

Run a multinode deployment, and then run setup-maas and check the cinder_backup template.

Expected content:

```
---snip---
details     :
    file    : run_plugin_in_venv.sh
    args    : ["/usr/lib/rackspace-monitoring-agent/plugins/cinder_service_check.py", "--host", "533811-node15", "192.168.100.2"]
---snip---
```

Actual content:

```
---snip---
details     :
    file    : cinder_service_check.py
    args    : ["--host", "533811-node15", "192.168.100.2"]
---snip---
```
##### How can we reproduce this issue?

Run a multinode deployment, and then run setup-maas and verify-maas - the cinder_backup check template will not have the run_plugin_in_venv wrapper.
##### How can we verify your issue is addressed?

After running setup-maas, check the cinder_backup template and ensure it has the run_plugin_in_venv wrapper configured
##### If you are using or know of a workaround please describe the necessary steps?

At this time, not necessary as the plugin still runs
##### What is your evaluation on the importance of this issue, and why?

Low as the plugin still runs from outside the venv

---
###### For each pull request, update the branch line to reference it.
- [x] master - https://github.com/rcbops/rpc-openstack/pull/1570
- [x] mitaka-13.1 https://github.com/rcbops/rpc-openstack/pull/1578

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:
##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:
##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.
##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues)
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc)
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by Frank-ZhangXin** [comment]
@mancdaz hi, Darren, did this only happened when multi-node deployment? Previous venv patch of MaaS should be based on AIO test environment I think. Thanks.

**Comment by mancdaz** [comment]
@Frank-ZhangXin this is a new template that got added after the venv patch went in, so it probably got missed because of timing.

**Comment by Frank-ZhangXin** [comment]
@mancdaz Not sure if we have enough WIP to move this to doing. So that I can start working on this.

**Comment by Frank-ZhangXin** [comment]
Update:
Added cinder_backup_check to venv and verified the feasibility. Going to create a PR for this soon.

**Comment by alextricity25** [comment]
Please don't forget to backport this to mitaka-13.1.
There is no need to backport to liberty or kilo since we don't use virtual environment's for maas plugins there.

**Comment by Frank-ZhangXin** [comment]
@alextricity25 thanks for remind, and I'm working on them still.

**Comment by git-harry** [comment]
@Frank-ZhangXin I have merged the backport however I would have expected to see a release note as part of the patch. I will defer to @alextricity25 to confirm whether one is required and how to proceed.

**Comment by alextricity25** [comment]
@Frank-ZhangXin, @git-harry. It would be nice to have a releasenote detailing the fix.
@Frank-ZhangXin Could you create one for this and link the PR to this bug report?
