### ISSUE TITLE
filebeat service is not started on containers with first run of playbook

### ISSUE THREAD

**Issue by sigmavirus24** [rcbops/rpc-openstack#1310]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

master

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

The filebeat service should be started on containers after the first run of the `filebeat.yml` playbook.

##### What is actually happening?

`filebeat.yml` needs to be run a second time for filebeat to be started on containers.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Deploy RPC-OpenStack using deploy.sh. The filebeat playbook runs but filebeat does not start on the containers.

##### How can we reproduce this issue?

On an environment without filebeat installed with containers, run the filebeat playbook (or setup-logging) and check the service status on the containers. Run the playbook a second time and then check the service status on the containers. You'll also notice a spike in log events in kibana after the second run because filebeat is actually shipping logs to logstash at that point.

##### How can we verify your issue is addressed?

You run the filebeat playbook once and log events from keystone/glance/etc. are shipped to logstash

##### If you are using or know of a workaround please describe the necessary steps?

Run `filebeat.yml` a second time.

##### What is your evaluation on the importance of this issue, and why?

Blocking rc1

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master (https://github.com/rcbops/rpc-openstack/pull/1318)

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [x] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links: #1236 

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment]
This change is not tested by the existing setup.

**Comment by sigmavirus24** [comment]
@git-harry did you mean to comment on #1318 ?

**Comment by sigmavirus24** [comment]
@git-harry as I understand it, @tomc603 is including filebeat in his process monitoring work so it would be tested it just isn't tested now. Is that satisfactory?

**Comment by git-harry** [comment]
@sigmavirus24 yes if there is something to track the additional work that is fine but the general ask is that the description is updated to note it.

**Comment by tomc603** [comment]
@git-harry @sigmavirus24 The parent issue for the process monitoring work is #1236

**Comment by sigmavirus24** [comment]
Updated the description @git-harry
