### ISSUE TITLE
migrate-yaml.py not merging lists correctly

### ISSUE THREAD

**Issue by mattt416** [rcbops/rpc-openstack#1346]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

master (mitaka)

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

The migrate-yaml.py script should merge variable files correctly.

##### What is actually happening?

If the DeepDiff library sees a changed element in a list, it returns just that changed element.  That means migrate-yaml.py needs to go back and find out what the full list is, and then return the list w/ the changed element.  A quick example:

```
root@liberty-aio:/opt/rpc-openstack/scripts# cat 1 2 test.py
repo_build_upper_constraints_overrides:
- elasticsearch<2.1.0
- foo
repo_build_upper_constraints_overrides:
- elasticsearch>=2.1.0
- foo
from deepdiff import DeepDiff
import yaml

f1 = yaml.load(open('1', 'r'))
f2 = yaml.load(open('2', 'r'))

d = DeepDiff(f1, f2)
print d['values_changed']
root@liberty-aio:/opt/rpc-openstack/scripts# python test.py
{"root['repo_build_upper_constraints_overrides'][0]": {'new_value': 'elasticsearch>=2.1.0', 'old_value': 'elasticsearch<2.1.0'}}
root@liberty-aio:/opt/rpc-openstack/scripts#
```

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Merge old user_variables.yml file on a liberty deploy w/ the new variable files in rpco's master branch.

##### How can we reproduce this issue?

Deploy a liberty AIO, then run:

```
# /opt/rpc-openstack/scripts/migrate-yaml.py --overrides /etc/openstack_deploy/user_variables.yml --danger-mode DANGER
```

You'll see the following returned:

```
repo_build_upper_constraints_overrides'][0]: elasticsearch<2.1.0
```

##### How can we verify your issue is addressed?

Ensure that changed lists have the entire list rewritten to output, not just the changed element.

##### What is your evaluation on the importance of this issue, and why?

This blocks release of r13.1.0rc1.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by prometheanfire** [comment]
try with --info as well
