### ISSUE TITLE
Maas checks failing due to maas_common.py

### ISSUE THREAD

**Issue by phalmos** [rcbops/rpc-openstack#1350]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
r13.0.0rc1

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
Maas checks work

##### What is actually happening?
Maas check fail with error "cannot import keystoneclient"

##### What were you attempting to do when you encountered this error (give as much detail as possible)?
Install MaaS on Mitaka upgrade. Checks were failing. I tried to run them manually from the hosts and got the error: "cannot import keystoneclient". 

##### How can we reproduce this issue?
Install MaaS in Mitaka and run checks manually

##### How can we verify your issue is addressed?
manual run of any check works as expected

##### If you are using or know of a workaround please describe the necessary steps?
the maas_common script is attempting to import a library from keystoneclient client which no longer exists at the specified path.  The offensive line in maas_common.py is:
_**from keystoneclient.openstack.common.apiclient import exceptions as k_exc**_
 It should now be:
**_from keystoneclient import exceptions as k_exc_**

##### What is your evaluation on the importance of this issue, and why?
Very important as all checks fail without the above change.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by cloudnull** [comment]
To make this work we @phalmos and I needed to change ``from keystoneclient.openstack.common.apiclient import exceptions as k_exc`` to ``from keystoneclient import exceptions as k_exc`` as found here: [ https://github.com/rcbops/rpc-openstack/blob/51e68a8b8e99ce4d16c771ce023c2125a5bdcb2b/maas/plugins/maas_common.py#L198 ] which allowed maas_common to load. While this worked, it's likely that some of the exceptions we're depending on will be missing due to the change in import.

**Comment by git-harry** [comment]
@phalmos the report include the sentence 'Install MaaS on Mitaka upgrade.' r13.0.0rc1 does not support upgrading from Liberty, that support will not be in place till r13.1.0. Are you able to provide additional details regarding what you were attempting to do.

**Comment by git-harry** [comment]
@rcbops/support-feedback are you able to shed any more light on this issue?

**Comment by mattt416** [comment]
@phalmos doubt this is related, but just a reminder that the maas scripts need to be run via the venv, for example:

```
/usr/lib/rackspace-monitoring-agent/plugins/run_plugin_in_venv.sh /usr/lib/rackspace-monitoring-agent/plugins/keystone_api_local_check.py 172.29.237.50
```

**Comment by phalmos** [comment]
@git-harry This was an upgrade from Liberty to Mitaka.  I understand that this is not the upgrade version.  However, customer's requirements dictated the need to upgrade.  So, I went for it following the OSA docs.  All went well aside from this issue with MaaS.

**Comment by git-harry** [comment]
@phalmos thanks for the update. Based on the work @mattt416 is doing, https://github.com/rcbops/u-suk-dev/issues/204, I'm going to mark this issue as invalid. It appears there error you encountered was a result of using the greenfield rc.
