### ISSUE TITLE
Flat network creation throws a disabled warning

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/rpc-openstack#1359]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
r13.0.0rc1

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
Flat network creation is allowed and works out of the box

##### What is actually happening?
Neutron agent is throwing a error stating that flat networks are disabled

```
TASK: [os_tempest | Ensure public network exists] *****************************
skipping: [node84_utility_container-2450f7b5]
skipping: [node89_utility_container-da65ebfb]
failed: [node98_utility_container-3f6bee67] => {"failed": true, "parsed": false}
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Traceback (most recent call last):
  File "<stdin>", line 2034, in <module>
  File "<stdin>", line 2031, in main
  File "<stdin>", line 1799, in command_router
  File "<stdin>", line 1927, in _create_network
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 97, in with_params
    ret = self.function(instance, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 681, in create_network
    return self.post(self.networks_path, body=body)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 363, in post
    headers=headers, params=params)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 298, in do_request
    self._handle_fault_response(status_code, replybody, resp)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 273, in _handle_fault_response
    exception_handler_v20(status_code, error_body)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 84, in exception_handler_v20
    request_ids=request_ids)
neutronclient.common.exceptions.BadRequest: Invalid input for operation: Flat provider networks are disabled.
Neutron server returns request_ids: ['req-640762b7-0955-4de2-99e4-8cf7190fc9bb']


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/os-tempest-install.retry

node84_utility_container-2450f7b5 : ok=28   changed=6    unreachable=0    failed=0
node89_utility_container-da65ebfb : ok=28   changed=6    unreachable=0    failed=0
node98_utility_container-3f6bee67 : ok=38   changed=9    unreachable=0    failed=1
```

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
I was installing the os_tempest role. There is a post install task that sets up the default configuration for tempest resources. One of these resources is a flat provider network called public

##### How can we reproduce this issue?
Install and run the os_tempest install role

##### How can we verify your issue is addressed?
Flat networks can be created and used

##### If you are using or know of a workaround please describe the necessary steps?
Currently the only information i can find about this error is as follows

https://bugs.launchpad.net/openstack-charm-testing/+bug/1594567
https://bugs.launchpad.net/charms/+source/neutron-gateway/+bug/1577915

It seems that the ml2 plugin doesnt allow empty string for config values so setting flat networks to an empty string no longer is valid.

```
# ML2 flat networks
[ml2_type_flat]
flat_networks =
```
it needs to be

```
# ML2 flat networks
[ml2_type_flat]
flat_networks = *
```

I attempted to simply add the variable to user_osa_variables_overrides.yml as follows to allow arbitrary flat networks to be created.

```
neutron_provider_networks:
  network_flat_networks: "*"
```

This did not work do to more dictionary values needing to be set as follows

https://github.com/openstack/openstack-ansible-os_neutron/blob/stable/mitaka/defaults/main.yml#L352-L361

This may be a problem
##### What is your evaluation on the importance of this issue, and why?

This is a pretty important bug as without the request in the following issue we cannot get a tempest install without modifying the play

https://github.com/rcbops/rpc-openstack/issues/1356

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by hughsaunders** [comment]
@jacobwagner Are you using flat networks? If you are then flat_networks should be populated with a list of mappings for your flat networks.

If you aren't using any flat networks, then neutron_provider_networks.network_flat_networks should not be defined, then the config section will not be templated at all. 

From [ml2_conf.ini.j2](https://github.com/openstack/openstack-ansible/blob/liberty/playbooks/roles/os_neutron/templates/plugins/ml2/ml2_conf.ini.j2#L12-L18):
```
{% if neutron_provider_networks.network_flat_networks is defined %}

# ML2 flat networks
[ml2_type_flat]
flat_networks = {{ neutron_provider_networks.network_flat_networks }}

{% endif %}
```

The [example](https://github.com/openstack/openstack-ansible-os_neutron/blob/stable/mitaka/defaults/main.yml#L352-L361) you linked earlier should be fine if "network_flat_networks" is removed, eg:
```
neutron_provider_networks:
   network_mappings: "vlan:eth11"
   network_types: "vxlan,vlan"
   network_vlan_ranges: "vlan:1:1,vlan:1024:1025"
   network_vxlan_ranges: "1:1000"
```

Note that flat shouldn't be removed from network types if Neutron has already been deployed.

**Comment by jacobwagner** [comment]
We dont use flat networks for testing, we use vlan and vxlan, but we have never seen this error before when using tempest created flat networks. It seems like now we would have to define all of our flat networks before hand, which is new.

That example was straight from the OSA documentation. We have never had to have that dict in place to get any of the networks working as far as i know. And we def have never had to define a flat network, it always allowed arbitrary networks. If this is no longer the case then we will need to update how tempest uses a flat provider network out of the box

**Comment by jacobwagner** [comment]
@hughsaunders so rereading your question.

We dont define neutron_provider_networks.network_flat_networks. We never have. With that said we never needed to. With them not defined in the past we never got this error, and that is what I am trying to get across. I belive that the neutron client has changed functionality when it comes to undefined provider network types and them being allows to be arbitrary network names.

**Comment by hughsaunders** [comment]
Hey @jacobwagner, thanks for the updates. The tempest role is attempting to [create a public network](https://github.com/openstack/openstack-ansible-os_tempest/blob/master/tasks/tempest_resources.yml#L228-L243) of type flat - it assumes that flat networks will be available. In your situation flat networks aren't available so it fails. Tempest vars will need to be overridden so that the public network can be created with an alternate type such as vlan. 

The variables for controling the creation of the public network are defined in the defaults of the tempest role: [o-a-os_tempest/defaults/main](https://github.com/openstack/openstack-ansible-os_tempest/blob/stable/mitaka/defaults/main.yml#L69-L73):
```
tempest_public_subnet_cidr: "10.1.13.0/24"
tempest_public_net_provider_type: "flat"
tempest_public_net_physical_type: "flat"
tempest_public_net_seg_id: ""
tempest_public_router_external: "true"
```
These should be overridden in a variables file.

**Comment by b3rnard0** [comment]
@jacobwagner @jpmontez @tbyrom138 If we can get some feedback on the above, it would be most appreciated as we would like to get the rc2 done today.

**Comment by jpmontez** [comment]
I can confirm that overriding the Tempest networking variables works and leads to a successful playbook run.

For reference, I used these variables during my test:
```
tempest_private_subnet_cidr: "172.31.0.0/24"
tempest_private_net_provider_type: "vxlan"
tempest_private_net_seg_id: 1

tempest_public_subnet_cidr: "10.239.0.0/22"
tempest_public_net_provider_type: "vlan"
tempest_public_net_physical_type: "vlan"
tempest_public_net_seg_id: 613
tempest_public_router_external: "True"
```

**Comment by hughsaunders** [comment]
@jpmontez Excellent 🎉  glad it works. 

Closing as not-a-bug. The tempest role assumes flat networks, but this can be overridden for environments where flat networks are not available.

**Comment by b3rnard0** [comment]
Thanks peoples for getting this issue resolved!
