### ISSUE TITLE
RPC tunables missing for cinder

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1360]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added
##### What is the expected behavior?

Per https://review.openstack.org/#/c/360749/ we missed to maintain proper RPC settings.
Once this merges I like to add default values

cinder_rpc_thread_pool_size = {{ rpc_thread_pool_size }}
cinder_rpc_response_timeout = {{ rpc_response_timeout }}
##### What is actually happening?

Cinder is operated with default RPC settings which are too low if you (de)provision volumes in bulk, resulting in service disruption due to timing out 
##### How can we reproduce this issue?

N/A
##### How can we verify your issue is addressed?

Config is laid down with correct RPC default values
##### If you are using or know of a workaround please describe the necessary steps?

Where necessary we do one off config overrides
##### What is your evaluation on the importance of this issue, and why?

Prio 2

---
###### For each pull request, update the branch line to reference it.
- [x] master
- [ ] mitaka-13.1
- [ ] liberty-12.2
- [ ] kilo
##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:
##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:
##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.
##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues)
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc)
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment]
@BjoernT the top of the template had been chopped off, I have added it back but it is missing the version you see this issue.
 The section of the template below
```
This section is completed during the issue resolution process. If you are reporting an issue, please do not modify the section below.
```
is for use by the development team, please do not complete it because it is used to track the work as it is done.

Is there any reason this can't be achieved by updating user_osa_variables_defaults.yml with a config override? I.e.

```
cinder_cinder_conf_overrides:
  DEFAULT:
    executor_thread_pool_size: "{{ rpc_thread_pool_size }}"
    rpc_response_timeout: "{{ rpc_response_timeout }}"
```

**Comment by BjoernT** [comment]
As I said upstream I find it disturbing that you can override nova/neutron settings but not cinder. It would be inconsistent not doing it in the same way for cinder since overriding cinder.conf in default settings can cause conflicts

**Comment by git-harry** [comment]
Removed status-blocked, it appears to have been added by mistake.

**Comment by tomc603** [comment]
I've added a PR for this, but right now the "Needs Review" lane is at capacity.
