### ISSUE TITLE
r13.0.0rc2 lxc_container_caches not configured

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1382]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

greenfield deploy runs

##### What is actually happening?

```
TASK: [lxc_hosts | Download lxc cache(s)] *************************************
<172.19.40.7> ESTABLISH CONNECTION FOR USER: root
fatal: [773037-infra01] => One or more undefined variables: 'unicode object' has no attribute 'name'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/setup-hosts.retry
```

The issue is actually related to lxc_container_caches since lxc_hosts role does not preconfigure this override by default at /etc/ansible/roles/lxc_hosts/defaults/main.yml

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

I added

```
echo '
lxc_container_caches:
   - url: "https://rpc-repo.rackspace.com/container_images/rpc-trusty-container.tgz"
     name: "trusty.tgz"
     sha256sum: "56c6a6e132ea7d10be2f3e8104f47136ccf408b30e362133f0dc4a0a9adb4d0c"
     chroot_path: trusty/rootfs-amd64
' >> /etc/openstack_deploy/user_rpco_variables_overrides.yml
```
to overcome this issue

##### How can we reproduce this issue?

Just do a greenfield deploy

##### How can we verify your issue is addressed?

setup-hosts runs without error
##### What is your evaluation on the importance of this issue, and why?

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master
- [x] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [x] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by odyssey4me** [comment]
I'm not sure why you would want to set that override, as it is already the default set in the group_vars:

https://github.com/openstack/openstack-ansible/blob/stable/mitaka/playbooks/inventory/group_vars/hosts.yml#L44-L48

**Comment by BjoernT** [comment]
Closing this out which was related to a inventory screw up. Not sure why the group var has not been applied even if the inventory did not contain containers, the task should only delegate to hosts
