### ISSUE TITLE
filebeat apt repos not correctly added

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1384]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

r13.0.0rc2
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added
##### What is the expected behavior?

Task "Install Filebeat Apt Packages" does not fail
##### What is actually happening?

I noticed on first install of filebeat that the apt cache is not reliable updated in all containers even when using "update_cache: yes" , a manual apt-get update was necessary in order to update the cache prior to install the package.
##### What were you attempting to do when you encountered this error (give as much detail as possible)?

It seems we need to add a retry or a conditional task to update the cache manually once that happens. update_cache was never that reliable to begin with 
##### How can we reproduce this issue?

Unkown, since it's a race condition
##### How can we verify your issue is addressed?

Unknown
##### What is your evaluation on the importance of this issue, and why?

---
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo
##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:
##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:
##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.
##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues)
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc)
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment]
Given the nature of the bug and the ease of recovery I do not believe this should block the release of r13.0.0. I have marked it as a prio-2 and we will work on the assumption that this will be addressed in a future patch release.

**Comment by BjoernT** [comment]
Closing since we are likely not releasing r13 releases anymore
