### ISSUE TITLE
MAAS/verify-maas not work after r13.0.0rc2 install

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1391]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

No import errors

##### What is actually happening?

verify-maas.yml is throwing this error along with the maas checks, currently showing import keystoneclient errors too:

```
Checks and Alarms with failures:
 - Entity:enL774GY9g:infra03.sup-iad3-2.rpc.rackspace.com
   ! Check:remote.http:chfc0KRH10:lb_api_check_keystone-unspecified_lb: Completed:False Status:Connection refused
     ! Alarm:al4gw8ZLIf:lb_api_alarm_keystone:CRITICAL
   ! Check:agent.plugin:chg1mgeICG:cinder_scheduler_check-infra03-cinder-scheduler-container-44893d8d: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:altRXicB38:cinder_scheduler_status-infra03-cinder-scheduler-container-44893d8d:CRITICAL
   ! Check:agent.plugin:chmP6RvjHo:glance_api_local_check-infra03-glance-container-513246a4: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:alEIeo6qG0:glance_api_local_status-infra03-glance-container-513246a4:CRITICAL
   ! Check:agent.plugin:chnnCq98IM:nova_consoleauth_check-infra03-nova-console-container-7a696c48: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:al5k7uDOm1:nova_consoleauth_status-infra03-nova-console-container-7a696c48:CRITICAL
   ! Check:agent.plugin:choEM1sOlC:nova_api_local_check-infra03-nova-api-os-compute-container-8edbb39f: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:alQ0lswVQg:nova_api_local_status-infra03-nova-api-os-compute-container-8edbb39f:CRITICAL
   ! Check:agent.plugin:chrj435RXa:cinder_api_local_check-infra03-cinder-api-container-6710e15c: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:albTh70Zqa:cinder_api_local_status-infra03-cinder-api-container-6710e15c:CRITICAL
   ! Check:agent.plugin:chs5FnYXv1:nova_cert_check-infra03-nova-cert-container-92378466: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:al7G7NStR1:nova_cert_status-infra03-nova-cert-container-92378466:CRITICAL
   ! Check:remote.http:chx7aNOuzV:lb_api_check_glance-unspecified_lb: Completed:False Status:Connection refused
     ! Alarm:alideGs1JH:lb_api_alarm_glance:CRITICAL
   ! Check:remote.http:ch2Pq1kVVu:lb_api_check_heat_api-unspecified_lb: Completed:False Status:Connection refused
     ! Alarm:alL7tkQFPS:lb_api_alarm_heat_api:CRITICAL
   ! Check:agent.plugin:ch4JrVWSH4:heat_api_local_check-infra03-heat-apis-container-5ccd973b: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:albEwEV9P5:heat_api_local_status-infra03-heat-apis-container-5ccd973b:CRITICAL
   ! Check:agent.plugin:ch81zV8QRm:keystone_api_local_check-infra03-keystone-container-8145c4e9: Completed:False Status:Plugin exited with non-zero status code (code=1)
     ! Alarm:alHRo5ZGsa:keystone_api_local_status-infra03-keystone-container-8145c4e9:CRITICAL
   ! Check:agent.plugin:chAMIPlboY:neutron_dhcp_agent_check-infra03-neutron-agents-container-fe121255: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:alCCj0qjic:neutron_dhcp_agent_status-infra03-neutron-agents-container-fe121255:CRITICAL
   ! Check:remote.http:chBdoY2TCO:lb_api_check_nova-unspecified_lb: Completed:False Status:Connection refused
     ! Alarm:aleuxOeG6y:lb_api_alarm_nova:CRITICAL
   ! Check:agent.plugin:chC3xLLIvn:glance_registry_local_check-infra03-glance-container-513246a4: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:alyhHvB7Rt:glance_registry_local_status-infra03-glance-container-513246a4:CRITICAL
   ! Check:agent.plugin:chCEaSkkP7:neutron_api_local_check-infra03-neutron-server-container-2662c976: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:alx3XuATWF:neutron_api_local_status-infra03-neutron-server-container-2662c976:CRITICAL
   ! Check:agent.plugin:chJvAgjNeS:neutron_l3_agent_check-infra03-neutron-agents-container-fe121255: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:alE0LLJFsO:neutron_l3_agent_status-infra03-neutron-agents-container-fe121255:CRITICAL
   ! Check:remote.http:chLReznNX5:lb_api_check_heat_cfn-unspecified_lb: Completed:False Status:Connection refused
     ! Alarm:alDDC9nPMv:lb_api_alarm_heat_cfn:CRITICAL
   ! Check:agent.plugin:chLUlaFVVZ:neutron_linuxbridge_agent_check-infra03-neutron-agents-container-fe121255: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:alrt9A17BE:neutron_linuxbridge_agent_status-infra03-neutron-agents-container-fe121255:CRITICAL
   ! Check:remote.http:chNs4DOF1E:lb_api_check_horizon-unspecified_lb: Completed:False Status:Connection refused
     ! Alarm:alCdxggcYJ:lb_api_alarm_horizon:CRITICAL
   ! Check:agent.plugin:chQB1SMn3j:nova_scheduler_check-infra03-nova-scheduler-container-1411d0aa: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:alPhKN3e9r:nova_scheduler_status-infra03-nova-scheduler-container-1411d0aa:CRITICAL
   ! Check:agent.plugin:ch0ixrxNMr:neutron_metering_agent_check-infra03-neutron-agents-container-fe121255: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:al7GL9LX1k:neutron_metering_agent_status-infra03-neutron-agents-container-fe121255:CRITICAL
   ! Check:remote.http:chTDyLuo3F:lb_api_check_cinder-unspecified_lb: Completed:False Status:Connection refused
     ! Alarm:almnDevzTd:lb_api_alarm_cinder:CRITICAL
   ! Check:agent.plugin:chYadxQCUM:nova_cloud_stats_check-infra03-nova-api-os-compute-container-8edbb39f: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:alFI1CGKag:nova_cloud_vcpu_status-infra03-nova-api-os-compute-container-8edbb39f:CRITICAL
     ! Alarm:alLZeRBgEm:nova_cloud_disk_status-infra03-nova-api-os-compute-container-8edbb39f:CRITICAL
     ! Alarm:algCM2JEds:nova_cloud_memory_status-infra03-nova-api-os-compute-container-8edbb39f:CRITICAL
   ! Check:remote.http:chaIxkpUjH:lb_api_check_heat_cloudwatch-unspecified_lb: Completed:False Status:Connection refused
     ! Alarm:alljulZ1UX:lb_api_alarm_heat_cloudwatch:CRITICAL
   ! Check:remote.http:chbXZdP4LM:lb_api_check_neutron-unspecified_lb: Completed:False Status:Connection refused
     ! Alarm:alCGeTipPM:lb_api_alarm_neutron:CRITICAL
	 
   ! Check:agent.plugin:chxVCgb7fW:nova_conductor_check-infra03-nova-conductor-container-694cc210: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:al4IqgfBad:nova_conductor_status-infra03-nova-conductor-container-694cc210:CRITICAL
   ! Check:agent.plugin:chedWOvGEH:neutron_metadata_agent_check-infra03-neutron-agents-container-fe121255: Completed:False Status:error Cannot import keystoneclient
     ! Alarm:alFrSx2429:neutron_metadata_agent_status-infra03-neutron-agents-container-fe121255:CRITICAL
  msg: Task failed as maximum retries was encountered
  
  PLAY RECAP ********************************************************************
  Verify Check & Alarm Status -------------------------------------- 2600.76s
  Allow MAAS time to run checks before verifying their status ------- 120.11s
  Verify Checks & Alarms are registered ------------------------------- 1.86s
  copy script to all hosts -------------------------------------------- 0.24s
  ensure remote directory -------------------------- 0.10s
           to retry, use: -limit @/root/verify-maas.retry
```

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

N/A

##### How can we reproduce this issue?

1st install of maas checks with r13.0.0rc2

##### How can we verify your issue is addressed?

All checks are passing

##### If you are using or know of a workaround please describe the necessary steps?

N/A

##### What is your evaluation on the importance of this issue, and why?

prio-1 since monitoring is affected

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by BjoernT** [comment]
Seems this is already being worked on per https://github.com/rcbops/u-suk-dev/issues/204
Closing here

**Comment by git-harry** [comment]
This has also been reported in https://github.com/rcbops/rpc-openstack/issues/1350

This may also be related to https://github.com/rcbops/u-suk-dev/issues/397

**Comment by b3rnard0** [comment]
@jacobwagner @jpmontez For MaaS related testing awareness.

**Comment by git-harry** [comment]
Lowering the priority, this will be targeted for the first patch release unless QE report discovering the issue.

**Comment by BjoernT** [comment]
@git-harry It does not matter who finds a bug so it is still prio-1 until otherwise proven

**Comment by xeregin** [comment]
I'm not seeing this in SYD2-1. This may be an environment/configuration issue.
"verify_maas" is working as expected and reporting alarms in alert status in MaaS.
The Keystone LB checks in our lab are successfully installed and reporting everything OKAY.
We are seeing 2 specific alerts that need to be looked into.
- lb_api_check_horizon (Alarm:alwtLA5atv:innodb_deadlocks--627551-infra01-galera-container-615ccaa9:CRITICAL)
- galera_check (Completed:False Status:[eventer_SSL_fd_opset.c:889:140770fc] error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol)
I believe both of these are environment issues but will verify.
In either case, at present, I do not believe this is a maas-related problem

**Comment by git-harry** [comment]
This issue has not been reproduced and appears to be the result of not following the documented steps for deploying an environment. As part of the upgrades work currently in progress, a similar issue was identified https://github.com/rcbops/rpc-openstack/issues/1404 but this does not impact greenfield deployments when deploying using the correct procedure.

**Comment by BjoernT** [comment]
@git-harry Please support your comment that documented steps have not been followed. The deployment script is simply just running the plays per https://github.com/rcbops/rpc-openstack/blob/mitaka-13.0/scripts/deploy.sh#L237-L238

**Comment by git-harry** [comment]
@BjoernT without precise steps to reproduce this issue it is difficult to say anything with certainty. As it stands the only known way to see the error with the MaaS plugins, assuming the appropriate deployment steps are taken, is when doing a upgrade and since that process is still in development it is not unexpected that we will find bugs. The only report of this error when performing a greenfield deployment is this issue and, given what causes the error to occur, the most likely reason relates to not completing the required steps.

If you are able to show how we can reproduce this issue the engineering team will be happy to investigate further.

**Comment by BjoernT** [comment]
I have a lead the venv is running the wrong python-keystoneclient package version (3.5.0) instead of 2.3.1. Need to investigate where this is coming from

**Comment by BjoernT** [comment]
OK the issue is related to deploy/upgrade sh stops and the resulting manual execution of playbooks, something still common. The PR 1409 addresses at least this loophole which has been cause of too many issues in the past
