### ISSUE TITLE
Add support for custom routes to containers (snet)

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#14]
In case br-snet is configured at the glance or neutron containers, ansible should add a route to the service net over the eth3 interface (br-snet)  like:

/etc/network/interfaces.d/provider_networks.cfg for eth3:
post-up ip route add 1.2.3.0/18 via 172.29.248.1

Currently I would like to have the service network to be configured  as mandatory option inside the rpc_user_config.yml and probably the host interface. So we can add 

iptables -t nat -A POSTROUTING  -s 172.29.248.0/22 -o <INTERFACE> -j MASQUERADE

to the infra nodes. iptables-persistent shoud be installed in that case too

**Comment by andymcc** [comment]
@BjoernT can you outline a usecase/what you're trying to achieve with this? Trying to understand this better so we can look at implementing it properly.

**Comment by BjoernT** [comment]
The objective is to use the eth3 interface on the glance container to route to the Rackspace service net, instead of the lxcbr0 bridge. eth3 on the container is connected to br-snet over an iptables rule, like br-snet was intended for. Without that route inside the container or without the iptables rule, br-snet does not work

**Comment by b3rnard0** [comment]
@andymcc @BjoernT @mattt416 Needs more investigation but not approved for a milestone (yet).

**Comment by mattt416** [comment]
Confirmed this is an issue.  I'm not sure what the solution is yet but I can verify that what @BjoernT reported is correct.  Service net functionality is there (through eth0) so I'd keep priority low, but this certainly isn't working as planned.

**Comment by mattt416** [comment]
Hi @BjoernT, I've created https://bugs.launchpad.net/openstack-ansible/+bug/1464639 for this since the fix will most likely live in os-ansible-deployment.
