### ISSUE TITLE
rabbitmq post_upgrade_check doesn't work (part deux)

### ISSUE THREAD

**Issue by b3rnard0** [rcbops/rpc-openstack#1414]
##### On which version(s) do you encounter this issue?

    heads/master

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

If there is *not* a network split in the rabbit cluster, the test should pass

##### What is actually happening?

The cluster looks fine, with no network partition, but the test of stdout from ```rabbitmqctl status``` fails.

Here is the output:

```
ok: [aio1_rabbit_mq_container-7b4eb8a9] => {
    "var": {
        "rabbitmqctl_output": {
            "changed": true,
            "cmd": [
                "rabbitmqctl",
                "cluster_status"
            ],
            "delta": "0:00:00.606497",
            "end": "2016-09-09 13:26:48.949645",
            "failed": false,
            "failed_when_result": false,
            "invocation": {
                "module_args": "rabbitmqctl cluster_status",
                "module_complex_args": {},
                "module_name": "command"
            },
            "rc": 0,
            "start": "2016-09-09 13:26:48.343148",
            "stderr": "",
            "stdout": "Cluster status of node 'rabbit@aio1_rabbit_mq_container-7b4eb8a9' ...\n[{nodes,[{disc,['rabbit@aio1_rabbit_mq_container-7b4eb8a9',\n                'rabbit@aio1_rabbit_mq_container-99201c9c',\n                'rabbit@aio1_rabbit_mq_container-d48dab3c']}]},\n {running_nodes,['rabbit@aio1_rabbit_mq_container-d48dab3c',\n                 'rabbit@aio1_rabbit_mq_container-99201c9c',\n                 'rabbit@aio1_rabbit_mq_container-7b4eb8a9']},\n {cluster_name,<<\"openstack\">>},\n {partitions,[]}]",
            "stdout_lines": [
                "Cluster status of node 'rabbit@aio1_rabbit_mq_container-7b4eb8a9' ...",
                "[{nodes,[{disc,['rabbit@aio1_rabbit_mq_container-7b4eb8a9',",
                "                'rabbit@aio1_rabbit_mq_container-99201c9c',",
                "                'rabbit@aio1_rabbit_mq_container-d48dab3c']}]},",
                " {running_nodes,['rabbit@aio1_rabbit_mq_container-d48dab3c',",
                "                 'rabbit@aio1_rabbit_mq_container-99201c9c',",
                "                 'rabbit@aio1_rabbit_mq_container-7b4eb8a9']},",
                " {cluster_name,<<\"openstack\">>},",
                " {partitions,[]}]"
            ],
            "warnings": []
        }
    }
}
```

The important bit is:

 ```" {partitions,[]}]"```

which shows that the cluster is not partitioned.  The tasks *try* to look for this (from ```/opt/rpc-openstack/rpcd/playbooks/roles/rpc_post_upgrade/tasks/post-upgrade-rabbitmq.yml```):

```
# Verify rabbit is not partitioned
# Here we check to see if partitions is empty
- name: Fail if network partitions are detected
  fail:
    msg: "Rabbitmq network partitions have been detected."
  when: "' {partitions,[]},' not in rabbitmqctl_output.stdout_lines"
```

...but the test is obviously not working

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Run an upgrade from liberty-12.2 (head) to master (head) on an AIO

##### How can we reproduce this issue?

Run an upgrade from liberty-12.2 (head) to master (head) on an AIO

##### How can we verify your issue is addressed?

Run an upgrade from liberty-12.2 (head) to master (head) on an AIO, and ensure the check for the rabbit cluster passes

##### What is your evaluation on the importance of this issue, and why?

High, for the 13.1.0 rc

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by Apsu** [comment]
Posted my thoughts on the easy solution https://github.com/rcbops/rpc-openstack/pull/1413#issuecomment-246785395

Waiting for feedback and I'll fix the PR

**Comment by Apsu** [comment]
Updated PR
