### ISSUE TITLE
valid hosts are deleted from /etc/hosts

### ISSUE THREAD

**Issue by jaime-gutierrez** [rcbops/rpc-openstack#1417]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
12.0.15

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
/usr/local/bin/openstack-host-hostfile-setup.sh to not delete valid hosts from /etc/hosts

##### What is actually happening?
/usr/local/bin/openstack-host-hostfile-setup.sh is deleting valid hosts from /etc/hosts as it is not properly matching host IPs. 

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

When running ````openstack-ansible --tags=openstack-host-hostfile setup-hosts.yml```` valid new hostname entries to /etc/hosts were added but then removed due to bad logic in the script /usr/local/bin/openstack-host-hostfile-setup.sh

#Example:

After running openstack-ansible --tags=openstack-host-hostfile setup-hosts.yml 

View the contents of openstack-host-hostfile-setup.sh and /etc/hosts for hosts in range 10.240.0.140 - 10.240.0.149 and another host (infra01) which has a last octet of .14:

````
grep 10.240.0.14 /usr/local/bin/openstack-host-hostfile-setup.sh
sed -i '/^10.240.0.141.*/d' /etc/hosts
echo '10.240.0.141 compute001' | tee -a /etc/hosts
sed -i '/^10.240.0.142.*/d' /etc/hosts
echo '10.240.0.142 compute002' | tee -a /etc/hosts
sed -i '/^10.240.0.14.*/d' /etc/hosts
echo '10.240.0.14 infra01' | tee -a /etc/hosts
````

The last sed statement for infra01 ends up deleting entries for the computes as there should be a space after the IP address:
````sed -i '/^10.240.0.14.*/d' /etc/hosts````

VS possible alternative

````sed -i '/^10.240.0.14 .*/d' /etc/hosts````

##### How can we reproduce this issue?
Add additional hosts to an environment with similar IP setup as shown above and after running ````openstack-ansible --tags=openstack-host-hostfile setup-hosts.yml````
make sure /etc/hosts is not missing valid host entries.
##### How can we verify your issue is addressed?
Ensure /usr/local/bin/openstack-host-hostfile-setup.sh no longer deletes valid host entires from /etc/hosts
##### If you are using or know of a workaround please describe the necessary steps?
Insert a space after the IP address for each sed to properly match host IPs
```` sed -i '/^10.240.0.14 .*/d' /etc/hosts````
##### What is your evaluation on the importance of this issue, and why?
Somewhat important as there could be communication issues between hosts if valid /etc/hosts entries are suddenly removed during maintenances or additions.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by BjoernT** [comment]
This has been addressed upstream with https://github.com/openstack/openstack-ansible/commit/3d3fed574ca93397ea1a6930928f468c1508a55d. Hence you should use a recent RPC 12.2.1 version to have this fixed. This will bring us in a bad situation where you have to update the RPC version before adding nodes for example

**Comment by git-harry** [comment]
I'm closing this as invalid because it is already fixed.

@jaime-gutierrez please include the RPCO version not the OSA version next time you create an issue.
