### ISSUE TITLE
hp-health tools cannot recognize controller

### ISSUE THREAD

**Issue by ihavegerms** [rcbops/rpc-openstack#1426]
[version information]

(pulled from infra host)
infra01:/opt/rpc-openstack/openstack-ansible$ git describe --all
11.2.16

(pulled from cinder host 1 of 2)
ii  hp-health                           10.0.0.1.3-4.                    amd64        hp System Health Application and Command line Utility Package
ii  hp-snmp-agents                      10.0.0.1.23-21.                  amd64        Insight Management SNMP Agents for HP ProLiant Systems
ii  hponcfg                             4.4.0.8-2.                       amd64        RILOE II/iLo online configuration utility
ii  hpsmh                               7.3.2-1.5-2.                     amd64        HP System Management Homepage
ii  hpssacli                            2.40-13.0                        amd64        HP Command Line Smart Storage Administration Utility

cinder02:~# lsmod | grep hp
hpwdt                  14257  0 
hpilo                  17394  10 
shpchp                 37047  0 
hpsa                   81092  3 

cinder02:~# uname -r
3.16.0-48-generic

--pulled from ILO to show hardware health

Subsystems and Devices
Fans	 OK
Fan Redundancy	 Redundant
Temperatures	 OK
Power Supplies	 OK
Power Status	 Redundant
Smart Storage Battery Status	 OK
Storage	 OK
Network	 OK
Processors	 OK
Memory	 OK
BIOS/Hardware Health	 OK
Agentless Management Service	 Not available

(pulled from cinder host 2 of 2)
ii  hp-health                              10.40-1815.49                    amd64        hp System Health Application and Command line Utility Package
ii  hp-smh-templates                       10.40.7-11.                      all          HP System Management Homepage Templates
ii  hp-snmp-agents                         10.40-2909.34                    amd64        Insight Management SNMP Agents for HP ProLiant Systems
ii  hponcfg                                4.6.0.5-23.                      amd64        RILOE II/iLo online configuration utility
ii  hpsmh                                  7.5.4-3.2-8.                     amd64        HP System Management Homepage
ii  hpssacli                               2.10-14.0                        amd64        HP Command Line Smart Storage Administration Utility

cinder04:~# lsmod | grep hp
hpwdt                  14257  0 
hpilo                  17394  10 
shpchp                 37047  0 
hpsa                   81092  3

cinder04:~# uname -r
3.16.0-48-generic

--pulled from ILO to show hardware health

Subsystems and Devices
Agentless Management Service	 Not available
Smart Storage Battery Status	 OK
BIOS/Hardware Health	 OK
Fan Redundancy	 Redundant
Fans	 OK
Memory	 OK
Network	 OK
Power Status	 Redundant
Power Supplies	 OK
Processors	 OK
Storage	 OK
Temperatures	 O

##### What type of issue is this? Please tick the appropriate box.
- [X ] bug - existing functionality that does not work for you as documented

##### What is the expected behavior?
For the controller to be recognized so the HP maas checks can pass.

##### What is actually happening?
The controller is not found on either host though ILO reports the hardware on both hosts are fine. 

cinder04:~# hpssacli ctrl all show config

Error: No controllers detected.

cinder02:~# hpssacli ctrl all show config

Error: No controllers detected.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Review the status of a MaaS agent down alert.

##### How can we reproduce this issue?
Unknown

##### How can we verify your issue is addressed?
HP checks would be passing on the host.

##### If you are using or know of a workaround please describe the necessary steps?
None

##### What is your evaluation on the importance of this issue, and why?
Pretty important I would say... while the actual host appears to be running fine, we would not be notified if any of the three failing checks actually DID fail. 

 (XXXXXXXX) [ Enabled] [CRITICAL] [                         hp-disk] Period: 60 
 (XXXXXXXX) [ Enabled] [CRITICAL] [                       hp-memory] Period: 60 
 (XXXXXXXX) [ Enabled] [CRITICAL] [                   hp-processors] Period: 60 

-- Additional Notes:

I've tried re-installing, upgrading, restarting the hp tools with no resolution.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by claco** [comment]
@ihavegerms seems like this is a case of the HP tools not recognizing the controllers, and thus an upstream thing outside of our controll rather than an RPC/MaaS issue. I'm going to close this for now, but feel free to reopen if you end up with newer tools/firmware, and the output changes or the checks fail one the controller is finally detected.
