### ISSUE TITLE
test-upgrade fails on "Get elastic search indicies"

### ISSUE THREAD

**Issue by evrardjp** [rcbops/rpc-openstack#1434]
I've never deployed logging stash (or at least I didn't ask for it by setting deploy logging to no in my exports) and my upgrade fails on the post-upgrade role, when it tries to do actions on elastic search.

The task failing is: 
"Get elastic search indicies" (there is a typo on the task name btw), which returns msg: Socket error: [Errno 111] Connection refused to http://172.29.239.40:9200/_cat/indices?v

As you can see there is an elastic search url defined (weird). I didn't got that issue on my first AIO upgrades, so I have to check what would be the cause. 

Let's keep this card for the record.

**Comment by mattt416** [comment]
Hi @evrardjp, I think the issue here is actually a bug in scripts/deploy.sh.  I've pushed a PR to address.

**Comment by alextricity25** [comment]
I created a backport for this. Please review when you get the chance.

**Comment by mattt416** [comment]
Closing this card since the backport has a separate issue for tracking.

**Comment by git-harry** [comment]
@mattt416 this is now in master and mitaka-13.1, what other backports are required?

**Comment by mattt416** [comment]
@git-harry What other backports are required to resolve this issue?  That should be it as far as I'm aware.

**Comment by alextricity25** [comment]
I personally feel like no other backport is needed

**Comment by git-harry** [comment]
@mattt416 Okay, not offering an opinion, just confirming that all our supported branches have been considered. I'll close this card.
