### ISSUE TITLE
Build sane rabbit sync policies

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1435]
##### What type of issue is this? Please tick the appropriate box.
- [ ] bug - existing functionality that does not work for you as documented
- [x] feature - new functionality that you would like to see added

##### What is the expected behavior?

Per https://bugs.launchpad.net/openstack-ansible/+bug/1607830 the performance is unacceptable when replicating across 3 nodes, which is actually the reason why we in RPC support stopped scaling rabbit container more than 3 nodes for setups using 5 or more infra nodes. 
Since OSA makes it possible now to deploy custom policies we need to create better ones than the current default policy. Especially we need to define which queues/exchanges or type of message should be even synced. I personally see no reason to sync heart beat messages across the entire cluster, just as example. We already account for intermittent lost heartbeats so it will not hurt.

Perhaps we can even rethink if we not want to split out rabbit by openstack type like a rabbit cluster for nova, neutron and common etc etc.

##### What is actually happening?

See  https://bugs.launchpad.net/openstack-ansible/+bug/1607830 

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Not scaling rabbit across more than 3 nodes

##### How can we reproduce this issue?

Deploy  cluster with 5 infra or more nodes and check the throughput in rabbit.
At some point you'll see that more openstack build request  are timing out based on our default settings (rpc response timeout)

##### How can we verify your issue is addressed?

Better msg/s throughput compared to a standard setup.

##### What is your evaluation on the importance of this issue, and why?

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by odyssey4me** [comment]
Implementing alternative policies is only one way to solve this issue. The best way to solve it is through a change in architecture, not a change in policies. In other words - don't use a single RabbitMQ cluster for all message processing. This is a well known strategy for large deployments.

Implementing the change in architecture to have multiple clusters should be possible from Kilo onwards with the ability to add more groups to the inventory through env.d files, and through the use of config overrides to adjust the configuration settings.

The work done in Newton just makes it simpler to break out the telemetry clustering.

**Comment by git-harry** [comment]
Moved to https://github.com/rcbops/u-suk-dev/issues/461
