### ISSUE TITLE
rpc_pre_upgrade role needs to be reworked

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#1443]
##### On which version(s) do you encounter this issue?

version ```r13.1.0rc1```

##### What type of issue is this? Please tick the appropriate box.

- [ ] bug - existing functionality that does not work for you as documented
- [x] feature - new functionality that you would like to see added

##### What is the expected behaviour?

That the playbook and role perform tasks in the manner that ansible was designed for. I would suggest either of the following approaches:

- all of the tasks are moved out of the role completely, and that there is a single playbook that just has a number of plays, each of which targets a specific group of hosts
- we keep the role, and just have task files that get included from ```main.yml``` based on the host group membership (as we have in the post-upgrade role)

##### What is actually happening?

We are targeting the play at 'localhost', and then in the role delegating tasks to hosts/containers based on their group membership. This is inefficient and slow (we recently had to move a service restart out of this model because it was taking about 14 seconds per host).

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Run an upgrade, specifically the ```rpc-pre-upgrade.yml``` playbook

##### How can we reproduce this issue?

It all works, but running the ```rpc-pre-upgrades.yml``` play is slower than it should be

##### How can we verify your issue is addressed?

We rework the structure of that playbook/role and it is peer reviewed as being better.

##### If you are using or know of a workaround please describe the necessary steps?

N/A

##### What is your evaluation on the importance of this issue, and why?

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment]
Closed in favour of https://github.com/rcbops/u-suk-dev/issues/473
