### ISSUE TITLE
deploy-rpc-playbooks.sh cannot be run independently of test-upgrade.sh

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/rpc-openstack#1447]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
r13.1.0rc1

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
The script runs and executes proper playbooks independent of other scripts

##### What is actually happening?
root@node84:/opt/rpc-openstack# bash scripts/deploy-rpc-playbooks.sh
+ set -o pipefail
scripts/deploy-rpc-playbooks.sh: line 6: BASE_DIR: unbound variable

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Finish a upgrade with a lab without maas that failed due to DEPLOY_MAAS being set to "YES" when it shouldnt have.

##### How can we reproduce this issue?
Attempt to run the script

##### How can we verify your issue is addressed?
The script runs and finishes all plays

##### If you are using or know of a workaround please describe the necessary steps?
I added the following lines to the top of the script under the setpipe

https://github.com/rcbops/rpc-openstack/blob/master/scripts/test-upgrade.sh#L21-L23

##### What is your evaluation on the importance of this issue, and why?
low, this script shouldnt really need to be run outside of the upgrade / deploy scripts which have the missing variables set

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment]
@jacobwagner this was a [design choice](https://github.com/rcbops/rpc-openstack/pull/1396#issuecomment-247050690) and so won't be addressed at this time.
