### ISSUE TITLE
RPC Branding/Logo missing from "Material" Horizon theme

### ISSUE THREAD

**Issue by sigmavirus24** [rcbops/rpc-openstack#1457]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

master (haven't checked older versions)

##### What type of issue is this? Please tick the appropriate box.
- [X] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

Whether users are using the "Default" or "Material" theme in Horizon, they should see the Rackspace Private Cloud branding.

##### What is actually happening?

<img width="1209" alt="screen shot 2016-09-30 at 13 37 04" src="https://cloud.githubusercontent.com/assets/240830/19002769/32015c48-8713-11e6-8c78-2a9af20b0259.png">
<img width="1218" alt="screen shot 2016-09-30 at 13 37 16" src="https://cloud.githubusercontent.com/assets/240830/19002768/32007ce2-8713-11e6-96df-958c9f029856.png">

The Material theme is missing the branding while the default theme has it.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Debug #1262 

##### How can we reproduce this issue?

Deploy an AIO and go to log in.

##### How can we verify your issue is addressed?

Visit Horizon after a successful deployment and see RPC branding for both Default and Material themes.

##### What is your evaluation on the importance of this issue, and why?

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by claco** [comment]
Related #1088

**Comment by sigmavirus24** [comment]
@claco that's the default theme though.

**Comment by git-harry** [comment]
I've labelled this as a prio-2 based on the assumption that we support both themes. If, however we don't currently support the material theme this issue will likely need re-categorising a an enhancement-medium.

**Comment by sigmavirus24** [comment]
So I recall this coming up as a "free feature" when looking at Mitaka. Based on that, I've assumed this is supported. We should chat with product though to see if this is actually a thing they care about (given that Material is not the default)

**Comment by git-harry** [comment]
I don't see it listed as a free feature, I've mark this as undecided. Once we clarify the expected support for themes other than default this can be labelled appropriately.

**Comment by evrardjp** [comment]
I thought the material theme was quite experimental, and wasn't production ready in this release.
I agree with @git-harry .

**Comment by sigmavirus24** [comment]
An alternative solution: Completely disable it until it is ready

**Comment by evrardjp** [comment]
Or fix it? What would be the path of the assets required for the branding?

**Comment by git-harry** [comment]
We are not supporting the material theme.
