### ISSUE TITLE
MaaS plays duplicate too much logic

### ISSUE THREAD

**Issue by stevelle** [rcbops/rpc-openstack#148]
Creating entities and checks have a lot of logic and that logic is duplicated in multiple places.

Probably a wishlist item, but using a proper raxmon ansible module, developing one if necessary, should improve the plays a lot.

**Comment by andymcc** [comment]
We've refactored MaaS now so I'm going to close this one out!

I think we reduced that logic since we now just drop conf files and only require the entity check for at initial setup.
