### ISSUE TITLE
innodb_deadlocks does not report on a rate per interval

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1486]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

r13.1.0rc1
13.3.4-1-ga489036
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added
##### What is the expected behavior?

The innodb_deadlocks galera check needs to report to a rate per check interval rather than a fixed number. In my case the database had occurred dead locks in the past so the alarm triggered after the upgrade, even if the counter is not growing.

If we  can't check a rate per check interval, then we need to deactivate this metric
##### What is actually happening?

See above
##### What were you attempting to do when you encountered this error (give as much detail as possible)?

Removed alarm
##### How can we reproduce this issue?

See above
##### How can we verify your issue is addressed?

No false alerts on not growing metric like innodb_deadlocks
##### If you are using or know of a workaround please describe the necessary steps?

N/A
##### What is your evaluation on the importance of this issue, and why?

Prio 2

---
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:
##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:
##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.
##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues)
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc)
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
I'm going to target this for r14.0.0rc1. Also, I'm removing the "Upgrade" context since this isn't related to upgrades.

**Comment by alextricity25** [comment]
I recommend we fix this before the Newton release. That includes the backport ot mitaka-13.1.

**Comment by major** [comment]
Assigning to @BjoernT since he made the PR. ;)
