### ISSUE TITLE
setup-maas.yml failing 

### ISSUE THREAD

**Issue by mattt416** [rcbops/rpc-openstack#149]
Commit https://github.com/rcbops/rpc-extras/commit/096b0a2a2bf679e326bbc9b75933c901ca3241c5 seems to have broken setup-maas.yml from running correctly.  I'm seeing:

```
TASK: [rpc_maas | At most one {{ inventory_hostname }}{{ maas_fqdn_extension }} entity exists] ***
fatal: [jenk-heat-297-node4] => error while evaluating conditional: entity_count.stdout|int != 1
fatal: [jenk-heat-297-node5] => error while evaluating conditional: entity_count.stdout|int != 1
fatal: [jenk-heat-297-node1] => error while evaluating conditional: entity_count.stdout|int != 1
fatal: [jenk-heat-297-node2] => error while evaluating conditional: entity_count.stdout|int != 1
```

**Comment by prometheanfire** [comment]
I'm fine with reverting it, should be doc'd so testing knows they need to do entity creating at host provisioning.

**Comment by mattt416** [comment]
I'm also seeing errors about galera_root_user var not existing, investigating now.

**Comment by prometheanfire** [comment]
not sure I touched that...

**Comment by mattt416** [comment]
Yep, identified cause, not related to your commit!

**Comment by mattt416** [comment]
This issue should not affect kilo branch.

**Comment by mattt416** [comment]
Only https://github.com/rcbops/rpc-extras/pull/151 needs backporting to kilo.
