### ISSUE TITLE
Maas playbooks are ignoring raxmon utilities failures

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#15]
```
<xxxxxx> REMOTE_MODULE command raxmon-alarms-create --entity-id xxxxx --label lb_api_alarm_heat_cloudwatch --check-id xxxxx --notification-plan-id npManaged --criteria ':set consecutiveCount=1 if (metric['"'"'code'"'"'] != '"'"'300'"'"') { return new AlarmStatus(CRITICAL, '"'"'API unavailable.'"'"'); }' #USE_SHELL
<10.242.0.194> EXEC ['ssh', '-C', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=120', u'10.242.0.194', u"/bin/sh -c 'LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python'"]
changed: [xxxx-Infra03_heat_apis_container-xxxxxx] => {"changed": true, "cmd": "raxmon-alarms-create --entity-id xxxxx --label lb_api_alarm_heat_cloudwatch --check-id xxxx --notification-plan-id npManaged --criteria ':set consecutiveCount=1 if (metric['\"'\"'code'\"'\"'] != '\"'\"'300'\"'\"') { return new AlarmStatus(CRITICAL, '\"'\"'API unavailable.'\"'\"'); }'", "delta": "0:00:01.431475", "end": "2015-02-26 22:42:21.488981", "rc": 0, "start": "2015-02-26 22:42:20.057506", "stderr": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/raxmon_cli/common.py\", line 130, in run_action\n    callback(instance, options, args, done)\n  File \"/usr/local/bin/raxmon-alarms-create\", line 39, in callback\n    why=options.why)\n  File \"/usr/local/lib/python2.7/dist-packages/rackspace_monitoring/drivers/rackspace.py\", line 485, in create_alarm\n    data=data, coerce=self.get_alarm, headers=headers)\n  File \"/usr/local/lib/python2.7/dist-packages/rackspace_monitoring/drivers/rackspace.py\", line 301, in _create\n    headers=headers)\n  File \"/usr/local/lib/python2.7/dist-packages/rackspace_monitoring/drivers/rackspace.py\", line 152, in request\n    raw=raw\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/common/openstack.py\", line 200, in request\n    raw=raw)\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py\", line 736, in request\n    response = responseCls(**kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py\", line 117, in __init__\n    raise Exception(self.parse_error())\n  File \"/usr/local/lib/python2.7/dist-packages/rackspace_monitoring/drivers/rackspace.py\", line 107, in parse_error\n    raise error\nRackspaceMonitoringValidationError: <ValidationError type=limitReached, message=\"Resource limit has been reached\", details=Limit for resource alarms has been reached. Maximum allowed objects: 1000>", "stdout": ""}
```

Unfortunately the playbooks just finished without reporting any error. I only got to this error using -vvv modifier.

**Comment by andymcc** [comment]
It looks like we're going to have to follow this up with upstream for MaaS - there is some resource limit that has been reached - which we haven't seen before this.

**Comment by BjoernT** [comment]
Yes, but the report is that this error was not reported to ansible to the playbooks finished without an error or hint why the alarms did not got installed. This bug is about incorrect error handling in connection to the raxmon utilities

**Comment by andymcc** [comment]
@BjoernT can you check what the exit status of the command is manually? So if you run that raxmon-alarms-create command (receiving the same error) and then do a echo $?

This isn't an ignored task so it should fail from an ansible POV if the command exits with a status of 1 - this would mean that the raxmon-alarms-create command is exiting with the incorrect status for a failure, which would also be an upstream failure on the part of the raxmon utils.

**Comment by BjoernT** [comment]
@andymcc Sorry, I was not able to reproduce it at this moment. Perhaps we can trigger on the ValidationError output ?

**Comment by mattt416** [comment]
I was able to replicate this, created a PR here:

https://github.com/racker/rackspace-monitoring-cli/pull/78

**Comment by mattt416** [comment]
Hi @BjoernT, https://github.com/racker/rackspace-monitoring-cli/pull/78 has merged and it looks like rpc-openstack master/kilo are installing rackspace-monitoring-cli v0.6.10, which is the tagged version which includes the linked fix.  In juno of os-a-d, we specify version v0.6.8 of rackspace-monitoring-cli.  Do you want us to bump this to version v0.6.10 or are you fine having this change in just kilo/master?

**Comment by d34dh0r53** [comment]
@BjoernT bump

**Comment by BjoernT** [comment]
Sorry didn't see that. I like to get it upgraded to the latest version especially in juno

**Comment by andymcc** [comment]
https://review.openstack.org/254321 bumped here.

**Comment by andymcc** [comment]
This has merged now so closing this one out!
