### ISSUE TITLE
Magnum Integration

### ISSUE THREAD

**Issue by chrishultin** [rcbops/rpc-openstack#1526]
##### What type of issue is this? Please tick the appropriate box.
- [ ] bug - existing functionality that does not work for you as documented
- [X] feature - new functionality that you would like to see added
##### What is the expected behavior?

Magnum is properly logged
##### What is actually happening?

Magnum log files are not picked up by FileBeat; Logstash does not know how to parse Magnum logs
##### How can we verify your issue is addressed?

Verify Magnum-API and Magnum-Conductor logs are stored and viewable via Logstash
##### What is your evaluation on the importance of this issue, and why?

---
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo
##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:
##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:
##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.
##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues)
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc)
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment]
Given that we don't currently support magnum I've marked this as a low priority enhancement.

**Comment by chrishultin** [comment]
@git-harry PR for the change can be found here:
https://github.com/rcbops/rpc-openstack/pull/1523

**Comment by jnoller** [comment]
Closing as magnum is no longer on the plan
