### ISSUE TITLE
13.1.0rc2 Horizon unable to delete load balancer pools.

### ISSUE THREAD

**Issue by Rydor** [rcbops/rpc-openstack#1528]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

r13.1.0rc2
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added
##### What is the expected behavior?

Within Horizon we need to expose a means by which we can delete a pool under a listener within a load balancer. 
##### What is actually happening?

Attempts to delete the load balancer at the top level returns this exception;
Error: The following load balancers could not be deleted, possibly due to existing listeners: lb1.

If you drill down to the listener and attempt to delete it first you get this exception;
Error: The following listeners will not be deleted due to existing pools: Listener 1.

There isn't functionality exposed to allow the deletion of the pool nor the healthmonitor associated with the pool.
##### What were you attempting to do when you encountered this error (give as much detail as possible)?

Attempts to verify the functionality of Horizon as part of RC testing for the r13.1.0rc2 release. This testing includes regression and functional testing within Horizon.
##### How can we reproduce this issue?

Attempt to delete a load balancer within the Horizon portal.
##### How can we verify your issue is addressed?

Once load balancers can be successfully deleted via Horizon.
##### If you are using or know of a workaround please describe the necessary steps?

Use of the CLI to remove the healthmonitor and the pool work which then allows the removal of the listener and load balancer via Horizon.
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo
##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:
##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:
##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.
##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues)
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc)
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by claco** [comment]
Possibly related? https://cloudnull.io/2016/10/how-to-delete-a-neutron-load-balancer/

**Comment by cloudnull** [comment]
Sadly this is a known limitation of the UI. In newton OpenStack this was addressed but this is not something we'll be able to fix in previous releases. I recommend following/documenting my blog post should it be of use. I'm closing this issue as it's not something we can fix however If needed please feel free to re-open the bug.

If we need to document this, let's get that into the hands of @robb-romans  and @asettle so they can help us do what's needed.

**Comment by LutzBirkhahn** [comment]
@cloudnull Could you clarify how this was addressed in OpenStack Newton version? I'm running Newton but also don't see a way in the Horizon UI to delete health monitors or pools. Using Horizon 3:10.0.0-0ubuntu1~cloud0

**Comment by LutzBirkhahn** [comment]
Meanwhile I found out how to delete health monitors and pools in Horizon (Newton version):
* in "Load Balancers" click on the name of the LB (e.g. "lb1")
* go to "Listeners" tab, click on the name of the listener
* click on the link shown next to "Default Pool ID"
* click on the link shown next to "Health Monitor ID"
* now you can click on the dropdown in the top right and select "Delete Health Monitor"
* (need to find your way back to get to the pool, worst case go the top Horizon page)
* back on the pool page, click on the dropdown in the top right and select "Delete Pool"
* then delete the listener, then delete the load balancer
