### ISSUE TITLE
MaaS plays expect pre-generated entities

### ISSUE THREAD

**Issue by stevelle** [rcbops/rpc-openstack#155]
> We made the conscious decision when putting these plays together not to create missing entities as 
> these should be created at server provisioning and missing entities could mean other provisioning-
> related errors. We felt it was best to bail and have the operator investigate. Also, if you misconfigure
> some variables in ansible you could end up with a slew of newly created entities which are unneeded.

This expectation needs to be captured in the role's readme file and maybe an additional note in the tasks/mainl.yml about why at the point where they are read or another solution to allow them to be more safely created should be discussed to remove this expectation.

I'm not seeing anything related to this topic in the RPC install guide either but that could be a pebsak.

See also: #147 and #152

Alternative to documenting this is to improve the design to allow entities to be auto-generated more safely.

**Comment by nrb** [comment]
This is largely a documentation task, but it's worth clarifying history for future reference.

**Comment by mancdaz** [comment]
@nrb @stevelle is there anything to be done here?

**Comment by nrb** [comment]
@mancdaz Documentation in the README/docs really, nothing that I know of in code.

**Comment by stevelle** [comment]
what @nrb said

**Comment by andymcc** [comment]
I'll create a docs issue and we can work to add this in.

**Comment by andymcc** [comment]
Happy to just go with the PR - I think it explains failures well enough to not have to create a separate docs issue.

**Comment by mancdaz** [comment]
@andymcc agree - with a second +1 on that review we can merge and close this off.

**Comment by andymcc** [comment]
Closing this issue out.
