### ISSUE TITLE
Incorrect tag for removal tasks in upgrade_elasticsearch.yml

### ISSUE THREAD

**Issue by d34dh0r53** [rcbops/rpc-openstack#1550]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

master
mitaka-13.1
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added
##### What is the expected behavior?

The reindexing plugin should remain installed when the `reindex-wrapper` tag is used.
##### What is actually happening?

The reindexing plugin is being removed by the `Remove Legacy Plugins` task due to the `reindex-wrapper` tag being included.
##### What were you attempting to do when you encountered this error (give as much detail as possible)?

pre-upgrade reindex
##### How can we reproduce this issue?

Use the `reindex-wrapper` tag while running `elasticsearch.yml`
##### What is your evaluation on the importance of this issue, and why?

High - this could impact upgrades in customer environments
---
###### For each pull request, update the branch line to reference it.
- [x] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo
##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [x] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:
##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:
##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.
##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues)
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc)
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by b3rnard0** [comment]
@d34dh0r53 Does this need to go into 13.1.1?

**Comment by d34dh0r53** [comment]
@b3rnard0 yes
