### ISSUE TITLE
rpc-maas-tool.py does not support checks without arguments

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1575]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

master

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

Script does not ex

##### What is actually happening?
```
/opt/rpc-openstack/scripts/rpc-maas-tool.py --entity xxxx --verbose verify-local

Added debug output:
['/usr/lib/rackspace-monitoring-agent/plugins/hp_monitoring.py'] {'file': 'hp_monitoring.py'}
```

Actual trace:
```
Traceback (most recent call last):
  File "/opt/rpc-openstack/scripts/rpc-maas-tool.py", line 822, in <module>
    sys.exit(cli.main())
  File "/opt/rpc-openstack/scripts/rpc-maas-tool.py", line 316, in main
    result = dd[self.args.command]()
  File "/opt/rpc-openstack/scripts/rpc-maas-tool.py", line 424, in verify_local
    args.extend(check['details']['args'])
KeyError: 'args'
```

I have added some output to see why the script failed and it was clearly it fails on plugin checks having no arguments configured like the hp_monitoring.py

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

N/A

##### How can we reproduce this issue?

See above

##### How can we verify your issue is addressed?

No more key error

##### If you are using or know of a workaround please describe the necessary steps?

N/A

##### What is your evaluation on the importance of this issue, and why?

Prio 2 since verify_maas play will fail on all standard setups

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master - https://github.com/rcbops/rpc-openstack/pull/1576
- [ ] mitaka-13.1

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
Hi @BjoernT. Hmmm...we have a jenkins job that tests rpc-maas-tool.py(via verify-maas.yml) with the ``verify-local`` flag. Those jobs seem to be running just fine on master i.e http://jenkins.propter.net/job/test_offline_maas/129/
Is this on a recent mitaka build?

**Comment by BjoernT** [comment]
@alextricity25 I don't think you install hp monitors in gating, hence this got not detected

**Comment by alextricity25** [comment]
@BjoernT Ah! Good catch. This would be good to note as part of our QE efforts to close these gaps.
Thanks!

**Comment by alextricity25** [comment]
Thanks @BjoernT for the fix! Anyway we can get this backported to the mitaka-13.1 branch soon?

**Comment by BjoernT** [comment]
@alextricity25 No problem I get a PR ready this morning

**Comment by BjoernT** [comment]
@alextricity25  I had to cherry pick two changed in order to back port this bug due to other improvements we made around rpc-maas-tool.py which I believe is definitely beneficial for mitaka 13.1
