### ISSUE TITLE
ceph.ceph-osd was NOT installed successfully: - command git checkout 434a13f4d3ee3f60c410052d2670d5dfea034bf8 failed in directory

### ISSUE THREAD

**Issue by alextricity25** [rcbops/rpc-openstack#1596]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
ceph.ceph-osd role is installed successfully

##### What is actually happening?
ceph-osd role isn't being installed successfully
```
09:22:38 + ansible-galaxy remove --roles-path /opt/rpc-openstack/rpcd/playbooks/roles/ ceph-common ceph-mon ceph-osd
09:22:39 - ceph-common is not installed, skipping.
09:22:39 - ceph-mon is not installed, skipping.
09:22:39 - ceph-osd is not installed, skipping.
09:22:39 + ansible-galaxy install --role-file=/opt/rpc-openstack/ansible-role-requirements.yml --force --roles-path=/opt/rpc-openstack/rpcd/playbooks/roles
09:22:40 - extracting ceph.ceph-common to /opt/rpc-openstack/rpcd/playbooks/roles/ceph.ceph-common
09:22:40 - ceph.ceph-common was installed successfully
09:22:40 - extracting ceph.ceph-mon to /opt/rpc-openstack/rpcd/playbooks/roles/ceph.ceph-mon
09:22:40 - ceph.ceph-mon was installed successfully
09:22:40 [DEPRECATION WARNING]: The comma separated role spec format, use the 
09:22:40 yaml/explicit format instead..
09:22:40 This feature will be removed in a future 
09:22:40 release. Deprecation warnings can be disabled by setting 
09:22:40 deprecation_warnings=False in ansible.cfg.
09:22:40 - dependency ceph.ceph-common already pending installation.
09:22:40  [WARNING]: - ceph.ceph-osd was NOT installed successfully: - command git
09:22:40 checkout 434a13f4d3ee3f60c410052d2670d5dfea034bf8 failed in directory
09:22:40 /tmp/tmpgJOuKO (rc=128)
09:22:40 
09:22:40 ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```
I suspect this is related to https://github.com/ceph/ceph-ansible/pull/1110 recently merging.
##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
This failure is occurring in our gate jobs. For example:
http://jenkins.propter.net/job/JJB-RPC-AIO_master-swift/1349/console

##### How can we reproduce this issue?
NA
##### How can we verify your issue is addressed?
ceph.ceph-osd is installed successfully
##### If you are using or know of a workaround please describe the necessary steps?
Not known at this time.
##### What is your evaluation on the importance of this issue, and why?
prio-expedite. This is currently breaking our gate jobs and is preventing anyone from deploying RPCO.
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
This is fixed upstream now. The commit we were pinning to was mistakenly removed but it seems to be there again now.

**Comment by b3rnard0** [comment]
@alextricity25 Thanks for the quick dive on this issue and for bringing it up in the chat room to get additional eyes and help.
