### ISSUE TITLE
Use latest python-magnumclient

### ISSUE THREAD

**Issue by shane-c** [rcbops/rpc-openstack#1599]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs
.
root@infra01:/opt/rpc-openstack/rpcd# git describe --all
r13.0.3

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

python-magnumclient 2.3.0 installed

##### What is actually happening?

Our repo container only has python-magnumclient 2.0.0 which is missing the `magnum cluster-*` commands. I also ran into errors with service type and 2.0.0. 

```
root@infra01:~# curl -s http://172.29.236.51:8181/os-releases/13.3.6/ | grep magnum
<a href="python_magnumclient-2.0.0-py2.py3-none-any.whl">python_magnumclient-2.0.0-py2.py3-none-any.whl</a><br />
```

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Trying to create magnum templates and clusters

##### How can we reproduce this issue?

Install magnum and pip install python-magnumclient, verify it's 2.0.0 and notice it's missing the cluster-* commands. Also try creating a template/cluster. 

##### How can we verify your issue is addressed?

python-magnumclient 2.3.0 is in our repo 

##### If you are using or know of a workaround please describe the necessary steps?

```
pip --isolated install python-magnumclient
```

However, because of other dependencies this breaks openstack CLI as far as I can tell.

##### What is your evaluation on the importance of this issue, and why?

Low, I don't think we're supporting Magnum yet

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
FYI - @chrishultin

**Comment by jnoller** [comment]
Closing as magnum is no longer on the plan
