### ISSUE TITLE
Allow pinning of infrastructure package versions

### ISSUE THREAD

**Issue by b3rnard0** [rcbops/rpc-openstack#16]
In order to assist with providing a supportable and predictable infrastructure, it would be useful to be able to pin infrastructure (eg: mariadb, rabbitmq, lxc, libvirt, elasticsearch, logstash) packages to specific versions.

**Comment by nrb** [comment]
This is status dev-done; can we close it?

Did this come from somewhere else?

**Comment by d34dh0r53** [comment]
@b3rnard0 any idea if we can close this?

**Comment by b3rnard0** [comment]
@d34dh0r53 This was from the old board so go ahead and close it.
