### ISSUE TITLE
neutron_service_check.py not recognizing fqdn after change from short reporting linuxbridge-agent down

### ISSUE THREAD

**Issue by ihavegerms** [rcbops/rpc-openstack#1603]
##### On which version(s) do you encounter this issue?
Kilo - r11.1.6

###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

root@infra-node1:/opt/rpc-openstack# git describe --all
tags/r11.1.6

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
That no alert would be created when the service is indeed responding/ok. 

##### What is actually happening?
When the maas plugin attempts to verify it can find itself with the following piece of code;

    # gather nova service states
    if args.host:
        services = nova.services.list(host=args.host)
    else:
        services = nova.services.list()

    if len(services) == 0:
        status_err("No host(s) found in the service list")

It is not finding the hosts that have changed from short, to a fqdn.

To fix the issue, I modified the plugin as follows;

agents = neutron.list_agents(host=args.host + '.l42scl.hortonworks.com')['agents']

... and the check was successful.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Verify an alert detailing that neutron_linuxbridge_agent was failing/down. When I ran the check manually, it was claiming that "No host(s) found in the agents list". So I looked at the code and realized that it couldn't find itself after the customer changed to fqdn's.

##### How can we reproduce this issue?

Create a host with a short name, install maas, then change the hostname to a fqdn. If you run the neutron_service_check.py maas plugin after, it should fail even though within the environment it is checking in without issue.

##### How can we verify your issue is addressed?

We should be able to work with our customer and re-install/update maas on the hosts effected and ensure all checks are good to go. (via lab you should be able to reproduce and verify as well)

##### If you are using or know of a workaround please describe the necessary steps?

As previously mentioned, if you add a short bit to the specified line in the plugin code;

[from]

agents = neutron.list_agents(host=args.host)['agents']

[to]

agents = neutron.list_agents(host=args.host + '.l42scl.hortonworks.com')['agents']

The error goes away.

##### What is your evaluation on the importance of this issue, and why?

Pretty significant in my opinion. Any customer using MaaS that receives an alert about linuxbridge-agent being down may mobilize resources to address the instances on that compute only to find out that there is in fact no issue at all. (a hair extreme in my opinion, but seems feasible)
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
Thanks @ihavegerms!
My guess is that we are not setting the right host value in the neutron_*.yml checks i.e. https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/templates/neutron_linuxbridge_agent_check.yaml.j2#L8.
I could be wrong, but we haven't had much experience with people changing to FQDNs. However, this is definitely still worth a fix. I'm marking this as prio-3 as it doesn't prevent the default deployment from succeeding. Please let me know if you feel if this priority needs to be higher.

**Comment by alextricity25** [comment]
It could be that this issue has already been fixed by all of the recent MaaS PRs that have gone through. If not, then this probably effects newton as well and needs to be addressed. I'm going to milestone it as r14.0.1, but I do not guarantee it will be fixed by then.

**Comment by alextricity25** [comment]
I've confirmed that this is still a problem in our master branch.
The neutron_service_check.py plugin takes in a ``host`` argument. If you look at the check yaml files, ``ansible_nodename`` is passed to the plugin via the ``host`` argument. Per [Ansible documentation](http://docs.ansible.com/ansible/playbooks_variables.html#information-discovered-from-systems-facts), ``ansible_nodename`` is the hostname as reported by the system [by the ``hostname`` command](https://github.com/ansible/ansible/issues/9971), which doesn't include the domain.

This means that these checks that are using ``ansible_nodename`` will not pass on an openstack environment that uses fqdns instead of shortnames for hosts.

A possible solution would be to modify the ``neutron_service_check.py`` plugin to take in the fqdn as well, then check to see if the hosts reported by ``neutron.list_agents()`` match either ``args.fqdn`` OR ``args.host``.

**Comment by cjloader** [comment]
Update: I am investigating this issue in Master. The setup-maas.yml playbook is failing. Trying to figure out why.

**Comment by cjloader** [comment]
Update -- setup-maas.yml is succeeding.

**Comment by cjloader** [comment]
Update: rewriting the script. Still working on it.
