### ISSUE TITLE
Swifft template named incorrectly

### ISSUE THREAD

**Issue by rpawlik** [rcbops/rpc-openstack#1604]
##### On which version(s) do you encounter this issue?
r12.2.8

###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
12.2.8

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

Swift playbook completes.

##### What is actually happening?

A failure occurs because roles/os_swift/tasks/swift_post_install.yml is looking for a template called "swift-container-sync-realms.conf.j2" but the template is actually called "container-sync-realms.conf.j2".

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Upgrading to 12.2.8

##### How can we reproduce this issue?
Install or upgrade swift.

##### How can we verify your issue is addressed?
Either rename the template or set the proper template name in roles/os_swift/tasks/swift_post_install.yml

##### If you are using or know of a workaround please describe the necessary steps?
I renamed the template to "container-sync-realms.conf.j2".

##### What is your evaluation on the importance of this issue, and why?
It important as it causes the upgrade/install to fail.
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by BjoernT** [comment]
This is invalid since OSA does not manage  swift-container-sync-realms.conf.j2 per https://github.com/openstack/openstack-ansible/blob/eol-kilo/playbooks/roles/os_swift/tasks/swift_post_install.yml
this has been added post install, manually
