### ISSUE TITLE
Newton: openstack-ansible-security : V-38660 failure

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1616]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

We need to investigate the snmp configuration in regards to HP/Dell montioring tools and our default configuration if managed by kick.
We may need to add migrations steps to fix the snmpd config.
Additionally it seems the egrep is a little to greedy....

##### What is actually happening?

```
TASK [openstack-ansible-security : V-38660 - The snmpd service must only use SNMPv3 or newer] ***
fatal: [storage02]: FAILED! => {"changed": false, "failed": true, "msg": "Insecure SNMP configuration found -- use SNMPv3 only"}
fatal: [storage01]: FAILED! => {"changed": false, "failed": true, "msg": "Insecure SNMP configuration found -- use SNMPv3 only"}
fatal: [storage03]: FAILED! => {"changed": false, "failed": true, "msg": "Insecure SNMP configuration found -- use SNMPv3 only"}
fatal: [infra03]: FAILED! => {"changed": false, "failed": true, "msg": "Insecure SNMP configuration found -- use SNMPv3 only"}
fatal: [infra01]: FAILED! => {"changed": false, "failed": true, "msg": "Insecure SNMP configuration found -- use SNMPv3 only"}
fatal: [infra02]: FAILED! => {"changed": false, "failed": true, "msg": "Insecure SNMP configuration found -- use SNMPv3 only"}
fatal: [logging01]: FAILED! => {"changed": false, "failed": true, "msg": "Insecure SNMP configuration found -- use SNMPv3 only"}
fatal: [compute01]: FAILED! => {"changed": false, "failed": true, "msg": "Insecure SNMP configuration found -- use SNMPv3 only"}
fatal: [compute02]: FAILED! => {"changed": false, "failed": true, "msg": "Insecure SNMP configuration found -- use SNMPv3 only"}

NO MORE HOSTS LEFT *************************************************************




egrep 'v1|v2c|com2sec|community' /etc/snmp/snmpd.conf | grep -v '^\\s*#'
#rocommunity public  localhost
 rocommunity public  default    -V systemonly
                                                 #     settings, change the community string,
#rocommunity secret  10.0.0.0/16
#  It's no longer typically necessary to use the full 'com2sec/group/access' configuration
#  r[ow]user and r[ow]community, together with suitable views, should cover most requirements
                                    #   send SNMPv1  traps
                                    #   send SNMPv2c traps
                                    #   send SNMPv2c INFORMs
```
##### How can we reproduce this issue?

Run stable/newton security hardening on 14.04 hosts

##### How can we verify your issue is addressed?

See above

##### If you are using or know of a workaround please describe the necessary steps?

Disabling security hardening/skipping check

##### What is your evaluation on the importance of this issue, and why?

Prio 2

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
This doesn't affect any published releases, but would be good to look at as part of our newton effort.
