### ISSUE TITLE
Ensure ansible.cfg is still needed

### ISSUE THREAD

**Issue by alextricity25** [rcbops/rpc-openstack#1639]
##### On which version(s) do you encounter this issue?
Master on Newton

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
TBD

##### What is actually happening?
Currently we override a few ansible behavior configurations here. However, this behavior may overlap with the upstream defaults that are set and might not be needed anymore. We need to investigate to see if any of these configurations are needed. If not, then we can following in the footsteps of OSA to remove the ansible.cfg file as done in this patchset: https://review.openstack.org/#/c/345572/17

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
This was something that came out of the OSA newton SHA bump work done here: https://github.com/rcbops/rpc-openstack/pull/1577
##### How can we reproduce this issue?
NA
##### How can we verify your issue is addressed?
By the time this issue is ready to be closed, we should have determined whether the ansible.cfg file is still needed and which configurations still need to be overridden.
##### If you are using or know of a workaround please describe the necessary steps?
NA
##### What is your evaluation on the importance of this issue, and why?
Prio-3. It's not needed to continue deployment, but it is necessary to align ourselves with OSA.
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by major** [comment]
All of the data in `ansible.cfg` is the same as the upstream OSA configuration with the exception of:

```
# SSH timeout
timeout = 120
```
