### ISSUE TITLE
PKB: Deprecate openstack_volume_size flag and use data_disk_size instead

### ISSUE THREAD

**Issue by vhe182** [rcbops/rpc-openstack#1645]
Address Issue: GoogleCloudPlatform/PerfKitBenchmarker: Issue #1122

PR that addresses above issue:
GoogleCloudPlatform/PerfKitBenchmarker: Pull Request 1206

**Comment by vhe182** [comment]
Status is blocked because this suggested change requires confirmation on the performance lab.  The lab is currently in the middle of an upgrade to OpenStack Mitaka.

**Comment by alextricity25** [comment]
@vhe182 Did you mean to log this issue in https://github.com/rcbops/u-suk-dev? Issues logged here should be specific to RPCO code in tree.

**Comment by vhe182** [comment]
@alextricity25 My bad, I will move it to u-suck-dev.  Thanks for the headsup.
