### ISSUE TITLE
Add timelines to KPIs to execute and automate

### ISSUE THREAD

**Issue by vhe182** [rcbops/rpc-openstack#1646]

**Comment by alextricity25** [comment]
Hi @vhe182. I'm a little confused about this issue. Could you add some more information by using our issue template, please? For example: https://github.com/rcbops/rpc-openstack/issues/new

**Comment by vhe182** [comment]
Sorry for the confusion, @alextricity25.  This issue is for our performance test plans and shouldn't be in /rpc-openstack.  I'll move it to /u-suk-dev and make sure the issue follows the appropriate guidelines.
