### ISSUE TITLE
Maas deprecation warnings and errors in Newton

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1647]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

No warnings

##### What is actually happening?

When running setup-maas.yml you run into several warning and errors for

- maas_requires_pip_packages
- plugin_files.stdout_lines
- maas_filesystem_monitors
- maas_filesystem_overrides
- vhost_json
- inventory_hostname == groups['swift_proxy'][0]

Warnings:

```
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{maas_requires_pip_packages}}').
This feature
will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

Error:

```
fatal: [infra03_nova_conductor_container-ce254a90]: FAILED! => {"failed": true, "msg": "The conditional check 'inventory_hostname == groups['swift_proxy'][0]' failed. The error was: error while evaluating conditional (inventory_hostname == groups['swift_proxy'][0]): list object has no element 0\n\nThe error appears to have been in '/opt/rpc-openstack/rpcd/playbooks/roles/rpc_maas/tasks/main.yml': line 48, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include: swift_access_check.yml\n  ^ here\n"}
```
##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

See above

##### How can we reproduce this issue?

See above

##### How can we verify your issue is addressed?

No warning

##### If you are using or know of a workaround please describe the necessary steps?

N/A

##### What is your evaluation on the importance of this issue, and why?

Prio 2

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
Nice catch. I'm going to target this for r14.0.0rc1 and mark it as prio-2.

**Comment by alextricity25** [comment]
FYI - This will need to be backported to the newton-14.0 branch before it's closed.

**Comment by BjoernT** [comment]
@alextricity25 Submitted a pr for newton-14.0
