### ISSUE TITLE
master branch build fails on keystone db sync

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/rpc-openstack#166]
For some reason a master branch build of RPC fails during the keystone db sync - it appears that there's some weird deployment of both juno and kilo packages as there's a conflicting db migration script which comes from the juno package.

**Comment by miguelgrinberg** [comment]
The keystone wheel stored in mirror.rackspace.com for master is bad. It was probably generated when the upstream repo was undergoing a db migration cleanup, because there are two migrations with the same number. Moving the SHA forward and regenerating the package will likely address this issue.

**Comment by odyssey4me** [comment]
The suggested workaround at this time is to build RPC using the kilo branch.

**Comment by miguelgrinberg** [comment]
The updated keystone wheel works fine. Closing this issue.
