### ISSUE TITLE
maas tasks getting cluttered

### ISSUE THREAD

**Issue by stevelle** [rcbops/rpc-openstack#167]
There are a number of tasks performed during maas install which all rely on related or identical conditions to be applied. This is only getting worse as more conditionally included tasks are added to support variations of environment. Some refactor to clean this up would be helpful.

Specifically, more than half of the tasks named in the main.yml depend on a test that is targeted to run on hardware hosts as opposed to containers. Extracting that logic can make this easier to scan and make the other conditions that is combined with appear more straight forward.

**Comment by nrb** [comment]
Merged into master and Kilo, closing.
