### ISSUE TITLE
setup-logging does not work correctly with Multi Region swift

### ISSUE THREAD

**Issue by kstev** [rcbops/rpc-openstack#1673]
##### On which version(s) do you encounter this issue? 

r12.1.2-1-ge30a48f

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
Running setup-logging should configure nodes in same region to ship logs, etc to rsyslog and logstash in the same region.

##### What is actually happening?
Running setup-logging in region 1 configures necessary r1 nodes plus swift remote hosts' beaver to send data to logstash node in region 1.
Afterwards, running setup-logging in region 2 configures necessary r2 nodes plus swift remote hosts' beaver to send data to logstash node in region 2.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
I was attempting to get Kibana working by configuring beaver to ship data to logstash so ES would get the appropriate data

##### How can we reproduce this issue?
In an environment with multi-region Swift, run "openstack-ansible --skip-tags lock-down-pip-conf setup-logging.yml"

##### How can we verify your issue is addressed?
Ideally, you could run the setup-logging playbook without having to skip tag lock-down-pip-conf and only nodes in the same region would be involved/configured

##### If you are using or know of a workaround please describe the necessary steps?
1. Run setup-logging in R1
2. Run setup-logging in R2
3. In R1, run ansible swift_acc -m shell -a "sed -i 's/<R2-logstash-ip>/<R1-logstash-ip>/g' /etc/beaver/beaver.conf"

##### What is your evaluation on the importance of this issue, and why?
Low. edge case and easy workaround 

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by byronmccollum** [comment]
See: https://github.com/rcbops/rpc-openstack/issues/1217#issuecomment-230805488

**Comment by cloudnull** [comment]
Closing as we no longer use beaver in Mitaka+ which resolves this bug. If we need to backport the filebeat process to Liberty/Kilo we can take a look at that later. Due to Libety/Kilo being end-of-life and the fact the changes that needed to get that to work on the old logging stack would be very large, I'm not of the opinion it's worth the effort. That said, please re-open this issue or create new one if we need to prioritize and track a backport attempt.
