### ISSUE TITLE
Can't find os_magnum role using deploy.sh

### ISSUE THREAD

**Issue by shane-c** [rcbops/rpc-openstack#1693]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

git describe --all
r13.1.3

##### What type of issue is this? Please tick the appropriate box.
- [ x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

Magnum installed with deploy.sh on first run

##### What is actually happening?

On the first attempt at running deploy.sh, it errors out with "ERROR: cannot find role in /opt/rpc-openstack/openstack-ansible/playbooks/roles/os_magnum or /opt/rpc-openstack/openstack-ansible/playbooks/os_magnum or /etc/ansible/roles/os_magnum"

I think this is an ordering problem in deploy.sh. On running deploy.sh for the first time it downloads ansible roles at https://github.com/rcbops/rpc-openstack/blob/r13.1.3/scripts/deploy.sh#L55-L56, but the contrib/scripts/mangum.sh script doesn't put the os_magnum role into $OA_DIR/ansible-role-requirements.yml until https://github.com/rcbops/rpc-openstack/blob/r13.1.3/scripts/deploy.sh#L143. 

Rerunning depoy.sh a second time does download the os_magnum role because it's in ansible-role-requirements.yml at that point.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Running deploy.sh for first time with DEPLOY_MAGNUM:-"yes"

##### How can we reproduce this issue?

Run deploy.sh with export DEPLOY_MAGNUM=${DEPLOY_MAGNUM:-"yes"}

##### How can we verify your issue is addressed?

deploy.sh installs magnum the first run

##### If you are using or know of a workaround please describe the necessary steps?

Rerun deploy.sh

##### What is your evaluation on the importance of this issue, and why?

Low

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
cc @chrishultin

**Comment by chrishultin** [comment]
See https://github.com/rcbops/rpc-openstack/pull/1720

**Comment by chrishultin** [comment]
Merged
