### ISSUE TITLE
contrib/scripts/magnum.sh doesn't verify if echo to setup-openstack.yml is needed

### ISSUE THREAD

**Issue by shane-c** [rcbops/rpc-openstack#1695]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

git describe --all
r13.1.3

##### What type of issue is this? Please tick the appropriate box.
- [ x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

Rerunning deploy.sh doesn't result in multiple '- include: os-magnum-install.yml' being added to setup-openstack.yml

##### What is actually happening?

On each deploy.sh run, contrib/scripts/magnum.sh is adding '- include: os-magnum-install.yml' to setup-openstack.yml resulting in multiple lines.

```
root@shane-mitaka:/opt/rpc-openstack/contrib/scripts# grep -n 'echo' magnum.sh
60:  echo "- include: os-magnum-install.yml" >> $OA_DIR/playbooks/setup-openstack.yml

root@shane-mitaka:/opt/rpc-openstack/openstack-ansible/playbooks# grep magnum setup-openstack.yml
- include: os-magnum-install.yml
- include: os-magnum-install.yml
```

magnum.sh needs something like a grep for magnum in setup-openstack.yml and echo or not based on return code.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Ran deploy.sh multiple times

##### How can we reproduce this issue?

Run deploy.sh multiple times

##### How can we verify your issue is addressed?

Running deploy.sh doesn't result in multiple magnum entries in setup-openstack.yml

##### If you are using or know of a workaround please describe the necessary steps?

Remove extra magnum lines from setup-openstack.yml

##### What is your evaluation on the importance of this issue, and why?

Low

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
cc @chrishultin

**Comment by chrishultin** [comment]
See https://github.com/rcbops/rpc-openstack/pull/1720

**Comment by chrishultin** [comment]
Merged
