### ISSUE TITLE
Magnum missing RabbitMQ variables

### ISSUE THREAD

**Issue by shane-c** [rcbops/rpc-openstack#1696]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

git describe --all
r13.1.3

##### What type of issue is this? Please tick the appropriate box.
- [ x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

When magnum is installed it can talk to rabbitmq

##### What is actually happening?

With the default variables set by contrib/script/magnum.sh, magnum can't communicate with rabbitmq. It tries to use localhost:

```
/var/log/magnum/magnum-api.log

2017-01-20 05:59:17.586 4180 ERROR oslo.messaging._drivers.impl_rabbit [req-878bcc7c-0a5a-4fe5-8669-4ebdd2848e07 admin admin - - -] AMQP server on 127.0.0.1:5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 16 seconds.
2017-01-20 05:59:33.609 4180 ERROR oslo.messaging._drivers.impl_rabbit [req-878bcc7c-0a5a-4fe5-8669-4ebdd2848e07 admin admin - - -] AMQP server on 127.0.0.1:5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 18 seconds.
```
and magnum-conductor won't connect, our rabbitmq clusters are setup for SSL/TLS. 

```
/var/log/magnum/magnum-conductor.log

2017-01-20 06:32:38.603 4612 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server 172.29.238.34:5671 closed the connection. Check login credentials: Socket closed
2017-01-20 06:33:10.645 4612 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server 172.29.237.45:5671 closed the connection. Check login credentials: Socket closed
```
I verified the rabbitmq user can auth to rabbitmq. 
```
root@shane-mitaka-rabbit-mq-container-90ed8ff8:/# rabbitmqctl authenticate_user magnum f93a85cfb0ba24e5f4ada26cdfc86b4f46c6622
Authenticating user "magnum" ...
Success
```

Adding these variables to user_osa_variables_overrides.yml and rerunning openstack-ansible os-magnum-install.yml --tags magnum-config got the magnum service up.

```
magnum_rabbitmq_servers: "{{ rabbitmq_servers }}"
magnum_rabbitmq_port: "{{ rabbitmq_port }}"
magnum_rabbitmq_use_ssl: "{{ rabbitmq_use_ssl }}"
```

```
(magnum-13.3.12) root@shane-mitaka-magnum-container-fd88d6df:/# magnum service-list
+----+----------------+------------------+-------+----------+-----------------+---------------------------+---------------------------+
| id | host           | binary           | state | disabled | disabled_reason | created_at                | updated_at                |
+----+----------------+------------------+-------+----------+-----------------+---------------------------+---------------------------+
| 3  | 172.29.238.206 | magnum-conductor | up    |          | -               | 2017-01-20T05:25:13+00:00 | 2017-01-20T06:42:25+00:00 |
+----+----------------+------------------+-------+----------+-----------------+---------------------------+---------------------------+
```

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Verify magnum was up by running magnum service-list

##### How can we reproduce this issue?

Install default magnum from deploy.sh

##### How can we verify your issue is addressed?

Default magnum install from deploy.sh shows conductor up when service-list is run

##### If you are using or know of a workaround please describe the necessary steps?

Described above

##### What is your evaluation on the importance of this issue, and why?

Medium, current defaults result in broken magnum install

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
cc @chrishultin

**Comment by chrishultin** [comment]
The variables in question (magnum_rabbitmq_servers, magnum_rabbitmq_port, magnum_rabbitmq_use_ssl) are set in /etc/openstack_deploy/env.d/magnum.yml, but it appears that they aren't taking effect.

**Comment by chrishultin** [comment]
See https://github.com/rcbops/rpc-openstack/pull/1720

**Comment by chrishultin** [comment]
Merged
