### ISSUE TITLE
Iteration over ansible device for disk_utilisation maas check include sr0 device

### ISSUE THREAD

**Issue by b3rnard0** [rcbops/rpc-openstack#17]
The new iteration over all SCSI devices does include now sr0 for disk_utilisation maas check and that check fails since we have no media mounted on this device. SR0 need to be excluded from this device list, otherwise the alarms will fail.

**Comment by b3rnard0** [comment]
Need feedback from @mancdaz @claco @cloudnull .

**Comment by prometheanfire** [comment]
I'm not sure this is still the case, @BjoernT does this still happen?

**Comment by andymcc** [comment]
Closing this - there is an ability to exclude devices from the utilisation checks (maas_excluded_devices) - if this is still an issue feel free to re-open

**Comment by BjoernT** [comment]
So we can close this issue only when: 
a) we either exclude sr0 by default 
or b) change the logic to exclude all virtual devices and sr0 automatically
