### ISSUE TITLE
Investigate cleanup of Swift tasks 

### ISSUE THREAD

**Issue by stevelle** [rcbops/rpc-openstack#170]
Identify and apply simplifying refactors to the roles/rpc_maas/tasks/swift.yml tasks since #169 ensures none of these tasks run if there is no swift services enabled.

**Comment by prometheanfire** [comment]
need to backport #169 to kilo as well (and #152)

**Comment by nrb** [comment]
Be warned: the 'fix swift-recon.py' commit fixes https://github.com/rcbops/rpc-maas/issues/170, not this issue.

This was a consequence of pulling in the rpc-maas git history.

**Comment by andymcc** [comment]
I don't believe this is required anymore? @stevelle if incorrect please feel free to re-open perhaps I am misinterpreting the issue.
