### ISSUE TITLE
Add rally install options to deploy.sh

### ISSUE THREAD

**Issue by vhe182** [rcbops/rpc-openstack#1705]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
N/A
##### What type of issue is this? Please tick the appropriate box.
- [ ] bug - existing functionality that does not work for you as documented
- [x] feature - new functionality that you would like to see added

##### What is the expected behavior?
Have the option to install rally using deploy.sh
##### What is actually happening?
No option to install rally using deploy.sh :(
##### How can we reproduce this issue?
N/A
##### How can we verify your issue is addressed?
Try to install rally using rpc-openstack
##### If you are using or know of a workaround please describe the necessary steps?
N/A
##### What is your evaluation on the importance of this issue, and why?
High for performance team.  We use Rally for gating performance tests
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by odyssey4me** [comment]
Rally can be deployed by simply executing the playbook that deploys it. Personally I don't really understand the need for an environment variable to set whether it's deployed or not.

**Comment by vhe182** [comment]
@odyssey4me , it doesn't seem necessary that Rally should install on all deployments.  The reason for providing this deploy option is so that the performance team can implement their performance tests in accordance with unified gating expectations.  Yes, I agree, that the playbook could just be called outside of the deploy script but adding the call seemed like a simple option with little impact.  Since Rally is one of the primary tools used for gating all builds, it makes sense to include it as an option in deploy.sh.

**Comment by alextricity25** [comment]
It seems like this has a fix and has merged.
