### ISSUE TITLE
Add Magnum metrics to MaaS

### ISSUE THREAD

**Issue by Kuwagata** [rcbops/rpc-openstack#1738]
##### On which version(s) do you encounter this issue?
master

##### What type of issue is this? Please tick the appropriate box.
- [ ] bug - existing functionality that does not work for you as documented
- [x] feature - new functionality that you would like to see added

##### What is the expected behavior?
Magnum integrates with MaaS by including plugins to:
- Provide Magnum API health metrics
- Provide Magnum service metrics

##### What is actually happening?
Magnum does not send metrics to MaaS.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
n/a

##### How can we reproduce this issue?
n/a

##### How can we verify your issue is addressed?
n/a

##### If you are using or know of a workaround please describe the necessary steps?
n/a

##### What is your evaluation on the importance of this issue, and why?
This is a key component for actively ensuring service stability for Magnum.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master #1738

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [x] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):
[docs-rpc PR](https://github.com/rackerlabs/docs-rpc/pull/962)

**Comment by alextricity25** [comment]
Magnum is still in tech-preview mode in the mitaka branch. Tech-preview items will not include MaaS plugins for monitoring. However, we are currently looking into bringing Magnum into the newton branch and developing it further there. Once it solidifies there we can look at integrating the service with our MaaS plugins.
