### ISSUE TITLE
Ceph mon container fails build in LTS 16.04 

### ISSUE THREAD

**Issue by jmiracle-cbts** [rcbops/rpc-openstack#1751]
##### On which version(s) do you encounter this issue?
newton-14.0
commit 51ac3a68b65d9d86cc39d71d4f1a3609d93cc8f1

###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

root@os-deployment:/opt/rpc-openstack# git describe --all
heads/newton-14.0

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
Ceph mon should be enabled / started via systemd.

##### What is actually happening?
Looks like it's trying to enable/start via upstart (and failing due to some control code garbage / improper passthrough).
TASK [ceph.ceph-mon : start and add that the monitor service to the init sequence (ubuntu)] ***
fatal: [node02_ceph_mon_container-411654cd]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to start id\\x3dnode02-ceph-mon-container-411654cd.service: Unit id\\x3dnode02-ceph-mon-container-411654cd.service not found.\n"}
fatal: [node03_ceph_mon_container-041e5567]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to start id\\x3dnode03-ceph-mon-container-041e5567.service: Unit id\\x3dnode03-ceph-mon-container-041e5567.service not found.\n"}
fatal: [node04_ceph_mon_container-1a0c4e8e]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to start id\\x3dnode04-ceph-mon-container-1a0c4e8e.service: Unit id\\x3dnode04-ceph-mon-container-1a0c4e8e.service not found.\n"}

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Deploy a fresh environment via build.sh 

##### How can we reproduce this issue?
Standard deploy with 3x ceph mons with is_metal: false.

##### How can we verify your issue is addressed?
I can rerun / patch and test.

##### If you are using or know of a workaround please describe the necessary steps?
I am able to manually lxc-attach to the containers created and enable/start the units manually 
root@node02-ceph-mon-container-411654cd:~# systemctl enable ceph-mon@node02-ceph-mon-container-411654cd
Created symlink from /etc/systemd/system/ceph-mon.target.wants/ceph-mon@node02-ceph-mon-container-411654cd.service to /lib/systemd/system/ceph-mon@.service.
root@node02-ceph-mon-container-411654cd:~# systemctl start ceph-mon@node02-ceph-mon-container-411654cd
root@node02-ceph-mon-container-411654cd:~# 

However, the playbook still fails there because the service name it's passing to upstart is invalid:
TASK [ceph.ceph-mon : start and add that the monitor service to the init sequence (ubuntu)] ***
fatal: [node02_ceph_mon_container-411654cd]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to start id\\x3dnode02-ceph-mon-container-411654cd.service: Unit id\\x3dnode02-ceph-mon-container-411654cd.service not found.\n"}

##### What is your evaluation on the importance of this issue, and why?
Moderately important for 16.04- automated builds/installs with ceph mon containers are not possible.

Note: this probably wouldn't be an issue if it was still possible to specify container_release: trusty (because then the init system would still be using upstart instead of systemd), it seems that the fact it's forced to 16.04 by the host OS is causing issues now. This appears to have changed a few days ago on: https://github.com/rcbops/rpc-openstack/issues/1712

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
Thanks @jmiracle-cbts for submitting this issue!
At the moment we are not going to dedicate much time into shoe-horning the current version of Ceph that we deploy onto a Xenial system. If anything, we are most likely going to bump the ceph-ansible role version so that it complies with systemd and deploys Jewel.
I'm going to mark this at won't-fix, as I don't see this as something we will address in the near future.
