### ISSUE TITLE
RPC f5_config.py SNAT IP default

### ISSUE THREAD

**Issue by b3rnard0** [rcbops/rpc-openstack#18]
The f5_config.py uses .15 by default. Would it be possible to have it check rpc_user_config.yml for the 'used_ips' section and if .15 is specified have it choose a different IP to avoid a conflict?

**Comment by b3rnard0** [comment]
From @stevelle: https://review.openstack.org/#/c/150144/ and https://review.openstack.org/#/c/139726/ fyi

**Comment by andymcc** [comment]
You can override the value using a -s or --snat-pool-address
I'm not sure this is a required bug - its also been open for 10 months with no real update, so I'm going to close this one out.
