### ISSUE TITLE
Update docs for Newton to ensure greenfields are 16.04

### ISSUE THREAD

**Issue by claco** [rcbops/rpc-openstack#1825]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

The install docs should mention 16.04 instead of 14.04 for install and target hosts.

https://pages.github.rackspace.com/rpc-internal/docs-rpc/rpc-install-internal/ch-overview.html#deployment-host

https://github.com/rackerlabs/docs-rpc/blob/master/doc/rpc-install-internal/ch-hosts-deployment.rst

##### What is actually happening?

These pages still mention 14.04, so we need to remember to update them.

https://pages.github.rackspace.com/rpc-internal/docs-rpc/rpc-install-internal/ch-overview.html#deployment-host

https://github.com/rackerlabs/docs-rpc/blob/master/doc/rpc-install-internal/ch-hosts-deployment.rst

##### What is your evaluation on the importance of this issue, and why?

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by Frank-ZhangXin** [comment]
#1220

**Comment by robb-romans** [comment]
Please see https://github.com/rackerlabs/docs-rpc/pull/928

**Comment by Frank-ZhangXin** [comment]
@b3rnard0 @alextricity25 wonder if this card still is needed.

**Comment by Frank-ZhangXin** [comment]
@robb-romans already linked new doc card which include improvement required on this one. So it can be closed.

**Comment by Frank-ZhangXin** [comment]
CC @claco FYI
