### ISSUE TITLE
rpcd openstack_deploy copy needs '/*'

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#183]
In our deploy instructions, step 2ii should be `cp -R /opt/rpc-openstack/etc/openstack_deploy/* /etc/openstack_deploy`.

Otherwise, we get `/etc/openstack_deploy/openstack_deploy`.

**Comment by mattt416** [comment]
Step 2ii also needs updating as we now include a user_variables.yml in rpc-openstack/rpcd/etc/openstack_deploy and just copying everything across would wipe out the user_variables.yml copied in from openstack-ansible-deployment.

**Comment by mattt416** [comment]
We'll need to hold backport of this PR to kilo until https://github.com/rcbops/rpc-openstack/pull/243 has merged.

**Comment by nrb** [comment]
Blocking for the 243 merge.

**Comment by nrb** [comment]
Unblocking and closing since the changes merged.
