### ISSUE TITLE
Rackspace monitoring agent memory errors

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#184]
Reference https://github.com/rcbops/rpc-maas/issues/110

# ps aux | grep [r]ackspace
root     27914 94.6  1.9 552412 160640 ?       Rsl  13:49  24:15 rackspace-monitoring-agent --exit-on-upgrade --production -l /var/log/rackspace-monitoring-agent.log

# strace -p $(pgrep rackspace)
Process 27914 attached
mremap(0x4166e000, 294912, 147456, 0)   = 0x4166e000
mremap(0x4166e000, 147456, 294912, 0)   = 0x4166e000
munmap(0x4210b000, 131072)              = 0
mremap(0x4166e000, 294912, 147456, 0)   = 0x4166e000
mremap(0x4166e000, 147456, 294912, 0)   = 0x4166e000
mremap(0x4166e000, 294912, 147456, 0)   = 0x4166e000
mremap(0x4166e000, 147456, 294912, 0)   = 0x4166e000

# Extracts from /var/log/rackspace-monitoring-agent.log
First time the agent was started
Fri Jun 12 13:22:51 2015 INF: Log file started (pid 9114, path=/var/log/rackspace-monitoring-agent.log)
Fri Jun 12 13:22:52 2015 INF: Using config agent ID (id=maas1-node1)
Fri Jun 12 13:22:52 2015 INF: Starting agent maas1-node1 (guid=ec8a8829-c906-496e-c9c5-bc764e091f51, version=1.1.0-86, bundle_version=1.1.0-86)

Restarted automatically 1
Fri Jun 12 13:38:53 2015 INF: SRV:_monitoringagent._tcp.ord1.prod.monitoring.api.rackspacecloud.com -> Retrying connection in 64660ms
Fri Jun 12 13:47:52 2015 ERR: Runtime Error: [../base/lib/virgo_lua.c:395] (-2)
Lua Runtime Error: not enough memory
stack traceback:
	[builtin#2]: at 0x004f6749
	[C]: in function 'run'
	...ce-monitoring-agent-1.1.0-86/base/lib/lua/virgo_init.lua:638: in function <...ce-monitoring-agent-1.1.0-86/base/lib/lua/virgo_init.lua:633>
Fri Jun 12 13:47:52 2015 ERR: Main exiting: [../base/lib/virgo_lua.c:395] (-2)
Lua Runtime Error: not enough memory
stack traceback:
	[builtin#2]: at 0x004f6749
	[C]: in function 'run'
	...ce-monitoring-agent-1.1.0-86/base/lib/lua/virgo_init.lua:638: in function <...ce-monitoring-agent-1.1.0-86/base/lib/lua/virgo_init.lua:633>
Fri Jun 12 13:47:52 2015 INF: Log file started (pid 24423, path=/var/log/rackspace-monitoring-agent.log)
Fri Jun 12 13:47:53 2015 INF: Using config agent ID (id=maas1-node1)
Fri Jun 12 13:47:53 2015 INF: Starting agent maas1-node1 (guid=b2f337d1-ddd2-4594-c5f4-bc764e091f51, version=1.1.0-86, bundle_version=1.1.0-86)

Restarted automatically 2
Fri Jun 12 13:48:01 2015 INF: (plugin=nova_service_check.py, id=chBeyPPQsc, iid=idg2TvEdtn) -> agent.plugin (details=args="--host","maas1-node1_nova_console_container-623d484a","172.29.236.3",file="nova_service_check.py",id="chBeyPPQsc",period=60) scheduled for 60128s
Fri Jun 12 13:48:57 2015 ERR: Connection: 2001:4800:7902:1:0:a:4323:45:443 (2001:4800:7902:1:0:a:4323:45:443) -> 139622696732544:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:../base/deps/luvit/deps/openssl/openssl/crypto/buffer/buffer.c:169:

Fri Jun 12 13:48:57 2015 ERR: Connection: 2001:4800:7902:1:0:a:4323:45:443 (2001:4800:7902:1:0:a:4323:45:443) -> 139622696732544:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:../base/deps/luvit/deps/openssl/openssl/crypto/buffer/buffer.c:169:

Fri Jun 12 13:48:57 2015 ERR: Connection: 2001:4800:7902:1:0:a:4323:45:443 (2001:4800:7902:1:0:a:4323:45:443) -> 139622696732544:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:../base/deps/luvit/deps/openssl/openssl/crypto/buffer/buffer.c:169:

Fri Jun 12 13:48:57 2015 INF: SRV:_monitoringagent._tcp.dfw1.prod.monitoring.api.rackspacecloud.com -> Retrying connection in 85090ms
Fri Jun 12 13:49:58 2015 INF: Log file started (pid 27914, path=/var/log/rackspace-monitoring-agent.log)
Fri Jun 12 13:49:58 2015 INF: Using config agent ID (id=maas1-node1)
Fri Jun 12 13:49:58 2015 INF: Starting agent maas1-node1 (guid=a63a8483-5a31-4c98-cc05-bc764e091f51, version=1.1.0-86, bundle_version=1.1.0-86)

Final log entries without manual intervention
Fri Jun 12 13:48:57 2015 INF: SRV:_monitoringagent._tcp.dfw1.prod.monitoring.api.rackspacecloud.com -> Retrying connection in 85090ms
Fri Jun 12 13:49:58 2015 INF: Log file started (pid 27914, path=/var/log/rackspace-monitoring-agent.log)
Fri Jun 12 13:49:58 2015 INF: Using config agent ID (id=maas1-node1)
Fri Jun 12 13:49:58 2015 INF: Starting agent maas1-node1 (guid=a63a8483-5a31-4c98-cc05-bc764e091f51, version=1.1.0-86, bundle_version=1.1.0-86)

Fri Jun 12 13:51:23 2015 INF: (plugin=swift-recon.py, id=chS4AqI4Ky, iid=idWEXps2DH) -> agent.plugin (details=args="--ring-type","account","replication",file="swift-recon.py",id="chS4AqI4Ky",period=60) scheduled for 64184s
Fri Jun 12 13:52:15 2015 ERR: Connection: 2001:4801:7902:1:0:a:6036:10:443 (2001:4801:7902:1:0:a:6036:10:443) -> 140467875514240:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:../base/deps/luvit/deps/openssl/openssl/crypto/buffer/buffer.c:169:

Fri Jun 12 13:52:15 2015 ERR: Connection: 2001:4801:7902:1:0:a:6036:10:443 (2001:4801:7902:1:0:a:6036:10:443) -> 140467875514240:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:../base/deps/luvit/deps/openssl/openssl/crypto/buffer/buffer.c:169:

Fri Jun 12 13:52:15 2015 ERR: Connection: 2001:4801:7902:1:0:a:6036:10:443 (2001:4801:7902:1:0:a:6036:10:443) -> 140467875514240:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:../base/deps/luvit/deps/openssl/openssl/crypto/buffer/buffer.c:169:

Fri Jun 12 13:52:15 2015 ERR: Connection: 2001:4801:7902:1:0:a:6036:10:443 (2001:4801:7902:1:0:a:6036:10:443) -> 140467875514240:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:../base/deps/luvit/deps/openssl/openssl/crypto/buffer/buffer.c:169:

Fri Jun 12 13:52:15 2015 INF: SRV:_monitoringagent._tcp.ord1.prod.monitoring.api.rackspacecloud.com -> Retrying connection in 67406ms

**Comment by BjoernT** [comment]
This is actually a known issues which I had already had send over to the dev team

**Comment by nrb** [comment]
@BjoernT Over to the MaaS team?

**Comment by claco** [comment]
So this is something we've worked with them on a few times now. As of -71, it was fixed. Now with that said, I've seen this in AIO and cloud build all the time, because we're on machines with 8, 16, 32GB of ram, which is still much lower than our ref arch. Appearances were the instances are running out of ram during installation things, but once the agent was restarted, they were fine.

Are all of the agents on all of our customer installs up to date with the latest version? I'm incline to hold on this, and we can retest again once we get the new version with the agent disconnect feature they're making for us.

**Comment by nrb** [comment]
@claco So we're in a holding pattern until the MaaS team gets back to us? That's mainly what I'm trying to determine here.

**Comment by claco** [comment]
Not necessarily holding, but if we're going to do a round of testing anyways in a few weeks for the agent disconnected feature, we don't have to re test this issue just right this week.

**Comment by nrb** [comment]
@git-harry Can you confirm whether your initial report was from an AIO or a cluster?

**Comment by nrb** [comment]
@BjoernT Are you guys still seeing this in customer deployments? Also, do you know if customers are running the latest MaaS agent?

**Comment by nrb** [comment]
Setting to priority 2 so we can test a newer version of the agent out in the next sprint.

**Comment by git-harry** [comment]
@nrb - 5 nodes using 'performance1-8' Rackspace cloud servers built using rpc-heat

**Comment by rackertom** [comment]
@nrb @claco @git-harry Any update on this? Last change was Jul. 6.

**Comment by claco** [comment]
I vote close it. We've gotten multiple releases form them in the mean time. If it crops up again, we can re open.

**Comment by BjoernT** [comment]
:+1:
