### ISSUE TITLE
Magnum install overwriting user_osa_variables_overrides.yml

### ISSUE THREAD

**Issue by shane-c** [rcbops/rpc-openstack#1858]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
```
# git describe --all
r13.1.4
```
##### What type of issue is this? Please tick the appropriate box.
- [x ] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

Deploying magnum does not overwrite user_osa_variables_overrides.yml

##### What is actually happening?

Setting DEPLOY_MAGNUM=yes and running deploy.sh overwrites any variables previously in user_osa_variables_overrides.yml

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Installing magnum, noticed some of my other variables I had set were not implemented

##### How can we reproduce this issue?

Add a variable to /etc/openstack_deploy/user_osa_variables_overrides.yml, set DEPLOY_MAGNUM=yes and run deploy.sh. Check user_osa_variables_overrides.yml and it will only contain magnum overrides.

##### How can we verify your issue is addressed?

Installing magnum doesn't overwrite user_osa_variables_overrides.yml

##### What is your evaluation on the importance of this issue, and why?

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
cc @chrishultin

**Comment by zhmarvi** [comment]
Hi Shane,

The RCA as to why running deploy.sh with magnum enabled will overwrite the user_osa_variables_overrides.yml.

When DEPLOY_MAGNUM=yes flag is set in deploy.sh, the script will call the /opt/rpc-openstack/contrib/scripts/magnum.sh 

Here is where the variables will be placed into the /etc/openstack_deploy/ variable files.

PROBLEM:

On line 14 in the magnum.sh: 

 cat > /etc/openstack_deploy/user_osa_variables_overrides.yml <<'EOF'

SOLUTION: 

this needs to be changed to (>>) for appending

 cat >> /etc/openstack_deploy/user_osa_variables_overrides.yml <<'EOF'


I tested this on an AIO and it appended the overrides file instead of overwriting it.

**Comment by chrishultin** [comment]
Since we're targeting Newton 14.1 for the Magnum integration, should we just go ahead and remove all of the Magnum components from Mitaka at this point?

**Comment by alextricity25** [comment]
@chrishultin That's really up to you. I personally don't foresee us deplying Magnum on Mitaka once we have it available in Newton 14.1.

I'm going to go ahead and close this one off since Magnum is indeed targeted for 14.1.
