### ISSUE TITLE
megacli

### ISSUE THREAD

**Issue by albertcard** [rcbops/rpc-openstack#186]
Looking to see if we can get the megacli utility added to our builds as we are having more and more customers being built into CDC without HP or Dell gear. Having this utility would help us with investigation into Drives/Controllers/Raid Arrays/PSU/etc issues and diagnosing issues a little bit quicker. 

http://hwraid.le-vert.net/wiki/DebianPackages

## Branches

- [x] Master #840
- [x] Liberty - >=12.0.1
- [x] Kilo

**Comment by nrb** [comment]
Can I ask how many customers this affects? Not names, just a count.

**Comment by albertcard** [comment]
Looks like we have 28 customers with CDC environments -- This would help with examination of hardware in their chassis/blades. However, we've also found a bit of useful use cases on drive errors -- more verbose than 'omreport' -- for all of our customers in using Dell Chassis which covers all of our customers in house (72 customers)

**Comment by rackertom** [comment]
@albertcard Are all of these environments Debian-based (Debian, Ubuntu, Mint, etc.) or are there also RPM-based distributions (RHEL, SuSE, and the like)?

**Comment by BjoernT** [comment]
+1 we should add this to the rpc_support role and also add the lsi utils. Those are common controllers

**Comment by prometheanfire** [comment]
to be clear, liberty here is 12.0.1
