### ISSUE TITLE
Use port 443/http for horizon monitor

### ISSUE THREAD

**Issue by alextricity25** [rcbops/rpc-openstack#1941]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
Per email conversation with @dpham:
> This was a change brought to my attention by Kevin Carter.  Newton now assumes a load-balancer is in front and has SSL-termination enabled.  (Naturally, this donks up anything pre-Newton for Horizon:443.)
Please verify that Horizon runs HTTP:443 and not HTTPS:443 on Newton.

##### What is actually happening?
Currently the ``f5-config.py`` script is using the ``MON_HTTP_HORIZON`` monitor for the horizon_ssl pool. This means that the service will be monitoring on port 80 using http.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Running the ``f5-config.py`` script.

##### How can we reproduce this issue?
Run the ``f5-config.py`` script.

##### How can we verify your issue is addressed?
The horizon_ssl pool should use a monitor that uses HTTP on port 443.

##### If you are using or know of a workaround please describe the necessary steps?
NA
##### What is your evaluation on the importance of this issue, and why?
prio-1, Per email conversation with @dpham 

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master
- [x] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
@dpham:
Per @prometheanfire conversation I had with him just now, this can be closed off since it's not the case for Newton. Could you confirm?

**Comment by b3rnard0** [comment]
@prometheanfire Confirmed by Thode at the standup.
