### ISSUE TITLE
how to determine if a wheel contains a commit

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#195]
An ask from support was "how do we know if a wheel that is installed inside a container contains a particular commit?", in order to know if a customer's environment contains a particular fix or not.  This is somewhat non-trivial because of the way we now build wheels outside the containers, and the wheel names do not directly indicate the SHA from which they were built (rather just the semver version)

**Comment by prometheanfire** [comment]
@mancdaz backport to kilo or want me to?

**Comment by prometheanfire** [comment]
merged into kilo, closing
