### ISSUE TITLE
host_only.yml play for maas ordering is wrong.

### ISSUE THREAD

**Issue by andymcc** [rcbops/rpc-openstack#197]
The host_only.yml play includes a play to setup monitors (network.yml) before the raxmon-cli is setup properly (the raxmon_cli_config.yml & raxmon_agent_install.yml)

This needs to be fixed or else any new maas installs will not work.

**Comment by nrb** [comment]
This breaks greenfield deployments.

**Comment by prometheanfire** [comment]
backported to kilo and in master
