### ISSUE TITLE
MaaS: Nova checks fail with python-novaclient>=7.0.0

### ISSUE THREAD

**Issue by melissa-kam** [rcbops/rpc-openstack#1982]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
Alarms the alarms for nova checks should be OK.

##### What is actually happening?
In the multi-node AIO and lab environments, the following alarms are going to CRITICAL.

nova_api_local_status
nova_cert_status
nova_cloud_disk_status
nova_cloud_memory_status
nova_cloud_vcpu_status
nova_conductor_status
nova_consoleauth_status
nova_scheduler_status

```
/openstack/venvs/maas-r13.1.0rc1/local/lib/python2.7/site-packages/novaclient/client.py:278: UserWarning: The 'bypass_url' argument is deprecated in Ocata and its use may result in errors in future releases. Use 'endpoint_override' instead.
  warnings.warn(msg)
status error agent/plugins/nova_api_local_check.py", line 83, in main\n    check(auth_ref, args)\n  File "/usr/lib/rackspace-monitoring-agent/plugins/nova_api_local_check.py", line 44, in check\n    try:\nAttributeError: 'NoneType' object has no attribute 'services'\n
Traceback (most recent call last):
  File "/usr/lib/rackspace-monitoring-agent/plugins/nova_api_local_check.py", line 94, in <module>
    main(args)
  File "/usr/lib/rackspace-monitoring-agent/plugins/nova_api_local_check.py", line 83, in main
    check(auth_ref, args)
  File "/usr/lib/rackspace-monitoring-agent/plugins/nova_api_local_check.py", line 44, in check
    try:
AttributeError: 'NoneType' object has no attribute 'services'
```
This is only happening when the version of python-novaclient is greater than 7.0.0. It does not happen in 6.0.0, which is what is installed in the AIO environments. Downgrading the client fixes these issues, and upgrading the client in the AIO introduced the errors.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Built a multi-node AIO with master, ran setup-maas.yml, and ran verify-maas.yml.

##### What is your evaluation on the importance of this issue, and why?

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master
- [x] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by major** [comment]
``python-novaclient`` 7.x changed how the ``list()`` and related methods work. We will need to downgrade to ``<7.0.0`` until more work can be done to fix this one.

**Comment by alextricity25** [comment]
I presume this also effects the newton-14.0 branch. Could we have this backported to that branch as well?
