### ISSUE TITLE
horizon extension is compressing the files with the wrong user compared to horizon

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1994]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

Liberty and up 

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

Use the same user as horizon

##### What is actually happening?

The static files have mixed permissions, owned by root rather than the horizon_system_user_name configuration

##### How can we reproduce this issue?

Install any Liberty + release and roll out the horizon extension

##### How can we verify your issue is addressed?

Ownership is the same for all static horizon files

##### What is your evaluation on the importance of this issue, and why?

Prio 3

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by cloudnull** [comment]
This was merged. Additionally, we're trying to have the extensions removed, as we've done in Newton+, which makes this irrelevant going forward. I'm closing this issue as the original bug has been resolved.
