### ISSUE TITLE
Refactor command line searching

### ISSUE THREAD

**Issue by b3rnard0** [rcbops/rpc-openstack#20]
Opened by d34dh0r53 on 2014-10-01 21:49:32+00:00 at https://github.com/rcbops/ansible-lxc-rpc/issues/213

------------------------------------------------------------

For a CDC install as well as general troubleshooting the CLI for elasticsearch is glaringly inefficient and should probably be developed from the ground up to suit our particular needs. Some of the things that would be great are:

Service specific searches
Rapid container identification (i.e. you search for a UUID and you get a list of all of the containers that UUID has hit)
Firehose for grepping, this is not as useful as people think but it shouldn't be too hard to implement and will hopefully help drive home the point that tailing and grepping does not work at scale
Container specific logs for a time period

I'm sure there are more but those are the real hot button items that I'm wanting myself as well as what I'm hearing from support.

**Comment by d34dh0r53** [comment]
This is nearly a year old and there has been very little clamor about it so I'm going to close in preparation for Liberty.
