### ISSUE TITLE
cinder_service_check.py not using --host option

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#200]
The host argument is not used by the script leading to metrics being returned when they shouldn't.
Witthout host arg:
./cinder_service_check.py 172.29.236.3
status okay
metric cinder-scheduler_on_host_maas2-node3_cinder_scheduler_container-0377f639 uint32 1
metric cinder-scheduler_on_host_maas2-node1_cinder_scheduler_container-2706e6d1 uint32 1
metric cinder-scheduler_on_host_maas2-node2_cinder_scheduler_container-38784141 uint32 1
metric cinder-volume_on_host_maas2-node4 uint32 1

With host arg:
./cinder_service_check.py 172.29.236.3 --host maas2-node3_cinder_scheduler_container-0377f639
status okay
metric cinder-scheduler_status uint32 1
metric cinder-scheduler_on_host_maas2-node1_cinder_scheduler_container-2706e6d1 uint32 1
metric cinder-scheduler_on_host_maas2-node2_cinder_scheduler_container-38784141 uint32 1
metric cinder-volume_on_host_maas2-node4 uint32 1

Expected output with host arg:
./cinder_service_check.py 172.29.236.3 --host maas2-node3_cinder_scheduler_container-0377f639
status okay
metric cinder-scheduler_status uint32 1

**Comment by nrb** [comment]
Does this need to go into Juno as well?

**Comment by git-harry** [comment]
@nrb - It affects juno, if that is good enough reason for a backport then, yes, it does.

**Comment by git-harry** [comment]
There look to be commits for this in master, kilo, juno.
