### ISSUE TITLE
[MaaS] swift-recon.py plugin runs swift-recon locally

### ISSUE THREAD

**Issue by alextricity25** [rcbops/rpc-openstack#2008]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
The swift-recon.py plugin doesn't try to invoke ``swift-recon`` on the infra hosts.

##### What is actually happening?

After running the ``setup-maas.yml`` playbook, I noticed that the swift-recon checks are being dropped in my infra hosts:
```
root@568575-infra01:/opt/rpc-openstack/rpcd/playbooks# ls /etc/rackspace-monitoring-agent.conf.d/ | grep swift
filebeat_process_check-568575-infra01_swift_proxy_container-65b24edd.yaml
lb_api_check_swift_access.yaml
lb_api_check_swift_healthcheck.yaml
swift_account_replication_check--568575-infra01_swift_proxy_container-65b24edd.yaml
swift_async_check--568575-infra01_swift_proxy_container-65b24edd.yaml
swift_container_replication_check--568575-infra01_swift_proxy_container-65b24edd.yaml
swift_md5_check--568575-infra01_swift_proxy_container-65b24edd.yaml
swift_object_replication_check--568575-infra01_swift_proxy_container-65b24edd.yaml
swift_proxy_server_check--568575-infra01_swift_proxy_container-65b24edd.yaml
swift_quarantine_check--568575-infra01_swift_proxy_container-65b24edd.yaml
swift_time_sync_check--568575-infra01_swift_proxy_container-65b24edd.yaml
```
The current swift_recon.py maas plugin is trying to invoke the swift-recon executable on the host it's running on. That can be seen here:
https://github.com/rcbops/rpc-openstack/blob/newton-14.0/rpcd/playbooks/roles/rpc_maas/files/plugins/swift-recon.py#L65-L67

The result of this is that we now have failing checks on the infra hosts since the infra hosts aren't running swift binaries. cc @xeregin

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
We ran ``setup-maas.yml`` on our multi-node lab for QE testing after blowing away all of the content in ``/etc/rackspace-monitoring-agent.conf/*``. We noticed that the swift recon checks are also being dropped into this directory on our infra hosts.

##### How can we reproduce this issue?
See above.

##### How can we verify your issue is addressed?
The ``swift-recon.py`` plugin runs successfully.

##### If you are using or know of a workaround please describe the necessary steps?
NA
##### What is your evaluation on the importance of this issue, and why?
prio-1. This should be fixed before our Newton rc1 release.
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master
- [x] newton-14.0
- [x] mitaka-13.1
- [x] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [x] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
I think the problem here is that we are writing out the compound conditional expression here as a yaml list, which munges the expressions together with an 'OR':
https://github.com/rcbops/rpc-openstack/blob/newton-14.0/rpcd/playbooks/roles/rpc_maas/tasks/main.yml#L80-L82

Of course the first conditional, ```groups['swift_all'] | length > 0``` will be true for every hosts on an environment with swift deployed.

That conditional needs to be fixed to use an AND operator.

**Comment by alextricity25** [comment]
IGNORE MY LAST COMMENT! 
Turns out that conditional is correct the way it is. I suspect the problem is that these checks are being dropped into the infra hosts via delegation. Note in this Ansible output:
```
changed: [568575-infra01_swift_proxy_container-65b24edd -> 10.240.0.160] => (item={u'group': u'swift_proxy', u'name': u'swift_quarantine_check'})
```
The task is being delegated over to 10.240.0.160(infra1), which is the physical host of the swift proxy container. The delegation is being done here:
https://github.com/rcbops/rpc-openstack/blob/newton-14.0/rpcd/playbooks/roles/rpc_maas/tasks/ensure_local_checks.yml#L28

Dropping this check into the infra hosts is a problem, since the current ``swift_recon.py`` maas plugin is trying to invoke the ``swift-recon`` executable on the host it's running on. That can be seen here:
https://github.com/rcbops/rpc-openstack/blob/newton-14.0/rpcd/playbooks/roles/rpc_maas/files/plugins/swift-recon.py#L65-L67

The only way I can see of solving this is writing bits into the ``swift-recon.py`` plugin to run the ``swift-recon`` command on a remote server(i.e. the swift proxy container). I say this because, AFAIK, these plugins can only run on a host with the maas agent on them -- the physical hosts.
It'll also be possible to run the ``swift-proxy`` command using 'lxc-attach', or some other container connection python module, but either way it'll still require the ``swift_recon.py`` maas plugin to change.
cc @antonym @major @cloader89

**Comment by claco** [comment]
So I have what seems like a simple question. How did we make it this far into a bunch of AIO deployments without seeing this? Are we not deploying Swift in our AIOs? IS this error not happening in gating with Swift turned on?

It seems strange to see this rather late in the process. It's not like we just added Swift and Swift MaaS checks last week.

**Comment by alextricity25** [comment]
@claco: I was thinking about that too. I would like to investigate some of the multi-node AIOs that @mkam is working with to see if it's happening there.
The reason it wasn't caught in palin-old regular AIO is because the swift object-server runs on the host on AIO deployments, causing the plugin to succeed.

Still, I would like to figure out why the multi-node AIO isn't catching this.

**Comment by alextricity25** [comment]
FYI - I'm backporting this to newton. I'll leave the other backports to @antonym.

**Comment by antonym** [comment]
Backported this to Mitaka and Liberty, but they break as the release number does not line up to {{ rpc_release }} (DISTRIB_RELEASE).  The script currently grabs the version from /etc/rpc-release.

Example:

Kilo: No venvs so I'll need to adjust appropriately
Liberty: DISTRIB_RELEASE="r12.2.8", {{ openstack_release }} = "12.2.8"
Mitaka: DISTRIB_RELEASE='"r13.1.4", {{ openstack_release }} = "13.3.15"

I guess that behavior changed here: https://github.com/rcbops/rpc-openstack/commit/36cb8bea267999f54d69bbcb91c3877e7c4f225e so going forward it should be more consistent.

It looks like if I grab DISTRIB_RELEASE from /etc/openstack-release instead of /etc/rpc-release, it's more consistent across all releases and this issue goes away.

**Comment by alextricity25** [comment]
> It looks like if I grab DISTRIB_RELEASE from /etc/openstack-release instead of /etc/rpc-release, it's more consistent across all releases and this issue goes away.

That's a solid change for the <= Mitaka backports. I don't think it's a necessary one for the newton release though.

**Comment by antonym** [comment]
Yeah, your call, this is my proposed patch which would work for all except Kilo:

https://github.com/rcbops/rpc-openstack/pull/2023

**Comment by alextricity25** [comment]
Let's go ahead and get that patch into all of the branches before mitaka, then. Or you could modify the backport PRs you already have open and make a note in the commit message.

The newton PR can stay using ``/etc/rpc-release``.
