### ISSUE TITLE
RPC14/OSA : warnings/error during setup-hosts

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#2025]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

RPC newton-14.0 branch
OSA 14.1.0-16-g9a14560

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

No warning

##### What is actually happening?

OSA setup-hosts:

No 1:
```
TASK [pip_install : Install external repo manually (yum)] **********************
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'user_external_repos_list' is undefined.
This feature will be removed in a future release. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
```

No 2:
```
TASK [openstack_hosts : Update SSH keys] ***************************************
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'ssh_key_url' is undefined.
This feature will be removed in a future release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
```

##### How can we reproduce this issue?

N/A

##### How can we verify your issue is addressed?

N/A

##### If you are using or know of a workaround please describe the necessary steps?

N/A

##### What is your evaluation on the importance of this issue, and why?

Prio 2

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
Is there a corresponding launchpad bug for this?

**Comment by BjoernT** [comment]
No I have not yet created a OSA bug

**Comment by odyssey4me** [comment]
This is only exposed when doing an AIO bootstrap as far as I know.

**Comment by alextricity25** [comment]
UPDATE:
The first deprecation warning concerning ``user_external_repos_list`` has been resolved with the latest OSA SHA bump made [here](https://github.com/rcbops/rpc-openstack/pull/2126).

The second deprecation warning isn't such as easy fix. Adding a default value of ``""`` for ``ssh_key_url`` causes the ``authorized_keys`` Ansible module to fail with ``ValueError: unknown url type:``. This is even if the ``when`` conditional on that task evaluates to false. Because of this, it's probably best to leave it as it is. No harm, no foul ;)

I'll be closing this bug off soon if there aren't any further concerns.
