### ISSUE TITLE
setup-maas.yml fails on hosts that are not part of lxc_hosts group

### ISSUE THREAD

**Issue by mattt416** [rcbops/rpc-openstack#2026]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

Encountered on r14.0.0rc1, but will affect master also.

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

setup-maas.yml should complete successfully

##### What is actually happening?

When deploying the openstack-ansible-ops multi-node-aio, setup-maas.yml fails with the following error:

```
TASK [rpc_maas : Install pip packages to venv] *********************************
...
failed: [loadbalancer1] (item=lxc-python2) => {"cmd": "/openstack/venvs/maas-r13.1.0rc1/bin/pip install lxc-python2", "failed": true, "item": "lxc-python2", "msg": "stdout: Collecting lxc-python2\n  Using cached lxc-python2-0.1.zip\nBuilding wheels for collected packages: lxc-python2\n  Running setup.py bdist_wheel for lxc-python2: started\n  Running setup.py bdist_wheel for lxc-python2: finished with status 'error'\n  Complete output from command /openstack/venvs/maas-r13.1.0rc1/bin/python -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-8XFDoG/lxc-python2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" bdist_wheel -d /tmp/tmpA3PTu6pip-wheel- --python-tag cp27:\n  running bdist_wheel\n  running build\n  running build_py\n  creating build\n  creating build/lib.linux-x86_64-2.7\n  creating build/lib.linux-x86_64-2.7/lxc\n  copying lxc/__init__.py -> build/lib.linux-x86_64-2.7/lxc\n  running build_ext\n  building '_lxc' extension\n  creating build/temp.linux-x86_64-2.7\n  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c lxc.c -o build/temp.linux-x86_64-2.7/lxc.o\n  lxc.c:27:30: fatal error: lxc/lxccontainer.h: No such file or directory\n   #include <lxc/lxccontainer.h>\n                                ^\n  compilation terminated.\n  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n  \n  ----------------------------------------\n  Running setup.py clean for lxc-python2\nFailed to build lxc-python2\nInstalling collected packages: lxc-python2\n  Running setup.py install for lxc-python2: started\n    Running setup.py install for lxc-python2: finished with status 'error'\n    Complete output from command /openstack/venvs/maas-r13.1.0rc1/bin/python -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-8XFDoG/lxc-python2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-_tl8qx-record/install-record.txt --single-version-externally-managed --compile --install-headers /openstack/venvs/maas-r13.1.0rc1/include/site/python2.7/lxc-python2:\n    running install\n    running build\n    running build_py\n    creating build\n    creating build/lib.linux-x86_64-2.7\n    creating build/lib.linux-x86_64-2.7/lxc\n    copying lxc/__init__.py -> build/lib.linux-x86_64-2.7/lxc\n    running build_ext\n    building '_lxc' extension\n    creating build/temp.linux-x86_64-2.7\n    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c lxc.c -o build/temp.linux-x86_64-2.7/lxc.o\n    lxc.c:27:30: fatal error: lxc/lxccontainer.h: No such file or directory\n     #include <lxc/lxccontainer.h>\n                                  ^\n    compilation terminated.\n    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n    \n    ----------------------------------------\n\n:stderr:   Failed building wheel for lxc-python2\nCommand \"/openstack/venvs/maas-r13.1.0rc1/bin/python -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-8XFDoG/lxc-python2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-_tl8qx-record/install-record.txt --single-version-externally-managed --compile --install-headers /openstack/venvs/maas-r13.1.0rc1/include/site/python2.7/lxc-python2\" failed with error code 1 in /tmp/pip-build-8XFDoG/lxc-python2/\n"}
...
```

In this scenario, the problem is that the host loadbalancer1 has no containers on it (only runs haproxy) and is therefore not added to the lxc_hosts group (see recent change https://review.openstack.org/#/c/427855/).  Previously, all hosts were part of lxc_hosts.  While in this situation it's loadbalancer1 failing, this is likely to be a problem if you have ceph OSD storage nodes, swift storage nodes, etc. that do not have any containers on them.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Running setup-maas.yml on the multi-node-aio

##### How can we reproduce this issue?

Run the multi-node-aio from openstack-ansible-ops.  Alternatively, the problem should also be visible when attempting to deploy ceph OSDs onto bare metal (as support would).

##### How can we verify your issue is addressed?

setup-maas.yml runs successfully even when there are hosts present which are not part of lxc_hosts group.

##### If you are using or know of a workaround please describe the necessary steps?

None at this time.

##### What is your evaluation on the importance of this issue, and why?

High.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master - https://github.com/rcbops/rpc-openstack/pull/2058
- [ ] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by nrb** [comment]
I think all the MaaS stuff is targeted at `hosts`. [Searching for `lxc_hosts`](https://github.com/rcbops/rpc-openstack/search?utf8=%E2%9C%93&q=lxc_hosts) comes up empty. The setup-maas.yml playbook [targets `hosts` and `all_containers`](https://github.com/rcbops/rpc-openstack/blob/r14.0.0rc1/rpcd/playbooks/setup-maas.yml#L25).

That said, hosts that don't have lxc containers (compute, Ceph, Swift) probably shouldn't have lxc checks installed.

**Comment by claco** [comment]
@nrb, assuming QE hits this in the happy path rc1 testing in a lab, what's the way to fix this in Newton? I see a backport to Ocata upstream.

Thanks!

**Comment by nrb** [comment]
https://review.openstack.org/#/c/427885/ is the newton backport. As I stated in the previous comment, I don't think `lxc_hosts` is actually being used by RPC-O, though. It's not in code search, and the `setup-maas.yml` playbook targets `hosts:all_containers` on the r14.0.0rc1 tag.

Ideally, the correct thing is 1) ensure RPC-O has that Newton backport so that it has the correct `lxc_hosts` membership 2) Only install lxc checks and Python packages on members of `lxc_hosts`.

**Comment by claco** [comment]
@nrb Awesome. Thanks for the guidance on this.

**Comment by b3rnard0** [comment]
@jacobwagner @Rydor this is the issue to see investigate as part of the MaaS testing for rc1.

**Comment by Rydor** [comment]
@xeregin I added you to this card to provide feedback when you do the Maas deploy if you run into any similar issues.

**Comment by Rydor** [comment]
I did not see this issue when deploying an AIO on Xenial. 

Actual QE validation to be done in LEM labs.

**Comment by xeregin** [comment]
I'm not seeing this issue in IAD3-2 Trusty

**Comment by nrb** [comment]
@xeregin What nodes?

**Comment by cloader89** [comment]
@nrb I can answer that, yes, compute, infra and storage

**Comment by cloader89** [comment]
Update: This is an issue of a couple different forms. This issue is confirmed.

**Comment by claco** [comment]
Should we change the milestone on this to rc2?

**Comment by b3rnard0** [comment]
@claco Done.

**Comment by b3rnard0** [comment]
@cloader89 Updates please.

**Comment by claco** [comment]
And move to doing. :-P

**Comment by cloader89** [comment]
We are in the process of gathering ideas on how to fix it. So far Bjoern and I agreed on adding LXC to all hosts. We are waiting for @npawelek to give his opinion. I am going to create a patch today with adding lxc to all of the hosts. That way @xeregin can re-test it.

**Comment by odyssey4me** [comment]
Adding LXC to all hosts will extend the build time and maintenance for all hosts, meaning that every upgrade takes much, much longer. The whole reason why the lxc_hosts group was created was to reduce the time taken for deployments and upgrades.

The solution here should be to scope the deployments better. This role is targeting all hosts, then using conditionals to scope where tasks are applied. This is very bad practise and causes the deployment and upgrade processes to take unnecessarily long.

I would suggest either breaking these tasks out into purpose-specific roles, or playbooks, or using dynamic groups (and/or group_vars) to target specific portions of the role to specific hosts.

**Comment by claco** [comment]
@odyssey4me You may want to drop this into the PR so it's not least, or rather, read there.

```
Adding LXC to all hosts will extend the build time and maintenance for all hosts, meaning that every upgrade takes much, much longer. The whole reason why the lxc_hosts group was created was to reduce the time taken for deployments and upgrades.
```

The proposed PR is adding one python package to the rpc_mass required packages list. Doesn't seem we're moving things in or our of groups at all, so there wouldn't be any change in terms of all of the lxc_hosts work being done, or causing more time, unless I'm thinking sideways on that.

I think the PR might need a better title and commit message. I'm not sure this issue as it stands post QE testing is the the same issue we thought it was when first reported.

**Comment by odyssey4me** [comment]
@claco This python package won't install unless the accompanying LXC packages are installed on the same host. This is a very slippery slope.

**Comment by antonym** [comment]
Put up a PR that splits the process_check into host and container plugins.  Seemed to work in my lab so could be an option instead of installing LXC:

https://github.com/rcbops/rpc-openstack/pull/2058

**Comment by alextricity25** [comment]
Thanks @antonym.I'll take a look at that PR.
It sounds like the other PR to install the ``lxc-python2`` package on all hosts is a no-go, leaving PR #2058 as our path moving forward in the short-term.

I am, however, intrigued by @odyssey4me suggestion he made in an earlier comment:
> The solution here should be to scope the deployments better. This role is targeting all hosts, then using conditionals to scope where tasks are applied. This is very bad practise and causes the deployment and upgrade processes to take unnecessarily long.

I have noticed that ``setup-maas.yml`` takes a  horrible amount of time to complete. I'll create an issue for this and backlog it for the our longer-term solution.
