### ISSUE TITLE
Need to be able to specify default user_variables.yml for rpcd

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#203]
rpcd needs some defaults that do not match those defined in osad.

The default for [cinder]/cross_az_attach in nova.conf is True for osad and support would like it set to False.
https://bugs.launchpad.net/openstack-ansible/+bug/1457140

**Comment by nrb** [comment]
Are you then abandoning https://github.com/rcbops/rpc-openstack/pull/187 ?

**Comment by git-harry** [comment]
@nrb - am I failing to github? You asked for an issue, so I created this. The other thing is the pull request.

**Comment by nrb** [comment]
Nope, sorry, my mistake. You referenced it correctly, I was misreading.

**Comment by d34dh0r53** [comment]
Can this be closed as #187 has merged?

**Comment by nrb** [comment]
Looks like we still need it in Kilo.

**Comment by prometheanfire** [comment]
kilo done, closing

**Comment by b3rnard0** [comment]
@nrb Need doc impact information which Harry will provide.
