### ISSUE TITLE
Intermittent libxslt1-dev package install failures

### ISSUE THREAD

**Issue by mkam** [rcbops/rpc-openstack#2055]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
RPC deploys without failures on Xenial.

##### What is actually happening?
On Xenial builds, we're intermittently seeing:
```
TASK [os_cinder : Install apt packages] ****************************************
FAILED - RETRYING: TASK: os_cinder : Install apt packages (5 retries left).
FAILED - RETRYING: TASK: os_cinder : Install apt packages (5 retries left).
FAILED - RETRYING: TASK: os_cinder : Install apt packages (4 retries left).
FAILED - RETRYING: TASK: os_cinder : Install apt packages (4 retries left).
FAILED - RETRYING: TASK: os_cinder : Install apt packages (3 retries left).
FAILED - RETRYING: TASK: os_cinder : Install apt packages (3 retries left).
changed: [cinder2_cinder_scheduler_container-07cda304] => (item=[u'rpcbind', u'rsync', u'git', u'nfs-common', u'libpq-dev', u'libkmod-dev', u'libkmod2', u'libxslt1-dev', u'zlib1g', u'zlibc', u'libffi-dev', u'libssl-dev'])
changed: [cinder1_cinder_api_container-e616a8b8] => (item=[u'rpcbind', u'rsync', u'git', u'nfs-common', u'libpq-dev', u'libkmod-dev', u'libkmod2', u'libxslt1-dev', u'zlib1g', u'zlibc', u'libffi-dev', u'libssl-dev'])
changed: [cinder2_cinder_api_container-674f0d15] => (item=[u'rpcbind', u'rsync', u'git', u'nfs-common', u'libpq-dev', u'libkmod-dev', u'libkmod2', u'libxslt1-dev', u'zlib1g', u'zlibc', u'libffi-dev', u'libssl-dev'])
changed: [cinder1_cinder_scheduler_container-87e85c1a] => (item=[u'rpcbind', u'rsync', u'git', u'nfs-common', u'libpq-dev', u'libkmod-dev', u'libkmod2', u'libxslt1-dev', u'zlib1g', u'zlibc', u'libffi-dev', u'libssl-dev'])
FAILED - RETRYING: TASK: os_cinder : Install apt packages (2 retries left).
FAILED - RETRYING: TASK: os_cinder : Install apt packages (2 retries left).
FAILED - RETRYING: TASK: os_cinder : Install apt packages (1 retries left).
FAILED - RETRYING: TASK: os_cinder : Install apt packages (1 retries left).
failed: [cinder2] (item=[u'rpcbind', u'rsync', u'git', u'nfs-common', u'libpq-dev', u'libkmod-dev', u'libkmod2', u'libxslt1-dev', u'zlib1g', u'zlibc', u'libffi-dev', u'libssl-dev']) => {"cache_update_time": 0, "cache_updated": false, "failed": true, "item": ["rpcbind", "rsync", "git", "nfs-common", "libpq-dev", "libkmod-dev", "libkmod2", "libxslt1-dev", "zlib1g", "zlibc", "libffi-dev", "libssl-dev"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'rpcbind' 'nfs-common' 'libpq-dev' 'libxslt1-dev' 'zlibc'' failed: E: Unable to correct problems, you have held broken packages.\n", "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n libxslt1-dev : Depends: libxml2-dev (>= 2.6.26) but it is not going to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " libxslt1-dev : Depends: libxml2-dev (>= 2.6.26) but it is not going to be installed"]}
failed: [cinder1] (item=[u'rpcbind', u'rsync', u'git', u'nfs-common', u'libpq-dev', u'libkmod-dev', u'libkmod2', u'libxslt1-dev', u'zlib1g', u'zlibc', u'libffi-dev', u'libssl-dev']) => {"cache_update_time": 0, "cache_updated": false, "failed": true, "item": ["rpcbind", "rsync", "git", "nfs-common", "libpq-dev", "libkmod-dev", "libkmod2", "libxslt1-dev", "zlib1g", "zlibc", "libffi-dev", "libssl-dev"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'rpcbind' 'nfs-common' 'libpq-dev' 'libxslt1-dev' 'zlibc'' failed: E: Unable to correct problems, you have held broken packages.\n", "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n libxslt1-dev : Depends: libxml2-dev (>= 2.6.26) but it is not going to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " libxslt1-dev : Depends: libxml2-dev (>= 2.6.26) but it is not going to be installed"]}
```
We currently haven't seen this issue on any Trusty builds.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Ran OnMetal multi-node AIO periodic builds. The earliest occurrence that we've seen of this error was March 13th.
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO_newton-xenial/4/
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO_newton-xenial/7/
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO_master-xenial/24/
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO_master-xenial/25/

##### How can we reproduce this issue?
Run the master and newton Xenial jobs, or manually deploy a mult-node AIO environment.
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO_newton-xenial
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO_master-xenial

##### How can we verify your issue is addressed?
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO_newton-xenial
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO_master-xenial

##### What is your evaluation on the importance of this issue, and why?

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master
- [x] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by nrb** [comment]
I have hit this as well, outside of a gate. I did not investigate, however.

**Comment by alextricity25** [comment]
@cloader89 Any update on this?

**Comment by cloader89** [comment]
As an update --- I have been trying to create a Multinode AIO to get the error for me to look around on. I have an OnMetal Xenial server, working towards an AIO. There are many differences between Trusty and Xenial, however there was no way to get a Multinode AIO in xenial on OnMetal without Dave's guide to Upgrade. I have a Xenial onmetal box now, Iam 1/5th through the AIO build on my own AIO. I will update when I fully complete the AIO. Xenial is complicated without being able to use the image that QE uses, so I will update you guys as I proceed.

**Comment by cloader89** [comment]
P.S., I am using a good ol' upgrade from Trusty. as per @d34dh0r53 guide:

https://gist.github.com/d34dh0r53/95e0488a5588ffc2a71f837041098ea4

**Comment by cloader89** [comment]
Update: Multinode AIO built, and got past the spot in the error, I will run another two tests tomorrow.  @mkam could you link me an active jenkins multinode run that has the error on it?

**Comment by alextricity25** [comment]
Moving this to "swimlane-rr" since it's targeting for the next Newton patch release(if any).

**Comment by cloader89** [comment]
Update: Talked with @mkam and we are no longer seeing this as an issue. Closing.
