### ISSUE TITLE
Gate job timing out trying to compress logstash.log

### ISSUE THREAD

**Issue by mattt416** [rcbops/rpc-openstack#2064]
##### On which version(s) do you encounter this issue?

mitaka-13.1

###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

```
root@ramcp-18-41c0:/opt/rpc-openstack# git describe --all
remotes/origin/pr/2010/merge
root@ramcp-18-41c0:/opt/rpc-openstack#
```

This job was triggered by PR 2010 on rpc-openstack.

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

We're hitting an error where a gate job periodically cannot finish because it spins trying to compress logstash.log (/openstack/log/ramcp-18-41c0_logstash_container-f58fb259/logstash.log for example).  The log should be a manageable size such that it can be compressed and the job finish successfully.

##### What is actually happening?

The log has numerous errors in it and gets appended so fast that the compress cannot finish.  An error includes:

```
"error"=>{"type"=>"mapper_parsing_exception", "reason
"=>"failed to parse [timestamp]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"Invalid format: \"21/Mar/2017:13:16:59 +0000\" is malformed at \"Mar/2017:13:16:59 +0000\""}}}}, :level=>:warn
```

This seems to be associated with the `"source"=>"/var/log/nginx/openstack-slushee.access.log"`.

Note that these errors are so large that it's difficult to post an entire error message in this bug report.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

This is from a standard gate job in new CIT jenkins instance.  We've seen this failure a couple of times and have disregarded thinking it was transient, but it seems to have happened enough that it's worth reporting.

##### How can we reproduce this issue?

We don't hit this issue every time, so I'm not sure it happens every time.  However, building an AIO running mitaka-13.1 will be a good start.

##### How can we verify your issue is addressed?

The logstash.log should not have the error listed above.

##### What is your evaluation on the importance of this issue, and why?

Medium, since I don't believe this error is thrown on every build.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by cloudnull** [comment]
This issue seems to be resolved when PR #2085 was merged. I'm closing this issue but please feel free to reopen it if needed.
