### ISSUE TITLE
Use Safer YAML Function in rpc-maas-tool.py

### ISSUE THREAD

**Issue by YasmineK** [rcbops/rpc-openstack#2073]
##### On which version(s) do you encounter this issue?
14.0.0rc1

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
When loading a YAML document, it is safer to use the *yaml.safe_load()* function as opposed to *yaml.load()* in order to protect from data that may originate from untrusted source.

##### What is actually happening?
The script uses *yaml.load()* (https://github.com/rcbops/rpc-openstack/blob/r14.0.0rc1/scripts/rpc-maas-tool.py#L212)

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Security code review.

##### How can we reproduce this issue?
See https://github.com/rcbops/rpc-openstack/blob/r14.0.0rc1/scripts/rpc-maas-tool.py#L212.

##### How can we verify your issue is addressed?
*yaml.load()* will be replaced with *yaml.safe_load()*.

##### If you are using or know of a workaround please describe the necessary steps?
N/A.

##### What is your evaluation on the importance of this issue, and why?
Improves the security posture of the code.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master
- [x] newton-14.0
- [x] mitaka-13.1
- [x] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by cloudnull** [comment]
All merged, all fixed.
