### ISSUE TITLE
f5-config.py Monitor for GALERA uses incorrect username haproxy

### ISSUE THREAD

**Issue by Mudpuppy12** [rcbops/rpc-openstack#209]
r'create ltm monitor mysql /' + PART + '/' + PREFIX_NAME + '_MON_GALERA { count 1 database'
    r' information_schema debug no defaults-from mysql destination *:*'
    r' interval 3 recv big5_chinese_ci recv-column 2 recv-row 0 send "select'
    r' * from CHARACTER_SETS;" time-until-up 0 timeout 10 username haproxy }',

The correct username should be monitoring, as the haproxy user no longer seems added to kilo releases

    r'create ltm monitor mysql /' + PART + '/' + PREFIX_NAME + '_MON_GALERA { count 1 database'
    r' information_schema debug no defaults-from mysql destination *:*'
    r' interval 3 recv big5_chinese_ci recv-column 2 recv-row 0 send "select'
    r' * from CHARACTER_SETS;" time-until-up 0 timeout 10 username monitoring }',

**Comment by nrb** [comment]
Does this impact anything further back than Kilo?

**Comment by mattt416** [comment]
I'm not familiar enough with this script or how the load balancers are operated.  Are we better off replacing reference to `haproxy` w/ `monitoring` or overriding galera_monitoring_user in rpc-openstack to use haproxy user?  The upside to doing the latter is it an upgrade from juno onwards will not create another monitoring user (called `monitoring`) when the `haproxy` user already exists.

Thoughts?

**Comment by nrb** [comment]
From my perspective, the `galera_monitoring_user` override makes sense as a fix.

**Comment by Mudpuppy12** [comment]
I am guessing the intent of this change was to remove all references to the haproxy. It doesn't make sense to have that username in the database, as monitoring is a better name for it. I am not sure how upgrades will handle it.

**Comment by nrb** [comment]
I'll do a little bit more code spelunking and see if I can find anything related to this.

**Comment by nrb** [comment]
So for upgrades, the f5-config.py script will need to be run anyway, since the repo server VIPs are not registered with the F5. They weren't present in Juno.

Given that, I *think* changing the user name during the F5 configuration part of an upgrade should be fine, but may want some input from netsec.

**Comment by nrb** [comment]
Neither Juno nor Kilo's f5-config.py script are templated, so we might have to change that.

Juno: https://github.com/stackforge/os-ansible-deployment/blob/juno/scripts/f5-config.py#L32
Kilo: https://github.com/rcbops/rpc-openstack/blob/master/scripts/f5-config.py#L46

**Comment by nrb** [comment]
https://review.openstack.org/#/c/199625/2 does the clean up work inside OSAD's run-upgrade.sh script.

**Comment by claco** [comment]
Looks like that review needs the recheck/verify love again

**Comment by nrb** [comment]
The timestamps seem to indicate to me that it's in process now. http://status.openstack.org/zuul/ says it's currently in queue.

**Comment by nrb** [comment]
Kilo and master are merged, marking as closed.

**Comment by nrb** [comment]
Re-opening because we found the following issue during actual upgrades - When making the switch, the haproxy user is still used, but is deleting without being replaced.

We need to 1) add the new monitoring user 2) change the monitor to use the `monitoring` user prior to upgrade 3) upgrade

Will also add this to the bug description.

**Comment by nrb** [comment]
Actually, closing and referencing in #335.
