### ISSUE TITLE
Block Device Mapping is Invalid: failed to get volume - multi-node deployments

### ISSUE THREAD

**Issue by alextricity25** [rcbops/rpc-openstack#2095]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

tag r14.0.0rc2

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
The user is able to create an instance off a bootable cinder volume successfully

##### What is actually happening?
When trying to create an instance from a volume using the CLI, I get the following message:
```
root@605055-infra01-utility-container-1b2de33d:~# openstack server create --flavor $FLAVOR --volume boot_volume3 --key-name alex_key --nic net-id=$NETWORK
 test_volume_instance2                                                                                                                                    
  
WARNING: openstackclient.common.utils is deprecated and will be removed after Jun 2017. Please use osc_lib.utils
Block Device Mapping is Invalid: failed to get volume 43ada3f3-0af3-42ff-a8dc-b961a0543f2a. (HTTP 400) (Request-ID: req-43e456c2-9446-4cdc-8a91-bf0e431915
8b)
```
I get the same message when trying to boot an instance from a volume via the UI:
![screenshot from 2017-03-30 08 29 39](https://cloud.githubusercontent.com/assets/4964964/24508882/76b59c00-152a-11e7-9142-91b8e30446a2.png)

A full log, with the req-id grep'ed, can be viewed here:
https://gist.github.com/alextricity25/4b3199a2c489466d66e203f64996e528

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
I'm deploying RPC off of the r14.0.0rc2 tag using a multi-node architecture. For details on the deployment, please see https://github.com/rcbops/u-suk-dev/issues/1461.

I uploaded an image to glance and created a bootable volume using this command:
```
openstack volume create --image cirros --size 10 boot_volume3
```

I then tried to create an instance off that volume. See error message above.

I also tried doing this in an AIO, but this issue does not come up in our AIOs.
##### How can we reproduce this issue?
Note: This issue does not come up in the AIOs
* Deploy RPCO r14.0.0rc2 on a multi-node environment
* configure the f5 using our tooling
* Upload an image
* Create a bootable volume off that image
* Try to create an instance from that volume

##### How can we verify your issue is addressed?
Instances will be able to spawn using a volume as the source.

##### If you are using or know of a workaround please describe the necessary steps?
NA

##### What is your evaluation on the importance of this issue, and why?
prio-1. Users should be able to create instances off of bootable volumes.
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
Changing [nova_cross_az_attach](https://github.com/rcbops/rpc-openstack/blob/newton-14.0/rpcd/etc/openstack_deploy/user_osa_variables_defaults.yml#L59) to True(or removing the override) fixed this problem for me. According to the documentation:
> If False, volumes attached to an instance must be in the same availability zone in Cinder as the instance availability zone in Nova. This also means care should be taken when booting an instance from a volume where source is not “volume” because Nova will attempt to create a volume using the same availability zone as what is assigned to the instance. If that AZ is not in Cinder (or allow_availability_zone_fallback=False in cinder.conf), the volume create request will fail and the instance will fail the build request. By default there is no availability zone restriction on volume attach.

Now, if that's OK with support, then we will keep the default override as it is. To me it seems a little strange to have that set to False by default, and IMO this default override should be removed and should only be overridden on environments that use cinder AZs(which by default, rpco does not deploy).
@rcbops/support-feedback Could we have your thoughts here?

**Comment by alextricity25** [comment]
Per https://github.com/rcbops/rpc-openstack/pull/2098#issuecomment-290517171, there is awareness in support that deploying an environment without cinder AZs will cause instances booting from a volume to fail if this default override stays.

The decision is to keep the override. At the very least, a doc issue will be raised to add this note under "known issues" to outline that care should be taken when creating an instance from a volume and this variable is set.

**Comment by b3rnard0** [comment]
@alextricity25 should this be mentioned in the release notes? 

cc: @robb-romans @erikmwilson

**Comment by alextricity25** [comment]
@b3rnard0: Correct. I'm in the process of submitting a doc issue now.

**Comment by robb-romans** [comment]
Published: https://pages.github.rackspace.com/rpc-internal/docs-rpc/master/rpc-releasenotes/known-issues.html

Thanks @alextricity25

**Comment by alextricity25** [comment]
Turns out I was incorrect in saying that RPCO does not deploy a default cinder AZ. It indeed creates an AZ called ``nova``. Further QE testing has revealed that, even though a bootable volume is in the cinder AZ ``nova``, it still fails to create an instance from volume when nova_cross_az_attach is set to false.
An upstream bug is open here: https://bugs.launchpad.net/nova/+bug/1648324 and will be tracked by another card. Further details incoming..

**Comment by alextricity25** [comment]
This is now being tracked in https://github.com/rcbops/rpc-openstack/issues/2179
