### ISSUE TITLE
F5 Magnum monitor

### ISSUE THREAD

**Issue by dpham-rs** [rcbops/rpc-openstack#2096]
##### What type of issue is this? Please tick the appropriate box.
- [X] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
Magnum monitor exists.  Optimally a health check would poll something that actually measures availability.

It doesn't necessarily have to use RPC-MON-EXT-ENDPOINT, it could be a regular HTTP or TCP monitor, it just needs something to pass.

##### What is actually happening?
F5-config script uses RPC-MON-EXT-ENDPOINT but RPC-MON-EXT-ENDPOINT does not include an entry for TCP/9511.  Since no entry is included, the script bails and the pool members are marked down.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
The F5 config can be made to the F5, but the Magnum pool will always fail since f5-monitor.sh will bail.

##### How can we reproduce this issue?
Deploy the f5-config generated, the magnum pool will fail due to missing monitor definitions.

##### How can we verify your issue is addressed?
F5 pool for Magnum shows available.

##### If you are using or know of a workaround please describe the necessary steps?
Switched to regular /Common/tcp.

##### What is your evaluation on the importance of this issue, and why?
Low, only seeing it trial and demo so far.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by chrishultin** [comment]
@dpham-rs Do you think that making the Magnum endpoint public would resolve the issue?

**Comment by dpham-rs** [comment]
@chrishultin 

Not in this case, this is the health monitor for the F5 to determine if services on the magnum container are healthy (whether or not they're in rotation).  We're polling <code>http://<pool_member>:9511/v1/</code> at the moment, just curious if there was another URI considered for health monitoring.

<pre>
ltm monitor http /RPC/RPC_MON_HTTP_MAGNUM {
    defaults-from http
    destination *:9511
    interval 5
    ip-dscp 0
    partition RPC
    recv "200 OK"
    send "GET /v1/ HTTP/1.1\r\nHost: rpc\r\n\r\n"
    time-until-up 0
    timeout 16
}
</pre>

**Comment by chrishultin** [comment]
@dpham-rs We don't have a specific health check URL right now - that should respond, as long as it's accessible.

**Comment by BjoernT** [comment]
Closing due to Magnum project situation
