### ISSUE TITLE
Newton targets compute nodes for neutron_l3_agent and neutron_metadata_agent

### ISSUE THREAD

**Issue by shane-c** [rcbops/rpc-openstack#2118]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

root@infra01:/opt/rpc-openstack# git describe --all
r14.0.0rc1

##### What type of issue is this? Please tick the appropriate box.
- [x ] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

Compute nodes don't have MaaS checks for L3/metadata agent

##### What is actually happening?

Inventory is setting the compute nodes into the neutron_l3_agent and neutron_metadata_agent sections in openstack_inventory.json which creates L3/metadata agent checks for those which fail because those services are not running on the compute nodes.

```
    "neutron_l3_agent": {
        "children": [],
        "hosts": [
            "infra01_neutron_agents_container-35a353fc",
            "infra02_neutron_agents_container-25d348d8",
            "infra03_neutron_agents_container-57606f6c",
            "compute02",
            "compute03",
            "compute01",
            "compute04"
        ]

    "neutron_metadata_agent": {
        "children": [],
        "hosts": [
            "infra01_neutron_agents_container-35a353fc",
            "infra02_neutron_agents_container-25d348d8",
            "infra03_neutron_agents_container-57606f6c",
            "compute02",
            "compute03",
            "compute01",
            "compute04"
        ]
```

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Complete maas with no failures 

##### How can we reproduce this issue?

Not sure if related, but this was done with LBaaS v2 enabled. Enable LBaaS v2 and run MaaS. Check for failed checks on the compute nodes.

##### How can we verify your issue is addressed?

Compute nodes don't have failed L3/metadata agent checks

##### If you are using or know of a workaround please describe the necessary steps?

Remove the checks from  /etc/rackspace-monitoring-agent.conf.d/ and restart rackspace-monitoring-agent

##### What is your evaluation on the importance of this issue, and why?
Low

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
This sounds like a step was skipped in the "Before you Begin" section of the documentation.
Did you complete step 5 here? https://pages.github.rackspace.com/rpc-internal/docs-rpc/master/rpc-install-internal/configure-req/configure-prereqs.html

That step copies over the nova.yml override environment file that we have in ``rpcd/etc/openstack_deploy/env.d``, which, in turn, fixes the behavior you are describing in the bug description.

The bug you are hitting is here: https://bugs.launchpad.net/openstack-ansible/+bug/1645979.

We put that override nova.yml file in place to get around that issue.

Let me know if you have any questions.

**Comment by shane-c** [comment]
Thanks @alextricity25, looks like that is the problem.
