### ISSUE TITLE
/tmp/fix_host_things.yml  file not found issue.

### ISSUE THREAD

**Issue by weezer** [rcbops/rpc-openstack#212]
# Run the fix host things play
  openstack-ansible /tmp/fix_host_things.yml
Variable files: "-e @/etc/openstack_deploy/user_group_vars.yml -e @/etc/openstack_deploy/user_variables.yml "

PLAY [Fix host things] ********************************************************

TASK: [find containers in /var/lib/lxc] ***************************************
changed: [605059-compute03]
changed: [605057-compute01]
changed: [605061-storage01]
changed: [605062-storage02]
changed: [605063-storage03]
changed: [605020-infra01]
changed: [605021-infra02]
changed: [605024-logging01]
changed: [605058-compute02]
changed: [605023-infra03]

TASK: [get the basic container network] ***************************************
skipping: [605057-compute01]
skipping: [605059-compute03]
skipping: [605058-compute02]
changed: [605062-storage02] => (item=605062-storage02_cinder_volumes_container-74ec845d)
changed: [605061-storage01] => (item=605061-storage01_cinder_volumes_container-602ad78a)
changed: [605063-storage03] => (item=605063-storage03_cinder_volumes_container-741b0541)
changed: [605020-infra01] => (item=605020-infra01_cinder_api_container-572e6fe8)
changed: [605023-infra03] => (item=605023-infra03_cinder_api_container-372ef53a)
changed: [605024-logging01] => (item=605024-logging01_elasticsearch_container-1bb5e3a4)
changed: [605021-infra02] => (item=605021-infra02_cinder_api_container-ac9bb840)
changed: [605020-infra01] => (item=605020-infra01_galera_container-a3def92c)
changed: [605023-infra03] => (item=605023-infra03_galera_container-bd4b49ab)
changed: [605021-infra02] => (item=605021-infra02_galera_container-d43cfc6c)
changed: [605024-logging01] => (item=605024-logging01_kibana_container-b1d93ddd)
changed: [605020-infra01] => (item=605020-infra01_glance_container-9e725df6)
changed: [605023-infra03] => (item=605023-infra03_glance_container-03291979)
changed: [605021-infra02] => (item=605021-infra02_glance_container-c333998e)
changed: [605020-infra01] => (item=605020-infra01_heat_apis_container-6d31e66b)
changed: [605023-infra03] => (item=605023-infra03_heat_apis_container-6ebddc5a)
changed: [605024-logging01] => (item=605024-logging01_logstash_container-1b842ca5)
changed: [605021-infra02] => (item=605021-infra02_heat_apis_container-2c4a88fb)
changed: [605020-infra01] => (item=605020-infra01_heat_engine_container-daedeab7)
changed: [605023-infra03] => (item=605023-infra03_heat_engine_container-2fd187ff)
changed: [605024-logging01] => (item=lost+found)
changed: [605021-infra02] => (item=605021-infra02_heat_engine_container-3c0e9c32)
changed: [605020-infra01] => (item=605020-infra01_horizon_container-c239a78f)
changed: [605023-infra03] => (item=605023-infra03_horizon_container-ce7c7866)
changed: [605020-infra01] => (item=605020-infra01_keystone_container-1f3f0468)
changed: [605021-infra02] => (item=605021-infra02_horizon_container-3441cd39)
changed: [605023-infra03] => (item=605023-infra03_keystone_container-ff063358)
changed: [605020-infra01] => (item=605020-infra01_memcached_container-36b0a9bf)
changed: [605021-infra02] => (item=605021-infra02_keystone_container-49891781)
changed: [605023-infra03] => (item=605023-infra03_memcached_container-d8105824)
changed: [605020-infra01] => (item=605020-infra01_neutron_agents_container-9e21abb9)
changed: [605023-infra03] => (item=605023-infra03_neutron_agents_container-4bab63ac)
changed: [605021-infra02] => (item=605021-infra02_memcached_container-44934d6d)
changed: [605020-infra01] => (item=605020-infra01_neutron_server_container-e9314f83)
changed: [605023-infra03] => (item=605023-infra03_neutron_server_container-431c0c03)
changed: [605021-infra02] => (item=605021-infra02_neutron_agents_container-c20b08b7)
changed: [605020-infra01] => (item=605020-infra01_nova_api_metadata_container-1cb3f825)
changed: [605023-infra03] => (item=605023-infra03_nova_api_metadata_container-295ff1b4)
changed: [605021-infra02] => (item=605021-infra02_neutron_server_container-be2d3a82)
changed: [605020-infra01] => (item=605020-infra01_nova_api_os_compute_container-87d6021d)
changed: [605023-infra03] => (item=605023-infra03_nova_api_os_compute_container-a83257f7)
changed: [605021-infra02] => (item=605021-infra02_nova_api_metadata_container-7f51a887)
changed: [605020-infra01] => (item=605020-infra01_nova_cert_container-204e78f3)
changed: [605023-infra03] => (item=605023-infra03_nova_cert_container-38d9824e)
changed: [605020-infra01] => (item=605020-infra01_nova_conductor_container-ba0c7b1e)
changed: [605021-infra02] => (item=605021-infra02_nova_api_os_compute_container-7566653f)
changed: [605023-infra03] => (item=605023-infra03_nova_conductor_container-3f7b4b78)
changed: [605020-infra01] => (item=605020-infra01_nova_scheduler_container-36d278db)
changed: [605023-infra03] => (item=605023-infra03_nova_scheduler_container-c64e1480)
changed: [605021-infra02] => (item=605021-infra02_nova_cert_container-082dbf77)
changed: [605020-infra01] => (item=605020-infra01_rabbit_mq_container-6e6d89fd)
changed: [605023-infra03] => (item=605023-infra03_rabbit_mq_container-ed811e20)
changed: [605021-infra02] => (item=605021-infra02_nova_conductor_container-a6c23358)
changed: [605020-infra01] => (item=605020-infra01_swift_proxy_container-01587b1f)
changed: [605023-infra03] => (item=605023-infra03_swift_proxy_container-31d70942)
changed: [605021-infra02] => (item=605021-infra02_nova_scheduler_container-97af35cd)
changed: [605020-infra01] => (item=605020-infra01_utility_container-fe880a3c)
changed: [605023-infra03] => (item=605023-infra03_utility_container-913ed620)
changed: [605021-infra02] => (item=605021-infra02_rabbit_mq_container-e9bef0e1)
changed: [605020-infra01] => (item=lost+found)
changed: [605023-infra03] => (item=lost+found)
changed: [605021-infra02] => (item=605021-infra02_swift_proxy_container-c7febee9)
changed: [605021-infra02] => (item=605021-infra02_utility_container-62939261)
changed: [605021-infra02] => (item=lost+found)

TASK: [Remove lxc.network from base config] ***********************************
skipping: [605057-compute01]
skipping: [605058-compute02]
skipping: [605059-compute03]
changed: [605062-storage02] => (item=605062-storage02_cinder_volumes_container-74ec845d)
changed: [605063-storage03] => (item=605063-storage03_cinder_volumes_container-741b0541)
changed: [605061-storage01] => (item=605061-storage01_cinder_volumes_container-602ad78a)
changed: [605023-infra03] => (item=605023-infra03_cinder_api_container-372ef53a)
changed: [605020-infra01] => (item=605020-infra01_cinder_api_container-572e6fe8)
changed: [605024-logging01] => (item=605024-logging01_elasticsearch_container-1bb5e3a4)
changed: [605021-infra02] => (item=605021-infra02_cinder_api_container-ac9bb840)
changed: [605023-infra03] => (item=605023-infra03_galera_container-bd4b49ab)
changed: [605020-infra01] => (item=605020-infra01_galera_container-a3def92c)
changed: [605021-infra02] => (item=605021-infra02_galera_container-d43cfc6c)
changed: [605024-logging01] => (item=605024-logging01_kibana_container-b1d93ddd)
changed: [605023-infra03] => (item=605023-infra03_glance_container-03291979)
changed: [605020-infra01] => (item=605020-infra01_glance_container-9e725df6)
changed: [605021-infra02] => (item=605021-infra02_glance_container-c333998e)
changed: [605023-infra03] => (item=605023-infra03_heat_apis_container-6ebddc5a)
changed: [605020-infra01] => (item=605020-infra01_heat_apis_container-6d31e66b)
changed: [605024-logging01] => (item=605024-logging01_logstash_container-1b842ca5)
changed: [605023-infra03] => (item=605023-infra03_heat_engine_container-2fd187ff)
changed: [605021-infra02] => (item=605021-infra02_heat_apis_container-2c4a88fb)
changed: [605020-infra01] => (item=605020-infra01_heat_engine_container-daedeab7)
ok: [605024-logging01] => (item=lost+found)
changed: [605023-infra03] => (item=605023-infra03_horizon_container-ce7c7866)
changed: [605020-infra01] => (item=605020-infra01_horizon_container-c239a78f)
changed: [605021-infra02] => (item=605021-infra02_heat_engine_container-3c0e9c32)
changed: [605023-infra03] => (item=605023-infra03_keystone_container-ff063358)
changed: [605020-infra01] => (item=605020-infra01_keystone_container-1f3f0468)
changed: [605021-infra02] => (item=605021-infra02_horizon_container-3441cd39)
changed: [605023-infra03] => (item=605023-infra03_memcached_container-d8105824)
changed: [605020-infra01] => (item=605020-infra01_memcached_container-36b0a9bf)
changed: [605021-infra02] => (item=605021-infra02_keystone_container-49891781)
changed: [605023-infra03] => (item=605023-infra03_neutron_agents_container-4bab63ac)
changed: [605020-infra01] => (item=605020-infra01_neutron_agents_container-9e21abb9)
changed: [605023-infra03] => (item=605023-infra03_neutron_server_container-431c0c03)
changed: [605021-infra02] => (item=605021-infra02_memcached_container-44934d6d)
changed: [605020-infra01] => (item=605020-infra01_neutron_server_container-e9314f83)
changed: [605023-infra03] => (item=605023-infra03_nova_api_metadata_container-295ff1b4)
changed: [605020-infra01] => (item=605020-infra01_nova_api_metadata_container-1cb3f825)
changed: [605021-infra02] => (item=605021-infra02_neutron_agents_container-c20b08b7)
changed: [605023-infra03] => (item=605023-infra03_nova_api_os_compute_container-a83257f7)
changed: [605020-infra01] => (item=605020-infra01_nova_api_os_compute_container-87d6021d)
changed: [605021-infra02] => (item=605021-infra02_neutron_server_container-be2d3a82)
changed: [605023-infra03] => (item=605023-infra03_nova_cert_container-38d9824e)
changed: [605020-infra01] => (item=605020-infra01_nova_cert_container-204e78f3)
changed: [605021-infra02] => (item=605021-infra02_nova_api_metadata_container-7f51a887)
changed: [605023-infra03] => (item=605023-infra03_nova_conductor_container-3f7b4b78)
changed: [605020-infra01] => (item=605020-infra01_nova_conductor_container-ba0c7b1e)
changed: [605021-infra02] => (item=605021-infra02_nova_api_os_compute_container-7566653f)
changed: [605023-infra03] => (item=605023-infra03_nova_scheduler_container-c64e1480)
changed: [605020-infra01] => (item=605020-infra01_nova_scheduler_container-36d278db)
changed: [605023-infra03] => (item=605023-infra03_rabbit_mq_container-ed811e20)
changed: [605021-infra02] => (item=605021-infra02_nova_cert_container-082dbf77)
changed: [605020-infra01] => (item=605020-infra01_rabbit_mq_container-6e6d89fd)
changed: [605023-infra03] => (item=605023-infra03_swift_proxy_container-31d70942)
changed: [605020-infra01] => (item=605020-infra01_swift_proxy_container-01587b1f)
changed: [605021-infra02] => (item=605021-infra02_nova_conductor_container-a6c23358)
changed: [605023-infra03] => (item=605023-infra03_utility_container-913ed620)
changed: [605020-infra01] => (item=605020-infra01_utility_container-fe880a3c)
changed: [605021-infra02] => (item=605021-infra02_nova_scheduler_container-97af35cd)
ok: [605023-infra03] => (item=lost+found)
ok: [605020-infra01] => (item=lost+found)
changed: [605021-infra02] => (item=605021-infra02_rabbit_mq_container-e9bef0e1)
changed: [605021-infra02] => (item=605021-infra02_swift_proxy_container-c7febee9)
changed: [605021-infra02] => (item=605021-infra02_utility_container-62939261)
ok: [605021-infra02] => (item=lost+found)

TASK: [Fix relative bind mounts] **********************************************
skipping: [605057-compute01]
skipping: [605058-compute02]
skipping: [605059-compute03]
changed: [605063-storage03] => (item=605063-storage03_cinder_volumes_container-741b0541)
changed: [605062-storage02] => (item=605062-storage02_cinder_volumes_container-74ec845d)
changed: [605061-storage01] => (item=605061-storage01_cinder_volumes_container-602ad78a)
changed: [605023-infra03] => (item=605023-infra03_cinder_api_container-372ef53a)
changed: [605021-infra02] => (item=605021-infra02_cinder_api_container-ac9bb840)
changed: [605020-infra01] => (item=605020-infra01_cinder_api_container-572e6fe8)
changed: [605024-logging01] => (item=605024-logging01_elasticsearch_container-1bb5e3a4)
changed: [605023-infra03] => (item=605023-infra03_galera_container-bd4b49ab)
changed: [605021-infra02] => (item=605021-infra02_galera_container-d43cfc6c)
changed: [605020-infra01] => (item=605020-infra01_galera_container-a3def92c)
changed: [605024-logging01] => (item=605024-logging01_kibana_container-b1d93ddd)
changed: [605021-infra02] => (item=605021-infra02_glance_container-c333998e)
changed: [605023-infra03] => (item=605023-infra03_glance_container-03291979)
changed: [605020-infra01] => (item=605020-infra01_glance_container-9e725df6)
changed: [605020-infra01] => (item=605020-infra01_heat_apis_container-6d31e66b)
changed: [605021-infra02] => (item=605021-infra02_heat_apis_container-2c4a88fb)
changed: [605023-infra03] => (item=605023-infra03_heat_apis_container-6ebddc5a)
changed: [605024-logging01] => (item=605024-logging01_logstash_container-1b842ca5)
changed: [605021-infra02] => (item=605021-infra02_heat_engine_container-3c0e9c32)
changed: [605020-infra01] => (item=605020-infra01_heat_engine_container-daedeab7)
changed: [605023-infra03] => (item=605023-infra03_heat_engine_container-2fd187ff)
changed: [605020-infra01] => (item=605020-infra01_horizon_container-c239a78f)
changed: [605021-infra02] => (item=605021-infra02_horizon_container-3441cd39)
changed: [605023-infra03] => (item=605023-infra03_horizon_container-ce7c7866)
failed: [605024-logging01] => (item=lost+found) => {"changed": true, "item": "lost+found", "rc": 1}
stderr: OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /root/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 10.240.0.79 closed.

stdout: Working on file [ /var/lib/lxc/lost+found/config ]
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1435710869.81-227440887563389/config-fix.py", line 49, in <module>
    main(config_file=sys.argv[1])
  File "/root/.ansible/tmp/ansible-tmp-1435710869.81-227440887563389/config-fix.py", line 19, in main
    with open(config_file) as f:
IOError: [Errno 2] No such file or directory: '/var/lib/lxc/lost+found/config'

changed: [605020-infra01] => (item=605020-infra01_keystone_container-1f3f0468)
changed: [605021-infra02] => (item=605021-infra02_keystone_container-49891781)
changed: [605023-infra03] => (item=605023-infra03_keystone_container-ff063358)
changed: [605021-infra02] => (item=605021-infra02_memcached_container-44934d6d)
changed: [605020-infra01] => (item=605020-infra01_memcached_container-36b0a9bf)
changed: [605023-infra03] => (item=605023-infra03_memcached_container-d8105824)
changed: [605021-infra02] => (item=605021-infra02_neutron_agents_container-c20b08b7)
changed: [605023-infra03] => (item=605023-infra03_neutron_agents_container-4bab63ac)
changed: [605020-infra01] => (item=605020-infra01_neutron_agents_container-9e21abb9)
changed: [605021-infra02] => (item=605021-infra02_neutron_server_container-be2d3a82)
changed: [605020-infra01] => (item=605020-infra01_neutron_server_container-e9314f83)
changed: [605023-infra03] => (item=605023-infra03_neutron_server_container-431c0c03)
changed: [605020-infra01] => (item=605020-infra01_nova_api_metadata_container-1cb3f825)
changed: [605023-infra03] => (item=605023-infra03_nova_api_metadata_container-295ff1b4)
changed: [605021-infra02] => (item=605021-infra02_nova_api_metadata_container-7f51a887)
changed: [605020-infra01] => (item=605020-infra01_nova_api_os_compute_container-87d6021d)
changed: [605023-infra03] => (item=605023-infra03_nova_api_os_compute_container-a83257f7)
changed: [605021-infra02] => (item=605021-infra02_nova_api_os_compute_container-7566653f)
changed: [605023-infra03] => (item=605023-infra03_nova_cert_container-38d9824e)
changed: [605020-infra01] => (item=605020-infra01_nova_cert_container-204e78f3)
changed: [605021-infra02] => (item=605021-infra02_nova_cert_container-082dbf77)
changed: [605023-infra03] => (item=605023-infra03_nova_conductor_container-3f7b4b78)
changed: [605020-infra01] => (item=605020-infra01_nova_conductor_container-ba0c7b1e)
changed: [605021-infra02] => (item=605021-infra02_nova_conductor_container-a6c23358)
changed: [605023-infra03] => (item=605023-infra03_nova_scheduler_container-c64e1480)
changed: [605020-infra01] => (item=605020-infra01_nova_scheduler_container-36d278db)
changed: [605021-infra02] => (item=605021-infra02_nova_scheduler_container-97af35cd)
changed: [605023-infra03] => (item=605023-infra03_rabbit_mq_container-ed811e20)
changed: [605020-infra01] => (item=605020-infra01_rabbit_mq_container-6e6d89fd)
changed: [605021-infra02] => (item=605021-infra02_rabbit_mq_container-e9bef0e1)
changed: [605023-infra03] => (item=605023-infra03_swift_proxy_container-31d70942)
changed: [605020-infra01] => (item=605020-infra01_swift_proxy_container-01587b1f)
changed: [605021-infra02] => (item=605021-infra02_swift_proxy_container-c7febee9)
changed: [605023-infra03] => (item=605023-infra03_utility_container-913ed620)
changed: [605020-infra01] => (item=605020-infra01_utility_container-fe880a3c)
changed: [605021-infra02] => (item=605021-infra02_utility_container-62939261)
failed: [605023-infra03] => (item=lost+found) => {"changed": true, "item": "lost+found", "rc": 1}
stderr: OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /root/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 10.240.0.76 closed.

stdout: Working on file [ /var/lib/lxc/lost+found/config ]
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1435710871.35-158117962465252/config-fix.py", line 49, in <module>
    main(config_file=sys.argv[1])
  File "/root/.ansible/tmp/ansible-tmp-1435710871.35-158117962465252/config-fix.py", line 19, in main
    with open(config_file) as f:
IOError: [Errno 2] No such file or directory: '/var/lib/lxc/lost+found/config'

failed: [605020-infra01] => (item=lost+found) => {"changed": true, "item": "lost+found", "rc": 1}
stderr: OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /root/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 10.240.0.73 closed.

stdout: Working on file [ /var/lib/lxc/lost+found/config ]
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1435710871.37-155836247300297/config-fix.py", line 49, in <module>
    main(config_file=sys.argv[1])
  File "/root/.ansible/tmp/ansible-tmp-1435710871.37-155836247300297/config-fix.py", line 19, in main
    with open(config_file) as f:
IOError: [Errno 2] No such file or directory: '/var/lib/lxc/lost+found/config'

failed: [605021-infra02] => (item=lost+found) => {"changed": true, "item": "lost+found", "rc": 1}
stderr: OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /root/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 10.240.0.74 closed.

stdout: Working on file [ /var/lib/lxc/lost+found/config ]
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1435710871.39-45704528912752/config-fix.py", line 49, in <module>
    main(config_file=sys.argv[1])
  File "/root/.ansible/tmp/ansible-tmp-1435710871.39-45704528912752/config-fix.py", line 19, in main
    with open(config_file) as f:
IOError: [Errno 2] No such file or directory: '/var/lib/lxc/lost+found/config'

TASK: [Remove add_network_interface.conf entry] *******************************
skipping: [605058-compute02]
skipping: [605057-compute01]
skipping: [605059-compute03]
changed: [605062-storage02] => (item=605062-storage02_cinder_volumes_container-74ec845d)
changed: [605063-storage03] => (item=605063-storage03_cinder_volumes_container-741b0541)
changed: [605061-storage01] => (item=605061-storage01_cinder_volumes_container-602ad78a)

TASK: [Remove aa_profile entries] *********************************************
skipping: [605057-compute01]
skipping: [605058-compute02]
skipping: [605059-compute03]
changed: [605061-storage01] => (item=605061-storage01_cinder_volumes_container-602ad78a)
changed: [605062-storage02] => (item=605062-storage02_cinder_volumes_container-74ec845d)
changed: [605063-storage03] => (item=605063-storage03_cinder_volumes_container-741b0541)

TASK: [Remove old add_network_interface.conf file] ****************************
skipping: [605057-compute01]
skipping: [605058-compute02]
skipping: [605059-compute03]
changed: [605061-storage01] => (item=605061-storage01_cinder_volumes_container-602ad78a)
changed: [605063-storage03] => (item=605063-storage03_cinder_volumes_container-741b0541)
changed: [605062-storage02] => (item=605062-storage02_cinder_volumes_container-74ec845d)

TASK: [Ensure services log files are fix] *************************************
ok: [605061-storage01] => (item=nova)
ok: [605058-compute02] => (item=nova)
ok: [605063-storage03] => (item=nova)
ok: [605062-storage02] => (item=nova)
ok: [605057-compute01] => (item=nova)
ok: [605059-compute03] => (item=nova)
ok: [605061-storage01] => (item=neutron)
ok: [605063-storage03] => (item=neutron)
ok: [605062-storage02] => (item=neutron)
changed: [605058-compute02] => (item=neutron)
changed: [605057-compute01] => (item=neutron)
changed: [605059-compute03] => (item=neutron)
ok: [605058-compute02] => (item=swift)
ok: [605057-compute01] => (item=swift)
ok: [605059-compute03] => (item=swift)
changed: [605062-storage02] => (item=swift)
changed: [605063-storage03] => (item=swift)
changed: [605061-storage01] => (item=swift)

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/fix_host_things.retry

605020-infra01             : ok=3    changed=3    unreachable=0    failed=1
605021-infra02             : ok=3    changed=3    unreachable=0    failed=1
605023-infra03             : ok=3    changed=3    unreachable=0    failed=1
605024-logging01           : ok=3    changed=3    unreachable=0    failed=1
605057-compute01           : ok=2    changed=2    unreachable=0    failed=0
605058-compute02           : ok=2    changed=2    unreachable=0    failed=0
605059-compute03           : ok=2    changed=2    unreachable=0    failed=0
605061-storage01           : ok=8    changed=8    unreachable=0    failed=0
605062-storage02           : ok=8    changed=8    unreachable=0    failed=0
605063-storage03           : ok=8    changed=8    unreachable=0    failed=0

root@605020-infra01:/var/lib/lxc# ls -la
total 96
drwx------ 21 root root  4096 Jul  1 00:34 .
drwxr-xr-x 50 root root  4096 Jun 29 15:47 ..
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_cinder_api_container-572e6fe8
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_galera_container-a3def92c
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_glance_container-9e725df6
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_heat_apis_container-6d31e66b
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_heat_engine_container-daedeab7
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_horizon_container-c239a78f
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_keystone_container-1f3f0468
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_memcached_container-36b0a9bf
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_neutron_agents_container-9e21abb9
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_neutron_server_container-e9314f83
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_nova_api_metadata_container-1cb3f825
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_nova_api_os_compute_container-87d6021d
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_nova_cert_container-204e78f3
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_nova_conductor_container-ba0c7b1e
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_nova_scheduler_container-36d278db
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_rabbit_mq_container-6e6d89fd
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_swift_proxy_container-01587b1f
drwxrwx---  3 root root  4096 Jul  1 00:34 605020-infra01_utility_container-fe880a3c
**drwx------  2 root root 16384 Apr 15 21:07 lost+found**

The script want to access every folders under /var/lib/lxc and try to find the config file there, if a useless folder exist under the path, it will cause the file not found exception.

**Comment by tbyrom138** [comment]
Just to add, this is blocking Juno -> Kilo upgrades from finishing.

**Comment by nrb** [comment]
Since the actual issue resides in os-ansible-deployment, I've created https://bugs.launchpad.net/openstack-ansible/+bug/1470571.

**Comment by cloudnull** [comment]
The PR with the fix for master can be found here https://review.openstack.org/#/c/197657/ which will need to be backported into kilo. Since this is an OSAD problem and theres now a launchpad bug I'm inclined to close this issue here.

**Comment by nrb** [comment]
Closing this issue, but leaving milestone information for release notes.
