### ISSUE TITLE
Mitaka with Ceph can no longer be deployed to HTTP redirect on ceph.com

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#2146]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

r13.1.2

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

No apt issues

##### What is actually happening?

Currently `ceph_stable_repo` is set to `ceph_stable_repo: "http://ceph.com/debian-{{ ceph_stable_release }}"` which causes a HTTP redirect on the ceph download side and breaks APT
``` 
  File "<stdin>", line 464, in main
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 440, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: E:GPG error: http://ceph.com trusty InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)
```

I needs to be set to
```
ceph_stable_repo: "http://download.ceph.com/debian-{{ ceph_stable_release }}"
```

##### How can we reproduce this issue?

See above

##### How can we verify your issue is addressed?

No more apt error during ceph install

##### What is your evaluation on the importance of this issue, and why?

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
Is this only when DEPLOY_CEPH is set to yes? If so, could you change the title to say "Mitaka **with Ceph** can no..."

**Comment by BjoernT** [comment]
The issues is inside the ceph common role which can triggered when installing the ceph clients and/or MAAS playbooks installing the client for monitors

**Comment by major** [comment]
@BjoernT The `ceph_stable_repo` variable added to RPC-O should override the variable inside the version of the ceph role that we're bringing down onto the deployment host. Is the wrong version of the ceph-common role the correct version?

**Comment by BjoernT** [comment]
OK thanks, I guess the issue is related that this was a upgraded r13.0.1 to r13.1.2 and the default did not got changed accordingly. Closing since it's part of the branch
