### ISSUE TITLE
New version of libcloud(2.0.0rc2) causes setup-maas.yml to fail

### ISSUE THREAD

**Issue by alextricity25** [rcbops/rpc-openstack#2156]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
setup-maas.yml runs successfully, and libcloud version < 2.0.0 is installed on the maas venv.

##### What is actually happening?
libcloud version 2.0.0rc1 is being installed inside the venv on the master branch, which is [currently broken](https://github.com/racker/rackspace-monitoring/issues/53). 

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
We have been seeing setup-maas.yml failures in gate. For example:
https://rpc.jenkins.cit.rackspace.net/job/RPC-AIO_master-swift-periodic/49/consoleFull
https://rpc.jenkins.cit.rackspace.net/view/AIO/job/RPC-AIO_liberty-swift-periodic/37/execution/node/192/log/?consoleFull

##### How can we reproduce this issue?
Deploy RPCO on master, configure maas, then run setup-maas.yml

##### How can we verify your issue is addressed?
setup-maas.yml completes successfully.

##### If you are using or know of a workaround please describe the necessary steps?
None known at this time.

##### What is your evaluation on the importance of this issue, and why?
prio-1. This is currently blocking the master and liberty gate.
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master - https://github.com/rcbops/rpc-openstack/pull/2157
- [x] newton-14.0 - https://github.com/rcbops/rpc-openstack/pull/2159
- [x] mitaka-13.1 - https://github.com/rcbops/rpc-openstack/pull/2160
- [x] liberty-12.2 - https://github.com/rcbops/rpc-openstack/pull/2161

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
UPDATE:
Currently working on backports for this.

**Comment by mkam** [comment]
The multi-node AIO periodics still failed against master with the pin change. The error message is the same as before (Failed to establish a new connection: [Errno 111] Connection refused).

https://rpc.jenkins.cit.rackspace.net/view/Multi-Node%20AIO/job/OnMetal-Multi-Node-AIO_master-trusty-periodic/16/execution/node/326/log/?consoleFull

https://rpc.jenkins.cit.rackspace.net/view/Multi-Node%20AIO/job/OnMetal-Multi-Node-AIO_master-xenial-periodic/11/execution/node/326/log/?consoleFull

**Comment by alextricity25** [comment]
Thanks for the info @mkam! Multi-node-AIOs are still seeing this error, but regular AIOs are not. I wonder why that is...
 Is there anyway you could log into one of these multi-node-aios and verify if the proper version of libcloud is installed?
From any one of the infra hosts(KVM instances, on a muliti-node-AIO), run:
```
. /openstack/venv/<maas-venv>/bin/activate
pip freeze | grep libcloud
```

**Comment by alextricity25** [comment]
Looking over the logs, I see that the correct version of libcloud is indeed being installed:
```
[maas] changed: [infra3] => (item=apache-libcloud<2.0.0)
[maas] changed: [infra1] => (item=apache-libcloud<2.0.0)
[maas] changed: [loadbalancer1] => (item=rackspace-monitoring-cli)
[maas] changed: [swift3] => (item=python-neutronclient)
[maas] changed: [cinder1] => (item=python-neutronclient)
[maas] changed: [infra2] => (item=apache-libcloud<2.0.0)
```
The pin is working as intended. Could it be that it's somehow not installing the right version inside the venv? It would be good to get our hands on a multi-node-aio to poke around.

**Comment by mkam** [comment]
Yup, looks like the wrong version is still getting installed for some reason:
```
(maas-r13.1.0rc1) root@infra1:~# pip freeze | grep libcloud
apache-libcloud==2.0.0rc2
```

**Comment by alextricity25** [comment]
@mkam I've created a new issue to address the failure that we are seeing the mutli-node-aio jobs:
https://github.com/rcbops/rpc-openstack/issues/2164

**Comment by alextricity25** [comment]
@mkam I've created a new issue to address the failure that we are seeing the mutli-node-aio jobs:
https://github.com/rcbops/rpc-openstack/issues/2164
