### ISSUE TITLE
MaaS testing

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#216]
Currently there is little MaaS testing. Proper testing needs to be in place to help develop the solution futher.

**Comment by nrb** [comment]
@jpmontez @jacobwagner @klevenstein This has QE and doc impacts; just making you guys aware of it. Particularly the doc generation script which I know was a wish list item.

This will also likely be useful to backport into rpc-maas/juno, but I haven't looked at it in depth yet.

**Comment by prometheanfire** [comment]
just needs backports?

**Comment by nrb** [comment]
I believe so. Looks like @git-harry may have made a commit for it, but not a PR.

**Comment by d34dh0r53** [comment]
@git-harry do you have the commits for the backports of this?

**Comment by git-harry** [comment]
@d34dh0r53 - no, I'll put one together

**Comment by prometheanfire** [comment]
done in #414

**Comment by prometheanfire** [comment]
along with your other shame

**Comment by git-harry** [comment]
I see nothing shameful in what I've done

**Comment by prometheanfire** [comment]
it was a joke :P

**Comment by rackertom** [comment]
@prometheanfire @git-harry Since the PR has been merged, can we mark this as closed?

**Comment by prometheanfire** [comment]
not sure

#352 should probably be done too
