### ISSUE TITLE
Update MaaS RabbitMQ check to exclude versioned_notification queues

### ISSUE THREAD

**Issue by i-m-wisch** [rcbops/rpc-openstack#2162]
## Is this a feature or a bug?

- [ ] Feature _(request for enhancement, new functionality)_
- [X] Bug _(something is broken)_

## Which version of rpc-openstack does this issue relate to?
- [X] master
- [?] newton-14.0
- [?] mitaka-13.1
- [ ] liberty-12.2

## What happened?

https://github.com/rcbops/rpc-maas/blob/master/playbooks/templates/rax-maas/plugins/rabbitmq_status.py#L170-171
    
The old method of filtering based on .startswith won't catch the versioned_notifications.X (info,error,etc.) queues, causing false positive alerts when those queues build up.

This seems to only be an issue starting with the Mitaka release (when versioned notifications were introduced), and then only if the OpenStack services are configured to use the notification driver messagingv2. If not configured via the notification_format parameter, the default is to send both versioned and unversioned notifications.

## What were you doing when it happened?

I am an RPC-R team member, and we have run into this issue with our Newton environments as the notification driver defaults to messagingv2 for many of the services.

I am unsure when/if the notification driver has been changed from messaging to messagingv2 in OSA, but assumed a pro-active approach was better.  We have updated our fork of the checks to include this change.

## What did you expect to happen instead of what actually happened?

versioned_notifications queue is excluded from the metric 'msgs_excl_notifications' to prevent false positive alerts.

**Comment by alextricity25** [comment]
Thanks, @i-m-wisch for the heads up! We'll look into this and make the necessary changes to the MaaS check if need be.

**Comment by BjoernT** [comment]
Moved to https://github.com/rcbops/rpc-maas/issues/286
