### ISSUE TITLE
RabbitMQ version override is no longer needed

### ISSUE THREAD

**Issue by major** [rcbops/rpc-openstack#2167]
The version specified in the [defaults file](https://github.com/rcbops/rpc-openstack/blob/master/rpcd/etc/openstack_deploy/user_rpco_variables_defaults.yml#L118-L121) is no longer needed since OpenStack-Ansible already installs that version since 14.0.7 (release 2017-02-14).

**Comment by alextricity25** [comment]
It would be nice to get this backported to newton-14.0

**Comment by major** [comment]
@alextricity25 That version doesn't appear to be mentioned in `newton-14.0` (unless I missed it).

**Comment by alextricity25** [comment]
@major You're right! Ignore me :)

**Comment by cloudnull** [comment]
this issue has a fix that was merged. closing.
