### ISSUE TITLE
Revenge of the InvalidBDM when nova_cross_az_attach is set to False

### ISSUE THREAD

**Issue by alextricity25** [rcbops/rpc-openstack#2179]
> **THIS IS A PUBLIC FACING ISSUE.**
>
> Do not include private or confidential information in this issue.

## Is this a feature or a bug?

- [ ] Feature _(request for enhancement, new functionality)_
- [x] Bug _(something is broken)_

## Which version of rpc-openstack does this issue relate to?
- [x] master - https://github.com/rcbops/rpc-openstack/pull/2182
- [x] newton-14.0 - https://github.com/rcbops/rpc-openstack/pull/2217

Run `git log --pretty=oneline | head -n 1` and provide the output below between
the backtick lines:

```
c10c556e5b2f2c897b6cff773b89adc7cb8e0183 Remove RabbitMQ default version (#2168)
```

## What happened?
In the card https://github.com/rcbops/rpc-openstack/issues/2095, some investigation was done to see why we were getting the error ``Block Device Mapping is Invalid: failed to get volume 43ada3f3-0af3-42ff-a8dc-b961a0543f2a. (HTTP 400) (Request-ID: req-43e456c2-9446-4cdc-8a91-bf0e431915
8b)`` when trying to create an instance from a bootable volume. Turns out that this error had nothing to do with inconsistant AZs across cinder and nova, but is a legitimate upstream bug:
https://bugs.launchpad.net/nova/+bug/1648324

## What were you doing when it happened?
This was brought to our attention when @mkam and @mattt416 where investigating some tempest failures around creating instances from a volume. After further investigation, we found https://bugs.launchpad.net/nova/+bug/1648324

## What did you expect to happen instead of what actually happened?

I expected an instance booted from volume to be successfully created.

**Comment by alextricity25** [comment]
Because of the timing of things, it's going to be a little difficult to get the default ``nova_cross_az_attach`` removed in the r14.0.0 tag. The fix for this won't make it until the r14.0.1 tag.
In the meantime, we should create a doc issue under "known issues" for the Newton release.

**Comment by claco** [comment]
"get the default nova_cross_az_attach removed "   Making it what, True? Would that do more harm than good? We should get some direction from support on this one.

Wr also didn't see boot from volume thing when we were testing backed by Ceph did we?

**Comment by alextricity25** [comment]
> "get the default nova_cross_az_attach removed " Making it what, True?

That's right.

> Would that do more harm than good? We should get some direction from support on this one.

 It sounds like we really don't have a choice if we want boot from volume to work. Yes, support should definitely give us their feedback here. I was thinking we could tag them on the corresponding PR

> Wr also didn't see boot from volume thing when we were testing backed by Ceph did we?

I'm not sure if that was tested, tbh. Nova data disks on a ceph deployments are automatically put in a ceph pool, but that's different then booting an instance from a volume. My guess is that we would see the same thing when booting from volume since this bug has more to do with AZs than the backend cinder is using.

**Comment by claco** [comment]
For the sake of closing all of the loops, let's ask that team too, because storage is storage.

**Comment by alextricity25** [comment]
UPDATE:
Doc bug has been created here:
https://github.com/rackerlabs/docs-rpc/pull/1023

**Comment by claco** [comment]
I had comments on the doc bug, but they also merged it (sooner than I expected). @alextricity25 can you relook at the doc patch?

**Comment by alextricity25** [comment]
UPDATE:
A PR for this issue has been made here and is pending gate jobs and reviews:
https://github.com/rcbops/rpc-openstack/pull/2182

**Comment by alextricity25** [comment]
Blocked by https://github.com/rcbops/rpc-openstack/issues/2227

**Comment by alextricity25** [comment]
UPDATE:
Awaiting status checks on the newton-14.0 backport.
I've created a card so we can revisit this as part of the Ocata work: https://github.com/rcbops/u-suk-dev/issues/1637
