### ISSUE TITLE
[MaaS] Private Network Monitoring playbook

### ISSUE THREAD

**Issue by npawelek** [rcbops/rpc-openstack#2184]
## Is this a feature or a bug?

- [x] Feature _(request for enhancement, new functionality)_
- [ ] Bug _(something is broken)_

## Which version of rpc-openstack does this issue relate to?
- [x] master
- [x] newton-14.0
- [x] mitaka-13.1
- [x] liberty-12.2

## What's the issue

Unable to add the issue into the new rpc-maas repo. 

Private network monitoring (rackspace-monitoring-poller) functionality is now available from Rackspace Monitoring. We're looking to build a separate playbook or incorporate functionality into setup-maas. The private poller should only be utilized for lb_api_checks (remote.http) against the internal_vip_address, and for ping/ssh checks on the primary internal IP of the server. 

Documentation for the poller can found here: https://github.com/racker/rackspace-monitoring-poller

Requirements and deployment methodology:
1. Requires 'privateZones' feature to be enabled on an account. Must be enabled by the MaaS team (ele-dev@lists.rackspace.com).
    * This can be validated from the EleOps dashboard.
    * The private zone can be created with raxmon (>=0.7.1) if the flag exists on the account.
2. The poller package (.deb) can be found [here](https://github.com/racker/rackspace-monitoring-poller#apt).
    * Defaults to configuration `/etc/rackspace-monitoring-poller.cfg`.
        * The configuration requires `monitoring_token` and `monitoring_private_zones` fields.
    * Service requires `ENABLED=true` in `/etc/default/rackspace-monitoring-poller`.
3. The poller should be deployed to all `infra_hosts` as it maintains HA of private checks automatically.
4. `monitoring_zones_poll` should point to the associated `pzID` for associated checks.
5. Checks deployed against the private poller will include:
    * Remote checks against `internal_vip_address` (these will replace any existing API checks). They should be deployed to `infra_hosts` in the same fashion as before. i.e. all `infra_hosts`, but only enabled on one.
        * The maas scheme will need to revert to http for the internal vip.
    * Ping and SSH checks should be deployed against the primary IP of all `hosts`.
    * A gist including the yaml syntax for ping and ssh can be found [here](https://gist.github.com/npawelek/02072544c7782740201b547ee29b548d).

**Comment by CrashenX** [comment]
# An attempt at defining the problem scope and background

## Background
The rpc_maas role ( https://github.com/rcbops/rpc-openstack/tree/newton-14.0/rpcd/playbooks/roles/rpc_maas ) was removed from rpc-openstack on master. A new repo was created to house this bit of Ansible ( https://github.com/rcbops/rpc-maas ). The reason for doing this was to decouple the deployment of MaaS with the deployment of OpenStack.

## Problem Scope
MaaS has not been deployed since it was moved into the new repo. The previous process would have looked roughly like this:
1. clone rpc-openstack onto infra01 node
1. run play(s) to install OpenStack and MaaS

A possible solution could look like this:
1. clone rpc-maas onto infra01 node
1. run play to install MaaS

**Comment by alextricity25** [comment]
I'm marking this as "type-enhancement-small" mainly because I don't think it merits a mention in our intake process(anything above type-enchancement-small needs to be reflected by our intake process).
Thanks for the suggestion @npawelek!

**Comment by claco** [comment]
Just to tie this into other efforts. @prometheanfire is working with @npawelek and @Alfano93 to use rpc-maas repo to get monitoring on external Ceph installs now that RPC-O doesn't do those deployments.

**Comment by npawelek** [comment]
@CrashenX @claco I just want to ensure this effort and/or feature request is separate from the current maas decoupling and ceph monitoring efforts. While the decoupling process will affect where this ultimately ends up, this will be supplemental functionality to setup-maas for CDC and Openstack Anywhere deployments. Specifically, this playbook will deploy the rackspace-monitoring-poller across all infra nodes, register the private zone, and generate yamls for lb_api_checks (against the internal_vip_address), as well as ping and ssh. This is to help bridge the host-down monitoring gap for CDC and Openstack Anywhere environments. Support has been waiting on this functionality from the Rackspace Monitoring team for approximately 6 months, we just need a way to deploy it and finalize testing before going live.

**Comment by Frank-ZhangXin** [comment]
@npawelek Hi, Nathan, you mind to introduce more about privateZones enabling account for rackspace-monitoring-poller? Wish to learn some background about it. Thanks.

**Comment by Frank-ZhangXin** [comment]
@alextricity25 do you think this monitoring overlapped to existing one?

**Comment by CrashenX** [comment]
@npawelek Yes, I believe we are on the same page. Brian Curtin is looking into this. Although, I'm confused because he's not listed as a contributor, and I cannot @briancurtin him. I'd ping him on slack tomorrow.

**Comment by briancurtin** [comment]
If someone wants to assign me here that'd be great. I'm currently getting up to speed and working on a few other deadlines, plus out of the office 5/19, so real progress on the code won't happen until next week.

**Comment by Frank-ZhangXin** [comment]
@briancurtin Hi, Brian, I'm here to assist you going through to add this monitor on maas. Ping me here or on slack anytime if you need more info about maas.

**Comment by Frank-ZhangXin** [comment]
As reference:
MaaS host install: https://github.com/rcbops/rpc-maas/blob/master/tasks/maas_host_install.yml
MaaS host monitor install: https://github.com/rcbops/rpc-maas/blob/master/tasks/maas_host_monitoring.yml
The close case to 'private network monitor':
https://github.com/rcbops/rpc-maas/blob/master/tasks/maas_host_monitoring_network.yml

**Comment by supermari0** [comment]
@briancurtin @Frank-ZhangXin i started some very preliminary changes to rpc-maas here: https://github.com/supermari0/rpc-maas/tree/priv-net-maas

**Comment by Frank-ZhangXin** [comment]
@supermari0 repo build and setup of the tool looks good to me. Just wonder what the plan of monitor checks is.

**Comment by Frank-ZhangXin** [comment]
Checks implemented in plugins of maas: https://github.com/rcbops/rpc-maas/tree/master/files/plugins
Since rackspace-monitoring-poller has its own checks, I think we need work out how to integrate its checks to maas.

**Comment by npawelek** [comment]
@Frank-ZhangXin These won't have any plugins associated as all affected checks are remote.* check types (https://developer.rackspace.com/docs/rackspace-monitoring/v1/tech-ref-info/check-type-reference/#remote-check-type-ref). We'll just need a template to deploy the yaml, which was specified in my initial comment for ping and ssh. lb_api_checks are already implemented as part of rpc-maas, we'll just need to change the zone for these and redeploy if the deployment is CDC or OpenStack Anywhere.

**Comment by briancurtin** [comment]
Are the private zones that will be used for this already going to be setup and configured, or should we be creating one or more zones for this setup? I'm looking at raxmon stuff right now and I'm not sure if I should be building something that creates a new one/ones or reuses something that will be configured.

**Comment by npawelek** [comment]
@briancurtin I was thinking about this when I was running through my testing and I think that's up for debate. To include a the private zone as a variable would mean that we've already created the zone prior to running the playbook to deploy private network monitoring.

In the past with deployments of setup-maas, we already have a manual step to validate whether the 'entityLabel' matches the {{ inventory_hostname }}{{ maas_fqdn_extension }}. If we didn't and there was an incorrectly labelled entity, the playbook would fail. Maybe it makes more sense here to create the zone manually...? At the least, we'll most likely be using raxmon which would need to be updated with a current auth token (if already deployed with setup-maas in the past) or deployed outright if it didn't exist yet.

**Comment by Frank-ZhangXin** [comment]
@npawelek could you please show me some background (link of doc?) of the private zone utilized by this pole? Thanks

**Comment by npawelek** [comment]
@Frank-ZhangXin Technically that variable is only used with remote.* checks, so yes we would effectively overwrite that variable to only include the pzID of the zone to be used.

**Comment by briancurtin** [comment]
Question on the `infra_hosts` group where the poller should be deployed: Mario and I are currently working on this with via RPC-O AIO environments (following the few steps [here](https://github.com/briancurtin/rpc-openstack#quick-start-with-an-rpco-all-in-oneaio)), and `infra_hosts`doesn't seem to be a known group. I do see references around the docs for `infra_hosts` being an actual thing, but the only instances of an `infra_host` related string on this box are the `repo-infra_hosts` and `shared-infra_hosts` groups inside `/etc/openstack_deploy/openstack_user_config.yml`.

Did I do something wrong or should `infra_nodes` be something else? I'm running it right now with `hosts` which I know is not correct, but it runs for right now.

**Comment by Frank-ZhangXin** [comment]
@briancurtin `shared-infra_hosts` is typically the infra host.

**Comment by npawelek** [comment]
@briancurtin Sorry for the delay, I've been in the middle of moving. As Frank mentioned, shared-infra_hosts should work. This seems to be version agnostic, I believe anything prior to RPC Kilo used infra_hosts. Offhand, I can't recall any customers pre-Kilo that we'll need to deploy this on, so using shared-infra_hosts should be fine moving forward.

**Comment by CrashenX** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Playbook for MaaS private networking deployment](https://trello.com/c/hn2BBKjp/49-playbook-for-maas-private-networking-deployment)

**Comment by briancurtin** [comment]
Sorry for this taking so long. Between getting things going in the first place and then later refactoring to fit into how rpc-maas is laid out, this has drawn on for a while.

However, I'm now noticing that the poller and agent can't be run on the same machine. If the agent is started first, the poller will "start" (as in Ansible kicks off the service successfully) but the rackspace-monitoring-poller service is running `/usr/bin/rackspace-monitoring-agent` on an endlessly restarting loop.

Should the agent not be deployed where the poller is deployed? From an earlier conversation, we had said the agent goes everywhere but the poller only goes to the infra nodes. Should that still be the case or should the poller only be on the infra nodes and the agent goes everywhere but infra nodes (as in, just in the containers?)

**Comment by npawelek** [comment]
@briancurtin Interesting. That's correct, the poller and agent will live together on the infra nodes. These should be the only hosts where they overlap. Let me do some testing in my environment and I will get back to you. I don't recall the issue of the agent continually restarting if the poller is running. What versions of the poller and agent are you deploying, the latest?

**Comment by briancurtin** [comment]
Both are latest.

I'll try re-ordering some things, but as it stands now the agent stuff happens first and then poller second. I noticed that `systemctl status rackspace-monitoring-poller.systemd` doesn't show it as active after a full run of rpc-maas, then looking at the poller log file it just shows that it tries to keep starting over and over. If you kill `rackspace-monitoring-agent` and then run the playbook with the poller tags so it avoids trying to startup an agent, only then will the poller start and actually run.

**Comment by npawelek** [comment]
@briancurtin When thinking about this, you probably want to ensure the poller is started before the agent restart happens. When the agent starts, it will attempt to register those checks with the private poller, which might not exist yet. Maybe this is causing the issue? 

Also, how are you daemonizing the poller?

**Comment by briancurtin** [comment]
Ok, I'll reorder them.

I haven't done anything fancy there, just using Ansible `service` to start it up, though I need to do some work to get it working the same for upstart. I assume—if I ordered poller before agent—that's really all I should have to do, right?

**Comment by npawelek** [comment]
I believe so. I'm not sure how quick the creation/registration process is for the poller with the MaaS infrastructure. You might want to put a 30-60s sleep between the first start of the poller and subsequent restart of the agent. We noted some weird things last week testing with rpc-maas and agent restarts. You'll want to make sure that only a single restart happens per playbook run, at the very end.

**Comment by jjbuchan** [comment]
@npawelek @briancurtin The order of starting the poller/agent shouldn't make a difference.  I'm not sure what problem you could be hitting.  Might be worth trying to talk to rphillips or itzg in irc.

**Comment by jjbuchan** [comment]
Turns out we are currently only supporting upstart since that's what the requirement was.  Coincidentally, however, a fix for systemd was made this week and a new poller release will happen later today with it included.

If you pick this up again on Monday all should be good with an upgrade, or you could just start using upstart and that should be fine now.

**Comment by jjbuchan** [comment]
Slight change.  The poller update will happen sometime on Monday.

**Comment by briancurtin** [comment]
Ah, alrighty then. Thanks a lot for the update, will check it out Monday.

**Comment by jjbuchan** [comment]
@briancurtin New poller is released.
