### ISSUE TITLE
Please check for the following default values in nova/neutron

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#220]
We want to consider the following neutron and nova settings around database and RPC pool management as default in RPC. I personally would have seen that in OSAD but I'm pretty sure a bug would have been down voted :-1 there. Lastly we need to either make sure that these settings are set or are actively being set during the installation

keystone_db_max_pool_size: 120
keystone_db_pool_timeout: 30
neutron_db_pool_size: 120
neutron_db_pool_timeout: 30
nova_db_max_pool_size: 120
nova_db_pool_timeout: 30
rpc_conn_pool_size: 180
rpc_response_timeout: 180
rpc_thread_pool_size: 180
nova_rpc_conn_pool_size: '{{rpc_conn_pool_size}}'
nova_rpc_response_timeout: '{{rpc_response_timeout}}'
nova_rpc_thread_pool_size: '{{rpc_thread_pool_size}}'

BTW, the nova_rpc settings have not been implemented yet in OSAD (https://bugs.launchpad.net/openstack-ansible/+bug/1471926)

**Comment by nrb** [comment]
Can you give an idea of a priority? This looks fairly straightforward.

**Comment by BjoernT** [comment]
should be implemented for kilo, prio 3 is ok

**Comment by claco** [comment]
Possibly something that duplicates this, or this is the more up to date request for RPC:  https://bugs.launchpad.net/openstack-ansible/+bug/1471926

**Comment by BjoernT** [comment]
I opened this issue here to run our clouds with this special setup and the osad with a more generic parameter configuration. In the end I have no real preference where we set these parameters as long as they are pushed as default configuration for our RPC clouds

**Comment by nrb** [comment]
Sounds like we have 2 issues (not using acronyms because I think we're overloading them here):

1. Get the oslo.messaging remote procedure call settings into OSAD as variables
2. Define values for Rackspace Private Cloud usage.

**Comment by sigmavirus24** [comment]
@nrb that sounds correct.

**Comment by nrb** [comment]
This should be on 10.1.11 and 11.0.1 milestones

**Comment by prometheanfire** [comment]
db settings don't need to be added upstream

db == db in juno
db == database in kilo/master

**Comment by claco** [comment]
Also seems, the defaults in kilo can set set in rpc-openstack which will automatically update (I think)
The defaults for juno may land squarely on changing the local config in the installation.

**Comment by prometheanfire** [comment]
thought we had user_* stuff we could override with, or is that not in juno?

**Comment by prometheanfire** [comment]
oh ya, upstream is juno but we are tracking it here :(

**Comment by prometheanfire** [comment]
keystone_db_max_pool_size: 120
keystone_db_pool_timeout: 30
neutron_db_pool_size: 120
neutron_db_pool_timeout: 30
nova_db_max_pool_size: 120
nova_db_pool_timeout: 30

    nova - max_pool_size && pool_timeout in database section
      nova_db_max_pool_size && nova_db_pool_timeout
    neutron - max_pool_size && pool_timeout in database section
      neutron_db_pool_size && neutron_db_pool_timeout
    keystone - max_pool_size && pool_timeout in database section
      keystone_db_max_pool_size && keystone_db_pool_timeout

**Comment by prometheanfire** [comment]
juno will need to go upstream

**Comment by prometheanfire** [comment]
the options need readding in kilo

**Comment by prometheanfire** [comment]
https://review.openstack.org/#/c/205678/
https://review.openstack.org/#/c/205675/
https://review.openstack.org/#/c/205671/

go do the reviews, kthnx

all needed after that is overriding the values for the RPC stuff in the userconfig
