### ISSUE TITLE
rpc-support.yml failing trying to create default flavors

### ISSUE THREAD

**Issue by alextricity25** [rcbops/rpc-openstack#2227]
> **THIS IS A PUBLIC FACING ISSUE.**
>
> Do not include private or confidential information in this issue.

## Is this a feature or a bug?

- [ ] Feature _(request for enhancement, new functionality)_
- [x] Bug _(something is broken)_

## Which version of rpc-openstack does this issue relate to?
- [ ] master
- [ ] newton-14.0

Run `git log --pretty=oneline | head -n 1` and provide the output below between
the backtick lines:

```
9f2812e0cb89c8b561d6b546d7fee3789ec68cdd Merge pull request #2222 from rcbops/odyssey4me/octavia-ceilometer-build-fix
```

## What happened?

The `rpc-support.yml` playbook is failing on the task ``TASK [rpc_support : Add default flavors]`` with the following error:
failed: [ramcp-209-7c99_utility_container-c5118c3b] (item={u'vcpus': u'1', u'disk': u'1', u'ram': u'512', u'name': u'm1.tiny'}) => {"failed": true, "item": {"disk": "1", "name": "m1.tiny", "ram": "512", "vcpus": "1"}, "msg": "Error fetching flavor list (Inner Exception: __init__() got an unexpected keyword argument 'app_name')"}

The error can be seen on the following jenkins jobs:
https://rpc.jenkins.cit.rackspace.net/job/RPC-AIO_master-ceph-pr/209/consoleFull
https://rpc.jenkins.cit.rackspace.net/job/RPC-AIO_master-swift-pr/205/console

## What were you doing when it happened?
This failure was noticed in the gate jobs referenced above.

## What did you expect to happen instead of what actually happened?

The task runs successfully

**Comment by alextricity25** [comment]
I've compared the version of shade between a successfully job and a job that failed on this tasks, and they were both 1.16.0. We can rule out shade version inconsistencies as the problem.

**Comment by alextricity25** [comment]
Looking into this now

**Comment by evrardjp** [comment]
I know how to fix it.

**Comment by evrardjp** [comment]
#2229 Is including the flavor fix, but also the flake8 fix.

**Comment by evrardjp** [comment]
Should be fixed.

**Comment by alextricity25** [comment]
Thanks @evrardjp. The changes to the flavor creation task will also need to go in the newton-14.0 branch.

**Comment by evrardjp** [comment]
I can backport it for you.

**Comment by alextricity25** [comment]
@evrardjp Can this close?

**Comment by evrardjp** [comment]
I guess?
