### ISSUE TITLE
rabbit_mq user CVE fix breaks MaaS

### ISSUE THREAD

**Issue by andymcc** [rcbops/rpc-openstack#223]
Since we are removing the guest user (which maas uses by default) as part of the bug fix for: https://bugs.launchpad.net/openstack-ansible/+bug/1466982 MaaS will not work as intended anylonger and the rabbitmq monitors will start failing.

We should fix this moving forward - but this will require rabbitmq checks to be removed or manually edited, as it won't update existing checks monitors.

**Comment by nrb** [comment]
Both PRs merged, closing.
