### ISSUE TITLE
Standalone Swift - MaaS RabbitMQ Check Failing

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/rpc-openstack#229]
In standalone swift deployments, RabbitMQ is installed as part of the shared-infra host group. When installing MaaS, the RabbitMQ check tries to discern the max number of channels. Unfortunately, as RabbitMQ isn't even used, the API returns an empty list, which max() seems to not like.

### RabbitMQ Channels API Call
```
root@9d0ae713-infra1_rabbit_mq_container-f247d7c7:~# http -a  guest:guest http://172.29.236.241:15672/api/connections?columns=channels 
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Length: 2
Content-Type: application/json
Date: Tue, 07 Jul 2015 21:09:53 GMT
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)

[]
```

### RabbitMQ MaaS Check
```
root@9d0ae713-infra1:/usr/lib/rackspace-monitoring-agent/plugins# ./rabbitmq_status.py -H 172.29.236.241 -n 9d0ae713-infra1_rabbit_mq_container-f247d7c7
status error e "./rabbitmq_status.py", line 166, in <module>\n    main()\n  File "./rabbitmq_status.py", line 98, in main\n    max_chans = max(connection['channels'] for connection in resp_json if 'channels' in connection)\nValueError: max() arg is an empty sequence\n
Traceback (most recent call last):
  File "./rabbitmq_status.py", line 166, in <module>
    main()
  File "./rabbitmq_status.py", line 98, in main
    max_chans = max(connection['channels'] for connection in resp_json if 'channels' in connection)
ValueError: max() arg is an empty sequence
```

**Comment by rackertom** [comment]
@byronmccollum I'd like some information about his this deployment was done. When I deploy a stand-alone swift environment, rabbitmq is barely set up. I get 401s because none of the users typically associated with rabbitmq or maas use are present.

**Comment by byronmccollum** [comment]
@rackertom I'm building an environment, and will let you know if this is still the case...

**Comment by byronmccollum** [comment]
Yes, this is still failing. The check is slightly different after the RabbitMQ guest user removal, but still failing in the same way...

```
# ./rabbitmq_status.py -H 172.29.237.136 -n 4dbf96e2-infra1_rabbit_mq_container-8d229323 -U maas_user -p ********
status error print_output\n    yield\n  File "./rabbitmq_status.py", line 170, in <module>\n    main()\n  File "./rabbitmq_status.py", line 101, in main\n    max_chans = max(connection['channels'] for connection in resp_json\nValueError: max() arg is an empty sequence\n
Traceback (most recent call last):
  File "./rabbitmq_status.py", line 170, in <module>
    main()
  File "./rabbitmq_status.py", line 101, in main
    max_chans = max(connection['channels'] for connection in resp_json
ValueError: max() arg is an empty sequence
```

```
# http -a maas_user:******** http://172.29.237.136:15672/api/connections?columns=channels
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Length: 2
Content-Type: application/json
Date: Mon, 05 Oct 2015 16:29:00 GMT
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)

[]
```

I can get you access to the environment if you want to further diagnose...

**Comment by git-harry** [comment]
Why is RabbitMQ being installed if it isn't used? It seems like it would be better to tweak the environment so there are no rabbitmq containers.

**Comment by byronmccollum** [comment]
@git-harry Good question. Seems like there needs to be a `swift-shared-infra_hosts` group with just Galera, and Memcache. And it looks like the RabbitMQ checks wouldn't even get created if there aren't any RabbitMQ containers.

**Comment by stevelle** [comment]
Given the above, can we recommend a change to the docs for a swift stand-alone to eliminate rmq and close this?

**Comment by byronmccollum** [comment]
@stevelle What is an appropriate host group(s) that will result in RabbitMQ not getting installed?

**Comment by rackertom** [comment]
I think generally speaking, we're looking to address the root issue upstream in OSA- Don't install RabbitMQ when it isn't necessary. When that is done, I think we can circle back to this issue and confirm that checks do not install for components that are not present.

Objections @byronmccollum @stevelle or @git-harry?

**Comment by byronmccollum** [comment]
Sounds good to me.

**Comment by stevelle** [comment]
@rackertom make it so IMO

**Comment by rackertom** [comment]
OSA bug filed. https://bugs.launchpad.net/openstack-ansible/+bug/1513132

**Comment by byronmccollum** [comment]
@rackertom Does #442 affect this in any way? I know the ultimate goal is to just not install RabbitMQ for Stand Alone Swift deployments, but just wondering if there is a nice side effect from the change?

**Comment by stevelle** [comment]
@byronmccollum confirming that #442 should partially address this issue.

**Comment by mancdaz** [comment]
osa bug confirms that the issue should be addressed using affinity settings (that is, just don't define a rabbit server in your config, and none of the monitoring stuff will get applied either).

@byronmccollum closing this issue here - please see and add commentary here https://bugs.launchpad.net/openstack-ansible/+bug/1513132 if you have an alternative view

**Comment by byronmccollum** [comment]
Impacts docs for stand alone swift deployments?
