### ISSUE TITLE
setup-hosts.yml fails at "Install host packages"

### ISSUE THREAD

**Issue by mrhillsman** [rcbops/rpc-openstack#2308]
> **THIS IS A PUBLIC FACING ISSUE.**
>
> Do not include private or confidential information in this issue.

## Is this a feature or a bug?

- [ ] Feature _(request for enhancement, new functionality)_
- [X] Bug _(something is broken)_

## Which version of rpc-openstack does this issue relate to?
- [ ] master
- [X] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

Run `git log --pretty=oneline | head -n 1` and provide the output below between
the backtick lines:

```
root@deploy01:/opt/rpc-openstack# git log --pretty=oneline | head -n 1
2f79a24b26c8a6e34fd335eddf1686b87af3620d Make possible to deploy rally (#2295)
```

## What happened?

> Example: I can't snapshot a cinder volume on an AIO RPC-O deployment.

When running scripts/deploy.sh it fails when trying to install packages on the target hosts, in particular, curl with the following error message:

failed: [compute02] (item=[u'apparmor-utils', u'apt-transport-https', u'bridge-utils', u'build-essential', u'cgroup-lite', u'curl', u'dmeventd', u'dstat', u'ebtables', u'
htop', u'iptables', u'irqbalance', u'libkmod-dev', u'libkmod2', u'linux-image-extra-4.4.0-64-generic', u'lvm2', u'python-software-properties', u'python-dev', u'rsync', u'
rsyslog', u'sshpass', u'sysstat', u'time', u'vlan', u'wget']) => {"cache_update_time": 0, "cache_updated": false, "failed": true, "item": ["apparmor-utils", "apt-transpor
t-https", "bridge-utils", "build-essential", "cgroup-lite", "curl", "dmeventd", "dstat", "ebtables", "htop", "iptables", "irqbalance", "libkmod-dev", "libkmod2", "linux-i
mage-extra-4.4.0-64-generic", "lvm2", "python-software-properties", "python-dev", "rsync", "rsyslog", "sshpass", "sysstat", "time", "vlan", "wget"], "msg": "'/usr/bin/apt
-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'apparmor-utils' 'cgroup-lite' 'curl' 'dstat' 'ebtables' 'htop' 'libkmod
-dev' 'python-software-properties' 'sshpass' 'sysstat'' failed: E: Unable to correct problems, you have held broken packages.\n", "stderr": "E: Unable to correct problems
, you have held broken packages.\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed.
 This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor b
een moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n curl : Depends: libcurl3-gnu
tls (= 7.47.0-1ubuntu2) but 7.47.0-1ubuntu2.2 is to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state informatio
n...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some 
required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following package
s have unmet dependencies:", " curl : Depends: libcurl3-gnutls (= 7.47.0-1ubuntu2) but 7.47.0-1ubuntu2.2 is to be installed"]}

## What were you doing when it happened?

> Example: I have an existing cinder volume and I get this error when I try
> to snapshot it using openstackclient:
>
>      $ openstack --os-cloud=mycloud volume snapshot list
>      publicURL endpoint for volumev2 service in RegionOne region not found

I had run scripts/deploy.sh from /opt/rpc-openstack
The above run was at the following stage prior to failure:

```shell
+ [[ no == \y\e\s ]]
+ run_ansible setup-hosts.yml --skip-tags=V-38660
+ openstack-ansible --forks 15 setup-hosts.yml --skip-tags=V-38660
Variable files: "-e @/etc/openstack_deploy/user_osa_secrets.yml -e @/etc/openstack_deploy/user_osa_variables_defaults.yml -e @/etc/openstack_deploy/user_osa_variables_ove
rrides.yml -e @/etc/openstack_deploy/user_rpco_secrets.yml -e @/etc/openstack_deploy/user_rpco_variables_overrides.yml -e @/etc/openstack_deploy/user_variables.yml "
```

## What did you expect to happen instead of what actually happened?

> Example: I expected a cinder volume snapshot to be successfully created.

I expected the packages to be installed.

## Do you think the documentation team wants to know about this?

- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [X] No documentation required for this change

## Does your change require a release note?

- [ ] Yes, it's a pretty big deal like I am and I've made a reno note!
- [ ] Nope, this change has no major impact.

Unfortunately I am not sure if a release note is required.

**Comment by mrhillsman** [comment]
Suggested resolution or what worked for me was to update the rpc-openstack/rpcd/playbooks/configure-apt-sources.j2 to the following:

# {{ ansible_managed }}

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb {{ host_ubuntu_repo }} {{ ansible_distribution_release }} main restricted
# deb-src {{ host_ubuntu_repo }} {{ ansible_distribution_release }} main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-updates main restricted
# deb-src {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## universe WILL NOT receive any review or updates from the Ubuntu security
## team.
deb {{ host_ubuntu_repo }} {{ ansible_distribution_release }} universe
# deb-src {{ host_ubuntu_repo }} {{ ansible_distribution_release }} universe
deb {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-updates universe
# deb-src {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb {{ host_ubuntu_repo }} {{ ansible_distribution_release }} multiverse
# deb-src {{ host_ubuntu_repo }} {{ ansible_distribution_release }} multiverse
deb {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-updates multiverse
# deb-src {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-backports main restricted universe multiverse
# deb-src {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu xenial partner
# deb-src http://archive.canonical.com/ubuntu xenial partner

deb {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-security main restricted
# deb-src {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-security main restricted
deb {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-security universe
# deb-src {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-security universe
deb {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-security multiverse
# deb-src {{ host_ubuntu_repo }} {{ ansible_distribution_release }}-security multiverse

**Comment by odyssey4me** [comment]
@mrhillsman The configure-apt-sources playbook does not exist in newton-14.0, only in newton-14.1, so I'm a little confused about this bug report. Also, this issue is being resolved in that branch with https://github.com/rcbops/rpc-openstack/pull/2307

**Comment by mrhillsman** [comment]
@odyssey4me thx for update. I'll close this one, not sure how I misread the version.
