### ISSUE TITLE
 Update elasticsearch and logstash to latest versions

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#235]
For kilo/master, we should upgrade Elasticsearch to the 1.6.x series, and Logstash to the 1.5.x series.

For Juno and Icehouse, this is recorded at https://bugs.launchpad.net/openstack-ansible/+bug/1472702.

**Comment by odyssey4me** [comment]
I suggest breaking this apart into each component as they are each a considerable body of work.

**Comment by nrb** [comment]
Yeah; actually, I think for Kilo, this can wait, but Juno and Icehouse should be brought up to match Kilo's versions.

**Comment by d34dh0r53** [comment]
I'm going to close this as we're going to move to galaxy roles for Liberty.

**Comment by b3rnard0** [comment]
@d34dh0r53 We closed this because we were planning galaxy roles for Liberty but that obviously did not happen. Will this now be covered as part of r13.2.0 technical debt items (RPC-O Galaxy Role Splits)?

cc: @git-harry

**Comment by git-harry** [comment]
@b3rnard0 elasticsearch and logstash are the 'E' and 'L' in ELK. The will be updated as part of the work for r13.0.0

**Comment by b3rnard0** [comment]
@git-harry Should this be reopened or a new issue created?

**Comment by git-harry** [comment]
@b3rnard0 it's part of the ELK spike so I wouldn't have thought an issue was required.
