### ISSUE TITLE
[r11.0.0rc7] Typo in `rpc_support` role

### ISSUE THREAD

**Issue by jpmontez** [rcbops/rpc-openstack#236]
http://jenkins.propter.net/job/release-rpc-openstack-docker/60/console

In the `r11.0.0rc7` tag, when running the `deploy.sh` script, we're seeing the installation fail with this error message:

```
16:45:23 + openstack-ansible --forks 25 rpc-support.yml
16:45:23 Variable files: "-e @/etc/openstack_deploy/user_extras_secrets.yml -e @/etc/openstack_deploy/user_extras_variables.yml -e @/etc/openstack_deploy/user_group_vars.yml -e @/etc/openstack_deploy/user_secrets.yml -e @/etc/openstack_deploy/user_variables.yml "
16:45:23 ERROR: inculde is not a legal parameter in an Ansible task or handler
```

The incorrect SHA that fixes issue https://github.com/rcbops/rpc-openstack/issues/24 was [included in the tag](https://github.com/rcbops/rpc-openstack/commit/62292b08d0d4cde4c1f02769adc085fdf94afe6c). The correct SHA is [this one](https://github.com/rcbops/rpc-openstack/commit/7854283be5bc862b1a4fcb5e57b9537f48f8f614). It's already fixed in the `master` branch; it just needs to be back ported.

This is currently breaking deployments within all of our laboratories.

**Comment by nrb** [comment]
Typo fixed in #237, and I re-cut r11.0.0rc7 using that commit.

**Comment by jpmontez** [comment]
Thanks! This has been fixed!

**Comment by nrb** [comment]
I've filed a Trello card for introducing linting to rpc-openstack, will get a GitHub issue filed soon.
