### ISSUE TITLE
Prevent unattended upgrades

### ISSUE THREAD

**Issue by kstev** [rcbops/rpc-openstack#24]
So as not to introduce instability in the environment. We would like to remove the unattended-upgrades package if it is installed.
Brought over from https://bugs.launchpad.net/openstack-ansible/+bug/1411897

**Comment by b3rnard0** [comment]
This sounds like a candidate for rpc-extras once we have that separated. @claco @mancdaz

**Comment by odyssey4me** [comment]
Yeah, I was thinking that we can introduce a package blacklist array to allow the deployed to set a list of packages to remove if they're on the hosts/containers.

**Comment by b3rnard0** [comment]
@nrb Can you please provide comments on this bug? @BjoernT would like to see this prioritized.

**Comment by cfarquhar** [comment]
Please parametrize the "APT::Periodic::Unattended-Upgrade" variable and set it to disabled by default.

root@691401-infra01:~# grep Unattended /etc/apt/apt.conf.d/20auto-upgrades
APT::Periodic::Unattended-Upgrade "1”;

**Comment by cfarquhar** [comment]
A little more information on why we're asking for this to be prioritized: customers' /boot volumes are being filled by new kernels being installed.  The initramfs' are corrupted since the volume is full.  This requires DRAC'ing in to each device to resolve if/when they are rebooted.  This causes unexpected and extended downtime which then results in unhappy customers.

**Comment by nrb** [comment]
This definitely looks valid to me, and I think we need a fix in the Juno line as well as master/kilo. For Juno, development is still in osad, and personally, I think putting this setting inside of osad itself makes sense, anyway. I realize this was already moved, but if we're doing a Juno version anyway, I'd prefer to see it upstream.

In the case that it goes upstream, I think trying to get it in for 10.1.10 would be reasonable.

Does anyone have objections to that? I know this was moved from osad already, so I don't want to play ping pong with it; I just think it might be better to provide the option upstream.

**Comment by nrb** [comment]
Also, I should mention @jacobwagner saw this in our QE lab environments, but we took a different approach to fixing it - I'll try to dig up what we did, but blacklisting/removing the unattended updates package makes sense to me.

**Comment by nrb** [comment]
Ok, I found it - https://trello.com/c/aLvRurMH/376-convert-dev-labs-to-cleanup-between-builds-rather-than-rekick-this-will-be-faster-and-rekick-full-install-can-be-tested-in-the-n

This work was around refining our lab management, and having some teardown scripts that would clean up the boot partition for us. Obviously, this won't work in customer environments.

**Comment by nrb** [comment]
```
root@nolan-aio:~# apt-get remove unattended-upgrades
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python-cheetah python-configobj python-json-pointer python-jsonpatch
  python-oauth python-prettytable python-pycurl python-serial python-yaml
  python3-pycurl
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  cloud-init python-software-properties python3-software-properties
  software-properties-common unattended-upgrades
0 upgraded, 0 newly installed, 5 to remove and 3 not upgraded.
After this operation, 1,731 kB disk space will be freed.
```

Removing the package entirely removes some other useful software. Disabling the upgrades may leave the software without security fixes.

Have we implemented a mirror solution that support is happy with yet? Would it be acceptable to leave unattended-upgrades installed as long as we find a way to avoid filling /boot? @BjoernT @cfarquhar

**Comment by claco** [comment]
@nrb Given the original request, I would think the main goal is to remove the possibility if unintended changes w/ unknown consequences. 

'''
Once Openstack infrastructure is deployed, it would probably make sense to disable automatic package updates so as not to introduce the possibility of unexpected changes to the environment. Can we remove the 'unattended-upgrades' package?

If not that, perhaps we could have a tunable list of packages to exclude from auto updates that would be added to /etc/apt/apt.conf.d/50unattended-upgrades under "Unattended-Upgrade::Package-Blacklist {"
'''

Seems like they're ok with a filtered list of things as an option, which might be possible, or provided by osad with the other apt changes.

**Comment by nrb** [comment]
This comes close to the frozen repo/mirror discussions, then.

**Comment by claco** [comment]
@nrb Could be. I was curious if it fits inline with smaller, but related things now in OSAD:

https://github.com/stackforge/os-ansible-deployment/commit/0d6430d66ff9b3caee12ad5569dbf5cd82d2ee26

https://github.com/stackforge/os-ansible-deployment/commit/ea2681280ae4885e5cb333d573ed43ba92fdd08f

**Comment by nrb** [comment]
After talking to our support team, we will make sure we'll turn off unattended upgrades by default in rpc-openstack.

**Comment by BjoernT** [comment]
FYI, this ticket is pretty much about removing the file /etc/apt/apt.conf.d/50unattended-upgrades or changing

Unattended-Upgrade::Allowed-Origins {
	"${distro_id}:${distro_codename}-security";

to

Unattended-Upgrade::Allowed-Origins {
//	"${distro_id}:${distro_codename}-security";

that security related package updates  do not get installed unintentionally.
Technically we couldn't just add the linux-* packages to Unattended-Upgrade::Package-Blacklist to prevent filling up the disks. The general security and patching context is a different story

**Comment by nrb** [comment]
Thanks for that clarification @BjoernT.

**Comment by prometheanfire** [comment]
Since this is just disabling the upgrades entirely I'm going to go with the commenting out of the upgrades.

the `Unattended-Upgrade::InstallOnShutdown "true";` value seems like something we could do though.  Also the remove unused deps one.

**Comment by nrb** [comment]
@prometheanfire That sounds reasonable.

**Comment by prometheanfire** [comment]
cron job with this would do it

    apt-get purge $(dpkg -l 'linux-image*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | head -n -3) --assume-yes

**Comment by prometheanfire** [comment]
that's needed as autoremove doesn't remove kernels at all

**Comment by nrb** [comment]
@mattt416 I tested the lineinfile things on both PRs, looks good

**Comment by claco** [comment]
@nrb @prometheanfire We may want to update these two patches in master/kilo? The backport to juno fails the lint test in osad, which in itself may be a warning sign it will be interpreted in the wrong way and needs escaped:

```
2015-07-21 00:48:53.793 | find ${PLAYBOOK_PATH} -type f -name "*.yml"                     ! -name "os-service-config-update.yml"                     ! -name "host-network-setup.yml"
2015-07-21 00:50:30.868 | [ANSIBLE0001] Old style (${var}) brackets
2015-07-21 00:50:30.869 | /home/jenkins/workspace/os-ansible-deployment-check-lint/rpc_deployment/playbooks/openstack/roles/rpc_support_common/tasks/disable_unattended_upgrades.yml:20
2015-07-21 00:50:30.869 |     line: '//   "${distro_id}:${distro_codename}-security";'
```

http://logs.openstack.org/58/203858/3/check/os-ansible-deployment-check-lint/1ca11ae/console.html

**Comment by claco** [comment]
Just tried this on a fresh instance by running unattended-upgrades with and without the file:

With:
`2015-07-21 16:38:58,142 INFO Allowed origins are: ['o=Ubuntu,a=trusty-security']`

Without:

`2015-07-21 16:39:38,841 INFO Allowed origins are: []`

So it appears to do the right thing. If no one is apposed, I can change the task across all branches to just remove the file for now. Shouldn't be a shock since the request was to remove the entire package originally anyways. No more linter issues.

/cc @nrb @prometheanfire

**Comment by nrb** [comment]
I'm unopposed.

**Comment by claco** [comment]
reopening for a rework
