### ISSUE TITLE
Solution Tab Failures in kilo

### ISSUE THREAD

**Issue by weezer** [rcbops/rpc-openstack#247]
I was unable to launch any of the solutions.  They would go thru a creating process, however would never actually complete and timeout after the 60 minute window.  It appears that the stack gets created partially however since some steps never complete it eventually fails.  solutions appear to be stuck on the deploy-salt-master step.

**Comment by nrb** [comment]
Do you have any more details? Heat API logs would be helpful.

**Comment by weezer** [comment]
issue closed, related to the network issue. i can successfully create heat templates right now and fully tested.
