### ISSUE TITLE
MaaS check fails on self-signed certificates

### ISSUE THREAD

**Issue by jefftelesford** [rcbops/rpc-openstack#249]
Hi,
I'm starting to see this issue more. All have taken place in customer datacenters. Self signed certificates are being used on the LB. When MaaS goes to check if Horizon is up, the check fails. I can see the error when I try to curl the vip ip: "curl -vvv "vip_ip".  However, if i do a --insecure curl connection (curl -vvnk "vip_ip"), I get back a 200 ok along with the website content. 

Https checks need to account for self signed certificates.

Best Regards,

Jeff Telesford
OpenStack Engineer
Rackspace Hosting

**Comment by byronmccollum** [comment]
@jefftelesford Are the endpoints an IP address, or a hostname? If an IP address, its a bug on the MaaS side. When `follow redirects` is on, and the HTTP check is against an IP address, it tries to resolve the IP address as if it were a hostname. To make it go green, turn off `follow redirects`, and set the full check URL to `https://x.x.x.x:443/auth/login/`.

**Comment by nrb** [comment]
@jefftelesford Does @byronmccollum's work-around solve your issue? This sounds like an upstream MaaS issue.

**Comment by nrb** [comment]
Adding doc impact, since we should mention how to properly create these checks.

**Comment by prometheanfire** [comment]
it also sets up the check to be http, not https, seems odd

URL: http://23.253.65.167:443/auth/login/

**Comment by prometheanfire** [comment]
working for me if I set it to https with self signed (manual change for now)

**Comment by claco** [comment]
@prometheanfire Ironically, I think your 249 294 typo might be right. Maybe we should know issue this as well since it's relatively easy to work around until a fix is released.

**Comment by byronmccollum** [comment]
Any redirecting where the host is an IP address will cause the Cloud Monitoring (MaaS) bug [mentioned above](https://github.com/rcbops/rpc-openstack/issues/249#issuecomment-125663427) to manifest itself, and the check to fail.

Setting `maas_horizon_scheme` to `https` will prevent one redirect from happening (http to https). Setting `path` to `/auth/login/` will prevent the second redirect from happening. To be extra safe, disabling `follow_redirects` on the check might be advised as well.

**Comment by prometheanfire** [comment]
Just a resync with master, also looks like we already set the path in master at least.
