### ISSUE TITLE
/etc/openstack_deploy/user_extras_secrets.yml missing in rpc-openstack/osad

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#251]
The user_extras_secrets.yml is missing inside the OSAD git tree but I found it in /opt/rpc-openstack/rpcd/etc/openstack_deploy/user_extras_secrets.yml but not inside the osad directory as documented at http://docs-internal.rackspace.com/rpc/api/v11/bk-rpc-installation/content/sec_configure-prerequisites.html which refers to  /opt/rpc-openstack/os-ansible-deployment/etc/openstack_deploy.
Currently I'm not sure if the user_extras_secrets.yml file is supposed to be part of the OSAD or rpc-openstack project

**Comment by nrb** [comment]
#242 looks like it addresses this, but we need that to make it's way into the internal docs, too.

@robb-romans, @ionosphere80 would either of you be able to update the internal docs?

**Comment by odyssey4me** [comment]
``user_extras_variables.yml`` and ``user_extras_secrets.yml`` are files specifically to be used by playbooks/roles which are only in rpc-openstack (eg: ELK roles, etc). The idea is generally to try and keep the right variables in the right files to reduce confusion and ensure that if changes happen in either project they will only affect the variables in their specific files.

**Comment by BjoernT** [comment]
I believe this has been addressed. Closing
