### ISSUE TITLE
/etc/openstack_deploy/conf.d/repo-servers.yml not automatically configured

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#256]
Unlike https://github.com/stackforge/os-ansible-deployment/blob/master/scripts/run-upgrade.sh#L288 the deploy.sh from rpc-openstack is not generating the new repo-inventory_hosts group.
We either add this step into the deploy.sh or add this to the documentation

**Comment by nrb** [comment]
IMO, this is should be a documentation step - we don't create most of the host stanzas/config files automatically on greenfields. The decision to automatically make one on upgrades was done in OSAD to ensure we didn't have failing upgrades, since repo servers didn't exist before.

However, I am discussing with the dev team further.

**Comment by nrb** [comment]
Alternatively, you can set the `openstack_repo_url` variable to a PyPI-like index page.

**Comment by nrb** [comment]
@BjoernT Are the documentation updates enough here? Changing the process to automatically create the repo host group would likely be a feature request, but I wanted to check to see if the docs change answer the question.

**Comment by BjoernT** [comment]
Well if osad does it automatically why not rpc-openstack. The documentation would suffice but more importantly we still have an issue with the pip link builder and the unavailability of a repo vip will lead to 404, my pip conf after upgrading to kilo looks  like this :
find-links =
        http://172.29.236.21:8181/os-releases/11.1.0/
        https://mirror.rackspace.com/rackspaceprivatecloud/python_packages/10.1.8/

**Comment by nrb** [comment]
With the upgrade process, OSAD does it automatically. For greenfield, neither automatically create `repo-infra_hosts`.

**Comment by BjoernT** [comment]
I think this is obsolete now after populating the /etc/openstack_deploy/conf.d/repo-servers.yml
