### ISSUE TITLE
OSAD default token is now Fernet

### ISSUE THREAD

**Issue by claco** [rcbops/rpc-openstack#258]
With the latest sha bump for OSAD, the default token type is now Fernet, which is a functional difference from 10.x, which is uuid+sql storage.

In order to keep the functionality the same from a support perspective, we should override the config defaults in RPC back to uuid+sql to match what we had in 10.x

**Comment by odyssey4me** [comment]
I'm not entirely sure that enforcing UUID tokens as a default is doing anyone any favours. Currently the deployed environments have huge keystone databases which are causing operational problems. I really think that the decision to keep UUID tokens as a default should be thoroughly discussed with support.

I would rather suggest that moving to fernet tokens is a good new default, especially for new environments - and there should rather be a documentation note regarding how to set the token backend to UUID tokens if that is desired.

**Comment by cloudnull** [comment]
:+1: to what @odyssey4me said. Fernet addresses some serious performance and security issues as such I think it should remain the default. IMHO.

**Comment by JCallicoat** [comment]
Should we remove the user var and have fernet tokens be the default now for Liberty?

**Comment by nrb** [comment]
If it's the default for Keystone in Liberty, I don't see why not.

I know there was a desire to keep things the same from Juno to Kilo, but I think it's been given a release cycle and we should catch up. Note that supporting fernet does NOT mean we have to support federation.

@d34dh0r53 will probably have to weigh in, though.

**Comment by odyssey4me** [comment]
Confirmed - Fernet tokens have nothing to do with Federation. They have everything to do with saving yourself from wanting to burn everything... otherwise known as no more keystone token table truncates. Using fernet tokens is also a path to multi-region implementations (as the keystone DB is now much smaller and changing less often).
