### ISSUE TITLE
upgrade.sh has wrong path for deploy.sh

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#259]
Inside of the upgrade.sh script, we use `$RPCD_DIR/deploy.sh` and `RPCD_DIR=/opt/rpc-openstack/rpcd`. The file isn't found.

We need to either add the new path for just the script or edit it.

**Comment by nrb** [comment]
On further reflection, I think this *will* break QE deployments. As such I am retargeting to 11.0.0rc11

**Comment by nrb** [comment]
@tbyrom138 @jacobwagner QE hasn't reported this, but I'm fairly certain it will bite you in the labs once the other scripts can proceed.

**Comment by mancdaz** [comment]
@nrb 'reference issue in commit message' fail
