### ISSUE TITLE
[feature] Replace ELK stack with ElasticSearch on ObjectRocket

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/rpc-openstack#262]
We should provide the capability of using [ElasticSearch on ObjectRocket](http://www.rackspace.co.uk/objectrocket/elasticsearch) instead of a single ElasticSearch instance and a single Kibana instance on the logging host. This provides high availability for ElasticSearch and Kibana and far better scalability.

I would recommend that this be a feature within the Liberty series to replace our very heavily aging ELK stack. Ideally our ELK stack in its current form should be deprecated with the Kilo release and removed in our Mitaka release. The alternative here is to re-implement our stack using Ansible Galaxy ELK roles.

**Comment by nrb** [comment]
Per Jesse, this is more a feature request for a future version (12.x-ish).

**Comment by git-harry** [comment]
Based on the currently work to update the ELK stack for Mitaka I believe this issue is no longer valid.
