### ISSUE TITLE
[feature] Use ObjectRocket MongoDB for Ceilometer

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/rpc-openstack#263]
We should test and provide a supported solution for using [ObjectRocket MongoDB](http://www.rackspace.co.uk/objectrocket/mongodb) with RPC as the underpinning database for Ceilometer.

**Comment by nrb** [comment]
Per Jesse, this is more a feature request for a future version (12.x-ish).

**Comment by stevelle** [comment]
This will end up being a work card, with a new issue, if you close this.

**Comment by nrb** [comment]
As @stevelle said, this is of interest for the Liberty release, at least in terms of a spike.

**Comment by git-harry** [comment]
The is a spike in-progress/finished regarding the appropriate way to deploy Ceilometer and so I believe this issue is no longer valid.
