### ISSUE TITLE
maas needs to be updated to use Keystone v3

### ISSUE THREAD

**Issue by sigmavirus24** [rcbops/rpc-openstack#273]
OSAD has updated its keystone library to perform all actions with Keystone v3. Some portions of Keystone v3 cannot be served via v2, e.g., endpoints. v2 endpoints can be returned via v2 but not vice-versa. Our MaaS scripts for keystone need to be updated to also use v3.

**Comment by nrb** [comment]
So it sounds like MAaS scripts with 11.0 will fail against keystone without updating, correct?

**Comment by sigmavirus24** [comment]
*Maybe*

**Comment by nrb** [comment]
Sounds like we'll need to verify this, at the very least.

**Comment by sigmavirus24** [comment]
I was able to confirm this today.

**Comment by sigmavirus24** [comment]
So @xeregin and myself were able to confirm (yesterday) that pretty much every OpenStack check (except swift?) break due to the upgrade to Keystone v3. The entire monitoring dashboard for one of @xeregin's test deployments was red except for CDM checks, RabbitMQ, and Swift. Anything relying on Keystone will fail:

- All API local checks
- Most (if not all) service checks (Horizon service check may not be because we log in through the web page)

Our swift checks are mostly exempt because we use the swift cli tools to grab that (dispersion, recon) information.

**Comment by sigmavirus24** [comment]
Sorry that I was thinking about [QUIC](http://tools.ietf.org/html/draft-tsvwg-quic-protocol-00).
