### ISSUE TITLE
Turn down ansible forks variable in deploy.sh

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#276]
By default, OSAD's scripts-library.sh uses [25 forks](https://github.com/stackforge/os-ansible-deployment/blob/master/scripts/scripts-library.sh#L23). However, Juno's run-playbooks.sh scripts [sets it to 10](https://github.com/stackforge/os-ansible-deployment/blob/juno/scripts/run-playbooks.sh#L30).

We should probably drop the number of forks down to 10 or 15, because we're seeing SSH failures on multi-node installs when the containers aren't quite ready.

**Comment by nrb** [comment]
@robb-romans This affects docs; in the event that these patches don't merge, we should advise deployers to do the following:

When deploying, run `FORKS=15 scripts/deploy.sh`
When upgrades, run `FORKS=15 scripts/upgrade.sh`

**Comment by sigmavirus24** [comment]
Would installing the ssh-retry ansible plugin help with this (as an alternative)?

**Comment by robb-romans** [comment]
please review ^^^^

**Comment by odyssey4me** [comment]
FYI please note that https://bugs.launchpad.net/openstack-ansible/+bug/1479812 has been reported upstream and the review for master has merged, with a review for kilo pending. While the rpc-openstack override will still work you may find that the upstream fix changes what you'll want to be doing. The reviews are: https://review.openstack.org/#/q/I31ad7353344f7994063127ecfce8f4733769234c,n,z

**Comment by nrb** [comment]
Thanks @odyssey4me; I'm not totally sure we got the upstream changes, but I think setting this in the rpc-openstack scripts makes sense if for no other reason that to increase visibility for our deployers.

**Comment by nrb** [comment]
A suggestion - we include @odyssey4me's patch grep pattern for the number of CPUs instead of a hardset 10. (https://review.openstack.org/#/c/209426/1/scripts/scripts-library.sh)

Thoughts, @jacobwagner?

**Comment by nrb** [comment]
This was also merged kilo by mistake, but both @prometheanfire were fine with that. I'm closing this issue and leaving this comment to acknowledge that it happened.

**Comment by nrb** [comment]
Re-opening in light of delegate_to issues found on https://bugs.launchpad.net/openstack-ansible/+bug/1479812/comments/5.

We should go with Jacob's original proposal of 10.

**Comment by claco** [comment]
@nrb @jacobwagner What setting did we use today in the upgrade?

**Comment by nrb** [comment]
I did not see what was set.

**Comment by robb-romans** [comment]
please review doc commit referenced here: https://github.com/robb-romans/rpcdocs/commit/a4d1f9542d321639fe06cb27d2bc4a591058a3c5
