### ISSUE TITLE
Deploying using scripts/deploy.sh tries to deploy ceilometer

### ISSUE THREAD

**Issue by sigmavirus24** [rcbops/rpc-openstack#278]
If you create a clean server and try to build an AIO with

```
DEPLOY_AIO="yes" ./scripts/deploy.sh
```

The swift role will fail when trying to add the `ResellerAdmin` role the `ceilometer` user.

**Comment by stevelle** [comment]
@nrb  please review for backport potential thanks

**Comment by nrb** [comment]
Both branches merged, closing.

**Comment by sigmavirus24** [comment]
Closed  because @nrb probably pressed comment instead of "close and comment"
