### ISSUE TITLE
Galera wsrep_sst_method=xtrabackup causing cluster failures when nodes attempt to rejoin

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/rpc-openstack#284]
This is an osad bug that will need to be fixed for upgrades in rpc-openstack

https://bugs.launchpad.net/openstack-ansible/+bug/1478105

**Comment by prometheanfire** [comment]
it's being worked upstream, already double +2'd

**Comment by nrb** [comment]
Reopened because GitHub.

**Comment by nrb** [comment]
All merged, closing.
