### ISSUE TITLE
Archive and sync critical inventory and configuration data

### ISSUE THREAD

**Issue by cfarquhar** [rcbops/rpc-openstack#293]
https://bugs.launchpad.net/openstack-ansible/+bug/1399416

Any form of tar+gzip'ing the /etc/os-ansible-deployment directory and shipping it to the backup directory on the other infra nodes will be fine.

**Comment by seancarlisle** [comment]
This is still very much an issue. At present, the configuration files for a deployment are not backed up anywhere.

**Comment by claco** [comment]
Well, they should be backed up by the MBU, but yes, this helps us not when that node is the dead node and we'e waiting on a restore.

**Comment by BjoernT** [comment]
Yes still valid concern. Many customers don't have MBU and won't get it like CDC deployments. Don't think it'll be difficult to write a small sync/backup role which copies the data to all infra nodes. Assign the bug to me and I hack it into rpc-openstack

**Comment by ameserole** [comment]
How often should we be doing the backup and sync?

**Comment by ameserole** [comment]
After doing some digging around I found that /etc/openstack_deploy directory with all of the user config files are only created and used on the deployment node. This means that the config files may not even be on infra1 if something else is used for the deployment node. This makes me think we won't have the synchronization problem @claco mentioned here: https://github.com/rcbops/ansible-lxc-rpc/issues/453

I think it would still be a good idea to compress the files and back them up on to the other nodes just in case the config files get corrupted. This can be done with a playbook that can be manually run or set up to be run as a cron job.

If I am wrong please correct me.

**Comment by hughsaunders** [comment]
Customers need a real backup solution. If they don't have one then they or we are playing with fire (depends on contracts).  Adding hacky syncing cron jobs is no substitute for backups. RAX DC deployments should be using MBU. As far as I'm aware, CDC backups are the customer's responsibility. Backups require infrastructure (tapes, trucks) that we can't provide as a project, as a business we must ensure that we make use of MBU, and make sure the CDC customers understand their risks and responsibilities. I realise that some of this is beyond dev/support control, however its our collective responsibility to flag risks to our superiors, rather than hiding them with band-aid solutions.

**Comment by ameserole** [comment]
Based off the discussion that we had in our dev meeting and @hughsaunders comment I am closing this issue. We already have a backup service offered for Rax DC deploys that covers these files and have a policy that the customer is responsible for coming up with a backup solution in their own data center. Here is a link to more info about backups https://one.rackspace.com/pages/viewpage.action?title=RCB+Backups+v9.0&spaceKey=PrivateCloud

@BjoernT let us know if you think that this is still an issue.

**Comment by BjoernT** [comment]
Yes but the solution has to work in customer data centers too hence I will do something on git level and distribute that across the infra nodes. No need to fix it here, we in support do it outside of the product

**Comment by hughsaunders** [comment]
@BjoernT as stated, CDC customers need real backups too, there is no need to hack something in as the problem must be solved more generally. Initially the question is whos responsibility are backups in CDC deployments? If they are our responsibility then we need to invest more than a syncing cron job. If its not our responsibility, then let the customer do it.
