### ISSUE TITLE
r11.0.0rc9 - Maas Local Checks - error Authorization failed: The resource could not be found. (HTTP 404)

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/rpc-openstack#294]
Lots of checks failing with the following error:

```
error Authorization failed: The resource could not be found. (HTTP 404)
```

Running the checks manually shows the same error:

```
# python nova_api_local_check.py 172.29.236.119
status error Authorization failed: The resource could not be found. (HTTP 404) (Request-ID: req-7585071e-73b0-41a3-a3ff-ef4db9c1263e)
```

And using the `openrc` in the utility container, running any keystone commands returns the following:

```
# source openrc 
# keystone --debug catalog
/usr/local/lib/python2.7/dist-packages/keystoneclient/shell.py:65: DeprecationWarning: The keystone CLI is deprecated in favor of python-openstackclient. For a Python library, continue using python-keystoneclient.
  'python-keystoneclient.', DeprecationWarning)
WARNING: unsupported identity-api-version 3, falling back to 2.0
DEBUG:keystoneclient.auth.identity.v2:Making authentication request to http://172.29.236.1:5000/v3/tokens
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.29.236.1
DEBUG:requests.packages.urllib3.connectionpool:"POST /v3/tokens HTTP/1.1" 404 93
DEBUG:keystoneclient.session:Request returned failure status: 404
Authorization Failed: The resource could not be found. (HTTP 404) (Request-ID: req-33e2ab0e-9b06-45b4-b3e1-beb5a848f34e)
```

Interestingly, the openstack client seems to be able to communicate with keystone:

```
# source openrc 
# openstack catalog list
+----------+----------------+-------------------------------------------------------------------------------+
| Name     | Type           | Endpoints                                                                     |
+----------+----------------+-------------------------------------------------------------------------------+
...snip...
```

**Comment by nrb** [comment]
Was this with 11.0.0rc9?

**Comment by byronmccollum** [comment]
One other thing...the catalog seems to have a mix of v2 / v3 endpoints for keystone...

```
| keystone | identity       | RegionOne                                                                     |
|          |                |   public: http://104.130.192.79:5000/v2.0                                     |
|          |                | RegionOne                                                                     |
|          |                |   admin: http://172.29.236.1:35357/v3                                         |
|          |                | RegionOne                                                                     |
|          |                |   internal: http://172.29.236.1:5000/v2.0                                     |
```

**Comment by byronmccollum** [comment]
Yes, 11.0.0rc9 this yesterday and today.

**Comment by sigmavirus24** [comment]
This is related to https://review.openstack.org/#/c/205192/2

**Comment by odyssey4me** [comment]
keystone client via CLI cannot consume a service catalogue created via the v3 API. The openstack CLI can and should be used. The mix of endpoint versions is intentional - v3 for the admin endpoint, and v2 for the internal/public endpoints.

**Comment by byronmccollum** [comment]
Should these be the same?

openrc:
```
export OS_AUTH_URL=http://172.29.236.1:5000/v3
```

openrc-maas
```
export OS_AUTH_URL=http://172.29.236.1:5000/v2.0
```

**Comment by nrb** [comment]
I'm not super familiar with the Keystone changes that have been going on to get federation working, but I would assume that both openrc and openrc-maas should both use the same OS_AUTH_URL.

What I find strange is that os-ansible-deployment in Kilo is setting v3 for `keystone_service_internalurl` ([source](https://github.com/stackforge/os-ansible-deployment/blob/a72d22e203bfaf5196ed21ea7e9be1d98205f241/playbooks/roles/os_keystone/defaults/main.yml#L117)), which is evidently what our `rpc_maas` task is using ([source](https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/templates/openrc#L5)).

**Comment by byronmccollum** [comment]
Problem is `openrc-maas` rc file. I telplated from `openrc`, and early indications are that MaaS checks are starting to work...

**Comment by byronmccollum** [comment]
@nrb look again...

`keystone_service_internalurl` vs `keystone_service_internalurl_v3`.

**Comment by nrb** [comment]
Right, it is `openrc-maas`. Trying to figure out the best way to get the right values pulled over from `os-ansible-deployment`, since it looks like there are some overrides happening between the role defaults and group vars.

**Comment by nrb** [comment]
@byronmccollum Right, but we were assigning `keystone_service_internalurl_v3`'s value to `keystone_service_internalurl`.

**Comment by odyssey4me** [comment]
v2 endpoints for internal/public in the final delivery https://github.com/stackforge/os-ansible deployment/blob/master/playbooks/inventory/group_vars/hosts.yml#L146-L158 - this is busy being worked on to set them to v3 in https://review.openstack.org/205192 but that's failing tempest and thus still WIP

**Comment by claco** [comment]
I would like to get some evaluation from @tbyrom138 @jacobwagner around this so we can determine the scope and severity of this based on what they're seeing in QE.

**Comment by prometheanfire** [comment]
just to be clear, changing v2.0 to v3 seems to fix it (first simple test)

**Comment by claco** [comment]
Because if the tight 11.0 timeline, and that the work around is relatively easy, I'm in favor of making this a 11.0.1 timeline fix, and making sure we document this as a known issue w/ the workaround asap. This will also give us a sprint to keep an eye on the other v2 vs v3 mini discussions , and see if anything changes there in upstream OSAD Kilo.

@prometheanfire can you open a docs bug with the relevant issue, error, workaround?

**Comment by b3rnard0** [comment]
@claco +1 on pushing this to 11.0.1 if it's not high priority.

cc: @nrb

**Comment by nrb** [comment]
Setting the milestone and priority appropriately, then.

**Comment by byronmccollum** [comment]
@nrb, @claco, @b3rnard0 
11.0.1, or 11.1.0? I'm seeing references to both.

**Comment by claco** [comment]
The least complex answer I can give is 11.0.1. Revision released will be out every two weeks post 11.0.0 being cut. But 11.1.x rc start dropping soon as well.

**Comment by prometheanfire** [comment]
repoening for #296

**Comment by nrb** [comment]
PRs for Kilo and master merged, closing this issue.
