### ISSUE TITLE
OSAD upgrades fail

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#302]
The upstream issue at https://bugs.launchpad.net/openstack-ansible/+bug/1479916 causes failures when doing upgrades from OSAD juno to rpc-openstack Kilo.

**Comment by nrb** [comment]
The fix is upstream, but we'll have to bump our SHA to consume it.

**Comment by sigmavirus24** [comment]
See https://review.openstack.org/#/c/207687/ for a very likely fix.

**Comment by nrb** [comment]
@jacobwagner, @tbyrom138 tagging for reference.

**Comment by prometheanfire** [comment]
needs backport, assigning to myself so I don't forget (also, rc10 needs to go to rc11)

kilo
