### ISSUE TITLE
on upgrades, the galera restart fails due to the new cluster name in kilo

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#308]
In juno, the galera cluster name is ```rpc_galera_cluster```. In kilo it was changed to ```openstack_galera_cluster```.

On an upgrade, some config file changes are made, necessitating a restart of the galera nodes.  The galera play restarts them one at a time, in a rolling upgrade fashion.  Unfortunately this means that the first node to restart is now trying to connect to a cluster called ```openstack_galera_cluster```, and the other 2 are still running a cluster called ```rpc_galera_cluster```, so the restart times out and fails.

We need to override this back to rpc_galera_cluster in:

```
 rpcd/etc/openstack_deploy/user_variables.yml
```

**Comment by nrb** [comment]
Master merged, needs kilo backport.

**Comment by nrb** [comment]
Both issues merged, closing.
