### ISSUE TITLE
the rpc-openstack upgrade.sh script does not merge in the rpcd specific user_variables

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#310]
In ```scripts/deploy.sh``` we have this:

```
pushd ${RPCD_DIR}
        for i in $(find etc/openstack_deploy/ -type f -iname '*.yml'); do ../scripts/update-yaml.py /$i $i; done
popd
```

This does a nice job of merging in all the ```rpcd/etc/openstack_deploy/*.yml``` user variables files, meaning all our overrides work nicely.

In ```scripts/upgrade.sh```, we do not have this. This script actually calls ```deploy.sh```, but not until it's too late (i.e. after the osad ```run-upgrade.sh``` has run) so the rpcd specific variables do not get merged in. They therefore get ignored on upgrades.

We need to run the above three liner at the top of the ```rpc-openstack/scripts/upgrade.sh```. Something like:

```
diff --git a/scripts/upgrade.sh b/scripts/upgrade.sh
index 3ca67a8..6649436 100755
--- a/scripts/upgrade.sh
+++ b/scripts/upgrade.sh
@@ -18,6 +18,11 @@ set -eux pipefail

 BASE_DIR=$( cd "$( dirname ${0} )" && cd ../ && pwd )
 OSAD_DIR="$BASE_DIR/os-ansible-deployment"
+RPCD_DIR="$BASE_DIR/rpcd"
+
+pushd ${RPCD_DIR}
+    for i in $(find etc/openstack_deploy/ -type f -iname '*.yml'); do ../scripts/update-yaml.py /$i $i; done
+popd

 # Do the upgrade for os-ansible-deployment components
 cd ${OSAD_DIR}
```

**Comment by mancdaz** [comment]
actually not sure this works.  We've not yet created the ```/etc/openstack_deploy/*``` files yet to update at this point.  Need to figure something out to ensure we're using the rpcd specific user variables on upgrade though.

**Comment by nrb** [comment]
Yeah - we'd need to inject this in somehow; I'm not sure we have a good way to do that right now. Might this necessitate a hook in the OSAD upgrade scripts?

**Comment by nrb** [comment]
On more thought, I have the following proposal:

Move [update-yaml.py](https://github.com/rcbops/rpc-openstack/blob/master/scripts/update-yaml.py) into OSAD, and modify the OSAD upgrade script to take the override file as a parameter.

This would ensure that the community could take advantage of customized deploys, and would give us the hook this bug apparently requires in the upstream.

**Comment by mancdaz** [comment]
Why can't we just call update-yaml.py from the rpc-openstack script, and
target it at the existing user_variables.yml under /etc/rpc_deploy/ from
the juno install. These get moved over to openstack_deploy as part of the
osad run-upgrade.sh so the merged vars would be preserved.

Not sure about user_extra_variables.yml as that doesn't exist yet.

**Comment by nrb** [comment]
When would we call update-yaml.py then? Doesn't the merge need to happen before galera is touched? That happens in the OSAD run-upgrades script.

Updating the YAML before running OSAD is too early, and after is too late, if I'm understanding the bug,

**Comment by nrb** [comment]
Oh, yes, I see what you're saying now. That may work, but I'm not sure.

**Comment by mancdaz** [comment]
Yeah, as per my original diff, except targeting the files under rpc_deploy
rather than openstack_deploy (which rpc_deploy hasn't been renamed to yet,
but will be, thereby preserving the merged vars)

**Comment by odyssey4me** [comment]
If this automated merge is used, then there needs to be documentation stating that this happens and that any customisations that were put into user_variables in rpc_deploy prior to the upgrade will have to be revisited after the upgrade is complete and the deployer will need to evaluate whether the new defaults are suitable, or they should revert some of the settings.

**Comment by stevelle** [comment]
Made a note for docs team to capture the comment from @odyssey4me above.
This has been merged and backported, so closing.
