### ISSUE TITLE
Apparmor not loading lxc profile, causing container start failures and duplicate containers

### ISSUE THREAD

**Issue by claco** [rcbops/rpc-openstack#311]
More detail here: https://gist.github.com/nrb/a3a16d4ea3c9973deafb

TASK: [container_extra_setup | Ensure extra container config options] *********
is taking a while, and I'm seeing >50 copies of memcached's container.
Playbooks failed with the errors seen in this gist https://gist.github.com/nrb/a3a16d4ea3c9973deafb

Running ansible "hosts:is_metal" -m shell -a "apparmor_parser -Kr /etc/apparmor.d/lxc-containers && service apparmor restart" fixes this;
nodes were failing on the container_extra_setup step of memcached and rsyslog installs. Long story short,

**Comment by nrb** [comment]
Per @sigmavirus24, he followed the install guide and did not see this.

I ran setup-everything, which may have different behavior.

**Comment by mancdaz** [comment]
I have also not observed this behaviour

**Comment by nrb** [comment]
I have a feeling this is environment-dependent.

**Comment by nrb** [comment]
I haven't see this again, and it was on Juno deployments, not 11.0.0. I am closing the bug and removing priority.
