### ISSUE TITLE
irqbalance fails to restart on is_metal hosts (not installed)

### ISSUE THREAD

**Issue by claco** [rcbops/rpc-openstack#312]
NOTIFIED: [host_common | Restart irqbalance] **********************************
failed: [578126-infra01] => {"failed": true}
--- All of the metal hosts failed with this; verifying if it's a problem.

--- `ansible "hosts:is_metal" -m shell -a "apt-get install -y irqbalance"` fixes it

This maybe just be a lab/image issue. Tracking with everything else for now.

**Comment by claco** [comment]
via @sigmavirus24 

```
I'm running the playbooks the way the install guide describes and so far
so good. Looks like my lab was kicked before the new image was made so I
already had irqbalance on my hosts. I'll be walking through the install
guide and I'll see if I run into the same problems as Nolan
```

**Comment by nrb** [comment]
Will note here - I ran `setup-everything.yml`, rather than following the install guide.

**Comment by odyssey4me** [comment]
See https://bugs.launchpad.net/openstack-ansible/+bug/1482146 and https://review.openstack.org/209840

**Comment by mancdaz** [comment]
For now, this can be something added to docs? IIRC there are a bunch of other things that get installed in 'pre-flight checks'.

**Comment by claco** [comment]
Fixed as the upstream patch merged anyways. Including in the sha bump of osad in rc13. Closing.
