### ISSUE TITLE
Utility containers have incorrect IP address for repo server

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#316]
The utility containers are looking at the internal LB VIP, which is not yet configured to handle the repo, since the F5 config script wasn't run yet; it should be using an IP to one of the containers directly, at least for install. 

```
# the utility container has the load balancer's IP

root@578126-infra01_utility_container-5dae2dab:~/.pip# cat links.d/openstack_release.link
http://172.24.240.49:8181/os-releases/11.1.0/root@578126-infra01_utility_container-5dae2dab:~/.pip#

root@578126-infra01:/opt/rpc-openstack# cat /etc/openstack_deploy/openstack_user_config.yml | grep internal_lb_vip_address
  internal_lb_vip_address: 172.24.240.49
```

**Comment by nrb** [comment]
I think this bug is coming from somewhere in [this range](https://github.com/stackforge/os-ansible-deployment/blob/kilo/scripts/run-upgrade.sh#L342-L370), but have not fully investigated yet.

**Comment by nrb** [comment]
According to [the pip lock down role](https://github.com/stackforge/os-ansible-deployment/blob/kilo/playbooks/roles/pip_lock_down/defaults/main.yml#L29), we should be using `openstack_repo_url` for [this line](https://github.com/stackforge/os-ansible-deployment/blob/kilo/scripts/run-upgrade.sh#L368) in the upgrade script.

**Comment by sigmavirus24** [comment]
This should be fixed by https://review.openstack.org/#/c/210054/ https://launchpad.net/bugs/1482311

**Comment by nrb** [comment]
This has now merged to kilo. https://review.openstack.org/#/c/210054/1

**Comment by nrb** [comment]
Closing this GH bug since the upstream change merged.
