### ISSUE TITLE
Repo containers don't have more than 1 level of directories 

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#317]
The repo containers appear to be missing their contents; the only directory structure is 1 level deep. See https://gist.github.com/nrb/d6142c104677c09683f1#file-03-repo-contents-bash

Re-running setup-infrastructure did not change either of the containers.

**Comment by nrb** [comment]
Running `repo-build.yml` fails, too. https://gist.github.com/nrb/d6142c104677c09683f1#file-05-repo-build-error-bash

It appears only infra03's repo server is being used in this install, too.

**Comment by odyssey4me** [comment]
I have seen cases where the sync between containers doesn't happen. Essentially the service that runs it starts, fails and nothing ever checks on it again so you end up with one repo container with the goods on it, and two empty repo containers. Verify whether the contents are missing from all containers and go from there.

**Comment by prometheanfire** [comment]
I'm curious if #316 fixes this.

**Comment by claco** [comment]
As we haven't seen this since our dupe ip fix, I'm going to lower the priority. If we don't see it again through release, we can close it.

**Comment by rackertom** [comment]
@claco @prometheanfire @nrb @odyssey4me I'm guessing at this point we can close this? Hasn't had attention in two months, so I'm guessing it's either not happening anymore or isn't a prio-2 + expedite.

**Comment by prometheanfire** [comment]
I say close, feel free to reopen
