### ISSUE TITLE
if an upgrade fails part way through, we need to be clear about what is left to do

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#324]
the ```run-upgrade.sh``` script from osad does a decent job of saying what's left to run, if it fails part way through.  

However, because ```run-upgrade.sh``` is actually being called from within  ```upgrade.sh```, there's also stuff from ```upgrade.sh``` that needs to be finished off - that is, re-running ```deploy.sh``` without deploying osad again, so that we update all the support/backup/maas stuff too)

**Comment by d34dh0r53** [comment]
@claco @mancdaz Can this be closed?

**Comment by mancdaz** [comment]
@d34dh0r53 I'm not sure. Did we add anything to our upgrade.sh to fix this? Seems like the last 2 attempts were abandoned.

**Comment by mancdaz** [comment]
@d34dh0r53 I don't think this issue is fixed is it?

**Comment by odyssey4me** [comment]
The OSA review that relates to this (I think) was recently abandoned by @nrb - https://review.openstack.org/237689 - if this functionality is desired then it should be easy enough to restore, rebase and update. I would suggest that perhaps now that the new upgrade script is the QE'd method that the old one should be removed.

**Comment by nrb** [comment]
No, it's not - should I reopen that upstream patch, but only target it for the current process?

**Comment by mancdaz** [comment]
That upstream patch relates to failures in the osa playbooks. This issue
was raised because we don't have anything in the rpc-openstack
deploy/upgrade scripts that accounts for failures outside the osa upgrade
script

**Comment by nrb** [comment]
Ah, yeah, good point.

I think we need both.

**Comment by nrb** [comment]
Does this need to be backported to Kilo, since we're looking at Liberty work now?

**Comment by mancdaz** [comment]
@nrb I'd consider it a bug (i.e. not a feature, because kilo is now stable), and given that near enough nobody has yet been through the juno -> kilo upgrade, it would be worth having in kilo

**Comment by mancdaz** [comment]
@d34dh0r53 I'd suggest this is made a medium/high priority targeted at 11.1.3 - fixed in master and backported to kilo, of course

**Comment by stevelle** [comment]
This looks like it should be closed one way or another since the upstream change was abandoned and Juno->Kilo upgrades are running individual operations.

**Comment by b3rnard0** [comment]
@d34dh0r53 Sounds like this should be closed.

**Comment by git-harry** [comment]
Closing this issue, clearly it doesn't need expediting. For Liberty to Mitaka deployments the upgrade script will be replaced.
