### ISSUE TITLE
after upgrades, some maas checks have old names

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#326]
in kilo, the nova_spice container is renamed to nova_console. After an upgrade, we have 2 issues.  Some checks that are pointing at a non-existent container, and some checks that are newly created at the new nova_console container, but are named after the old container:

remaining checks after an upgrade, for a container that no longer exists:

```
nova_consoleauth_check--heat-node1_nova_spice_console_container-3dd09091
nova_spice_console_check--heat-node1_nova_spice_console_container-3dd09091
```

And I had 2 new checks that were now pointing at the new nova_console container:

```
nova_consoleauth_check--heat-node1_nova_console_container-b14bb7aa
nova_spice_console_check--heat-node1_nova_console_container-b14bb7aa
```

We need to add a doc step somewhere (or something else?) to delete those old checks. But I wonder, do we want to rename the nova-spice-console-check to nova-console-check

**Comment by prometheanfire** [comment]
iirc, the expectation is that maas checks are removed as part of the upgrade so that they can be created from scratch.  If that is the case then this bug can be closed.

**Comment by claco** [comment]
@prometheanfire expectation by whom? Not sure we spell it out in the docs that the deployer needs to delete those. Do we automate the delete as part of the upgrade? Can you sift through the docs w/ a docs person to see if we mention this as part of the 11.0 upgrade docs?

**Comment by prometheanfire** [comment]
the memory comes from talking with support a couple of months ago about monitoring.  could easily be wrong.

**Comment by claco** [comment]
easy to verify. please reach out to them and find out. :-)

**Comment by mancdaz** [comment]
Deleting the checks that are now against a non existent container is easy.
Deleting the others that are created with the wrong name won't help,
because they will be recreated again with the wrong name. The ansible that
creates the checks needs to be updated.

**Comment by prometheanfire** [comment]
ah, also, support doesn't delete checks between upgrades

**Comment by claco** [comment]
@mancdaz @prometheanfire 

So for me, this means:

```
# add docs release notes to delete
nova_consoleauth_check--heat-node1_nova_spice_console_container-3dd09091
nova_spice_console_check--heat-node1_nova_spice_console_container-3dd09091
```

Because the idea is that they're pluggable in the future, we should make the sec one one generic like the first:

```
nova_consoleauth_check--heat-node1_nova_console_container-b14bb7aa
nova_console_check--heat-node1_nova_console_container-b14bb7aa
```

The first half being a higher priority at the moment.

**Comment by prometheanfire** [comment]
sure, so that means this is a doc-only bug?

**Comment by mancdaz** [comment]
No. The ansible needs to change to update the name of the check

**Comment by prometheanfire** [comment]
is this not generic enough? `nova_console_check--heat-node1_nova_console_container-b14bb7aa`

**Comment by mancdaz** [comment]
Yes, once the check has been renamed to that, it will be. That's the second
part of the work that @claco was talking about

**Comment by prometheanfire** [comment]
then what was it's name before? I'm confused...  this combining of issues is not good

**Comment by stevelle** [comment]
before there were checks related to '...nova_spice_console_container...'
they should be changed to '...nova_console_container...' in kilo.

**Comment by stevelle** [comment]
This does not include a change to the 'nova_spice_api_local_status' Alarm.
Does this seem like a good opportunity to fix that as well?

**Comment by claco** [comment]
@stevelle @prometheanfire @mancdaz This is a good question. Maybe we're going too far down the rabbit hole here? I would think that the metric name is absolutely correct since it's spice. Maybe that means the check is correct with spice, and the check is correct?

If OSAD allowed pluggable consoles, beit it with a generic container name, maybe the maas playbook should name checks and alarms based on that toggle? In which case, maybe the current check name is right?

**Comment by claco** [comment]
In other words, if OSAD is installed using spice, the metric would be nova_spice_api_local_status, the check would be nova_spice_console_check, etc

If OSAD were to add support for novnc, the metric could be nova_novnc_api_local_status, and the check could be nova_novnc_console_check.

If we don't like that, then I would say that the check, the alarm, AND the metric should be made generic as well. Turtles.

**Comment by prometheanfire** [comment]
and the name (at least for now) doesn't mean upgrades fail.  Even the leftover checks don't mean that.

**Comment by mancdaz** [comment]
Yep you're all right. The check/alarm name is correct as it's spice
specific. The container name is generic, and if we change the console
technology inside it we'd need to change the check/alarm name at that
point.

**Comment by prometheanfire** [comment]
so....

the change was merged into master,`nova_spice_console_check` is now `nova_console_check`.

@mancdaz are you saying that we should not have done this, instead we should leave the check name specific?

**Comment by claco** [comment]
@prometheanfire For now, let's revert that patch out of master. As we've already covered the doc part, we should be good for now.

**Comment by claco** [comment]
Closing for now as problem is primary issue is documented. We can revisit the name issue again if we find we don't agree again.
