### ISSUE TITLE
Monitoring user not switched correctly during upgrades

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#335]
When doing an actual upgrade, we found that the haproxy user is still used, but is deleted before being replaced. The `monitoring` user  added in #209 is not created until after the upgrade is done.

However, this means that the user doing the monitoring disappears, and the F5 marks the pools as down.

We need to 1) add the new monitoring user 2) change the monitor to use the monitoring user prior to upgrade 3) upgrade.

**Comment by nrb** [comment]
Adding QE, since our update documentation should mention this ordering.

**Comment by robb-romans** [comment]
@nrb I don't know, but will look into it. Can you be a little more specific about what you want us to mention? Are you wanting a documentation workaround, or are you fixing the issue programmatically? Thanks.

**Comment by nrb** [comment]
haproxy is moved: https://review.openstack.org/#/c/199625/
Updating the F5: https://github.com/rcbops/rpc-openstack/pull/245

**Comment by claco** [comment]
From James:

```
I recommend the following:

1. Add the ‘monitoring’ user to all pre-v11 Galera installs
2. Change the monitor from using the ‘haproxy’ user to the ‘monitoring’ user (during maintenance window, perhaps)
3. Upgrade from v10 to v11
4. …
5. Profit!
```

**Comment by prometheanfire** [comment]
1. Disable checks or change checks to tcp half open
    2. Run upgrade
    3. Make sure checks are re-enabled
    4. ???
    5. Profit

**Comment by rackertom** [comment]
A :+1: to @prometheanfire comment

**Comment by claco** [comment]
Make sure checks are re-enabled after the F5 config is updated with the kilo changes :-)

**Comment by prometheanfire** [comment]
@claco that's step 3 :P

**Comment by prometheanfire** [comment]
ok, sounds good, making doc bug

**Comment by mancdaz** [comment]
Surely during an upgrade maintenance window all alerts will be suppressed by support anyway? Does it matter if the f5 reports services as down during this window? Things will be going up and down all over the place during the upgrade run anyway.

**Comment by mancdaz** [comment]
ah ok, I see now, the upgrade will fail part way through as a lot of the actions can't be performed against a VIP with no services that are 'up'

**Comment by mancdaz** [comment]
I think somewhere along the line we decided that actually just overriding the monitoring user name back to the juno default, rather than messing about with f5 changes, would be the cleaner way to complete an upgrade.

**Comment by prometheanfire** [comment]
https://i.imgur.com/Eah37Jg.jpg

**Comment by mancdaz** [comment]
@andymcc is working on a proposed change to account for this

**Comment by andymcc** [comment]
I've put the following PR into openstack-ansible https://review.openstack.org/#/c/228983/

The problem is that the user is removed and changed before it exists in mysql - which means the galera VIP dies until the galera play runs (adding the new user in) - meaning the OpenStack cluster is unusable from the time the haproxy play runs and the galera play runs (which can be quite lengthy).

I toyed with just adding the var for galera_monitoring_user: haproxy to user_variables, but the haproxy play has already run by the time we clean up the user, so I'd rather we add the mysql monitoring user just before running the galera play so that the vip continues to function.

**Comment by d34dh0r53** [comment]
We are going to handle this via docs.

**Comment by prometheanfire** [comment]
specifically to define the old user in user_extra so that tcp half open isn't needed

**Comment by d34dh0r53** [comment]
It looks ilke the docs issue has merged, does anything else need to happen with this one? ping @prometheanfire @mancdaz @andymcc @nrb @rackertom

**Comment by andymcc** [comment]
@d34dh0r53 I think we're good to close this if the docs have merged. There isn't a clean way around it aside from the docs change and I think that adequately addresses this (in my opinion at least).

**Comment by nrb** [comment]
Agreed with Dave and Andy, I'm closing.

**Comment by b3rnard0** [comment]
@klevenstein @robb-romans I'm adding you for documentation awareness.

**Comment by andymcc** [comment]
I think we have already doc'd this in the upgrade guide.
