### ISSUE TITLE
repository missing on bare metal. it will stop the swift installation.

### ISSUE THREAD

**Issue by weezer** [rcbops/rpc-openstack#338]
# # Major bug fix updates produced after the final release of the
 # # distribution.
deb http://mirror.rackspace.com/ubuntu/ trusty main restricted
deb-src http://mirror.rackspace.com/ubuntu/ trusty main restricted
deb http://mirror.rackspace.com/ubuntu/ trusty-updates main restricted
deb-src http://mirror.rackspace.com/ubuntu/ trusty-updates main restricted

 # # N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
 # # team. Also, please note that software in universe WILL NOT receive any
 # # review or updates from the Ubuntu security team.
deb http://mirror.rackspace.com/ubuntu/ trusty universe
deb-src http://mirror.rackspace.com/ubuntu/ trusty universe
deb http://mirror.rackspace.com/ubuntu/ trusty-updates universe
deb-src http://mirror.rackspace.com/ubuntu/ trusty-updates universe

 # # N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
 # # team, and may not be under a free licence. Please satisfy yourself as to
 # # your rights to use the software. Also, please note that software in
 # # multiverse WILL NOT receive any review or updates from the Ubuntu
 # # security team.
deb http://mirror.rackspace.com/ubuntu/ trusty multiverse
deb-src http://mirror.rackspace.com/ubuntu/ trusty multiverse
deb http://mirror.rackspace.com/ubuntu/ trusty-updates multiverse
deb-src http://mirror.rackspace.com/ubuntu/ trusty-updates multiverse

 # # N.B. software from this repository may not have been tested as
 # # extensively as that contained in the main release, although it includes
 # # newer versions of some applications which may provide useful features.
 # # Also, please note that software in backports WILL NOT receive any review
 # # or updates from the Ubuntu security team.
 # deb http://mirror.rackspace.com/ubuntu/ trusty-backports main restricted universe multiverse
 # deb-src http://mirror.rackspace.com/ubuntu/ trusty-backports main restricted universe multiverse

deb http://mirror.rackspace.com/ubuntu trusty-security main restricted
deb-src http://mirror.rackspace.com/ubuntu trusty-security main restricted
deb http://mirror.rackspace.com/ubuntu trusty-security universe
deb-src http://mirror.rackspace.com/ubuntu trusty-security universe
deb http://mirror.rackspace.com/ubuntu trusty-security multiverse
deb-src http://mirror.rackspace.com/ubuntu trusty-security multiverse

 # # Uncomment the following two lines to add software from Canonical's
 # # 'partner' repository.
 # # This software is not part of Ubuntu, but is offered by Canonical and the
 # # respective vendors as a service to Ubuntu users.
 # deb http://archive.canonical.com/ubuntu trusty partner
 # deb-src http://archive.canonical.com/ubuntu trusty partner

 # # Uncomment the following two lines to add software from Ubuntu's
 # # 'extras' repository.
 # # This software is not part of Ubuntu, but is offered by third-party
 # # developers who want to ship their latest software.
 # deb http://extras.ubuntu.com/ubuntu trusty main
 # deb-src http://extras.ubuntu.com/ubuntu trusty main
 #we need the deb https://mirror.rackspace.com/ubuntu trusty-backports main restricted universe multiverse to install the liberasurecode1,liberasurecode-dev,

**Comment by claco** [comment]
For bare metal servers (Swift Object Servers), it is left up to the deployer to manage the apt configurations. In this case, the trusty-backports was commented out, but is normally enabled by default in 14.04.

This normally would go un noticed, but now can cause Swift installation (and upgrades) in 11.0 to fail as liberasurecode1 et al are in backports.

We need to document that this repo is required as part of an 11.0 Swift installation.

**Comment by erikmwilson** [comment]
How does this sound for a release note know issue?
Trusty-backports repository required to install or upgrade Object Storage (swift)
For bare metal servers (swift object servers), the trusty-backports repository has been commented out. This repository is required to install or upgrade Object Storage as liberasurecode1 et al are contained in the repository. 
What are the steps to fix this?
Do we want to list what is in the backports?

**Comment by claco** [comment]
"For bare metal servers (swift object servers), the trusty-backports repository has been commented out. "

In this case, this is a discrepancy with our lab/image. The if it enabled by default in 14.04 proper, so maybe just mentioning it is require is enough. I would hope for most host server, that is the case.

I'm not sure we need to go in depth on how to fix it. If you're installing OSAD and can't enable a repo, you have bigger problems. But not mentioning the requirement at all is a problem.
