### ISSUE TITLE
Repo Build vs. Repo Sync - Deployment steps differ between OSAD and RPC

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/rpc-openstack#343]
What is the expected repo population behavior for production deployments?

OSAD run-playbooks.sh builds the repo from scratch at runtime.
RPC deploy.sh rsyncs from rpc-repo.rackspace.com at runtime.

From a comment in run-playbooks.sh, the latter seems to be the expected behavior:

```
# For the purposes of gating the repository of python wheels are built within
# the environment. Normal installation would simply clone the upstream mirror.
```

This all seems related to https://github.com/rcbops/rpc-openstack/issues/339#issuecomment-130902052

**Comment by nrb** [comment]
run-playbooks is *not* a supported production method; use the setup-infrastructure plays themselves.

**Comment by nrb** [comment]
Cloning is being removed, too - https://blueprints.launchpad.net/openstack-ansible/+spec/remove-upstream-repo-dependency

**Comment by byronmccollum** [comment]
@nrb This is the point I'm trying to get across. Gate and QE use `run-playbooks.sh`, but the docs say to use `deploy.sh`. They behave differently. You are saying don't use `run-playbooks.sh`, but that is precisely what is being tested.

If cloning shouldn't be used and is planned for removal, then the path `deploy.sh` takes needs to be updated (or more precisely, `repo-install.yml`).

### deploy.sh
```
setup-infrastructure.yml
    repo-install.yml
        repo-server.yml
        repo-clone-mirror.yml
```

### run-playbooks.sh
```
repo-server.yml
repo-build.yml
```

**Comment by claco** [comment]
@jacobwagner @tbyrom138 Can you clarify what your gate runs for r11? (run-playbooks or deploy.sh)

**Comment by jacobwagner** [comment]
@claco @byronmccollum 

It depends on what we are testing
https://github.com/rcbops/jenkins-rpc/blob/master/scripts/multinode.sh#L175-L198

for rpc-openstack we run the deploy.sh script
for openstack-ansible we directly run the run-playbooks script

**Comment by d34dh0r53** [comment]
This is probably best solved by adding a sync vs. build flag in openstack-ansible.

**Comment by odyssey4me** [comment]
The reason that OSA gate checks using the 'build' is that a commit may contain a SHA update or requirements changes on any commit. Once a tag is released, no requirements or SHA's change - so QE testing and production deployments should actually use 'sync' option for Kilo to ensure that every deployment maintains its static set of wheels.

**Comment by odyssey4me** [comment]
For Liberty onwards, sync is not an option and both RPC and OSA are using build as the default option. This produces consistent results thanks to OpenStack's upper-constraints file and the way the repo build is done. The only inconsistencies that can be found would be based on files that are not in upper-constraints and it is therefore advisable that any files outside of this are fixed per tag (in requirements.txt or something similar). In OSA we've implemented a per tag requirements update in the sources-branch-updater for pip, setuptools and wheel and we're likely to extend this to other wheels that are outside of upper-constraints to ensure that builds are consistent.

**Comment by git-harry** [comment]
As far as I can tell, it looks like this issue was raised to ask a question and there has been some discussion which appears to have answered it. Based on that I will close the issue.
