### ISSUE TITLE
Holland backup needs to backup localhost

### ISSUE THREAD

**Issue by claco** [rcbops/rpc-openstack#348]
Note: This is the Kilo+ location for this bug report. For Juno, see: https://bugs.launchpad.net/openstack-ansible/+bug/1479486

The current template for roles/rpc_support_holland/templates/holland-xtrabackup.conf.j2 has the host set to {{ internal_vip_address }}. This can cause issue if it is routed to a remote node from where holland is ran. The host should be set to localhost so we do not backup a remote node.

i.e. set host = 127.0.0.1 in /etc/holland/backupsets/rpc_support.conf

- [ ] Reproduce the issue. (N/A)
- [ ] Create a PR for fix and/or docs.
- [ ] Incorporate feedback from pull request reviews.
- [ ]  What is the gating for this on DEV and/or QE? Add related gating if appropriate. Also make sure current gating passes with this fix.
- [ ] Reach out to reporter to determine if the fix is resolving the issue.
- [ ] What are the upgrade impacts (if any).
- [ ] What are the backports are needed (if any).

**Comment by claco** [comment]
Needs more conversation at the next triage. Might not be a problem any more now that log_slave_updates is enabled?

**Comment by BjoernT** [comment]
So we either close https://github.com/rcbops/rpc-openstack/issues/716 or this one but it is still an issue

**Comment by BjoernT** [comment]
Still valid issue since the closed 716

**Comment by mancdaz** [comment]
apologies, I missed the impacts-onboarding label.

**Comment by mancdaz** [comment]
Why closed @b3rnard0?

**Comment by claco** [comment]
I think we thought it was fixed with the resent 11.x release w/ the holland fix. Bad title/description on the tracker card.

**Comment by b3rnard0** [comment]
@mancdaz Yeah basically it's @claco's fault.

**Comment by claco** [comment]
You're Welcome

**Comment by git-harry** [comment]
@mancdaz does this need backporting?

**Comment by mancdaz** [comment]
@git-harry yes, I was leaving it to the onboarding team once it was pointed out I'd grabbed one of their issues

**Comment by ameserole** [comment]
Submitted backports with pull request #1233 (12.2) and #1234 (kilo)

**Comment by andymcc** [comment]
Backports merged successfully.
