### ISSUE TITLE
Move MaaS playbooks out of upgrade process

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#355]
The MaaS checks likely need manual intervention, and thus should be moved out of the automated upgrade script process.

**Comment by nrb** [comment]
This can be address by a post-upgrade doc step.

**Comment by nrb** [comment]
@robb-romans This will require us to upgrade our post-upgrade docs.

**Comment by robb-romans** [comment]
@nrb ok sure let us know the doc bug

**Comment by mancdaz** [comment]
What specifically was the issue being seen here?  The only manual intervention I was aware of post upgrade was the need to remove a couple of old checks targeted at the no longer existing spice_console container.  That was addressed here:

https://github.com/rpcdocs/rpcdocs/issues/193

I'm not too bothered if the running of the new maas playbooks happens automatically inside or manually outside the script.  Just wondering if there were any other actual issues with maas post-upgrade other than the ones we've already seen?

**Comment by nrb** [comment]
@BjoernT Can you please answer @mancdaz's question in terms of the concerns? This is largely to facilitate support's request.

I will say we saw duplicated checks when running this on our most recent lab, which the playbooks do not handle at all - the grep lines will need to be revisited. I'm not sure if there's a way for us to validate which of the checks was the correct one right now.

**Comment by nrb** [comment]
Re-opening for backport.
