### ISSUE TITLE
MaaS playbooks fail on duplicate entities

### ISSUE THREAD

**Issue by sigmavirus24** [rcbops/rpc-openstack#357]
When MaaS has duplicate entries for an entity, the parsing in the playbooks can fail which causes the playbooks to fail and be unusable. I'm not sure how this should look exactly, but this is something we need to fix.

@BjoernT can you fill in more detail about this (since you seem to know MaaS better than the rest of us)?

**Comment by git-harry** [comment]
The playbooks should fail on duplicate entities. There should never be duplicate entities, that is to say entities with the same label, if there are that needs investigating and cleaning up before running the maas playbook.

**Comment by nrb** [comment]
Agreed with @git-harry, we did however see duplicate checks (not entities, but a specific disk space check).

**Comment by claco** [comment]
Halting with an error is the desired outcome for this problem as it should be rare and requires MaaS intervention upstream.
