### ISSUE TITLE
Disable input prompt during upgrade

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#360]
Right now, our `upgrade.sh` script does some pre-setup, then runs OSAD's `run-upgrade.sh`. This has a side-effect of appearing to do work, then stopping 'in the middle' to look for input.

We should probably silence the input prompt when running `run-upgrade.sh`.

**Comment by claco** [comment]
Backport: https://github.com/rcbops/rpc-openstack/pull/363

**Comment by d34dh0r53** [comment]
Closing as all PRs have merged.
