### ISSUE TITLE
Remove virtual disks from maas disk utilisation check

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#38]
With the recent implementation to iterate over all SCSI devices to install maas utilisation alarms, we introduced a new error. This maas  disk utilisation does now include cinder attached volumes if you run those playbooks after a system has been handed over. We basically need to amend this logic to exclude all disks with the model "VIRTUAL-DISK"

**Comment by BjoernT** [comment]
The playbook maas_local.yml is affected from this issue

**Comment by andymcc** [comment]
backport is here https://review.openstack.org/#/c/255833/

**Comment by d34dh0r53** [comment]
Can we retarget the backport for the `kilo` branch?

**Comment by nrb** [comment]
@d34dh0r53 The backport was already done via https://github.com/rcbops/rpc-openstack/pull/718

**Comment by prometheanfire** [comment]
ok, closing
