### ISSUE TITLE
lxc-container-config-lp-bug-1487130 patch causes container ssh timeouts during upgrade

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/rpc-openstack#385]
There have been consistent failures for ssh connections to containers in the openstack-ansible gate checks since the merge of https://review.openstack.org/216301.

The issue is caused directly by the above change - the apparmor profile is changed in the playbook pre task but the playbook does not wait for the container to be accessible via ssh before continuing.

The review to resolve this: https://review.openstack.org/218572
This is also registered as a critical upstream bug: https://bugs.launchpad.net/openstack-ansible/+bug/1490142

**Comment by claco** [comment]
Closing. All upstream references merged.
