### ISSUE TITLE
Update OSAD/OA SHA and remove patches

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#386]
rc14 and rc15 are carrying some OSAD patches and a pinned SHA that is fairly far behind upstream Kilo.

This issue will un-pin it and move us forward for testing the latest patches.

**Comment by miguelgrinberg** [comment]
I deployed this patch in an AIO without any problems. :+1:

**Comment by claco** [comment]
While we should just keep on merging kilo so it's consistent, we might want to rebump this week when this makes it: https://review.openstack.org/#/c/218572/

**Comment by nrb** [comment]
Yeah, I agree. For what it's worth, the relevant kilo patch is here: https://review.openstack.org/#/c/217014/.

Also, once that merges openstack-ansible will be cutting 11.2, which would be a good time to pin.

**Comment by mancdaz** [comment]
11.2.1 was a fast follow tag to fix a mistake in 11.2 in osad.  I'm going to bump the sha to 11.2.1, and use this issue as a reference.
