### ISSUE TITLE
f5-config.py --ssl-public-ip

### ISSUE THREAD

**Issue by Mudpuppy12** [rcbops/rpc-openstack#395]
The f5-config.py script has a switch called --ssl-public-ip. This information can be gathered from the openstack_inventory.json file as external_lb_vip_address.

This seems like a redundant switch. Since we do not provide a --option for internal_lb_vip_address, I think this can be removed and refer to what is in the json inventory.

**Comment by d34dh0r53** [comment]
Would it be better to remove this or add an option for `--internal_lb_vip_address`?

**Comment by BjoernT** [comment]
I don't know why this would be an issue if we leave the option available. Sometimes we do have a different remote IP for the F5 then used inside the external_lb_vip_address
