### ISSUE TITLE
update-yaml  does silently revert base changes

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#402]
Changes made inside the base yml file like
nova_cross_az_attach: true
are silently reverted to rpc-openstack defaults (nova_cross_az_attach: false for example)

Additionally it did add a newline at the glance_swift_store_user when using the a string like : 
'{{ rackspace_cloud_tenant_id }}:{{ rackspace_cloud_username }}'

Ideally the update-yaml script would retain existing settings and add only new parameters

Additionally the base file should be saved prior to changes

**Comment by claco** [comment]
Let's have a discussion about this at the next bug triage meeting.

**Comment by d34dh0r53** [comment]
We need to update the `update-yaml` script to prioritize the `user_variables.yml`

**Comment by claco** [comment]
extras overrides user by design (for rpc customization of osa). this might be a 'dupe key check' situations instead to warn that you're going to get something other than what you expected.

**Comment by git-harry** [comment]
I'm not entirely sure what the bug is here, there are no steps to reproduce what was seen.

**Comment by BjoernT** [comment]
We can close it, I was not able to reproduce it
