### ISSUE TITLE
Add purestorage pip wheel to yaprt report

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#406]
Alternatively please show us a way how we are able to include custom, customer driven cinder libraries for example, into a RPC release.
The purestorage driver is used as cinder api bridge to provision iscsi storage for the Pure FlashArray

**Comment by claco** [comment]
Can we get more detail around this? What are the errors seen, etc?

**Comment by BjoernT** [comment]
There are no errors. I only build the pip package manually and put it on the server. This is a generic request where we need to include 3rd party libraries in the future next to OSA.
If we can't include libraries because of license issues etc, then we need to document a process how to side load these in rpcd

**Comment by git-harry** [comment]
@claco @mancdaz Is there a formal policy on using backends? This request raises questions in terms of testing and validation that it would be good to clarify before addressing any potential change to the code.

**Comment by BjoernT** [comment]
I talked with Charles internally and we might even want to go that route to build all cinder and neutron plugins and include them. But and that's the important part, we are not responsible to the functionality of those plugins unless tested like EMC for example. Because we have already customers using HP lefthand, solidfire etc etc

**Comment by git-harry** [comment]
Currently as far as I can tell, to add an additional package, the appropriate variable needs overriding so the package is installed and a requirements file needs creating in the playbooks directory so that the repo containers get the package. I've logged a bug upstream to look at making this simpler to manage

[1]  - https://bugs.launchpad.net/openstack-ansible/+bug/1510575

**Comment by d34dh0r53** [comment]
This has been fixed upstream in `liberty` do we need to backport this to `kilo`?

**Comment by BjoernT** [comment]
I think we need it in kilo but currently I'm not aware how fast we can get the customers to liberty.
This particular is already on kilo

**Comment by BjoernT** [comment]
Closing, just tested https://review.openstack.org/#/c/252956/1/doc/source/developer-docs/extending.rst and it seem to work fine. I don't need this in Kilo anymore so we are good here
