### ISSUE TITLE
maas/plugins/README.md needs to be cleaned up

### ISSUE THREAD

**Issue by mattt416** [rcbops/rpc-openstack#429]
I originally wanted to document ceph_monitoring.py in maas/plugins/README.md, which is why this card was created.  In the process of updating maas/plugins/README.md, I made a bunch of minor formatting changes.  The ceph_monitoring.py changes ended up being yanked into https://github.com/rcbops/rpc-openstack/pull/380 so this card will remain open just to track the PR where maas/plugins/README.md gets cleaned up.

**Comment by git-harry** [comment]
@d34dh0r53 it's only formatting but it should be applicable. I'm not sure what the current policy is regarding backports to juno as to whether or not it should go in.

**Comment by mattt416** [comment]
@d34dh0r53 I personally wouldn't backport it to juno
