### ISSUE TITLE
ceph_monitoring.py updates

### ISSUE THREAD

**Issue by mattt416** [rcbops/rpc-openstack#432]
In the short term, we should make the following changes:

`--type` isn't marked as required, but the script fails to run if you don't specify it

`--osd_ids` says comma-separated, but needs to be space-separated and should indicate that this needs to be specified when `--type osd`

`--host` help information is not helpful, should indicate that this is a MON hostname and required `--type mon`

In the long, it'd be better to change `--type` to a positional argument and then have different subparsers for each type.  This would allow us to make `--osd_ids` required when we specify `osd` as the positional argument, `--host` required when `mon` is the positional argument, etc.

**Comment by mattt416** [comment]
Hi @git-harry , just close this off once you incorporate the minor changes into https://github.com/rcbops/rpc-openstack/pull/380.  Thanks!

**Comment by git-harry** [comment]
@mattt416 are  you able to test this?

**Comment by git-harry** [comment]
Addressed by #380
