### ISSUE TITLE
need to bump osa sha to 11.2.3

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#438]
This osa tag includes a lot of fixes for upgrade related issues.

**Comment by d34dh0r53** [comment]
So http://git.openstack.org/cgit/openstack/openstack-ansible/commit/?id=1d5c7f637f1519701b8232ef1f5d03b03320e8d6 didn't make it into 11.2.3 so ceph currently fails.

**Comment by d34dh0r53** [comment]
Other than this the build seems fine.

**Comment by claco** [comment]
@d34dh0r53 so... the hash from this PR (b473fe0b050b01d717783fd961edc1dba523906b) is above (after) the Ceph key hash (https://github.com/openstack/openstack-ansible/commits/kilo)  ?

**Comment by claco** [comment]
Ah I c. Github lies. Always fun.

**Comment by claco** [comment]
@prometheanfire @d34dh0r53 @mancdaz Since the driver of this change is to get a bump in for the Ceph testing that is starting, my vote is that we bump the sha to the Ceph key hash fix to keep that moving.

**Comment by prometheanfire** [comment]
ok, so change it to https://github.com/openstack/openstack-ansible/commit/85c71f24140bbf40d73eade22f4ed9ebab078ff5 ?

**Comment by d34dh0r53** [comment]
:+1: from me

**Comment by claco** [comment]
I think so. Someone will want to double check my assumption, but I think it's quite literally the next sha post 11.2.3:

```
 → git cherry -v 11.2.3 7bfbf5b42df1d11e8cb274df90206842877f47ff
+ 7bfbf5b42df1d11e8cb274df90206842877f47ff Update ceph key hash
```

**Comment by prometheanfire** [comment]
there are eight commits in between from osad upstream

https://github.com/openstack/openstack-ansible/commits/kilo

**Comment by claco** [comment]
Don't trust github. The order of things in the ui will lie. That's how we missed this hash to begin with. That's why I went with `git cherry -v rev rev` or `git log rev..rev`

**Comment by prometheanfire** [comment]
ah, good point lol, so why are we using github again?

**Comment by prometheanfire** [comment]
ya, git log / diff confirm, :+1: to update the sha

**Comment by claco** [comment]
Well, fwiw today, I don't trust myself, nor git atm. This is why I asked for another set of eyes. :-)

**Comment by prometheanfire** [comment]
sure, I'll submit another PR to update the sha in master then backport that instead of #441

**Comment by claco** [comment]
Or... `git cherry -v 7bfbf5b 11.2.3`
So you may be correct.

**Comment by claco** [comment]
https://github.com/openstack/openstack-ansible/compare/11.2.3...7bfbf5b

**Comment by prometheanfire** [comment]
just #446 and this is closable

**Comment by git-harry** [comment]
#446 is merged.
