### ISSUE TITLE
Check for empty rabbitmq channels list

### ISSUE THREAD

**Issue by rackertom** [rcbops/rpc-openstack#442]
When fetching the channels list from rabbitmq in the `rabbitmq_status.py` maas check, we can potentially fail by not checking the parsed returned json.

**Comment by rackertom** [comment]
Potential patch in pr #443

**Comment by rackertom** [comment]
Master and Kilo merged. Closing.

**Comment by stevelle** [comment]
I know that juno doesn't have plugins stored here, but clicking reopen here until we have a juno backport over in rpc-maas

**Comment by rackertom** [comment]
@stevelle Submitted https://github.com/rcbops/rpc-maas/pull/225 for rpc-maas.

**Comment by stevelle** [comment]
merged to juno
