### ISSUE TITLE
HP MaaS checks sending 3x alerts for disk check

### ISSUE THREAD

**Issue by stevelle** [rcbops/rpc-openstack#450]
Per: Mark DeVerter
first is on bad sectors,
second is on the drive being pulled,
third is when replacement is added to RAID

The duplicate tickets are messy.  They should be something we could clean up with the check script.

**Comment by stevelle** [comment]
@andymcc did I get this in right?
@BjoernT any comments?

**Comment by BjoernT** [comment]
Yes I can imagine this being an issue. As long as the alarm is not suppressed, the re-check of the MAAS check will catch a new state and generate a new ticket. I'm not sure how to prevent this issues inside MAAS, this seems more like a aric rule to suppress tickets for existing HP storage alerts.

**Comment by d34dh0r53** [comment]
The consensus is that this should be handled via ARIC an not MaaS.  MaaS is simply an alert generation service and adding correlation logic is outside of the scope of our MaaS plugins.
