### ISSUE TITLE
Add bashate linting

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#454]
Currently our linting only checks YAML and Python syntax, but some important pieces of our code are in bash. Upstream includes bashate already (see [this section](https://github.com/openstack/openstack-ansible/blob/master/tox.ini#L46-L58)), so this repo could probably mostly mirror that.

- [x] master

**Comment by ameserole** [comment]
@nrb What errors should be excluded during the linting? Currently the OSA implementation excludes E003 - Indent not multiple of 4
E006 - Line longer than 79 chars
E040 - Syntax errors reported by bash -n.

The other options are [here](http://docs.openstack.org/developer/bashate/readme.html )

**Comment by nrb** [comment]
@ameserole I would say matching OSA's bashate exclusions would be fine.

**Comment by ameserole** [comment]
@git-harry when we ran the bashate linting test we noticed that some of the the scripts failed. Would it be best to do two pull requests and the first one be the bashate linting fixes and then the second one be adding bashate linting or just do it all in one pull request?

**Comment by git-harry** [comment]
@ameserole my suggestion would be to add the linting and exclude any tests that are currently failing. Then create one or more separate pull requests to address the tests that were excluded. This should reduce the likelihood of you getting into a race with other patches.

**Comment by cloader89** [comment]
👍

**Comment by git-harry** [comment]
@alextricity25 issues should have a checklist of the branches to fix. Please be sure to complete it as code is merged and make verify all the work is done before closing the issue.

**Comment by alextricity25** [comment]
@git-harry Will do. Sorry about that. I honestly didn't feel like this needs a backport, but nonetheless it would be a good exercise for @ameserole.

**Comment by git-harry** [comment]
@alextricity25 I was not saying it had to be backported, simply that the description box is used to help track the work and so needs to correctly represent the state of things. I think it's perfectly reasonable not to backport the code, Liberty is supposed to be stable and this change is not functional, but in that case liberty (that's not actually a valid branch name) should be removed from the list and master checked.
