### ISSUE TITLE
maas_common attempts to log to /var/log/ always

### ISSUE THREAD

**Issue by sigmavirus24** [rcbops/rpc-openstack#466]
Logging should be optional and perhaps encapsulated in a function to allow the user to parameterize the path and whether logging is enabled or not.

*Note*: This is for RHEL compatibility when running as a non-root user.

**Comment by d34dh0r53** [comment]
@sigmavirus24 can we get more insight into whether or not this is a bug or an enhancement?  Does this break logging on RHEL OSP?
