### ISSUE TITLE
Add bash completion to openstack clients

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#469]

**Comment by sigmavirus24** [comment]
Why isn't this filed against OSA? This is a valid bug there too.

**Comment by git-harry** [comment]
@sigmavirus24 https://bugs.launchpad.net/openstack-ansible/+bug/1465723

**Comment by prometheanfire** [comment]
fixed in #483

**Comment by d34dh0r53** [comment]
Both have merged
