### ISSUE TITLE
Numerous references to github.com/rcbops/rcbops-extras

### ISSUE THREAD

**Issue by stevelle** [rcbops/rpc-openstack#473]
There are numerous references to an old repo name, particularly in files such as CONTRIBUTING.rst within each role.

These should be cleaned up.

**Comment by stevelle** [comment]
No juno backport needed.  The lingering references were in files that didn't exist in this repo during juno

**Comment by rackertom** [comment]
Awesome. :+1: I'm going to mark this closed.
