### ISSUE TITLE
nf_conntrack_ftp needed on computes to use active ftp with instances

### ISSUE THREAD

**Issue by h1pp13p373** [rcbops/rpc-openstack#475]
When trying to use ftp (ie to kernel.org) from an instance, active will fail on the return path if nf_conntrack_ftp is not loaded on the hypervisor due to the nature of active's port assignments.  After loading the module, active ftp worked.

This specific incident was on version 10.1.8, but I suspect others as well.

**Comment by d34dh0r53** [comment]
Hey Pete, this looks like a OSA bug rather than an RPC specific bug, can you please file this against openstack-ansible on Launchpad?

**Comment by h1pp13p373** [comment]
Suuuupppp Dave!

Will do man, thanks.

hippie




On 10/13/2015 10:04 AM, Dave Wilde wrote:
> Hey Pete, this looks like a OSA bug rather than an RPC specific bug, can
> you please file this against openstack-ansible on Launchpad?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rcbops/rpc-openstack/issues/475#issuecomment-147743065>.
>

-- 
Pete Smith
Openstack Engineer
Rackspace - the #1 managed cloud company
toll free: 1-888-480-7640
