### ISSUE TITLE
Lowering max_retries from 5 to 2 to catch build errors faster

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#485]
RPC-openstack utilizes the install_bits function from OSA which is a wrapper around successerator and by default it uses a MAX_RETRIES parameter of 5. 
I'm asking rpc-openstack to fail more early in case repeating errors occur. It has been our experience if playbooks fail more than one, there's usually a issue we have to take care off. There is then no need to wait for 3 more failures before we even get a chance to fix and rerun the playbooks again.

**Comment by BjoernT** [comment]
Pull requests see https://github.com/rcbops/rpc-openstack/pull/480 and  https://github.com/rcbops/rpc-openstack/pull/481

**Comment by d34dh0r53** [comment]
Thanks @BjoernT!

**Comment by rackertom** [comment]
Given the comments in #480 and #481 it seems the intent was never to actually use `scripts-library.sh` in the deploy.sh script, and probably not in any other script in the rpc-openstack repo.

If @git-harry @BjoernT @odyssey4me agree that we should remove `scripts-library.sh` from the `deploy.sh` script, I have a patch I can easily submit for review. This would remove the use of `install_bits` which in turn would also remove the use of `successerator`. This does mean that there would be no automatic retry during a `deploy.sh` run, but it seems like in our case this is actually preferable.

**Comment by BjoernT** [comment]
Yes this is alright by me.

**Comment by git-harry** [comment]
I've closed pull requests #480 and #481. This issue is now pending a pull request from @rackertom

**Comment by prometheanfire** [comment]
just needs backport now
