### ISSUE TITLE
upgrades missing https://github.com/openstack/openstack-ansible/commit/70656eb25bd678b541ff7e3a58a586701c79f12f

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/rpc-openstack#494]
Looks like the hash for 11.0.1 missed this commit

https://github.com/openstack/openstack-ansible/commit/70656eb25bd678b541ff7e3a58a586701c79f12f

This is needed to ensure upgrades go smoothly

**Comment by b3rnard0** [comment]
@d34dh0r53 @prometheanfire @git-harry Can we determine the priority on this one?

**Comment by prometheanfire** [comment]
No, I think the priority needs to come from support, we can update the hash and tag a new release if needed, but otherwise I'd say prio-2

**Comment by d34dh0r53** [comment]
Agree, @BjoernT any input?

**Comment by BjoernT** [comment]
Yes correct that's the change we are waiting for to improve the upgrade success rate.

**Comment by rackertom** [comment]
Issue is not closed until #509 is merged

**Comment by rackertom** [comment]
PR #509 is merged. Closing this issue.
