### ISSUE TITLE
openstack-ansible has renamed the old run-upgrade script to run-upgrade-old.sh

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#504]
In order to continue to consume the QE tested upgrade path, we should alter upgrade.sh to use run-upgrade-old.sh

**Comment by prometheanfire** [comment]
Do you have a reason for this?  why?

**Comment by mancdaz** [comment]
@prometheanfire because the RPC product should consume a tested path, and is an explicit ask from support. The new set of broken out scripts that run-upgrade.sh now points at are an untested path.

**Comment by prometheanfire** [comment]
ok, just wanted to be explicit in the bug report

**Comment by stevelle** [comment]
both merged.
