### ISSUE TITLE
Checking additional RabbitMQ metrics: fd and processes and sockets

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#516]
Currently we are not alarming on critical metrics like file descriptors or number of processes.
These are critical metrics which need to be monitored and are currently gathered by the rabbitmq_status.py script

**Comment by BjoernT** [comment]
Please ignore the first 3 commits, only #517 is valid. Looks like didn't notice that I removed those previous commits

**Comment by d34dh0r53** [comment]
:+1:

**Comment by claco** [comment]
Master merged. Is someone working backports on this yet?

**Comment by BjoernT** [comment]
Sure I can do it, the backport is actually my original pull request unless we want to convert the kilo  and juno branch as well to that new agent yaml format

**Comment by stevelle** [comment]
With the backport of template driven maas checks which @sigmavirus24 initiated (above), these new checks will be added to kilo, so hold off on that one @BjoernT.  We will need a backport of this to juno however.

**Comment by mancdaz** [comment]
The juno backport was completed https://review.openstack.org/#/c/236027/
