### ISSUE TITLE
deploy the ceph will block the heat tempalte image to get metadata from config-drive.

### ISSUE THREAD

**Issue by weezer** [rcbops/rpc-openstack#532]
from the Rpc installation document for kilo, if you want to install ceph, you have to set the

```
nova_force_config_drive: False.
```

but so far the heat solution’s image is using the config drive to fetch the metadata, so this change will make the heat template not working.

the document link is here, http://docs.rackspace.com/rpc/api/v11/bk-rpc-installation/bk-rpc-installation-20151027.pdf

```
8. Set the following variables related to OpenStack in /etc/openstack_deploy/user_variables.yml:
glance_default_store: rbd
nova_libvirt_images_rbd_pool: vms
nova_force_config_drive: False
nova_libvirtd_listen_tls: 0
nova_libvirtd_listen_tcp: 1
nova_libvirtd_auth_tcp: none
```

**Comment by weezer** [comment]
and set the nova_force_config_drive to True will block the live-migration.

**Comment by weezer** [comment]
Hi All,

I just finished the test on a kilo lab with ceph as the back-end, I can successfuly create the heat stack(means the config-drive is enable) and do the live-migration for the instance with config drive or without it, so if you set up the ceph as the backend, you should keep the nova_force_config_drive: True and add below in the user_variable.yml

nova_nova_conf_overrides:
  DEFAULT:
    config_drive_format: vfat

Add dosfstools and dosfstools-dbg to nova_compute_kvm_apt_packages at openstack-ansible/playbooks/roles/os_nova/defaults/main.yml and redeploy the os-nova-install.yml.

I think we need add it into the rpc-installation manual.

**Comment by d34dh0r53** [comment]
Closing as this is a docs issue. FYI @klevenstein @robb-romans @ionosphere80
