### ISSUE TITLE
Beaver won't start after host restart

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#564]
Beaver does not start anymore after a host has been restarted.
The reason for this is the missing /var/run/beaver directory.
Additionally beaver is not deleting the PID file after stopping.

**Comment by git-harry** [comment]
This patch should also clean up [1]; /run is a tmpfs and so it doesn't make much sense for the playbooks/roles to be creating a directory there.

[1] https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/beaver/tasks/beaver_pre_install.yml#L52

**Comment by BjoernT** [comment]
tmpfs will be cleaned up at reboot automatically

**Comment by git-harry** [comment]
Exactly, that's why I'm suggesting you remove the directory's creation from the role.

**Comment by d34dh0r53** [comment]
@BjoernT @git-harry is the merged fix appropriate for this or are there more steps needed to close this issue?

**Comment by BjoernT** [comment]
Nope we're good
