### ISSUE TITLE
Raxmon restart handler does not fire consistently on MaaS upgrade

### ISSUE THREAD

**Issue by sigmavirus24** [rcbops/rpc-openstack#571]
We noticed while running an upgrade of MaaS configuration from r11.0.0 to master we noticed that rackspace-monitoring-agent should have been restarted by a handler but wasn't. It appears we need to use `- meta: flush_handlers` in our playbooks to ensure the handlers are notified and fired appropriately.

See also: http://wherenow.org/ansible-handlers/

**Comment by sigmavirus24** [comment]
cc @stevelle

**Comment by andymcc** [comment]
Since the PR has merged for this, closing the issue out.
