### ISSUE TITLE
deploy.sh does not copy all files to /etc/openstack_deploy

### ISSUE THREAD

**Issue by d34dh0r53** [rcbops/rpc-openstack#576]
The `deploy.sh` script will not copy all files to `/etc/openstack_deploy`.  This is due to the fact that `update_yaml.py` will not merge files that do not exist.

**Comment by prometheanfire** [comment]
if we backport this we also need to cherry pick https://github.com/rcbops/rpc-openstack/commit/9ffc160dfddbbf22c0943f4ad55a769554a89697
