### ISSUE TITLE
submodules bad, let's not use them

### ISSUE THREAD

**Issue by prometheanfire** [rcbops/rpc-openstack#580]
As has been said on the lists, people don't like submodules, we can discuss and review solutions here if you'd like.

**Comment by d34dh0r53** [comment]
Initial testing indicates that we're going to need to figure out how to use multiple `ansible-role-requirements.yml` files.  The `ansible-role-requirements.yml` that we're using in `/opt/rpc-openstack` is overriding the file location that OSA is using.  Some how we need `deploy.sh` to use the file in `/opt/rpc-openstack` and OSA to use the file in `/opt/rpc-openstack/openstack-ansible`.  I think we could create a directory and place both of the files in there with multiple names, or merge the files, but I'm pretty sure the OSA file is appended to during the bootstrap stages.

**Comment by d34dh0r53** [comment]
The `bootstrap-ansible.sh` needs to be run earlier on in the `deploy.sh` script.

```bash
# bootstrap the AIO
if [[ "${DEPLOY_AIO}" == "yes" ]]; then
  # force the deployment of haproxy for an AIO
  export DEPLOY_HAPROXY="yes"
  if [[ ! -d /etc/openstack_deploy/ ]]; then
    ./scripts/bootstrap-ansible.sh
>>> PUT IT HERE >>>    ./scripts/bootstrap-aio.sh
    pushd ${RPCD_DIR}
      for filename in $(find etc/openstack_deploy/ -type f -iname '*.yml'); do
        if [[ ! -a "/${filename}" ]]; then
 ```

**Comment by prometheanfire** [comment]
already done did it

**Comment by mancdaz** [comment]
This issue is now redundant. We have moved to ansible roles for the things that are actual ansible roles, and we continue to use a submodule for OSA as it is not an ansible role.
