### ISSUE TITLE
linting.sh buries flake8 failures

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#595]
For example, there was a failing flake8 line in the PR, but the output from the travis run just says 'failed linting'. eg:

https://travis-ci.org/rcbops/rpc-openstack/builds/91598278#L1980

When running the relevant flake8 line manually locally, I saw the actual failure:

```
# flake8 $(grep -rln -e '^#!/usr/bin/env python' -e '^#!/bin/python' -e '^#!/usr/bin/python' * ) || failed=1
maas/plugins/nova_cloud_stats.py:103:80: E501 line too long (83 > 79 characters)
```

We should probably fix the linting script to output those errors properly

**Comment by nrb** [comment]
Originally, my intention was to let all of the linting run before finishing the script. Should we instead simply remove the `|| failed=1` logic and let the linting checks die on first failure? I think that would be cleaner.

@rackertom @d34dh0r53 you have both been bitten by this too - which would be preferred?

**Comment by mancdaz** [comment]
@nrb My personal preferred option would be to see all places that it is going to fail, in one go, so that I can fix them all in one go. 
If that's too painful, failing at the first failure (but ensuring it actually gets spat out) would work too.

**Comment by rackertom** [comment]
If it's going to fail anyway, I'd prefer it to fail early. But there is obvious utility from getting all of the linting output at once so there isn't a trial-and-error period.

Then again, it would be just as easy to do further lint checks on my local machine like an adult I guess.

**Comment by nrb** [comment]
@mancdaz That was my thinking, too. I'm doing a test PR on my own fork to see how the fail-fast method might work. In practice it's just removing a bunch of code. I think collecting then reporting failures may be more intensive and more code added to handle the collection.

**Comment by d34dh0r53** [comment]
@nrb @mancdaz I think the fail first is the right way to do it, it's a relatively quick test so running locally and iterating through your failures is not too painful.  Plus I think adding a ton of code to catch all of the errors has the possibility to mask certain errors like we're seeing now.

**Comment by stevelle** [comment]
I like the idea of a gate reporting all failures patiently, but getting it right adds complexity and opportunity for it to mask errors or give false positives if things change and the logic for this accumulation does not update in lockstep. I'd take a fail-fast if it's offered.

**Comment by stevelle** [comment]
related 
#612

**Comment by sigmavirus24** [comment]
I know we like having things "all-in-one" but separate travis checks would work well for fast failure without losing the information about the individual checks failing.

**Comment by nrb** [comment]
That's a good point, @sigmavirus24. So I take it you're suggesting we split flake8 and ansible linting?

**Comment by sigmavirus24** [comment]
Yeah, i can even tackle that this afternoon while I'm here at the doctor's.

**Comment by nrb** [comment]
I'd be behind separate jobs myself. That's more informative.
