### ISSUE TITLE
ceph playbooks fail quite often during initial install

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#599]
The ceph playbooks fail quite often during initial install with either downloading from upstream and comparing MD5 hashes or this error:

TASK: [ceph-mon | copy keys to the ansible server] ****************************
changed: [233d28af-infra1_ceph_mon_container-295016f6] => (item=/etc/ceph/ceph.client.admin.keyring)
changed: [233d28af-infra1_ceph_mon_container-295016f6] => (item=/etc/ceph/ceph.client.cinder-backup.keyring)
changed: [233d28af-infra1_ceph_mon_container-295016f6] => (item=/etc/ceph/ceph.client.cinder.keyring)
changed: [233d28af-infra1_ceph_mon_container-295016f6] => (item=/etc/ceph/ceph.client.glance.keyring)
fatal: [233d28af-infra1_ceph_mon_container-295016f6] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 815, in _executor_internal
    complex_args=complex_args
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1036, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/action_plugins/fetch.py", line 141, in run
    os.makedirs(os.path.dirname(dest))
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/etc/openstack_deploy/ceph_fetch/98cc124b-d0cc-4e2e-8a9e-55367e12a0ad/var/lib/ceph/bootstrap-osd'

changed: [233d28af-infra1_ceph_mon_container-8d55b576] => (item=/etc/ceph/ceph.client.admin.keyring)
changed: [233d28af-infra1_ceph_mon_container-8d55b576] => (item=/etc/ceph/ceph.client.cinder-backup.keyring)
changed: [233d28af-infra1_ceph_mon_container-8d55b576] => (item=/etc/ceph/ceph.client.cinder.keyring)
changed: [233d28af-infra1_ceph_mon_container-8d55b576] => (item=/etc/ceph/ceph.client.glance.keyring)
changed: [233d28af-infra1_ceph_mon_container-8d55b576] => (item=/var/lib/ceph/bootstrap-osd/ceph.keyring)
changed: [233d28af-infra1_ceph_mon_container-8d55b576] => (item=/var/lib/ceph/bootstrap-rgw/ceph.keyring)
changed: [233d28af-infra1_ceph_mon_container-8d55b576] => (item=/var/lib/ceph/bootstrap-mds/ceph.keyring)
changed: [233d28af-infra1_ceph_mon_container-03a55c41] => (item=/etc/ceph/ceph.client.admin.keyring)
changed: [233d28af-infra1_ceph_mon_container-03a55c41] => (item=/etc/ceph/ceph.client.cinder-backup.keyring)
changed: [233d28af-infra1_ceph_mon_container-03a55c41] => (item=/etc/ceph/ceph.client.cinder.keyring)
changed: [233d28af-infra1_ceph_mon_container-03a55c41] => (item=/etc/ceph/ceph.client.glance.keyring)
changed: [233d28af-infra1_ceph_mon_container-03a55c41] => (item=/var/lib/ceph/bootstrap-osd/ceph.keyring)
changed: [233d28af-infra1_ceph_mon_container-03a55c41] => (item=/var/lib/ceph/bootstrap-rgw/ceph.keyring)
changed: [233d28af-infra1_ceph_mon_container-03a55c41] => (item=/var/lib/ceph/bootstrap-mds/ceph.keyring)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/ceph-all.retry

233d28af-infra1_ceph_mon_container-03a55c41 : ok=39   changed=12   unreachable=0    failed=0
233d28af-infra1_ceph_mon_container-295016f6 : ok=38   changed=12   unreachable=1    failed=0
233d28af-infra1_ceph_mon_container-8d55b576 : ok=39   changed=13   unreachable=0    failed=0

A rerun fixes this usually.  Currently  I'm deploying cloud builds using https://github.com/BjoernT/rpc-heat-ansible/tree/ceph_integration for fast turn arounds

**Comment by d34dh0r53** [comment]
@BjoernT not sure there is much we can do as this is a bug in the ceph playbooks which we do not control.  I think the `ceph-ansible` repository is a better place for this.

**Comment by BjoernT** [comment]
I know we might want to add a loop with 2 retries ?

**Comment by BjoernT** [comment]
https://github.com/ceph/ceph-ansible/issues/410

**Comment by mattt416** [comment]
I've started seeing this recently also.  I've updated the linked bug with a suggestion for addressing.

**Comment by mattt416** [comment]
@BjoernT, I created https://github.com/ceph/ceph-ansible/pull/448 which from my testing resolves this, but it'd be great to get your feedback so we can be sure.

**Comment by git-harry** [comment]
https://github.com/rcbops/rpc-openstack/issues/702
