### ISSUE TITLE
MaaS: rabbitmq_status check, metric "rabbitmq_socket_used" is not available 

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/rpc-openstack#606]
The actual metric names should be `rabbitmq_sockets_used` and `rabbitmq_sockets_total`.

**Comment by stevelle** [comment]
should be means that this is what the metric names were before the refactor?

**Comment by byronmccollum** [comment]
I'm not sure if the metrics were renamed, or if these were new metrics, and the just didn't jibe from the start.

**Comment by stevelle** [comment]
these checks were added in https://github.com/rcbops/rpc-openstack/issues/516 and it looks like this has not made it into any release yet. (https://github.com/BjoernT/rpc-openstack/commit/1094f97909520c590896c8d4f6c7f59c83f4d671 and then reintroduced in https://github.com/rcbops/rpc-openstack/commit/cd091f3549194d1a10f4dcca175abe149b727900 -- tagged for 11.1.0rc2)

There was no backport of 516 performed so this hasn't hit kilo yet.

I'm not finding any support for these metrics actually being collected in maas/plugins/rabbitmq_status.py so while this rename may make sense it appears to be pointless to me right now.

Am I imagining things or are these metrics not actually being reported at all?
We might as well fix that while we're here.
