### ISSUE TITLE
rabbitmq permissions issue present in r11.1.0rc4

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#609]
```
TASK: [rabbitmq_server | Enable queue mirroring] ******************************
failed: [rc4-node3_rabbit_mq_container-5ad8cc6a] => {"cmd": "/usr/sbin/rabbitmqctl -q -n rabbit list_policies -p /", "failed": true, "rc": 2}
stderr: Error: unable to connect to node 'rabbit@rc4-node3_rabbit_mq_container-5ad8cc6a': nodedown

DIAGNOSTICS
===========

attempted to contact: ['rabbit@rc4-node3_rabbit_mq_container-5ad8cc6a']

rabbit@rc4-node3_rabbit_mq_container-5ad8cc6a:
  * connected to epmd (port 4369) on rc4-node3_rabbit_mq_container-5ad8cc6a
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on rc4-node3_rabbit_mq_container-5ad8cc6a
  * suggestion: start the node

current node details:
- node name: 'rabbitmq-cli-3157@rc4-node3_rabbit_mq_container-5ad8cc6a'
- home dir: /var/lib/rabbitmq
- cookie hash: ZXlCDDnOfAskKwiRflzNkw==


msg: Error:********@rc4-node3_rabbit_mq_container-5ad8cc6a'
- home dir: /var/lib/rabbitmq
- cookie hash: ZXlCDDnOfAskKwiRflzNkw==
failed: [rc4-node2_rabbit_mq_container-2701c6f1] => {"cmd": "/usr/sbin/rabbitmqctl -q -n rabbit list_policies -p /", "failed": true, "rc": 2}
stderr: Error: unable to connect to node 'rabbit@rc4-node2_rabbit_mq_container-2701c6f1': nodedown

DIAGNOSTICS
===========

attempted to contact: ['rabbit@rc4-node2_rabbit_mq_container-2701c6f1']

rabbit@rc4-node2_rabbit_mq_container-2701c6f1:
  * connected to epmd (port 4369) on rc4-node2_rabbit_mq_container-2701c6f1
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on rc4-node2_rabbit_mq_container-2701c6f1
  * suggestion: start the node

current node details:
- node name: 'rabbitmq-cli-3157@rc4-node2_rabbit_mq_container-2701c6f1'
- home dir: /var/lib/rabbitmq
- cookie hash: ZXlCDDnOfAskKwiRflzNkw==


msg: Error:********@rc4-node2_rabbit_mq_container-2701c6f1'
- home dir: /var/lib/rabbitmq
- cookie hash: ZXlCDDnOfAskKwiRflzNkw==
changed: [rc4-node1_rabbit_mq_container-5f865e07]

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/setup-infrastructure.retry
```

This review in openstack-ansible fixed the problem:

https://review.openstack.org/#/c/243227/

However, rc4 does not include this since the last osa commit is from 20th October.  I understand that we need to not move the goalposts while this is being tested, but currently openstack-ansible is undeployable.

**Comment by jacobwagner** [comment]
I was seeing this in rc3, but a rerun of the rabbitmq plays fixed it so i didnt investigate further, i thought it was a non issue but we will look at it again. If it is a known issue with a fix i would suggest pulling it into a rc5.

**Comment by byronmccollum** [comment]
OSA 11.2.5 is getting tagged tomorrow, which will include the fix.

**Comment by mancdaz** [comment]
@byronmccollum well we can move rpc-openstack to any arbitrary sha - it doesn't need to be a tag, if the sha contains a fix we need.  The problem here is more that we don't like moving the sha forward once qe have started testing an rc series.  I think, though, in this case we're going to have to.

**Comment by byronmccollum** [comment]
Understood...but there are a ton of things fixed in 11.2.5...this only being one.

**Comment by mancdaz** [comment]
True, but that also introduces potential problems.  We should always be striving to keep the rc series fairly static for QE so that we actually release what they tested.

Anyway, I think the discussion is moot - if QE confirm this as a breaking bug, we're going to have to bump forward and take the hit on that. IMO

**Comment by d34dh0r53** [comment]
This should be fixed in rc5 which dropped on Friday the 20th.  Please re-open if this continues to be an issue.
