### ISSUE TITLE
MaaS: rabbitmq_status check gives KeyError: 'mem_used'

### ISSUE THREAD

**Issue by stevelle** [rcbops/rpc-openstack#610]
Error looks like this:
```
status error toring-agent/plugins/rabbitmq_status_new.py", line 172, in
<module>\n    main()\n  File
"/usr/lib/rackspace-monitoring-agent/plugins/rabbitmq_status_new.py",
line 139, in main\n    metrics[k] = {'value': resp_json[0][k], 'unit':
v}\nKeyError: 'mem_used'\n
```

Not sure if this is because OPC is deploying RabbitMQ 3.3.5 or something else, but they are getting a response from the nodes endpoint which does not consistently position the current host first in the nodes array.

e.g.
```
[root@overcloud-controller-1 ~]# cat nodes | python -m json.tool
[
    {
        "name": "rabbit@overcloud-controller-0",
        "running": true,
        "type": "disc"
    },
    {
        "applications": [
            {
                "description": "RabbitMQ AMQP Client",
                "name": "amqp_client",
                "version": "3.3.5"
            },
            {
                "description": "INETS  CXC 138 49",
                "name": "inets",
                "version": "5.9.8"
            },
```
this check running on overcloud-controller-1

**Comment by stevelle** [comment]
http://paste.openstack.org/show/L7B5BB9jOjwTIuunwYYg/ as an example of the response format we get

http://paste.openstack.org/show/XQhuqdKHoeeQ96tDaFrd/ as an example of the response format from OPC

**Comment by sigmavirus24** [comment]
Has anyone backported #611 yet?

**Comment by stevelle** [comment]
@sigmavirus24 no backport yet the change was to support RPC-R and this issue did not originate in RPC-O so I don't know why it has a backport label, personally.
