### ISSUE TITLE
run_queues is not a rabbitmq metric

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#626]
run_queues is used by the rabbitmq plugin to check that the cluster is working [1]. This metric is not giving information about the rabbitmq message queues [2]. This section of the plugin should be revisited so that is testing as intended.

[1] https://github.com/rcbops/rpc-openstack/blob/master/maas/plugins/rabbitmq_status.py#L144
[2] http://erlang.org/pipermail/erlang-questions/2012-February/064141.html

- [x] Liberty #745
- [x] Kilo

**Comment by d34dh0r53** [comment]
This is not in fact fixed

**Comment by d34dh0r53** [comment]
Needs a backport
