### ISSUE TITLE
Elasticsearch Curator cron missing and misnamed fields

### ISSUE THREAD

**Issue by d34dh0r53** [rcbops/rpc-openstack#630]
In the Elasticsearch Curator cron there are several missing options and a misspelled option:

* `--older_than` should be renamed to `--older-than`
* `delete` should be `delete indices`
* the flag `--time-unit days` needs to be added
* the flag `--timestring %Y.%m.%d` needs to be added
* the flag `--prefix logstash` needs to be added

- [x] master
- [ ] kilo

**Comment by jacobwagner** [comment]
@d34dh0r53 I would also sit with OPS and find out what a good deletion default would be, or maybe we could better document how to override it. In our lab we were seeing about 100G a day, so @ 2TB that would mean a full disk in ~18 days. This brought the elasticsearch service down with caused the upgrade ELK plays to fail when trying to connect to elasticsearch. Trickle effect = bad times for all.

**Comment by d34dh0r53** [comment]
@jacobwagner yeah, I agree we should probably default to a lower value, but this seems like a very deployment dependent setting.  The proper value is going to be based on the size of the environment as well as compliance factors for the customer.

**Comment by d34dh0r53** [comment]
Note to self, create `kilo` backport
