### ISSUE TITLE
Additional ceph.conf configuration options for scrubbing

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#642]
I'm currently not aware of any ceph scrubbing jobs in our installation.
We might look at https://github.com/SamYaple/CephScrubManager/blob/master/csm.py  to implement this ?

**Comment by mancdaz** [comment]
@BjoernT I thought ceph did scrubbing automatically as part of it's own housekeeping activities?

http://docs.ceph.com/docs/v0.71/rados/configuration/osd-config-ref/#scrubbing

Seems to suggest light scrubbing daily, and deeps scrubbing weekly. There are tunables, of course, which may need to be tweaked per installation depending on requirements, but as far as a scrubbing 'job', I'm not sure we need one?

**Comment by BjoernT** [comment]
I have not seen any scrubbing inside my ceph cluster yet, that's why I'm looking into it.

**Comment by d34dh0r53** [comment]
If ceph has built in scrubbing functionality I would much rather use that.  I would like to avoid as many third party plugins as possible.

**Comment by d34dh0r53** [comment]
@BjoernT Any more information available on this?

**Comment by BjoernT** [comment]
Still researching.  I can not find any definitive docs when and how scrubbing is performed buy ceph ods/mons just the configuration

**Comment by mancdaz** [comment]
@bjoernt @d34dh0r53 the doc I linked shows that the default intervals are daily (light scrubbing) and weekly (deep scrubbing). The time of day, load at time if scrub etc are all configurable, but by default you're going to get a daily scrub at midnight, and weekly deep scrub at the same time.

The ask in the bug was to schedule a scrubbing job, which we don't need to do based on the above

**Comment by BjoernT** [comment]
Yes seems alright I saw it via ceph pg  dump |awk -F'\t' '/[0-9a-f]+\./ {print $1 " " $19}'
We might still run into issues that the scrub degrades the performance at midnight GMT so we probably want to configure this time since 0GMT is quite often production time for customers

**Comment by git-harry** [comment]
By default the scrubbing is scheduled to happen during a window, the default being anytime, and not at midnight. Scrubbing does not occur if the load is higher than 0.5. Currently the ceph.conf template does not support all the configurable scrubbing options [1] and so will need to be updating to support the additional configurability.

[1] https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/templates/ceph.conf.j2

**Comment by BjoernT** [comment]
Yes i'm working upstream to get this option in

**Comment by git-harry** [comment]
https://github.com/rcbops/rpc-openstack/issues/702
