### ISSUE TITLE
Redirection in f5-monitor.sh does not do what is described

### ISSUE THREAD

**Issue by ghost** [rcbops/rpc-openstack#661]
The redirection found [here](https://github.com/rcbops/rpc-openstack/blob/master/scripts/f5-monitor.sh#L4) does not redirect output to fd 3. We also have no description of what is at fd 3. Instead, the script redirects fd 3 into stdout, then properly redirects stdout and stderr to either /dev/null or the log file specified in the comment.

The comment should also be cleaned up to clearly note output can be sent to /dev/null or a log file for diagnostic purposes in the same comment block.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by rackertom** [comment]
I've downloaded the f5 docs for shell programming, and I'll go through those to see if there's a reference to fd 3 anywhere. If not, I'll probably remove it entirely. If fd 3 happens to be some kind of logging interface, then I'll actually fix the script's redirections.

**Comment by tomc603** [comment]
@git-harry Can I get some insight into what fd 3 was supposed to be on the F5? I can't find any references to it anywhere in their docs, examples, reference material, etc. I'm just worried that it's some kind of logging descriptor, and I don't want to remove it without being absolutely sure.

**Comment by git-harry** [comment]
@tomc603 I don't know the details of that decision, I believe the original version was written by @Apsu.

**Comment by ameserole** [comment]
I was looking into this bug and I found where fd 3 is used in the script [1]. It is used to redirect an echo command into stdout while stdout is redirected into the log file. I think that there is no issue here and if anything the comments just need to be updated or the code may need to be refactored a little bit.

@tomc603 @git-harry it looks like the original user who submitted the issue deleted their account. Should I just get opinions from the group channel?

[1] https://github.com/rcbops/rpc-openstack/blob/master/scripts/f5-monitor.sh#L128-L134

**Comment by tomc603** [comment]
@ameserole I'm actually that ghost user. 😄 

For the most part, I was looking at https://github.com/rcbops/rpc-openstack/blob/master/scripts/f5-monitor.sh#L4 That series of redirections looks incorrect to me, and there's still no description of _what_ fd 3 is, where it goes, etc. I briefly searched the F5 docs and couldn't find anything there either.

**Comment by ameserole** [comment]
@tomc603 oh ok haha. I think fd 3 isn't a F5 thing rather just a hack that the author of the script used in order to get all of the printf statements to go to the logs and this one echo command [1] to print to the console when it gets a proper status code. At least thats what has shown up in my testing. 

[1] https://github.com/rcbops/rpc-openstack/blob/master/scripts/f5-monitor.sh#L128-L134

**Comment by ameserole** [comment]
@BjoernT How does support use this script? Should all outputs be redirected to the log file including the "success" exit message?
If y'all like the way the success message works then I have noticed that [1] and [2] should probably be output to fd 3 as well.
[1] https://github.com/rcbops/rpc-openstack/blob/master/scripts/f5-monitor.sh#L140
[2] https://github.com/rcbops/rpc-openstack/blob/master/scripts/f5-monitor.sh#L151

**Comment by BjoernT** [comment]
This script is used inside an F5 so logging is done inside TMM processes. 
Logging is mostly not enabled as listed [here](https://github.com/rcbops/rpc-openstack/blob/master/scripts/f5-monitor.sh#L4l)

We are internally talking to get rid of this script until then I see no need to really touch it, unless we have to to make the token extraction working for new keystone versions

**Comment by ameserole** [comment]
Thanks for the info @BjoernT 
@tomc603 Based off the info that @BjoernT gave and my own investigations I am going to close this bug. If support starts using this script again an issue comes up with how the redirects are working this can be reopened.
