### ISSUE TITLE
KeyError when using v2 Auth in MaaS checks

### ISSUE THREAD

**Issue by stevelle** [rcbops/rpc-openstack#668]
`status error line 360, in get_auth_ref\n    if
is_token_expired(auth_ref):\n  File
"/usr/lib/rackspace-monitoring-agent/plugins/maas_common.py", line 345,
in is_token_expired\n    expires =
datetime.datetime.strptime(token['expires_at'], fmt)\nKeyError:
'expires_at'
`

**Comment by d34dh0r53** [comment]
Needs `kilo` backport

**Comment by d34dh0r53** [comment]
Prematurely closed this
