### ISSUE TITLE
Upgade gating to use ansible-lint 2.2.0

### ISSUE THREAD

**Issue by sigmavirus24** [rcbops/rpc-openstack#670]
ansible-lint 2.2.0 added the `--exclude` flag which will let us ignore the `ceph_*` roles without jumping through hoops (removing, recloneing) each time we run that lint job.

**Comment by nrb** [comment]
ansible-lint 2.3.2 is out now, too.

**Comment by git-harry** [comment]
Closing because the patch merged months ago.
