### ISSUE TITLE
Ceph OSD stats checks fail to get metrics

### ISSUE THREAD

**Issue by andymcc** [rcbops/rpc-openstack#675]
The ceph osd check fails to get metrics because the string passed in is incorrect.

**Comment by d34dh0r53** [comment]
Needs a `kilo` backport

**Comment by andymcc** [comment]
Ahh sorry missed you'd already done it @byronmccollum - I'll close off my branch and I've +2'd your kilo backport.

**Comment by byronmccollum** [comment]
Cheers

**Comment by mancdaz** [comment]
The backport got pulled in by master-kilo sync PR https://github.com/rcbops/rpc-openstack/pull/718. Closing backport PR and this issue
