### ISSUE TITLE
Network util checks fail when non-default network devices are in use

### ISSUE THREAD

**Issue by andymcc** [rcbops/rpc-openstack#677]
We may need to just document this, but the network utilisation checks fail and a var may need to be set to correct the device names for network interfaces.

**Comment by andymcc** [comment]
Looks like we don't add/remove the correct maas checks either, and we also aren't running the tasks against physical hosts, but rather against all containers (and then delegating to physical host).

**Comment by andymcc** [comment]
@asettle @robb-romans this is probably a docs issue too.

The issue is as follows:
There is no sensible way to discover the physical interfaces so we default the network_checks_list variable to consist of the interfaces eth0, eth1, eth2 and eth3: (https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/defaults/main.yml#L318-L322) if the physical host itself does not have those specific interfaces (they are either named differently or simply don't exist, OR there are additional interfaces to monitor), we need to set that variable in /etc/openstack_deploy/user_extras_variables.yml

For example, if we had the interfaces em0 em1 em2 em3, we would set the following var in /etc/openstack_deploy/user_extras_variables.yml:
network_checks_list:
  - { name: "em0", group: "hosts", max_speed: "{{ net_max_speed }}", rx_pct_warn: "{{ net_rx_pct_warn }}", rx_pct_crit: "{{ net_rx_pct_crit }}", tx_pct_warn: "{{ net_tx_pct_warn }}", tx_pct_crit: "{{ net_tx_pct_crit }}"}
  - { name: "em1", group: "hosts", max_speed: "{{ net_max_speed }}", rx_pct_warn: "{{ net_rx_pct_warn }}", rx_pct_crit: "{{ net_rx_pct_crit }}", tx_pct_warn: "{{ net_tx_pct_warn }}", tx_pct_crit: "{{ net_tx_pct_crit }}"}
  - { name: "em2", group: "hosts", max_speed: "{{ net_max_speed }}", rx_pct_warn: "{{ net_rx_pct_warn }}", rx_pct_crit: "{{ net_rx_pct_crit }}", tx_pct_warn: "{{ net_tx_pct_warn }}", tx_pct_crit: "{{ net_tx_pct_crit }}"}
  - { name: "em3", group: "hosts", max_speed: "{{ net_max_speed }}", rx_pct_warn: "{{ net_rx_pct_warn }}", rx_pct_crit: "{{ net_rx_pct_crit }}", tx_pct_warn: "{{ net_tx_pct_warn }}", tx_pct_crit: "{{ net_tx_pct_crit }}"}


NB This is a new check so its not in the 11.1 release we just did, but it would be in the next release, not sure how/where we would appropriately document that.

Let me know if that doesn't make sense, I can clarify.

**Comment by d34dh0r53** [comment]
@andymcc is it appropriate to target this to `r11.1.1` or should we hold off on this until `liberty`?

**Comment by andymcc** [comment]
@d34dh0r53 Ideally if we could target this one - its not necessarily breaking if we don't though - the more important PR is #682

**Comment by mancdaz** [comment]
backport to kilo on it's way

**Comment by git-harry** [comment]
In master and kilo.
