### ISSUE TITLE
Instance --> metadata agents connection doesn't work for RPC AIOs

### ISSUE THREAD

**Issue by hughsaunders** [rcbops/rpc-openstack#689]
Instance --> neutron metadata agents don't work for an AIO deployed via the RPC deploy.sh script. 

I think this is because the RPC deploy script doesn't call run-playbooks, so doesn't use the section that drops the iptables rule necessary to make instance<-->metadata agent connections work: 

https://github.com/openstack/openstack-ansible/blob/master/scripts/run-playbooks.sh#L118-L129

PRs:
---
- [x] master: #690 
- [x] kilo: #694

**Comment by nrb** [comment]
Correct, not calling `run-playbooks.sh` was a conscious decision when I first wrote it, but this is indeed a problem currently.

**Comment by tomc603** [comment]
Per my comment in #694 the desired change was already merged into Kilo. It actually looks like the same commit was applied to both Master and Kilo but I can't quite figure out if it happened all at once or if the commit was applied to a branch that was then branched for other work and subsequently applied.
