### ISSUE TITLE
disk_utilisation.py needs to specify sda and sdb to avoid the >30 metrics error

### ISSUE THREAD

**Issue by h1pp13p373** [rcbops/rpc-openstack#693]
We have seen tickets come in with:
REASON: error Maximum of 30 metrics per checkerror Maximum of 30 metrics per check

This happens on a compute node with cinder volumes.  The number of disks can exceed 30, which is a hard limit in our MAAS.  The following change to disk_utilisation.py makes the script only check /dev/sda and /dev/sdb:

from
output = subprocess.check_output(shlex.split('iostat -x -d %s 2' % time))
to
output = subprocess.check_output(shlex.split('iostat -x -d /dev/sda /dev/sdb %s 2' % time))

Thanks!

HippiePete

**Comment by h1pp13p373** [comment]
Here's the commands I used to fix the hosts for CAS:

Quick sed to fix the file:

sed -i 's/iostat\ -x\ -d/iostat\ -x\ -d\ \/dev\/sda\ \/dev\/sdb\ /' /usr/lib/rackspace-monitoring-agent/plugins/disk_utilization.py

I copied the file to /root and pushed out with ansible:

ansible hosts -m copy -a "src=/root/disk_utilisation.py dest=/home/rack/disk_utilisation.py"
ansible hosts -m shell -a "chmod 755 /home/rack/disk_utilisation.py"
ansible hosts -m shell -a "cp -r /home/rack/disk_utilisation.py /usr/lib/rackspace-monitoring-agent/plugins/disk_utilisation.py"

**Comment by git-harry** [comment]
I believe the 30 metric limit no longer exists in MaaS and so maas_common could be updated to remove the check.

**Comment by prometheanfire** [comment]
the 30 limit is still in place via rphillips, I would like to get more of supports view on this, reducing is something they'd know more about the goodness/badness of.  Limiting to sda type devices is probably bad as well if we ever start offering nvme and the like.

**Comment by prometheanfire** [comment]
@BjoernT opinion on what we'd do here?

**Comment by BjoernT** [comment]
Well we have actually other issues open to exclude virtual scsi devices from the check, so we won't catch iscsi devices etc.
Hard coding this to /dev/sda is probably not a good idea either.
I would close this one and actually work on https://github.com/rcbops/rpc-openstack/issues/708 so we can exclude the devices or figure out why https://github.com/rcbops/rpc-openstack/issues/38 does not work correctly

**Comment by prometheanfire** [comment]
ok, closing this then
