### ISSUE TITLE
Bump ceph-ansible SHA for RPC 11.1.1

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#702]
Please bump the ceph-ansbile playbook sha to include 

https://github.com/ceph/ceph-ansible/issues/451
https://github.com/ceph/ceph-ansible/issues/410

Since the master branch is still the stable branch we should be ok to include the head of the master for ceph-ansbile (SHA equivalent)

**Comment by git-harry** [comment]
The commits are already included by the SHAs currently referenced. This was addressed in master by [1] and in kilo by [2].

[1] https://github.com/rcbops/rpc-openstack/pull/672
[2] https://github.com/rcbops/rpc-openstack/pull/718
