### ISSUE TITLE
 Holland backup needs to backup localhost

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#716]
Transferred from https://bugs.launchpad.net/openstack-ansible/+bug/1479486:

The current template for roles/rpc_support_holland/templates/holland-xtrabackup.conf.j2 has the host set to {{ internal_vip_address }}. This can cause issue if it is routed to a remote node from where holland is ran. The host should be set to localhost so we do not backup a remote node.

i.e. set host = 127.0.0.1 in /etc/holland/backupsets/rcp_support.conf

**Comment by d34dh0r53** [comment]
Duplicate #348
