### ISSUE TITLE
Ceph needs testing

### ISSUE THREAD

**Issue by hughsaunders** [rcbops/rpc-openstack#732]
Currently the RPC AIO gate doesn't deploy/test ceph. Ceph is going into production and requires testing.

**Comment by hughsaunders** [comment]
Required PR: https://github.com/rcbops/rpc-openstack/pull/760

**Comment by hughsaunders** [comment]
Some backports may also be required. Will get a master job going first.

**Comment by prometheanfire** [comment]
this has been merged, closing

**Comment by prometheanfire** [comment]
does this need to go into 12.0.x as well?  If so, please update the top comment with the correct format.

**Comment by git-harry** [comment]
@prometheanfire it already is
