### ISSUE TITLE
Ansible linting Travis jobs fail

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#739]
We're routinely seeing this error in Travis Ansible linting jobs:

```
ansible-lint runtests: commands[0] | /home/travis/build/rcbops/rpc-openstack/scripts/linting-ansible.sh
/home/travis/build/rcbops/rpc-openstack/rpcd/playbooks /home/travis/build/rcbops/rpc-openstack
Running ansible-playbook syntax check
ERROR! ERROR! the file_name '/dev/fd/63' does not exist, or is not readable
ERROR: InvocationError: '/home/travis/build/rcbops/rpc-openstack/scripts/linting-ansible.sh'
```

I've been able to replicate this locally, too, with the `tox -e ansible-lint` command (on OS X, not linux). However, running `scripts/linting-ansible.sh` manually works.

Maybe the local inventory echoing file descriptor is breaking it?

**Comment by nrb** [comment]
Replacing the `{toxinidir}/scripts/linting-ansible.sh` with a harcoded path produces the same result.

**Comment by nrb** [comment]
Upgrading to ansible-lint 2.3.0 has the same behavior.

**Comment by d34dh0r53** [comment]
I think @prometheanfire fixed this with #741

**Comment by prometheanfire** [comment]
I did fix it, fixed in kilo too

**Comment by nrb** [comment]
Ah, thanks.
