### ISSUE TITLE
MAAS checks duplicate after switching to agent installs

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#761]
I just did a RPC11.0 to RPC11.1.1 upgrade and the MAAS checks have virtually duplicated for example:
```
raxmon-checks-list --entity-id=enAvmxREk9 |grep filesystem_/--
<Check: id=chX2uddapF label=filesystem_/--12345-infra01...>
<Check: id=chuRLnzbs6 label=filesystem_/--12345-infra01...>
```
To me the issue seem to be caused after switching from raxmon-utilities to the agent to install the checks and the MAAS agent is adding the same checks again for each entity.
Conversely we need to implement a cleanup step prior to adding the new checks.

**Comment by BjoernT** [comment]
There might be a possible connection to the old cached keystone token inside /root/.auth_ref.json because the duplicated checks have no alarm definition inside MAAS but they do inside the yml template

**Comment by d34dh0r53** [comment]
@BjoernT does this still affect `r11.1.2`?

**Comment by BjoernT** [comment]
retesting

**Comment by prometheanfire** [comment]
closing as docs state these checks get blown away and recreated on upgrade
