### ISSUE TITLE
Difficult to inject variables when building an AIO

### ISSUE THREAD

**Issue by hughsaunders** [rcbops/rpc-openstack#767]
Currently the rpc deploy script checks if /etc/openstac_deploy exists and skips large sections of setup if it does. This makes it difficult to pre-populate that directory with config. 

When running the deploy script there are no opportunities after /etc/openstack_deploy is created to insert extra variables. Currently the only option is to checkout rpc-openstack, modify or insert variables into the tree, then run the deploy script which will create /etc/openstack_deploy and copy in the changes. 

I propose that we test for an individual file within /etc/openstack_deploy so that the directory itself can be created before running the script and pre-populated with variables. This will help with gate jobs as we can have a variables file for each scenario and copy the relevant one into /etc/openstack_deploy before running deploy.sh. 

---
 - [ ] Master #768 
 - [ ] Kilo

**Comment by d34dh0r53** [comment]
Love it :+1:

**Comment by prometheanfire** [comment]
can merge earlier if it's ready, this is upgrade related

**Comment by nrb** [comment]
I like the idea, though I had some feedback on the implementation in the PR.

I'd like to be sure that the RPC defaults carried in tree always win over OSA defaults, but user-defined values beat both.
