### ISSUE TITLE
Make novnc the default console in RPC13 and later

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#771]
For more info see

https://review.openstack.org/#/c/228197/

**Comment by BjoernT** [comment]
Since we have this already in Kilo implemented I like to enable this ASAP because SPICE is not usable.

**Comment by BjoernT** [comment]
RPC Docs Bug : https://github.com/rpcdocs/rpcdocs/issues/457

**Comment by prometheanfire** [comment]
what should this target?

12.0.1 11.1.6 and 12.1.0?

**Comment by claco** [comment]
For the moment, please create a 13.0.0 milestone and put it there.

**Comment by sigmavirus24** [comment]
Since this is targeted for r13, I'm going to update the title of the issue because it's a bit ... confusing.

**Comment by evrardjp** [comment]
Shouldn't the milestone be set on 13.2.0 ?

**Comment by BjoernT** [comment]
@evrardjp See the waffle board, I'm not on board with moving this to 13.2.

**Comment by evrardjp** [comment]
@BjoernT Selecting this for 13.0 would be the contrary of the use cases: it would be a new feature that comes "non free."

**Comment by BjoernT** [comment]
@evrardjp  That is wrong, it is already implemented and in use for some customers since Kilo
Spice is horribly when using any GUI type OS. Postponing longer the availability of novnc is hurting customers. . Defacto it is a non free feature for us

**Comment by git-harry** [comment]
The change to novnc is being tracked in https://github.com/rcbops/u-suk-dev/issues/131 and so this issue should no longer be required.
