### ISSUE TITLE
Additional maas refactoring required

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#789]
When using a v2 keystone client, the token inside  is_token_expired can be accessed without the token.get function. 
Additionally I want to remove redundant auth code inside the individual plugins so that we can use auth code over the  maas_common function only. That also enables proper endpoint selection of the individual client like nova etc.

- [x] Liberty #794

**Comment by BjoernT** [comment]
PR following

**Comment by d34dh0r53** [comment]
Adding to `r11.1.4` per @BjoernT

**Comment by prometheanfire** [comment]
backport?

**Comment by BjoernT** [comment]
RPC-R could consume the changes from master so I would not really need a backport but since we already cherry-picked it I don't mind back porting it.
