### ISSUE TITLE
Allow snmpd configuration

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/rpc-openstack#793]
It would be useful to be able to configure options in snmpd.conf, such as setting an rocommunity string for external monitoring such as Cacti.

See: https://bugs.launchpad.net/openstack-ansible/+bug/1537949

**Comment by b3rnard0** [comment]
@git-harry Needs triaging.

**Comment by git-harry** [comment]
This is not suitable for a patch release, I'm removing the milestone.

**Comment by git-harry** [comment]
@JCallicoat I'd like to clarify the intention with this issue so it is being tracked in the appropriate backlog. It looks like you are requesting SNMP monitoring, how does your suggestion of integration with external monitoring fit with the current product? How do you envisage this change being utilised? Is it intended for all customer or a subset?

There have been some recent changes in the way we track issues to improve visibility. This issue sounds like a reasonably large piece of work in which case I will need to transfer it to a different board for tracking, but before I do that I would like to have a better understanding of your request.

**Comment by JCallicoat** [comment]
@git-harry Several customers have requested that we configure snmp on servers for consumption in their own monitoring services. The only ask here was to template /etc/snmp/snmpd.conf with some ansible variables. Looking back at previous requests they have been somewhat different in the configs each required. There may not be a common enough pattern to make this worthwhile. Let's close this for now and I'll revisit with a new issue in the future if it looks like a common pattern for snmpd config is emerging.

**Comment by git-harry** [comment]
Okay, thanks for the quick response.
