### ISSUE TITLE
Ceph SHA bump for ceph #506

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#797]
Just a reminder to bump the SHA once https://github.com/ceph/ceph-ansible/issues/506 has been merged. The desired commit is
https://github.com/mattt416/ceph-ansible/commit/0dab4084467a0194abaa2cd20496962c00f0d49c 

- [x] Liberty #811
- [x] Kilo #820

**Comment by d34dh0r53** [comment]
Blocked until upstream ceph merges.

**Comment by d34dh0r53** [comment]
This should be backported.  Why didn't the liberty PR reference this?

**Comment by prometheanfire** [comment]
https://github.com/rcbops/rpc-openstack/pull/811 for refrence
