### ISSUE TITLE
Verify MAAS should wait before checking alarm status

### ISSUE THREAD

**Issue by hughsaunders** [rcbops/rpc-openstack#798]
Currently the verify maas playbook loops until all checks & alarms are registered, then immediately checks that there are no active alarms. 

This doesn't make much sense as the alarm status will be checked before most of the checks have had time to run. 

---
- [x] master: #799 
- [x] kilo:

**Comment by prometheanfire** [comment]
maybe even impacts gating, given some of the timeouts related to checking mass

**Comment by prometheanfire** [comment]
please backport
