### ISSUE TITLE
 Add debug packages to the neutron_agent container

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#8]
Please add the arpping as package to the neutron_agent container, it probably makes sense to install it everywhere.

This tool is used to debug L2/ARP issues, not just including conflicting IPs and is usually used in combination with PING which is installed already

**Comment by odyssey4me** [comment]
I would suggest that a specific list be setup which can be used for extra packages and it can be set to be targeted at the various groups. This list must not conflict with anything from os-ansible-deployment.

**Comment by andymcc** [comment]
The rpc-support play is in there, so we can add it to all containers/hosts by simply adjusting the support_util_packages var in defaults/main.yml for the rpc-support role. 
If this should only be installed on the neutron_agent containers I can set that up - do we have an idea of whether this should definitely be installed everywhere or if its only required on neutron_agent containers.

**Comment by BjoernT** [comment]
Please add ethtool as well

**Comment by nrb** [comment]
Bumping to priority 1 for sprint starting 6/22/2015.

Internal docs should be updated to reflect that the debugging packages are added.

**Comment by nrb** [comment]
@BjoernT Can you confirm whether you want these packages installed everywhere, or only the neutron_agent containers?

**Comment by BjoernT** [comment]
neutron agent container is fine, that's where we need it most

**Comment by nrb** [comment]
#215 is the kilo backport.

**Comment by nrb** [comment]
Both master and kilo merged, closing issue.
