### ISSUE TITLE
RPC-AIO Doesn't need to test with duplicate containers.

### ISSUE THREAD

**Issue by hughsaunders** [rcbops/rpc-openstack#814]
The OSA gate uses container affinity > 1 to test replication code paths. We don't need to reproduce this in RPC. When we eventually have multi node gating, then we will again have multiple containers of each type and will be adding something else on top of OSA as OSA doesn't have multinode testing.

Currently most kilo RPC-AIO gate jobs are failing due to lsync not completing on time, I intend to fix that, but reducing container affinity will also make it go away. 

There is also a cirros image upload failure that may be related to multiple keystones, which may be prevented by reducing affinity.

**Comment by prometheanfire** [comment]
when we have a multi-node gate then I'd be fine reducing coverate, until then I don't think reducing coverage is a good idea.  We do set some different values for DB stuff than upstream OSA for instance.

:-1: til we have working multinode

**Comment by nrb** [comment]
While I can somewhat understand the argument that we don't have to retest large swaths of functionality, I feel like we should keep testing multiple containers as long as we can.

Is the problem that we lack resources on the AIOs we're building, or is it just getting around the lsync issue?

**Comment by hughsaunders** [comment]
consensus is that we do need to carry on testing multiple containers where applicable, at least untill we have multinode gating.
