### ISSUE TITLE
Set affinities for AODH and Ceilometer to 0

### ISSUE THREAD

**Issue by d34dh0r53** [rcbops/rpc-openstack#821]
We will not be using either of these in `r12.0.0` so they should be disabled.

- [ ] Liberty

**Comment by odyssey4me** [comment]
You could also just not have the aodh/ceilometer env.d files.

**Comment by prometheanfire** [comment]
heh, that is the simpler solution, will go that route

**Comment by prometheanfire** [comment]
and it doesn't work, neat
