### ISSUE TITLE
IOError exception for /var/log/maas_plugins.log when importing maas_common

### ISSUE THREAD

**Issue by tomc603** [rcbops/rpc-openstack#826]
When importing components from `maas_common`, `basicConfig` sets up `logging` to output to /var/log/maas_plugins.log, and provides a formatter. If the log file can not be accessed for some reason, an IOError exception is raised, causing the import to fail.

@git-harry notes that it is possible this can be removed entirely since logging has improved within the agents.

## Branches
- [x] Kilo #895 
- [x] Liberty #894 
- [x] Master #841

**Comment by prometheanfire** [comment]
Does this need to go into 12.0.0 or can it wait for 12.0.1?

**Comment by tomc603** [comment]
IMO, this can wait. This only fixes a corner case where the logging file isn't accessible.

**Comment by prometheanfire** [comment]
k, if you don't backport by tomorrow, I will
