### ISSUE TITLE
ansible-lint 2.3.7 breaks our linting

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#828]
ansible 2.3.7 introduced a test for the deprecated option of  ```sudo: yes``` and fails if it's used (it should be changed to the new version of that option ```becomes: True```)

The necessary changes for rpc-openstack in master have been made [here](https://github.com/rcbops/rpc-openstack/pull/825)

The necessary changes for osa master and liberty have been made [here](https://review.openstack.org/#/c/279038/) and [here](https://review.openstack.org/#/c/279059/)

For kilo, however, this has been fixed in openstack-ansible by pinning the version of ansible-lint [here](https://review.openstack.org/#/c/279072/)

For kilo, osa took the approach of pinning ansible-lint, rather than making the necessary changes to pass the new liniting test that ansible-lint 2.3.7 introduced - because kilo is technically a stable branch and so pinning introduces less flux.

In order to consume this pin (which is done in ```openstack-ansible/dev-requirements.txt```, which we consume), we are going to need an osa sha bump. We can't pin it ourselves directly in rpc-openstack because of the version specification that already exists in ```dev-requirements.txt``` from osa - when running tox you would get a ```double requirement given``` error (I've tried it).

**Comment by prometheanfire** [comment]
we fixed this in rpc-o in both master and kilo (close?)

**Comment by nrb** [comment]
As long as the relevant PRs are linked, yeah, I think closing this as a dupe is fine.
