### ISSUE TITLE
Change name of alert for disk_utilisation check

### ISSUE THREAD

**Issue by cemason** [rcbops/rpc-openstack#831]
Example output in ticket from this check when it alerts: 

"REASON: Disk utilisation for sdb >= 90%Disk utilisation for sdb >= 90%"

Desired output in ticket from this check when it alerts:

"REASON: Disk IO utilization for sdb >= 90%"

This check is giving us alerts that we mistakenly take for full disks, when in fact they are busy disks. Also, it is using the UK/Canadian spelling "utilisation" where most checks use US spellings. I don't have a preference, but it would be nice to standardize.  :)

- [x] Master #871 
- [x] liberty-12.0 #875
- [x] kilo #876

**Comment by byronmccollum** [comment]
This just bit me...spent a good chunk of time until I realized I was looking at the wrong check.

**Comment by prometheanfire** [comment]
@byronmccollum you working this?

**Comment by byronmccollum** [comment]
No I'm not working on it. Just saying I too was affected by the ambiguous check name. I don't know enough about what happens when renaming a check when using the new local configuration MaaS.

**Comment by mancdaz** [comment]
@byronmccollum it would be created as a completely new check, and the old one would get deleted along with any historical data. Probably nobody cares about historical data in the case of this check, but we'd need to clarify that before making the change.

**Comment by prometheanfire** [comment]
@cemason ^ you too

**Comment by mancdaz** [comment]
actually @cemason @byronmccollum @prometheanfire the check itself doesn't need to be renamed - what appears to be output as the REASON, is the text from the alarm https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/templates/disk_utilisation.yaml.j2#L17

Changing this text won't break or delete anything with the existing checks/alarms

**Comment by byronmccollum** [comment]
@mancdaz...sounds good.

just for my own understanding, if you do need to rename a check (and therefore a new check gets created), do you need to explicitly set something to remove the old check?

**Comment by prometheanfire** [comment]
yes

**Comment by prometheanfire** [comment]
@mancdaz that's the change I already made

**Comment by BjoernT** [comment]
:+1:
