### ISSUE TITLE
Snet configurations in the example config file need to be removed and added to rpc-extras

### ISSUE THREAD

**Issue by darrenchan** [rcbops/rpc-openstack#84]
For example:
https://github.com/stackforge/os-ansible-deployment/blob/master/etc/openstack_deploy/openstack_user_config.yml.example, line 23

**Comment by b3rnard0** [comment]
Needs more researching.

**Comment by claco** [comment]
Related to: https://github.com/rcbops/rpc-extras/issues/14

**Comment by b3rnard0** [comment]
@klevenstein Any feedback on this one? 

cc: @nrb

**Comment by nrb** [comment]
This is largely a doc request. @ionosphere80 is a good candidate.

**Comment by BjoernT** [comment]
Wrong product. Moved issues to https://bugs.launchpad.net/openstack-ansible/+bug/1542408 so we can close this one
