### ISSUE TITLE
r12.0.0rc1 - deploy.sh - rm: cannot remove ‘/etc/openstack_deploy/conf.d/aodh.yml’: No such file or directory 

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/rpc-openstack#842]
These conf.d files don't exist in OSA or RPC....

https://github.com/rcbops/rpc-openstack/blob/master/scripts/deploy.sh#L115-L116

```
rm: cannot remove ‘/etc/openstack_deploy/conf.d/aodh.yml’: No such file or directory 
```

- [x] Master (https://github.com/rcbops/rpc-openstack/pull/843)
- [x] liberty-12.0 (https://github.com/rcbops/rpc-openstack/pull/844)

**Comment by nrb** [comment]
Yep, correct - https://github.com/openstack/openstack-ansible/tree/liberty/etc/openstack_deploy/conf.d doesn't have them.

**Comment by prometheanfire** [comment]
those need to change to rm -f (which exits 0 when file not found)

**Comment by claco** [comment]
FWIW, the gate does not use deploy.sh.  http://jenkins.propter.net/job/RPC-AIO/1571/consoleFull

**Comment by prometheanfire** [comment]
from the same gate

    19:57:57 ********************** Run RPC Deploy Script ***********************
    19:57:57 + sudo DEPLOY_AIO=yes DEPLOY_HAPROXY=yes DEPLOY_TEMPEST=yes DEPLOY_CEPH=no DEPLOY_SWIFT=yes DEPLOY_MAAS=yes ANSIBLE_GIT_RELEASE=ssh_retry ANSIBLE_GIT_REPO=https://github.com/hughsaunders/ansible ADD_NEUTRON_AGENT_CHECKSUM_RULE=yes BOOTSTRAP_OPTS= bootstrap_host_ubuntu_repo=http://mirror.umd.edu/ubuntu/ bootstrap_host_ubuntu_security_repo=http://mirror.umd.edu/ubuntu/ scripts/deploy.sh

**Comment by byronmccollum** [comment]
I don't see the rm's right after the patcher runs...did that Jenkins run not include the the PR that introduced this change?

**Comment by prometheanfire** [comment]
that jenkins run was for #841 don't think that included #830 yet

**Comment by claco** [comment]
Here's the right build for 803, which passed:  http://jenkins.propter.net/job/RPC-AIO/1567/consoleFull

If did the rm just dandily it seems.

**Comment by byronmccollum** [comment]
The Ansible bootstrap-host is copying in the conf.d/*.yml.aio files...

```
18:25:22 TASK: [bootstrap-host | Deploy user conf.d configuration] ********************* 
18:25:22 changed: [localhost] => (item={'override': {}, 'name': 'aodh.yml.aio'})
18:25:22 changed: [localhost] => (item={'override': {}, 'name': 'ceilometer.yml.aio'})
18:25:22 changed: [localhost] => (item={'override': {}, 'name': 'swift.yml.aio'})
```

**Comment by byronmccollum** [comment]
This...which is AIO-ism only...

https://github.com/openstack/openstack-ansible/blob/liberty/tests/roles/bootstrap-host/tasks/prepare_aio_config.yml#L80-L94

**Comment by prometheanfire** [comment]
https://github.com/openstack/openstack-ansible/blob/master/tests/roles/bootstrap-host/tasks/prepare_aio_config.yml#L35-L38 too

./scripts/bootstrap-aio.sh calls bootstrap-host iirc

**Comment by odyssey4me** [comment]
Ah, so yes - for an AIO there is an assumption for which files are there. The better solution is therefore to ensure that there are no hosts allocated to the groups in the environment, and for the openstack infra hosts also ensure that the affinity is set to 0. This is perhaps a better solution anyway than simply removing the env files. My bad - I should have thought of that.

**Comment by nrb** [comment]
Following on from what Jesse said, simply not defining the groups in conf.d will work. My mistake for not double checking myself when writing down work to be done.

https://github.com/rcbops/rpc-openstack/pull/843#issuecomment-187339894

**Comment by jacobwagner** [comment]
QE has confirmed both the bug and the fix are present and work properly after the fix is applied

**Comment by nrb** [comment]
@jacobwagner And the fix is the one currently submitted?

**Comment by jacobwagner** [comment]
@nrb Correct, the -f fix. I cherry picked it in

**Comment by nrb** [comment]
@jacobwagner Ok - that actually changed per code review - see https://github.com/rcbops/rpc-openstack/pull/843. Sorry for pulling the rug out from under you guys :(

**Comment by jacobwagner** [comment]
Ok ill try that PR out

**Comment by jacobwagner** [comment]
@nrb https://github.com/rcbops/rpc-openstack/pull/843 has been verified by our deploy

**Comment by nrb** [comment]
Liberty backport: https://github.com/rcbops/rpc-openstack/pull/844

**Comment by prometheanfire** [comment]
fixed
