### ISSUE TITLE
rpc-support: Unnecessary host packages should be removed for old deployments 

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#845]
Starting with commit c6798eb778621819e13f0334778ff2d55d7ff2b1 we do not install the host packages on containers anymore but a remove task is missing to remove them from the old containers

- [ ] kilo

**Comment by prometheanfire** [comment]
this was kilo only, just docing that ehre

**Comment by prometheanfire** [comment]
closed based on PR and asking @BjoernT in irc
