### ISSUE TITLE
r12.0.0rc1 - Ceph Mon - Task "collect admin and bootstrap keys" Hangs w/ Multiple Infra Nodes

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/rpc-openstack#847]
When performing a multi-infra deployment (3 infra, 1 mon per infra), the task "collect admin and bootstrap keys" hangs.

https://github.com/ceph/ansible-ceph-mon/blob/master/tasks/start_monitor.yml#L53-L56

When all the mons are moved to a single infra (1 infra w/ affinity 3, and 2 infra w/ affinity 0), or when deploying with a single infra (w/ affinity 3), the task runs successfully.

All the mon containers are able to communicate with each other over the br-mgmt and br-storage networks.

**Comment by byronmccollum** [comment]
This may have something to do with my underlying network. Still investigating.

**Comment by byronmccollum** [comment]
I'm seeing a similar failure pattern (only works when services are co-located on the same host) when my Galera cluster is being built.

What is strange, is that this behavior is not being exhibited in earlier versions of RPC (10.1, 11.0, 11.1).

**Comment by byronmccollum** [comment]
Since I run an overlay network between my nodes, I had to lower container_mtu to 1450 to make things work. What I can't understand is why this exact same setup works just fine in earlier versions of RPC, where these container interfaces have the default MTU of 1500.

**Comment by b3rnard0** [comment]
We need to determine if this an issue specific to Byron's environment or whether this is an actual issue. I'm adding this to rc2 milestone for visibility but we are still not certain if this is an actual issue.

**Comment by byronmccollum** [comment]
@b3rnard0 I'm able to make it work as noted above, but I'm really interested in the *why*. Don't let this hold up the release, unless others are seeing the same issue using raw networks.

**Comment by b3rnard0** [comment]
@jacobwagner @jpmontez Would be great to determine if this issue appears when you start doing testing on the rc2.

**Comment by git-harry** [comment]
It doesn't look like there is anything to do here given the issue's age and the content of the comments so I will close it.
