### ISSUE TITLE
Branch name 'liberty-12.0' does not match format in contributing guidelines

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#850]
@d34dh0r53 https://github.com/rcbops/rpc-openstack/blob/master/CONTRIBUTING.md describes branches as being named by number e.g. '12.0' or '13.7'. The new liberty branch has been named 'liberty-12.0'. Based on the fact that the contributing guidelines have only just merged, it seems a bit early to be trying to change the format and so the branch should be renamed to '12.0'. If there is a strong argument for the format that is currently in place, the reasoning should be outlined and a pull request made to update the contributing text.

**Comment by prometheanfire** [comment]
my suggestion is to complete the docs (at least a bit) and then take actions.   We need to decide what we want to take from the other doc branches (if anything).

**Comment by claco** [comment]
So this happened for two reasons. First, we still have at least 3 versions of the workflow PRs floating around. Most of them don't spell out what to name the branch where the rc tag is made. Second, as part of that mess, there seemed to be some outstanding questions about if at the end of releases, we make a 'liberty' stable branch. If we do, imho, 'liberty-12.0', 'liberty-12.1', 'liberty' things seem to align better.

Frankly, it's fixable. QE should be using tags. So, at the status meeting this week, we can finalize and rename, because git.

**Comment by byronmccollum** [comment]
I'm throwing my vote in for numbered, long lived minor branches, ala "12.0", "12.1", not an all encompassing major / series "liberty" branch...



```
Master (next) -----> Branch "12.0" ---> Tag "12.0.0rc1" ---> Tag "12.0.0rc2" ---> Tag "12.0.0" --> Tag "12.0.1" ...
              \----> Branch "12.1" ---> Tag "12.1.0rc1" ---> Tag "12.1.0" ---> Tag "12.1.1" ...
```

**Comment by byronmccollum** [comment]
I prefer the long lived minor branches, because there will (have) arise situations where a bug fix is needed in say 12.0, but you don't want to force an upgrade to 12.1 (which could include new "features") just to get the bug fix.

**Comment by prometheanfire** [comment]
@byronmccollum the reason for having long live minor and major branches is so that we can continue development of 12.1 while 12.0.1 is also being develiop

**Comment by prometheanfire** [comment]
oops

**Comment by byronmccollum** [comment]
Then I'm thumbs up...

**Comment by byronmccollum** [comment]
Can some Kilo branches be created from their respective lineages to fulfill the naming convention set forth?

```
"kilo" Branch ---
                 \----> "kilo-11.1" Branch

"zzz-archive-kilo" Branch ---
                             \----> "kilo-11.0" Branch
```

I realize the "kilo-11.0" branch might be EOL'd, but having a clear source for the code, which follows the naming convention, would be nice.

**Comment by prometheanfire** [comment]
at the moment this is just going forward

**Comment by byronmccollum** [comment]
![please-sir-kindle-reconsider](https://cloud.githubusercontent.com/assets/954353/13331986/7fe46c74-dbc5-11e5-8b39-36454595232b.jpg)

**Comment by byronmccollum** [comment]
Typo fail

**Comment by byronmccollum** [comment]
![please-sir-kindly-reconsider](https://cloud.githubusercontent.com/assets/954353/13332050/c84b6594-dbc5-11e5-99b8-c5dd53d34a3c.jpg)
