### ISSUE TITLE
Multinode 12.0 deployments fail on os_cinder | Add in cinder devices types

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#852]
This is fixed upstream, the OSA SHA needs to be updated to include 9d03db957aca27f28af994131dd25a1a70bd05c8

- [x] Master #865 
- [x] liberty-12.0 (for rc) #870

**Comment by git-harry** [comment]
The review for the commit referenced above - https://review.openstack.org/#/c/276784

**Comment by prometheanfire** [comment]
why is this not going into rc2?  If it's not going into 12.0.0 is it targeted for 12.0.1 or 12.1.0?

**Comment by jacobwagner** [comment]
QE Verified that we are seeing this

TASK: [os_cinder | Add in cinder devices types] *******************************
skipping: [node89_cinder_scheduler_container-1d96acda] => (item=cinder_backends|dictsort)
skipping: [node89_cinder_api_container-15698120] => (item=cinder_backends|dictsort)
skipping: [node84_cinder_api_container-e33ed9d6] => (item=cinder_backends|dictsort)
skipping: [node98_cinder_api_container-61a9ffd8] => (item=cinder_backends|dictsort)
skipping: [node84_cinder_scheduler_container-825f0c67] => (item=cinder_backends|dictsort)
skipping: [node98_cinder_scheduler_container-f7592c57] => (item=cinder_backends|dictsort)
failed: [node118] => (item=(u'lvm', {u'volume_driver': u'cinder.volume.drivers.lvm.LVMISCSIDriver', u'volume_backend_name': u'LVM_iSCSI', u'volume_group': u'cinder-volume-hdd'})) => {"changed": true, "cmd": ". /root/openrc\n /openstack/venvs/cinder-12.0.5/bin/cinder type-create \"lvm\"\n /openstack/venvs/cinder-12.0.5/bin/cinder type-key \"lvm\" set volume_backend_name=\"LVM_iSCSI\"", "delta": "0:00:06.982501", "end": "2016-02-23 21:56:41.884749", "item": ["lvm", {"volume_backend_name": "LVM_iSCSI", "volume_driver": "cinder.volume.drivers.lvm.LVMISCSIDriver", "volume_group": "cinder-volume-hdd"}], "rc": 1, "start": "2016-02-23 21:56:34.902248", "warnings": []}
stderr: ERROR: Service Unavailable (HTTP 503)
ERROR: Service Unavailable (HTTP 503)
failed: [node119] => (item=(u'lvm', {u'volume_driver': u'cinder.volume.drivers.lvm.LVMISCSIDriver', u'volume_backend_name': u'LVM_iSCSI', u'volume_group': u'cinder-volume-hdd'})) => {"changed": true, "cmd": ". /root/openrc\n /openstack/venvs/cinder-12.0.5/bin/cinder type-create \"lvm\"\n /openstack/venvs/cinder-12.0.5/bin/cinder type-key \"lvm\" set volume_backend_name=\"LVM_iSCSI\"", "delta": "0:00:28.245239", "end": "2016-02-23 21:57:03.121274", "item": ["lvm", {"volume_backend_name": "LVM_iSCSI", "volume_driver": "cinder.volume.drivers.lvm.LVMISCSIDriver", "volume_group": "cinder-volume-hdd"}], "rc": 1, "start": "2016-02-23 21:56:34.876035", "warnings": []}
stderr: ERROR: Service Unavailable (HTTP 503)
ERROR: No volumetype with a name or ID of 'lvm' exists.
changed: [node118] => (item=(u'lvm_ssd', {u'volume_driver': u'cinder.volume.drivers.lvm.LVMISCSIDriver', u'volume_backend_name': u'LVM_iSCSISSD', u'volume_group': u'cinder-volume-ssd'}))
changed: [node119] => (item=(u'lvm_ssd', {u'volume_driver': u'cinder.volume.drivers.lvm.LVMISCSIDriver', u'volume_backend_name': u'LVM_iSCSISSD', u'volume_group': u'cinder-volume-ssd'}))

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
os_cinder | Add in cinder devices types -------------------------------- 47.70s
os_keystone | Ensure service tenant ------------------------------------ 29.44s
galera_client | Add galera repo(s) ------------------------------------- 28.48s
os_glance | Ensure glance user to admin role --------------------------- 20.98s
os_glance | Ensure glance endpoint ------------------------------------- 20.93s
os_keystone | Install apt packages ------------------------------------- 18.69s
os_keystone | Ensure Keystone Endpoint --------------------------------- 17.11s
os_cinder | Ensure cinder user to admin role --------------------------- 16.38s
os_cinder | Install apt packages --------------------------------------- 13.34s
pip_install | Install PIP ---------------------------------------------- 13.05s
           to retry, use: --limit @/root/setup-openstack.retry

node118                    : ok=56   changed=34   unreachable=0    failed=1
node119                    : ok=56   changed=33   unreachable=0    failed=1
node84_cinder_api_container-e33ed9d6 : ok=57   changed=37   unreachable=0    failed=0
node84_cinder_scheduler_container-825f0c67 : ok=57   changed=37   unreachable=0    failed=0
node84_glance_container-574af8fd : ok=80   changed=47   unreachable=0    failed=0
node84_keystone_container-ee43bb1a : ok=100  changed=50   unreachable=0    failed=0
node89_cinder_api_container-15698120 : ok=57   changed=37   unreachable=0    failed=0
node89_cinder_scheduler_container-1d96acda : ok=57   changed=36   unreachable=0    failed=0
node89_glance_container-533b6e49 : ok=80   changed=47   unreachable=0    failed=0
node89_keystone_container-d4e55b02 : ok=100  changed=50   unreachable=0    failed=0
node98_cinder_api_container-61a9ffd8 : ok=69   changed=46   unreachable=0    failed=0
node98_cinder_scheduler_container-f7592c57 : ok=57   changed=37   unreachable=0    failed=0
node98_glance_container-4b8e6d55 : ok=89   changed=55   unreachable=0    failed=0
node98_keystone_container-f254df6f : ok=119  changed=66   unreachable=0    failed=0

Will test commit has and post results

**Comment by jacobwagner** [comment]
So the commit stand alone isnt enough to fix this issue. It seems that the physical nodes will need httplib2 installed

```
TASK: [os_cinder | Ensure cinder api is available] ****************************
skipping: [node89_cinder_api_container-15698120]
skipping: [node98_cinder_api_container-61a9ffd8]
skipping: [node84_cinder_api_container-e33ed9d6]
<10.127.101.118> ESTABLISH CONNECTION FOR USER: root
<10.127.101.119> ESTABLISH CONNECTION FOR USER: root
skipping: [node98_cinder_scheduler_container-f7592c57]
skipping: [node89_cinder_scheduler_container-1d96acda]
<10.127.101.118> REMOTE_MODULE uri url=http://172.29.236.107:8776
<10.127.101.119> REMOTE_MODULE uri url=http://172.29.236.107:8776
<10.127.101.118> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 10.127.101.118 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
<10.127.101.119> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 10.127.101.119 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
skipping: [node84_cinder_scheduler_container-825f0c67]
<10.127.101.118> REMOTE_MODULE uri url=http://172.29.236.107:8776
<10.127.101.119> REMOTE_MODULE uri url=http://172.29.236.107:8776
<10.127.101.118> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 10.127.101.118 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
<10.127.101.119> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 10.127.101.119 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
Result from run 1 is: {u'msg': u'httplib2 is not installed', u'failed': True, 'attempts': 1}
Result from run 1 is: {u'msg': u'httplib2 is not installed', u'failed': True, 'attempts': 1}
<10.127.101.119> REMOTE_MODULE uri url=http://172.29.236.107:8776
<10.127.101.118> REMOTE_MODULE uri url=http://172.29.236.107:8776
<10.127.101.119> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 10.127.101.119 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
<10.127.101.118> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 10.127.101.118 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
Result from run 2 is: {u'msg': u'httplib2 is not installed', u'failed': True, 'attempts': 2}
Result from run 2 is: {u'msg': u'httplib2 is not installed', u'failed': True, 'attempts': 2}
<10.127.101.119> REMOTE_MODULE uri url=http://172.29.236.107:8776
<10.127.101.119> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 10.127.101.119 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
<10.127.101.118> REMOTE_MODULE uri url=http://172.29.236.107:8776
<10.127.101.118> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 10.127.101.118 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
Result from run 3 is: {u'msg': u'httplib2 is not installed', u'failed': True, 'attempts': 3}
Result from run 3 is: {u'msg': u'httplib2 is not installed', u'failed': True, 'attempts': 3}
<10.127.101.119> REMOTE_MODULE uri url=http://172.29.236.107:8776
<10.127.101.119> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 10.127.101.119 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
<10.127.101.118> REMOTE_MODULE uri url=http://172.29.236.107:8776
<10.127.101.118> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 10.127.101.118 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
Result from run 4 is: {u'msg': u'httplib2 is not installed', u'failed': True, 'attempts': 4}
Result from run 4 is: {u'msg': u'httplib2 is not installed', u'failed': True, 'attempts': 4}
<10.127.101.119> REMOTE_MODULE uri url=http://172.29.236.107:8776
<10.127.101.119> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 10.127.101.119 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
<10.127.101.118> REMOTE_MODULE uri url=http://172.29.236.107:8776
<10.127.101.118> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 10.127.101.118 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
Result from run 5 is: {u'msg': u'httplib2 is not installed', u'failed': True, 'attempts': 5}
Result from run 5 is: {u'msg': u'httplib2 is not installed', u'failed': True, 'attempts': 5}
```

**Comment by jacobwagner** [comment]
It seems like the physical hosts venv for cinder has httplib2 installed

```
root@node118:~# source /openstack/venvs/cinder-12.0.5/bin/activate
(cinder-12.0.5) root@node118:~# pip freeze
aioeventlet==0.4
alembic==0.8.3
amqp==1.4.8
anyjson==0.3.3
automaton==1.0.0
Babel==2.1.1
cachetools==1.1.5
cinder==7.0.2.dev9
cliff==1.15.0
cmd2==0.6.8
contextlib2==0.4.0
debtcollector==1.1.0
decorator==4.0.6
ecdsa==0.13
enum34==1.1.1
eventlet==0.17.4
fasteners==0.14.1
functools32==3.2.3.post2
futures==3.0.3
futurist==0.8.0
greenlet==0.4.9
httplib2==0.9.2
```

Im gonna dig around

**Comment by jacobwagner** [comment]
I manually installed httplib2 onto the hosts root pip environment and the play finished. Im not sure the order of operations here but it seems like the task is not using the venv to do the uri check

I am sure i am missing something

**Comment by byronmccollum** [comment]
In this context, httplib2 is a dependency of Ansible to use the URI module. Having httplib2 installed in a venv on the Cinder hosts will not work, unless there is a way to tell Ansible to use a specific venv.

So httplib2 needs to be install outside a venv (barring you can't tell Ansible to use a specific venv) on the Cinder hosts.

There is also the option of delegating to the deployment host, and adding httplib2 to the list of requirements used to bootstrap Ansible.

**Comment by git-harry** [comment]
@prometheanfire the bug needed QE verification before it could be targeted at rc2.

**Comment by git-harry** [comment]
@jacobwagner @byronmccollum the URI module does require httplib2, the master commit to fix this bug does add httplib2 as a required package. The liberty commit does not because httplib2 is already there [1]. This package should be installed on the cinder host by [2] prior to the use of the URI module.

[1] https://github.com/openstack/openstack-ansible/blob/liberty/playbooks/roles/os_cinder/defaults/main.yml#L235
[2] https://github.com/openstack/openstack-ansible/blob/liberty/playbooks/roles/os_cinder/tasks/cinder_install.yml#L40

**Comment by byronmccollum** [comment]
@jacobwagner Did you just cherry-pick in the upstream OSA commit, or did you do a SHA bump for the OSA submodule? There is another commit that adds httplib2 (https://github.com/openstack/openstack-ansible/commit/25606c27ca92172163abad8c4bb47ae0916d8360) which a SHA bump would account for.

**Comment by jacobwagner** [comment]
I cherry-picked this specific commit and didnt sha bump.

If this has been resolved then we will redeploy with rc2 when it is cut, with the understanding that the httplib2 requirement commit will also be included in the new sha

**Comment by mancdaz** [comment]
We can cherry-pick the OSA sha bump from master into liberty-12.0 once it gates https://github.com/rcbops/rpc-openstack/pull/865
