### ISSUE TITLE
better config for 10G interfaces

### ISSUE THREAD

**Issue by prometheanfire** [rcbops/rpc-openstack#854]
Just something to investegate

https://pastebin.com/embed_iframe/kUHdWPMn

- [ ] all branches?

**Comment by claco** [comment]
Bringing in some eyeballs. @JCallicoat @Apsu @busterswt @BjoernT

**Comment by prometheanfire** [comment]
ya, this is something I want to look at too, just noting it so I don't forget

**Comment by prometheanfire** [comment]
# connection limits, some for connection count, some for connection speed
    net.core.somaxconn = 64000
    net.core.netdev_max_backlog = 524288
    net.netfilter.nf_conntrack_max = 1048576
    net.ipv4.tcp_max_syn_backlog = 48960
    net.ipv4.tcp_max_tw_buckets = 1440000
    net.ipv4.tcp_max_orphans = 456000
    # conntrack changes, mainly for handling a ton of connections at a time
    net.netfilter.nf_conntrack_tcp_timeout_established = 30
    net.netfilter.nf_conntrack_tcp_timeout_unacknowledged = 10
    net.netfilter.nf_conntrack_tcp_timeout_syn_recv = 10
    net.netfilter.nf_conntrack_tcp_timeout_syn_sent = 10
    net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 4
    net.netfilter.nf_conntrack_tcp_timeout_close_wait = 4
    net.netfilter.nf_conntrack_tcp_timeout_last_ack = 10
    net.netfilter.nf_conntrack_tcp_timeout_time_wait = 10
    net.netfilter.nf_conntrack_tcp_timeout_max_retrans = 15
    net.netfilter.nf_conntrack_tcp_timeout_unacknowledged = 10
    net.netfilter.nf_conntrack_tcp_timeout_close = 10
    net.netfilter.nf_conntrack_udp_timeout = 15
    net.netfilter.nf_conntrack_udp_timeout_stream = 15
    net.netfilter.nf_conntrack_tcp_loose = 0
        # may change above to 1 which would cause it to track less stuff
    net.netfilter.nf_conntrack_tcp_max_retrans = 3
    # buffers, useful for speed
    net.core.rmem_default = 31457280
    net.core.rmem_max = 12582912
    net.core.wmem_default = 31457280
    net.core.wmem_max = 12582912
    net.core.optmem_max = 25165824
    net.ipv4.tcp_mem = 131072 1048576 1441792
    net.ipv4.tcp_rmem = 8192 87380 16777216
    net.ipv4.tcp_wmem = 8192 65536 16777216
    net.ipv4.udp_mem = 65536 131072 262144
    net.ipv4.udp_rmem_min = 16384
    net.ipv4.udp_wmem_min = 16384
    # timeouts, conn count mainly, but the defaults are a bit high for most usage
    net.ipv4.tcp_fin_timeout = 10
    net.ipv4.tcp_keepalive_time = 300
    net.ipv4.tcp_keepalive_probes = 5
    net.ipv4.tcp_keepalive_intvl = 10
    net.ipv4.tcp_synack_retries = 2
    # settings
    net.ipv4.tcp_rfc1337 = 1
    net.ipv4.tcp_tw_recycle = 1  # high connection counts, and new connections per second, enable if reuse isn't good enough only
    net.ipv4.tcp_tw_reuse = 1
    net.ipv4.tcp_slow_start_after_idle = 0 # useful to not renegotiate window size too often
    net.ipv4.conf.all.log_martians = 1

**Comment by BjoernT** [comment]
Nice list but I would say many values are way too high. What do you want with a syn backlog of 48k connection for example ? The more is usually not the better...
Currently we use net.ipv4.tcp_tw_reuse  for swift, and the tcp/udp rmem/wmem, net.netfilter.nf_conntrack_max   for all other hosts. 
net.ipv4.conf.all.log_martians is usually 1 already
net.ipv4.tcp_rfc1337 why enabling when the kernel has it disabled by default, not sure if we want risk arbitrary stack behavior.

In short do not touch any other parameter, especially timeouts, unless needed.
Those have no effect if the NIC speed is 1 or 10G,  tcp/udp rmem/wmem are much more important along with txqueue len on the NIC and jumbo frames

I personally would OK only net.ipv4.tcp_tw_reuse, tcp/udp rmem/wmem and net.netfilter.nf_conntrack_max.
max_syn_backlog can be changed when needed but if you have to enable it then there's something wrong with your application anyway, not fast enough processing the requests

**Comment by prometheanfire** [comment]
these are mostly for extremely high connection counts, the issue is here for discussion.

the main ones I see us using are these and the rmem.

    net.ipv4.tcp_tw_reuse = 1
    net.ipv4.tcp_slow_start_after_idle = 0

lowering the nf_conntrack_tcp_timeout_established time to something more sane then the default of 432000.  Many of the nf_conntrack stuff should probably be lower than defaults.

**Comment by d34dh0r53** [comment]
We use the OSA defaults which are generally ok, some customer specific tuning is done but generalized pre-emptive tuning is a bad idea @prometheanfire.
