### ISSUE TITLE
Kilo we need to make sure 'UsePAM Yes' is enabled where needed in sshd config.

### ISSUE THREAD

**Issue by timolow** [rcbops/rpc-openstack#859]
Having  'UsePAM = No' in sshd will cause os-swift-sync play to fail.  When the swift user is created on the object nodes, the users password is blank, an '!' is added to /etc/shadow preventing swift user from logging in, sshd is treating the user as disabled.  Changing the ! to a * in /etc/shadow will allow play to finish or turn 'UsePAM = Yes' and restart sshd. 

Tim

**Comment by claco** [comment]
@timolow do you have any background on this? I'm under the impression the default for Ubuntu is `UsePAM = yes`, which might indicate we've never seen this before, even in QE. Do we have any insight as to why/who/where it is now defaulting to `UsePAM = no`?

**Comment by timolow** [comment]
@claco Im not sure why my vanilla ubuntu nodes defaulted to UsePAM = NO, it appears that default isn't default in ubuntu (http://manpages.ubuntu.com/manpages/wily/man5/sshd_config.5.html):

Note that the Debian openssh-server package sets several options as
     standard in /etc/ssh/sshd_config which are not the default in sshd(8).
     The exact list depends on whether the package was installed fresh or
     upgraded from various possible previous versions, but includes at least
     the following:

           ·   UsePAM yes

If you keep reading:
If UsePAM is enabled, you will not be able to run sshd(8) as a
             non-root user.  The default is “no”.


So it really depends on how the openssh-server was installed.  My default kicks I had no reason to revert UsePAM=NO, if swift-os-sync requires the swift account to be unlocked, we should make sure that ansible is prepping the host correctly for both UsePAM cases.

**Comment by claco** [comment]
Thanks for the update. I'm mostly hoping to understand the situation. This is one of those grey areas where we assume a working ssh ahead of the install, and I think [could be wrong here] generally, we've avoided having the install tweak some core system things like ssh as part of the install. I could be wrong on that. Might be worth some additional chat just to make sure where we need the fix: in pre flight checks, in the install itself, or other.

**Comment by timolow** [comment]
@claco If updating sshd_config isnt an option, what about unlocking the swift user?

**Comment by byronmccollum** [comment]
Tangent, but if we do decide to start managing `sshd_config`, then there are other optimization that can be made, like `MaxStartups` that will allow for `FORKS` > 10.

**Comment by BjoernT** [comment]
I will send out a PR for the os-swift role, this should not be in rpc-openstack.
My opinion is quite simple, if we need to PAM enabled in SSHD for swift to do all the syncs then we
need to explicitly check for it, like we did inside the repo_server role.
Also if it is default in ubuntu we can’t assume that customers in CDC or wherever change it so back to actually checking it.

We can close this bug here and I fix up upstream

**Comment by prometheanfire** [comment]
If it is checked I feel like that's all it should be especially if done via upstream.  Check that `UsePAM = yes` and fail/exit 1 if not.  This could open up pandora's box in checking for things that are expected though, do we need to make sure the ssh binary is properly linked, that the cpu properly follows the generic spec for x86_64, and on down that rabbit hole.

I agree that this isn't a problem with OSA or RPC-O though, as it's defaulted to yes in ubuntu (what RPC-O and OSA both use).  I also feel we can close that here, but will leave that to someone else.

**Comment by timolow** [comment]
@prometheanfire couldn't we unlock the swift user if UsePam = Yes

**Comment by prometheanfire** [comment]
The swift user being locked is needed because it has no password, iirc, you can su to that user or log in without password otherwise, not so good.  (need to look that up)

**Comment by timolow** [comment]
@prometheanfire if that is the case, then UsePam = yes is requirement of os-swift-sync to work, but we won't check for that condition to be true before we start the run and then silently fail?

**Comment by prometheanfire** [comment]
No, I think it's fine to add the check (to usptream OSA), but not to manage the ssh config file.  Just exit fail bomb out, etc if it's a not enabled.

**Comment by claco** [comment]
What about unlock the user, but set a random long password?

**Comment by prometheanfire** [comment]
That would work too, but would be an upstream fix as well (as that's where the user is created).

**Comment by BjoernT** [comment]
No passwords please, that causes audit issues and stupid requests like password rotation procedures etc.

**Comment by BjoernT** [comment]
Flame-war start :  https://review.openstack.org/284396

**Comment by prometheanfire** [comment]
dunno what's flamish about it

**Comment by prometheanfire** [comment]
question, is this needed to be backported to kilo/liberty, if so why.

**Comment by BjoernT** [comment]
yeah you are not on the mail thread with some OSA folks. We would like to backport that in all active releases

**Comment by prometheanfire** [comment]
if it's not public it doesn't exist :P

**Comment by BjoernT** [comment]
Yeah like black holes

**Comment by prometheanfire** [comment]
Ok, so I'm going to close this issue as it doesn't affect our product (default ubuntu installs are fine).  We'll get a 'fix' when/if upstream acts on it.
