### ISSUE TITLE
New nova db pool seetings needed

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#861]
I just realized that 
https://github.com/rcbops/rpc-openstack/blob/master/rpcd/etc/openstack_deploy/user_variables.yml

does not include the nova DB settings, which needs to be added ASAP

- [x] [Master](https://github.com/rcbops/rpc-openstack/pull/862)
- [x] [liberty-12.0.1](https://github.com/rcbops/rpc-openstack/pull/886)
- [x] [Kilo](https://github.com/rcbops/rpc-openstack/pull/887)

**Comment by prometheanfire** [comment]
@BjoernT what branches should this target and any specific releases?

**Comment by BjoernT** [comment]
all active ones, back to kilo

**Comment by prometheanfire** [comment]
what is the urgency of this?

**Comment by BjoernT** [comment]
We missed it and no larger deployment does function without increased settings

**Comment by prometheanfire** [comment]
thanks, the issue helps in our prioritization.

**Comment by BjoernT** [comment]
yeah if RPC12 would be closer I would say not back port necessary but we will still build cluster with RPC11
