### ISSUE TITLE
change default token provider to fernet

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#873]
In kilo we overrode the default token provider in rpc-o to uuid (the default in osa was set to fernet). This proved to be a decent approach as there were subsequent problems with fernet.

For liberty, most of the problems have been addressed. Comments from the 2 keystone developers (dolph and lbragstad) regarding the current state of fernet:

**dolph**: *"I don't think we have any reasoning to recommend deployers use anything but Fernet today."*

**lbragstad**: *"The most recent “oddities” that have been circulating upstream are related to trusts + Fernet + the usage of v2.0. If a deployment issues Fernet tokens and a user obtains a trust scoped token using v3 can/should they be using that token to make v2.0 calls. This use case isn’t documented upstream but it is what we are trying to solve for since it wasn’t forbidden in the past with UUID tokens.*
*The unofficial decision to push making Fernet [in upstream kilo] the default was made this morning. Adam, Dolph and I are going continue fixing oddities through-out the Mitaka release so that we should be good to make that switch first thing in Newton.*

*If you see any oddities on your end, please let us know."*

We probably want to remove the override and test with fernet.

**Comment by mancdaz** [comment]
@d34dh0r53 @claco for rc3? Maybe we should have already done this in rc2 so that QE are testing 'the thing' ?

**Comment by git-harry** [comment]
The agreement for 12 is that there will be no new features beyond what is naturally gained by moving to the new release. Making this change is effectively introducing something new that possibly has the potential to impact QE, docs, support etc.

That said the change is simple enough to implement, is using something that is the default for OSA and is something that can be set by support currently. I have created a patch in case this does become a last minute addition.

**Comment by d34dh0r53** [comment]
This is something we should bring up in our next meeting, not sure if this constitutes a new feature or not.  That said I'm hesitant to introduce it in the middle of an RC cycle, perhaps r12.1.0.

**Comment by d34dh0r53** [comment]
Setting milestone now so that this doesn't get lost in the mix

**Comment by git-harry** [comment]
This work is being tracked in https://github.com/rcbops/u-suk-dev/issues/134 and so I am closing this issue in favour of that one.
