### ISSUE TITLE
os_swift fails apt package install for liberasurecode1, liberasurecode-dev due to trusty backports not being enabled on physical nodes

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/rpc-openstack#892]
##### What version (commit) do you encounter this issue on?
r12.0.0rc2

##### What type of issue is this (bug, feature, documentation, regression)?
bug, regression

##### What is the expected behavior?
Installation of required apt packages succeeds for os_swift role

##### What is actually happening?
Failing to install due to missing apt.sources

##### How can we reproduce this issue?
Install os_swift on rackspace kicked servers

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
The user could update the apt sources file by hand, we have done this before

http://docs.rackspace.com/rpc/api/v11/bk-rpc-upgrade/content/upgrade-v10-v11.html#upgrade-v10-v11-pre-trusty-backports

##### What is your evaluation on the importance of this issue, and why?
This is a blocker for swift installs as the physical hosts are configured wrong and will not get required packages

##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [x] Master
- [x] liberty-12.0

This is an OSA bug and it is being tracked here
https://bugs.launchpad.net/openstack-ansible/+bug/1555793

**Comment by jacobwagner** [comment]
enabling backport fixed the issue

```
TASK: [os_swift | Install apt packages] ***************************************
changed: [573963-storage01] => (item=curl,gcc,git-core,liberasurecode1,liberasurecode-dev,libffi-dev,openssh-server,python-dev,rsync)
changed: [573964-storage02] => (item=curl,gcc,git-core,liberasurecode1,liberasurecode-dev,libffi-dev,openssh-server,python-dev,rsync)
changed: [573965-storage03] => (item=curl,gcc,git-core,liberasurecode1,liberasurecode-dev,libffi-dev,openssh-server,python-dev,rsync)
```

**Comment by nrb** [comment]
This is enabled on all [lxc hosts](https://github.com/openstack/openstack-ansible/blob/liberty/playbooks/roles/lxc_hosts/templates/sources.list.j2#L4). `os_swift` [requires liberasurecode1](https://github.com/openstack/openstack-ansible/blob/liberty/playbooks/roles/os_swift/defaults/main.yml#L211), which is only in the backports.

This has been encountered before in #338.

**Comment by andymcc** [comment]
The sources.list.j2 we manage is only for the containers, which is correct, we do ensure that package exists on containers since we are creating those and can easily control the repositories they use whilst remaining certain we aren't overwriting the deployers initial host configuration.

We don't manage the repositories that are installed/setup on physical hosts - we could do this in our rpc-openstack install I imagine, although I was under the impression our default kick already included this, so it wasn't necessary? 

We do need to be careful in CDC since we can't be sure what repo's the customer would be using - and blanket templating of physical hosts sources.list will clear any existing repos that they may need. For our DC it would probably be safe, but then we shouldn't need it because the image should include it.

I feel like this should be a documentation piece?

**Comment by claco** [comment]
Yeah, pretty sure @nrb found that is was documented for upgrades, but not greenfields. So likely needs an update there.

**Comment by prometheanfire** [comment]
notifying @klevenstein for greenfield docs update

**Comment by nrb** [comment]
I'd agree this sounds like docs, given the impact on CDCs. Though I also think sources.list could only be applied to the swift servers, it's totally possible a bug in that could screw up the host machine.

> We don't manage the repositories that are installed/setup on physical hosts - we could do this in our rpc-openstack install I imagine, although I was under the impression our default kick already included this, so it wasn't necessary? 

Evidently not; the standard Ubuntu image has backports enabled, but not the Rackspace image.

**Comment by nrb** [comment]
https://github.com/rackerlabs/docs-rpc/blob/master/doc/rpc-swift/ch-object-storage-prereqs.rst has this documented, but the `/opt/os-ansible-deployment/rpc_deployment` directory needs to be updated to `/opt/rpc-openstack/openstack-ansible/playbooks`

**Comment by prometheanfire** [comment]
pr submitted https://github.com/rackerlabs/docs-rpc/pull/202

**Comment by prometheanfire** [comment]
this was completed as a doc change, closing
