### ISSUE TITLE
Update SHAs for r11.1.6

### ISSUE THREAD

**Issue by d34dh0r53** [rcbops/rpc-openstack#899]
##### What version (commit) do you encounter this issue on?
`r11.1.6`

##### What type of issue is this (bug, feature, documentation, regression)?
Minor release

##### What is the expected behavior?
N/A

##### What is actually happening?
N/A

##### How can we reproduce this issue?
N/A

##### How can we verify your issue is addressed?
N/A

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
N/A

##### What is your evaluation on the importance of this issue, and why?
High

##### What branches / milestones do you believe this issue should target?
- [x] kilo

**Comment by prometheanfire** [comment]
this is waiting on OSA 11.2.12 to be tagged.
