### ISSUE TITLE
Elasticsearch curator fails to install

### ISSUE THREAD

**Issue by hughsaunders** [rcbops/rpc-openstack#902]
##### What version (commit) do you encounter this issue on?
Master
##### What type of issue is this (bug, feature, documentation, regression)?
Regression
##### What is the expected behavior?
Elasticsearch pip packages install
##### What is actually happening?
Elasticsearch curator fails to install because v3.5 of elasticsearch curator requires elasticsearch>2.3.0, but we pin elasticsearch<2.1.0

```
07:26:55 TASK: [elasticsearch | Install pip packages] ********************************** 
07:26:55 changed: [jrpcaioiad-578_elasticsearch_container-3416a30f] => (item=elasticsearch<2.1.0)
07:26:55 failed: [jrpcaioiad-578_elasticsearch_container-3416a30f] => (item=elasticsearch-curator) => {"attempts": 5, "cmd": "/usr/local/bin/pip install elasticsearch-curator", "failed": true, "item": "elasticsearch-curator"}
07:26:55 msg: Task failed as maximum retries was encountered
07:26:55 
07:26:55 FATAL: all hosts have already failed -- aborting
```
##### How can we reproduce this issue?
try and deploy rpc-openstack master
##### How can we verify your issue is addressed?
Jenkins builds will succeed
##### What is your evaluation on the importance of this issue, and why?
Needs to be resolved, because its blocking rpc gating.
##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [x] Master: #901 
- [x] liberty-12.0 #905

**Comment by d34dh0r53** [comment]
@hughsaunders did the pin work?

**Comment by hughsaunders** [comment]
@d34dh0r53 yes.

**Comment by prometheanfire** [comment]
this doesn't need kilo?

**Comment by hughsaunders** [comment]
Not directly, because elasticsearch wasn't pinned in kilo.

**Comment by prometheanfire** [comment]
ok, closing
