### ISSUE TITLE
Update OSA SHA to include latest fixes

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#906]
##### What version (commit) do you encounter this issue on?
127950076bb7a883e3e25a645adc7eb33e502677
##### What type of issue is this (bug, feature, documentation, regression)?
Bug
##### What is your evaluation on the importance of this issue, and why?
This is required for 12.1.0, it pulls in the latest OSA Liberty fixes including addressing the Neutron port security upgrade issue.
##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [x] Master

**Comment by prometheanfire** [comment]
closed as this is an upgrade only thing
