### ISSUE TITLE
Elasticsearch not reachable through tunnel

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#916]
##### What version (commit) do you encounter this issue on?

ALL RPC versions

##### What type of issue is this (bug, feature, documentation, regression)?

feature

##### What is the expected behavior?

No hard coded server URLs

##### What is actually happening?

After login into kibana, the Kibana fronted will create HTTP urls to absolute server URLs which can not be reached through SSH tunnels

##### How can we reproduce this issue?

ssh rack@server -L8443:172.29.236.10:8443
and login into https://localhost:8443

##### How can we verify your issue is addressed?

It works

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Small issue

##### What is your evaluation on the importance of this issue, and why?

Normal prio, I fix it myself

##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [x] Master
- [x] liberty-12.0
- [x] liberty-12.1
- [x] kilo

**Comment by BjoernT** [comment]
PR in progress

**Comment by prometheanfire** [comment]
needs backports

**Comment by BjoernT** [comment]
See PR for backports

**Comment by prometheanfire** [comment]
needs kilo backport as well :D

**Comment by BjoernT** [comment]
@prometheanfire  https://github.com/rcbops/rpc-openstack/pull/943 is for kilo

**Comment by prometheanfire** [comment]
right, just 12.0.1 then

**Comment by BjoernT** [comment]
yeah the branch you secretly created over the weekend ;-)

**Comment by prometheanfire** [comment]
nah, no secret there :P

**Comment by BjoernT** [comment]
Ha, already is part of the 12.1 branch
