### ISSUE TITLE
Can a clean cherry-picked backport be voted on by the backporter?

### ISSUE THREAD

**Issue by prometheanfire** [rcbops/rpc-openstack#921]
##### What version (commit) do you encounter this issue on?
backports

##### What type of issue is this (bug, feature, documentation, regression)?
documentation

##### What is the expected behavior?
unknown

##### What is actually happening?
limbo

##### How can we reproduce this issue?
do a backport

##### How can we verify your issue is addressed?
doc who can vote and in what situations they cannot vote

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
doc

##### What is your evaluation on the importance of this issue, and why?
minor

##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [ ] Master

**Comment by stevelle** [comment]
Presumptions:
1) The backport is from master to a target branch for an issue that was previously tagged for this backport during triage. 
2) The original PR was was authored by person A.
3) The backport is performed by someone other than A, call that individual B.
4) The backport is a clean cherry-pick. 

One answer to use as a punching bag:
Either A or B may provide a +1, but not both.

**Comment by git-harry** [comment]
The purpose of the review process is to provide a reasonable level of scrutiny to any new code and not just tick a box. There will always be situations that are difficult to describe in the guidelines and so it is never unreasonable to ask others on the team to provide additional feedback. For example, what if A, B, C and D work on a commit and then E backports it.

I think the general principle is that any commit requires the involvement of at least 3 people. The individual submitting the pull request and two reviewers who have agreed that the patch should be merged. To use @stevelle's example, A giving a +1 to B's backport is equivalent to A doing the backport and B providing the +1.

**Comment by hughsaunders** [comment]
As @git-harry said, 3 People must approve each patch - the submitter's approval is implied, the first reviewer adds :+1: and the second merges. Each person may only perform one of those roles. IMO if the author is not the submitter, then they are free to vote. This is consistent with authors being allowed to submit backports of their own patches. 

To answer @prometheanfire's original question: no. The backporter has shown their support by submitting the backport, they should not vote on it as well.

**Comment by prometheanfire** [comment]
ok, then we should doc this :P

**Comment by stevelle** [comment]
So the answer emerging here is that there are no fast tracks, no expedite lanes, no short cuts.
Purpose served.

**Comment by prometheanfire** [comment]
right, just wanted it explicit :P  either...

1. I can vote on a cherry-pick that I submit and the original author can't
2. I can't vote on a cherry-pick that I submit and the original author can
3. Neither the original author or I can vote on a cherry-pick that I submit

seems like we are going with option 2

**Comment by stevelle** [comment]
Agreeing that this is what I see represented so far. Also, I'm not going to argue for another outcome.
