### ISSUE TITLE
cinder_service_check unable to find host in service list

### ISSUE THREAD

**Issue by xeregin** [rcbops/rpc-openstack#924]
This issue was discovered in r12.0.0rc2
From what I can tell, this is due to the fact that MaaS is configured to look for (in this case) '**573963-storage01@**'
The related entries in the service list are as follows:
  573963-storage01.qe-iad3-2.rpc.rackspace.com@lvm
  573963-storage01.qe-iad3-2.rpc.rackspace.com@lvm_ssd
  573963-storage01.qe-iad3-2.rpc.rackspace.com@emc_vnx

The command that is executed by MaaS is as follows:
cinder_service_check.py --host 573963-storage01 172.20.236.10

The output is as follows:
status error No host(s) found in the service list

With a standard installation of MaaS, it's already in alert status. This would probably be an important fix for the Support side.

**Comment by xeregin** [comment]
Either the scripts setting up the MaaS checks need to include the rest of the FQDN, or the python script that performs the actual check should not include the '@' symbol. Either case should fix this bug...

**Comment by b3rnard0** [comment]
@xeregin Can you please use the new template for this bug (https://github.com/rcbops/rpc-openstack/issues/new)? Thanks in advance.

**Comment by d34dh0r53** [comment]
@git-harry can you look at this during your day?  Based on the issue hopefully it's an easy fix.  After talking with @tbyrom138 we're not treating this as a blocker for RC3.

**Comment by git-harry** [comment]
@d34dh0r53 only if you're happy to wait till Tuesday.

**Comment by claco** [comment]
Personally, I'd think we would want to correct the hostname going into the alarm check setup, and not lter the search using @, since that was on purpose.

@BjoernT @busterswt @cemason @codebauss @timolow Can any of you shed some light on what we see most commonly in our installations? Do most installs not have a sub domain/domain name, or are we using some other work around, etc?  Thanks!

**Comment by BjoernT** [comment]
I would not alter the hostname either and just delimit by the @ sign. Also most installations seem to use the ansible hostnames rather than FQDN, this is more a QE thing

**Comment by d34dh0r53** [comment]
So, I'm going to table this for RC3 as it's not a blocker.  Relevant folks please continue to work this either as a docs issue or a bug.

**Comment by prometheanfire** [comment]
does this get backports and to what?

**Comment by git-harry** [comment]
@prometheanfire this has been targeted at r12.0.0rc4 however seeing as that tag has already been created it will have to go in the next milestone for the liberty-12.0 branch.

**Comment by prometheanfire** [comment]
Ah, then this needs the list of branches in the top comment.

**Comment by prometheanfire** [comment]
merged in master and liberty-12.0, closing
