### ISSUE TITLE
Disable port security for all Liberty releases

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#929]
In OpenStack-Ansible, a [bug was discovered](https://bugs.launchpad.net/neutron/+bug/1509312) that prevented networks created prior to the portsecurity extension being enabled from functioning. Neutron currently has no (released) way of cleanly handling networks that were created while the extension wasn't enabled, though [a patch merged into master](https://review.openstack.org/#/c/294132/) to fix that behavior.

[An Openstack-Ansible patch](https://review.openstack.org/#/c/294243/) was merged to disable the portsecurity extension in Kilo to Liberty upgrades, since it was made the default. Upgrading from Kilo to Liberty made VMs connected to networks created pre-Liberty break; they would not boot, simply entering an ERROR state.

This behavior from OSA means that greenfield installs would have port security enabled, while upgrades from Kilo would not. Such a split becomes a maintenance and support burden, and thus RPC would like to keep behavior the same regardless of how the environment came to Liberty.

- [x] Master
- [x] liberty-12.2
- [x] liberty-12.1
- [x] liberty-12.0

**Comment by nrb** [comment]
@BjoernT I will work on a patch for this today.

**Comment by odyssey4me** [comment]
If the intension is to enable it from Liberty onwards, I would recommend a release note to ensure that it's explicitly clear that this is happening. Some deployments may unwittingly be relying on the lack of port security as a 'feature' and that's only likely to become known after an upgrade is complete and people start yelling.

While I'm not entirely certain of the use-cases which would use it as a 'feature', I suspect that deployments that implement virtual IP's (Microsoft Cluster Services, haproxy implementations with keepalived, etc) are likely to be those that are at the highest risk of not working afterwards.

**Comment by b3rnard0** [comment]
@claco If this is going to affect QE's testing of r12.0, let's a summary over to them.

cc: @tbyrom138

**Comment by nrb** [comment]
@odyssey4me The intention is to keep it off in order to keep RPC installs more or less the same; not doing so would mean environments initially installed with a 12.x release would have port security enabled, while environments upgraded to a 12.x release wouldn't have it. To my knowledge the concern wasn't about port security itself breaking anything, but rather the disparity in between installs based on how they got to the 12.x/Liberty series. The upgrade case happens to be the most restrictive and lowest common denominator.

I don't know if the change to Neutron allowing for graceful handling of this will be backported, but I think it's probably better to move to the functionality when it can be safely turned on without breaking existing environments.

**Comment by nrb** [comment]
I don't believe this will impact QE testing beyond ensuring that the extension is indeed disabled. I included the impacts-qe tag as a way to notify them that it's included, though.

**Comment by tbyrom138** [comment]
cc @jpmontez @jacobwagner @weezer for awareness

**Comment by d34dh0r53** [comment]
The more I think about this and after having conversations with some security minded folks I think it is a *very* bad idea to do this for greenfields.  We are sacrificing security for some perceived convenience of not having disparate environments.  I think efforts should be focused on getting our upgraded customers to a state where we can enable the extension and handle the ones that absolutely cannot on a case by case basis.  I've still plus 1'd the PR and won't block it from going in but I think those arguing for disabling the extension should seriously look at the reasoning for doing so.

**Comment by major** [comment]
I definitely understand the value in keeping port security disabled for upgrades. After speaking to @prometheanfire about some of the shenanigans about ports not being populated with port security in the database, that stance is certainly understandable.

However, disabling port security by default on greenfield deployments is a concern. Even on trusted networks, port security provides real benefits for deployers and users.

**Comment by nrb** [comment]
I am all for dropping this PR. I think there needs to be a conversation with support about it though. @BjoernT @JCallicoat what are your thoughts about Dave and Major's comments?

**Comment by hughsaunders** [comment]
:-1: I agree that it seems odd to reduce security of greenfield deploys to solve an upgrade bug.

**Comment by prometheanfire** [comment]
still an issue and what we are trying to avoid, patch hasn't backported to mitaka or liberty

**Comment by busterswt** [comment]
Got it. So in that case, I'm in favor of enabling the port security extension for greenfield environments (kilo or liberty) and not enabling the extension on upgrades until the patch is backported. Worse case, this means that existing deployments that go through an upgrade keep existing functionality. New environments can utilize the port security extension as intended. 

Thoughts? Not sure how easy this is to implement. Or, you can simply not enable the port security extension in either case until the patch is backported. No harm, no foul.

**Comment by BjoernT** [comment]
So my stand on this was we should either enable/disable for a release no matter if the release has been upgraded or fresh installed. Also not enabling it does not make openstack more unsecure, because the anti spoofing is still there for as long as not doing --port-security-enabled=False per port. I would enable this feature with a 12.x release so we can do installs and upgrades with the same features and then add it once the patch merges as RPC feature

**Comment by nrb** [comment]
The core of the issue from an OSA/rpc-openstack POV is that neutron doesn't handle turning the extension on post-openstack install gracefully. For example, we were to install a Liberty cluster without it enabled, then try to turn it on, as things stand now the networks/ports created prior would no longer function. The same would apply if this was done in Kilo - install the stack, create networks, enable the plugin, networks break.

I will note, however, that [the bug](https://bugs.launchpad.net/neutron/+bug/1509312) got backport patches all the way to Kilo today, so hopefully they will actually get merged.

**Comment by nrb** [comment]
>  Not sure how easy this is to implement.

@busterswt Your recommendation is essentially what existing code (minus PR #933) does. PR #933 disables the plugin regardless of how the install got to Liberty, via greenfield or upgrade.

**Comment by nrb** [comment]
@tbreeds Would you mind having a look at https://review.openstack.org/#/c/299212/ and https://review.openstack.org/#/c/299204/ for Neutron's stable/liberty branch? These patches will help us move customers from Kilo to Liberty.

https://review.openstack.org/#/c/299218/ and https://review.openstack.org/#/c/299217/ are the backports to Kilo, but I'm not sure they're as important to RPC customers at this point, as all of those customers will keep the port security extension disabled.

**Comment by tbreeds** [comment]
I've had a look at those reviews and they're not straightforward (in terms of stable policy)  Ihar is a stable-maint-core so I suspect he's considered the corner cases but right now I'm not in a position to +2 them.

I'll take another run at them when I have cycles

**Comment by odyssey4me** [comment]
> anti spoofing is still there for as long as not doing --port-security-enabled=False per port

@BjoernT as a point of clarification, the crux of the issue is that with port security enabled right now, ``--port-security-enabled=False`` is not respected in the current Neutron code. This means that in an upgrade situation where the port security extension was not enabled in Kilo (but it is enabled after the upgrade), all networks which have port security disabled end up being blocked.

Another point of clarification is that there is no ARP spoofing protection by default in Kilo or Liberty. We did try to enable it by default in Liberty initially, [but was disabled soon afterwards](https://github.com/openstack/openstack-ansible/blob/liberty/playbooks/roles/os_neutron/templates/plugins/ml2/linuxbridge_agent.ini.j2#L28) we we found it caused gate failures a lot of the time.
In Mitaka we now have it enabled as the issues we found have been resolved in upstream code. As I recall the issues had something to do with l2pop, so it's plausible that it might work to enable ARP spoofing protection again in Liberty but I've opted to block that as it's a major change which has far reaching effects and I'd rather not see that done as a default and rather leave it up to the deployer.

Effectively this means that the port security extension is the only form of spoofing protection enabled by default in Liberty.

**Comment by nrb** [comment]
@tbreeds Thanks for checking in with that, I appreciate it!

**Comment by BjoernT** [comment]
Support had a small meeting and prefers that this extension is disabled for all releases until we can make sure that a) Users can upgrade and b) Greenfields work ok

**Comment by prometheanfire** [comment]
Will we ever be able to ensure `a`?  customers may be using networking in any number of ways that this security improvement would catch.

**Comment by BjoernT** [comment]
So the port security extensions give you only the benefit of disabling the MAC/anti spoofing feature in neutron per network/port bases. The use case was pretty much limited for NFV where you can't have APR spoofing protection enabled, something which we do not care yet. Hence disabling it not more unsecure, the neutron ports are as secure as we used to expect

**Comment by mancdaz** [comment]
@palendae can you please comment here? Is the work all done?

**Comment by BjoernT** [comment]
I'm not aware of any open issues here

**Comment by d34dh0r53** [comment]
I'm closing this as all of the work seems to be done, re-open if needed.
