### ISSUE TITLE
Beaver init script can not be enabled

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#934]
##### What version (commit) do you encounter this issue on?

11.1.5

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

It automatically enables upon installation

##### What is actually happening?

update-rc.d -f  beaver enable 2 3 4 5

update-rc.d: warning:  start runlevel arguments (none) do not match beaver Default-Start values (2 3 4 5)
update-rc.d: warning:  stop runlevel arguments (none) do not match beaver Default-Stop values (0 1 6)
 System start/stop links for /etc/init.d/beaver do not exist.
 

##### How can we reproduce this issue?

See above

##### How can we verify your issue is addressed?

Beaver autostarts after reboot

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Manual workaround possible

##### What is your evaluation on the importance of this issue, and why?

Normal Prio

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] liberty-12.2 #1277 
- [ ] kilo #1280 

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by BjoernT** [comment]
I''l convert the script to systemd then we should be fine

**Comment by d34dh0r53** [comment]
@BjoernT Is this an RPC-R issue, or are you seeing it on RPC-O?

**Comment by BjoernT** [comment]
This is RPC-O, didn't know if RPC-R consumes that role even

**Comment by b3rnard0** [comment]
@BjoernT Is this no longer a priority bug? We've committed to fixing it. Please advise.

cc: @claco @git-harry @mancdaz

**Comment by BjoernT** [comment]
I saw it only few times and a workaround could be to make sure that the services are started.
So I would say we postpone or even close it since we have to recreate the init scripts for newton anyway to be systemd compatible

**Comment by BjoernT** [comment]
Correction yes this issue is still there. After each reboot beaver would not be started since it's not liked inside the legacy init rcX.d directories installed. So the only way to lower the prio would be to have a workaround in place, which we can not guarantee in support at this moment

**Comment by BjoernT** [comment]
Fresh liberty install:

```
 update-rc.d -f beaver enable 2 3 4 5
update-rc.d: warning:  start runlevel arguments (none) do not match beaver Default-Start values (2 3 4 5)
update-rc.d: warning:  stop runlevel arguments (none) do not match beaver Default-Stop values (0 1 6)
 System start/stop links for /etc/init.d/beaver do not exist.

Beaver is missing as link inside /etc/rc*.d
```

**Comment by ameserole** [comment]
Master no longer uses beaver as of [1] so I am going to remove master from the list of affected branches

[1] https://github.com/rcbops/rpc-openstack/commit/2d7bce0ae13399b59ac98833b066ce9248f1fb00

**Comment by ameserole** [comment]
UPDATE:
Created a pull request for this issue against Liberty https://github.com/rcbops/rpc-openstack/pull/1277

**Comment by ameserole** [comment]
UPDATE:
Added the kilo backport #1280
