### ISSUE TITLE
Module 'horizon.dashboard.rackspace' is not available

### ISSUE THREAD

**Issue by Rydor** [rcbops/rpc-openstack#938]
##### What version (commit) do you encounter this issue on?
r12.0.0rc3

##### What type of issue is this (bug, feature, documentation, regression)?
bug, regression

##### What is the expected behavior?
Page should load with the correct tables, graphs and fonts. Also no js errors should appear in the console.

##### What is actually happening?
The pie graphs on the "Overview" tab under "Compute" do not show up. The font for the IP address field was much larger than the other fields.

##### How can we reproduce this issue?

1. Perform Greenfield deploy 
2. Log into the Horizon dashboard
3. Take note of the missing pie graphs
4. Inspect the "Overview" page
5. In Console you will see the exception

##### How can we verify your issue is addressed?
Once the pie graphs are visible on the "Overview" page and the error no longer exist within console.

##### What is your evaluation on the importance of this issue, and why?
This does not appear to affect functionality however it does cause visible changes in the Horizon dashboard that may draw customer's attention to the fact it isn't working.

##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [x] Master
- [x] liberty-12.1
- [x] liberty-12.0

Missing pie graphs:
<img width="1440" alt="screenshot 2016-03-29 11 35 39" src="https://cloud.githubusercontent.com/assets/8172208/14116698/b968beaa-f5a6-11e5-8c2b-18def0e63710.png">

Odd font size for IP address field:
<img width="1440" alt="screenshot 2016-03-29 11 30 13" src="https://cloud.githubusercontent.com/assets/8172208/14116705/be946424-f5a6-11e5-8bc0-6edc035aaf6c.png">

**Comment by neillc** [comment]
Starting to look into this.

**Comment by b3rnard0** [comment]
@neillc Thanks!

**Comment by neillc** [comment]
It looks like the javascript is not being installed into the correct location.  Trying to figure out how to fix this now.

**Comment by d34dh0r53** [comment]
Needs backports to `liberty-12.1` and `liberty-12.0`

**Comment by prometheanfire** [comment]
fixed, closing
