### ISSUE TITLE
Kilo AIO deploys Ceilometer

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#945]
##### What version (commit) do you encounter this issue on?
kilo
##### What type of issue is this (bug, feature, documentation, regression)?
bug
##### What is the expected behavior?
Ceilometer is not installed when creating an AIO and DEPLOY_CEILOMETER == "no"
##### What is actually happening?
Ceilometer is being configured.
##### How can we reproduce this issue?
Build a Kilo AIO.
##### How can we verify your issue is addressed?
The Ceilometer playbooks will be skipped and no Ceilometer containers will be created.
##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
N/A
##### What is your evaluation on the importance of this issue, and why?
Low. This should not be causing an issue with production deployments because they are manually creating the config in /etc/openstack_deploy
##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [x] kilo

**Comment by prometheanfire** [comment]
Is this only kilo?
