### ISSUE TITLE
tasks/raxmon_agent_install.yml does not upgrade to a new version correctly

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#95]
The git module called out of tasks/raxmon_agent_install.yml does not seem upgrade the git repo correctly. Running the setup-maas.yml playbook out of the master branch will leave the git repo stale. I did clone it manually to progress but we might want to check on that.

**Comment by d34dh0r53** [comment]
@BjoernT is this still an issue?

**Comment by mancdaz** [comment]
@BjoernT closing this for now - please re-open with additional detail if it's still a thing

**Comment by BjoernT** [comment]
No it's not an issue anymore after we killed rpc-maas repo. This issue would be still present for juno but that's quickly dying
