### ISSUE TITLE
Spelling mistake in motd

### ISSUE THREAD

**Issue by neillc** [rcbops/rpc-openstack#952]
##### What version (commit) do you encounter this issue on?
Master

##### What type of issue is this (bug, feature, documentation, regression)?
Bug

##### What is the expected behavior?
Correct spelling of question

##### What is actually happening?
motd contains: "Contact 700-NOVA if you have any questons"

##### How can we reproduce this issue?
Install rpc-openstack.  Log in via ssh

##### How can we verify your issue is addressed?
Verify spelling is corrected.

##### What is your evaluation on the importance of this issue, and why?
No functionality impact. No security impact. Would look better to have motd using correct spelling.

##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [x] Master
- [x] liberty-12.1 #975 
- [x] liberty-12.0 #976

**Comment by evrardjp** [comment]
Merged in all branches.
