### ISSUE TITLE
Tracking of upstream 1566915

### ISSUE THREAD

**Issue by d34dh0r53** [rcbops/rpc-openstack#961]
##### What version (commit) do you encounter this issue on?
`r12.1.0rc1`

##### What type of issue is this (bug, feature, documentation, regression)?
bug

##### What is the expected behavior?
N/A

##### What is actually happening?
Tracking of upstream [`1566915`](https://bugs.launchpad.net/openstack-ansible/+bug/1566915)

##### How can we reproduce this issue?
N/A

##### How can we verify your issue is addressed?
A fix for [`1566915`](https://bugs.launchpad.net/openstack-ansible/+bug/1566915) is merged and SHAs bumped.

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
N/A

##### What is your evaluation on the importance of this issue, and why?
High

###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.1

**Comment by major** [comment]
![Bug](https://i.imgflip.com/1222z7.jpg)

**Comment by sigmavirus24** [comment]
Cry me an upgrade

**Comment by prometheanfire** [comment]
backport?

**Comment by git-harry** [comment]
@prometheanfire the above commit reference links back to it. It's pr #969

**Comment by prometheanfire** [comment]
ah, that just popped up

**Comment by git-harry** [comment]
@prometheanfire the pull request description didn't reference this issue only the commit did. I've updated so the larger bold link appears in addition to the less useful commit one.

**Comment by mancdaz** [comment]
master commit and liberty-12.1 backport have both merged, closing
