### ISSUE TITLE
nova f5 health check is wrong

### ISSUE THREAD

**Issue by prometheanfire** [rcbops/rpc-openstack#965]
##### What version (commit) do you encounter this issue on?
v12.1.0-rc1

##### What type of issue is this (bug, feature, documentation, regression)?
bug, regression

##### What is the expected behavior?
heath check is happy

##### What is actually happening?
health check is sad

##### How can we reproduce this issue?
run in a lab with health checks

##### How can we verify your issue is addressed?
heath checks are happy

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
doc change / warning

##### What is your evaluation on the importance of this issue, and why?
high, this effects a current release

###### Remove branches (lines) you do not wish to target.
- [x] Master #966
- [x] liberty-12.1 #988 
- [x] liberty-12.0 #989

**Comment by mancdaz** [comment]
NB If I didn't have the PR to reference, this bug submission would give me no clue as to what the actual problem is, other than 'health check is sad'

**Comment by prometheanfire** [comment]
sorry, I was making this from @b3rnard0's laptop at the end of the day.

the nova url specifies v3, we need to change that to v2.1 as v3 is deprecated.
