### ISSUE TITLE
[r12.1.0rc1] Swift rings failing to build because of improper types

### ISSUE THREAD

**Issue by jpmontez** [rcbops/rpc-openstack#968]
##### What version (commit) do you encounter this issue on?
`r12.1.0rc1`

##### What type of issue is this (bug, feature, documentation, regression)?
Bug

##### What is the expected behavior?
For the rings to build successfully

##### What is actually happening?
A Python exception is returned because of improper types being passed into a built-in function

There is also a Launchpad bug and patch that I've submitted [here](https://bugs.launchpad.net/openstack-ansible/+bug/1567666)

##### How can we reproduce this issue?
By running the `os_swift_sync` role within a multi-region Swift installation

##### How can we verify your issue is addressed?
There is a Launchpad bug and patch that I've submitted [here](https://bugs.launchpad.net/openstack-ansible/+bug/1567666)

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
By applying my patch within an environment

##### What is your evaluation on the importance of this issue, and why?
High for multi-region Swift customers

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.1
- [ ] liberty-12.0
- [ ] kilo

**Comment by prometheanfire** [comment]
@jpmontez please leave the lines you wish to target, remove them if you don't want to target (bottom of issue template)

**Comment by jpmontez** [comment]
Sorry, my marks weren't correct syntax. Fixed.

**Comment by prometheanfire** [comment]
@jpmontez sorry, I it's still incorrect.  The purpose of those is so we can track when a fix is merged.  So leaving them unchecked is the thing to do.

**Comment by git-harry** [comment]
@andymcc do you know why you didn't hit this with your testing?

**Comment by andymcc** [comment]
@git-harry I'm not sure - however this should affect greenfields deploys too - which we haven't seen so far. 

The contents files get templated out and then (in this task) the ring_build file takes values from the existing ring and the contents file to calculate differences and make changes appropriately. This would happen for both upgrades and greenfield deploys, so i'm not sure how you would run into this in an upgrade specifically. 

@jpmontez I'd be interested to get a copy of your /etc/openstack_deploy/conf.d/swift.yml or whichever conf file you are defining your swift hardware/disk configuration, might be worth testing further.

**Comment by prometheanfire** [comment]
Do you have docs on how you are testing/deploying swift multi-region?

**Comment by prometheanfire** [comment]
Does this fix it for you?  https://review.openstack.org/#/c/303087/

**Comment by jpmontez** [comment]
There was bad leftover data on the Swift nodes from a previous installation. I've removed it and restarted the greenfield deployment. Everything's working now without any fix. Closing this issue.

**Comment by prometheanfire** [comment]
yay
