### ISSUE TITLE
using new github features

### ISSUE THREAD

**Issue by prometheanfire** [rcbops/rpc-openstack#974]
removed the normal template because this doesn't really fit that.

Github recently announced two new features.  I think we should discuss enabling them (or not).

1. commit squashing on PR merge.

  https://github.com/blog/2141-squash-your-commits
  https://help.github.com/articles/about-pull-request-merge-squashing/
  I'm not quite sure how it would handle the commit messages.  We've also been pretty good about not letting though multiple commits in a single PR without good reason.  So I personally don't see the need to enable this.

2. better protected branch settings

  https://github.com/blog/2137-protected-branches-improvements
  * we can allow merging out of date PRs now, this was the main reason we turned it off I think.
  * we can also limit who the 'core' reviewers are, or who can hit the button, could be useful for permission limiting.

I'd like to see us re-enabling protected branches, possibly using/defining a specific team as 'core' reviewers.

**Comment by git-harry** [comment]
I don't think we should squash commits, although generally there should be only one commit per pull request sometimes it's useful to have the option.

I agree with enabling 'Require status checks to pass before merging' but not 'Require branches to be up to date before merging'. While it would be preferable to have testing done on the rebased commit this gives us a better guarantee than we currently have without creating a manual overhead.

**Comment by git-harry** [comment]
Branch protection has been enabled with particular status check set as required.
