### ISSUE TITLE
repo-pip-setup doesnt run on haproxy hosts, causes beaver.yml play to fail

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/rpc-openstack#991]
##### What version (commit) do you encounter this issue on?
11.1.6, kilo
##### What type of issue is this (bug, feature, documentation, regression)?
bug
##### What is the expected behavior?
all proper pip.conf files get laid down on all hosts that will require rpc specific pip packages
##### What is actually happening?
haproxy host is not getting rpc specific repo links in pip.conf
##### How can we reproduce this issue?
install a kilo release on a lab that has an haproxy host only hosting ha proxy, then install logging on lab
##### What is your evaluation on the importance of this issue, and why?
low, logging plays will not finish until it is fixed
###### Remove branches (lines) you do not wish to target.
- [x] kilo

Only runs on hosts:all_containters
https://github.com/rcbops/rpc-openstack/blob/kilo/rpcd/playbooks/repo-pip-setup.yml#L20

Runs on all
https://github.com/rcbops/rpc-openstack/blob/kilo/rpcd/playbooks/beaver.yml#L17

Currently, hosts in openstack_inventory doesnt contain the ha_proxy host

```
    "hosts": {
        "children": [
            "metering-compute_hosts",
            "storage_hosts",
            "metering-infra_hosts",
            "os-infra_hosts",
            "osds_hosts",
            "network_hosts",
            "log_hosts",
            "infra_hosts",
            "swift-proxy_hosts",
            "compute_hosts",
            "swift_hosts",
            "identity_hosts",
            "repo-infra_hosts",
            "shared-infra_hosts",
            "storage-infra_hosts",
            "mons_hosts"
        ],
        "hosts": []
    },
```

**Comment by prometheanfire** [comment]
since haproxy isn't supported (to my knowlege) I'd reset the importance to low.

**Comment by jacobwagner** [comment]
@prometheanfire done, good point

**Comment by git-harry** [comment]
Considering haproxy is not supported and this won't affect AIO's I'm not sure there's necessarily something to fix. @jacobwagner why has this issue now appeared for you? Are you now performing additional forms of testing on a Kilo build?

**Comment by prometheanfire** [comment]
If it's not supported then we should remove it from use entirely.

**Comment by prometheanfire** [comment]
it's over
