### ISSUE TITLE
Set galera_wait_timeout to 3600 to match SQLAlchemy

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#995]
##### What version (commit) do you encounter this issue on?

All

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

Unnecessary sql connections should not stay open for 8 hours when SQL Alchemy actually recycles the connection after an hour

##### What is actually happening?

Unused SQL Alchemy connections stay open for 8 hours causing a high floor if idling sessions
 
##### How can we reproduce this issue?

If the idling sessions (sleeping) get dropped after an hour

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Minor issue

##### What is your evaluation on the importance of this issue, and why?

-

###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.2
- [ ] kilo

**Comment by prometheanfire** [comment]
https://review.openstack.org/307231

**Comment by prometheanfire** [comment]
Upstream merged master, @BjoernT you want to backport upstream as well?

**Comment by git-harry** [comment]
This has been addressed upstream for Mitaka and Liberty but will need overriding in Kilo if required in that release.

**Comment by BjoernT** [comment]
Being addressed upstream at https://review.openstack.org/#/c/307231/. Closing here
