### ISSUE TITLE
Add security hardening functionality

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#999]
##### What version (commit) do you encounter this issue on?
master
##### What type of issue is this (bug, feature, documentation, regression)?
feature
##### What is the expected behavior?
Liberty now includes the ability to use openstack-ansible-security, this is a role to apply security best practices host configurations. RPCO needs updating to be able to selectively deploy this capability.
##### What is actually happening?
Currently the openstack-ansible submodule does not include to relevant commit and deploy.sh has no ability to control the use of this role.
##### How can we verify your issue is addressed?
Once updated the role will apply the security best practices it defines, this will be observed in the logs and config.
##### What is your evaluation on the importance of this issue, and why?
High, this is a requirement for 12.2.0
###### Remove branches (lines) you do not wish to target.
- [x] Master

**Comment by prometheanfire** [comment]
merged
